/**
*@file
*@brief     ab281项目配置文件
*@details
*@author        zn.zeng
*@date        2024-03-22
*@version       v1.0
*/
#ifndef _UTE_PROJECT_CONFIG_AB281_H_
#define _UTE_PROJECT_CONFIG_AB281_H_

#define DEFAULT_BLE_DEV_NEME "AB281"
#define UTE_SW_VERSION "AB281V000004"

#define UTE_DRV_DSPI_FOR_SCREEN_SUPPORT 0
#define UTE_DRV_QSPI_FOR_SCREEN_SUPPORT 1

#define UTE_DRV_TFT_S240X284_NV3030B_HY201068AVC_QSPI_SUPPORT 1

/*! 屏最大亮度百分比 dengli.lu, 2021-10-29  */
#define DEFAULT_BACK_LIGHT_PERCENT_MAX 100

/*! 屏最小亮度百分比 dengli.lu, 2021-10-29  */
#define DEFAULT_BACK_LIGHT_PERCENT_MIN 20

/*! 调节屏亮度时增加或者减少的百分比 dengli.lu, 2021-10-29  */
#define BACK_LIGHT_PERCENT_INCREASE_OR_INCREASE 20

/*! 默认背光百分比zn.zeng, 2021-09-24  */
#define DEFAULT_SCREEN_BACKLIGHT_PERCENT    (BACK_LIGHT_PERCENT_INCREASE_OR_INCREASE*3)

#define UTE_DRV_GSENSOR_SC7A20H_SUPPORT 1

#define UTE_TASK_USER_SUPPORT 1

/*! 抬手亮屏参数 zn.zeng, 2021-10-22  */
#define ROLLOVER_HAND_SCREEN_X_MIN  -40
#define ROLLOVER_HAND_SCREEN_X_MAX  140
#define ROLLOVER_HAND_SCREEN_Y_MIN  -46
#define ROLLOVER_HAND_SCREEN_Y_MAX  40
#define ROLLOVER_HAND_SCREEN_Z_MIN  -136
#define ROLLOVER_HAND_SCREEN_Z_MAX  128
#define ROLLOVER_HAND_SCREEN_ACC_DIFF_VALUE  20

#define QUICK_SWITCH_NOT_DISTURB_SUPPORT 1
#define QUICK_SWITCH_ANTILOST_SUPPORT   1
#define QUICK_SWITCH_DISPLAY_TIME_SUPPORT   1
#define QUICK_SWITCH_FINDBAND_SUPPORT 0
#define QUICK_SWITCH_TURNTHEWRIST_SUPPORT 1
#define QUICK_SWITCH_SHOCK_TIME_SUPPORT    1
#define QUICK_SWITCH_LOCAL_WURAO_SET_TIME_SUPPORT 1

/*! 心率最大最小值数字显示跟随柱状图中的最大最小值 xjc, 2022-01-17  */
#define UTE_HEART_MAX_MIN_AVG_FOLLOW_HISTOGRAM_SUPPORT 1

/* 电池容量 zn.zeng 2022-01-07*/
#define UTE_DRV_BATTERY_ELECTRICITY_POWER_MAH      220 //mAh

/* 电池曲线 zn.zeng 2022-01-03*/
#define UTE_DRV_BATTERY_000      3480
#define UTE_DRV_BATTERY_010      3620
#define UTE_DRV_BATTERY_020      3740
#define UTE_DRV_BATTERY_030      3767
#define UTE_DRV_BATTERY_040      3791
#define UTE_DRV_BATTERY_050      3805
#define UTE_DRV_BATTERY_060      3872
#define UTE_DRV_BATTERY_070      3946
#define UTE_DRV_BATTERY_080      4090
#define UTE_DRV_BATTERY_090      4055
#define UTE_DRV_BATTERY_100      4140

#define UTE_DRV_TP_X_AXIS_EXCHANGE 1 // 交换X轴左右坐标
#define UTE_DRV_TP_Y_AXIS_EXCHANGE 0 // 交换Y轴上下坐标

/*! 一级界面默认排序,wang.luo 2024-11-16 */
#define UTE_CUI_SCREEN_TBL_SORT_CNT_DEFAULT 7
#define UTE_CUI_SCREEN_TBL_SORT_ARRAY_DEFAULT {FUNC_CLOCK, FUNC_ACTIVITY, FUNC_HEARTRATE, FUNC_SLEEP, FUNC_BLOOD_OXYGEN, FUNC_BT, FUNC_COMPO_SELECT}
/*! 默认表盘索引 zn.zeng, 2021-10-25  */
#define DEFAULT_WATCH_INDEX 0
/*! 最大表盘数量，不包括在线表盘 zn.zeng, 2021-10-23  */
#define UTE_MODULE_SCREENS_WATCH_CNT_MAX 4
/*! 表盘排序地址数组,wang.luo 2024-11-26 */
#define UTE_MODULE_WATCHS_SORT_ADDRESS_ARRAYS {UI_BUF_DIALPLATE_1_BIN, UI_BUF_DIALPLATE_4_BIN, UI_BUF_DIALPLATE_BTF_BIN, UI_BUF_DIALPLATE_CUBE_BIN}
#define UTE_WATCHS_BUTTERFLY_DIAL_SUPPORT 1 // 使用蝴蝶表盘
#define UTE_WATCHS_CUBE_DIAL_SUPPORT 1      // 使用立方体表盘
#define UTE_WATCHS_DIALPLATE_BTF_INDEX 2    // 蝴蝶表盘索引
#define UTE_WATCHS_DIALPLATE_CUBE_INDEX 3   // 立方体表盘索引

/*! SOS联系人拨号功能,xjc 2022-07-06  */
#define UTE_MODUEL_CALL_SOS_CONTACT_SUPPORT 1

/*! 支持的运动数量, xjc 2022-03-09  */
#define UTE_MODULE_SPORT_MAX_SPORT_NUM 25
#define UTE_MODULE_SPORT_RUNNING_SUPPORT                1 //跑步
#define UTE_MODULE_SPORT_BIKE_SUPPORT                   1 //骑行
#define UTE_MODULE_SPORT_JUMP_ROPE_SUPPORT              1 //跳绳
#define UTE_MODULE_SPORT_SWIMMING_SUPPORT               1 //游泳
#define UTE_MODULE_SPORT_BADMINTION_SUPPORT             1 //羽毛球
#define UTE_MODULE_SPORT_TABLE_TENNIS_SUPPORT           1 //乒乓球
#define UTE_MODULE_SPORT_TENNIS_SUPPORT                 1 //网球
#define UTE_MODULE_SPORT_CLIMBING_SUPPORT               1 //登山
#define UTE_MODULE_SPORT_WALKING_SUPPORT                1 //徒步
#define UTE_MODULE_SPORT_BASKETBALL_SUPPORT             1 //篮球
#define UTE_MODULE_SPORT_FOOTBALL_SUPPORT               1 //足球
#define UTE_MODULE_SPORT_BASEBALL_SUPPORT               1 //棒球（或垒球）
#define UTE_MODULE_SPORT_VOLLEYBALL_SUPPORT             1 //排球
#define UTE_MODULE_SPORT_CRICKET_SUPPORT                1 //板球
#define UTE_MODULE_SPORT_RUGBY_SUPPORT                  1 //橄榄球（或美式足球）
#define UTE_MODULE_SPORT_HOCKEY_SUPPORT                 1 //曲棍球
#define UTE_MODULE_SPORT_DANCE_SUPPORT                  1 //跳舞
#define UTE_MODULE_SPORT_SPINNING_SUPPORT               1 //动感单车
#define UTE_MODULE_SPORT_YOGA_SUPPORT                   1 //瑜伽
#define UTE_MODULE_SPORT_SIT_UP_SUPPORT                 1 //仰卧起坐
#define UTE_MODULE_SPORT_TREADMILL_SUPPORT              1 //跑步机
#define UTE_MODULE_SPORT_GYMNASTICS_SUPPORT             1 //体操
#define UTE_MODULE_SPORT_BOATING_SUPPORT                1 //划船
#define UTE_MODULE_SPORT_JUMPING_JACK_SUPPORT           1 //开合跳
#define UTE_MODULE_SPORT_FREE_TRAINING_SUPPORT          1 //自由训练

#define GUI_SCREEN_SIZE_240X284RGB_I330001_SUPPORT      1

#endif//_UTE_PROJECT_CONFIG_AB281_H_
