/**
*@file
*@brief     ab281项目配置文件
*@details
*@author        zn.zeng
*@date        2024-03-22
*@version       v1.0
*/
#ifndef _UTE_PROJECT_CONFIG_AB281GA_H_
#define _UTE_PROJECT_CONFIG_AB281GA_H_

#define DEFAULT_BLE_DEV_NAME "oraimo Watch Nova 2N"
#define UTE_SW_VERSION "AB281GAV000300"
/*! 指定资源路径,如果不定义则使用对应项目号的路径,wang.luo 2025-01-07 */
#define UTE_UI_CONFIG_PATCH "AB281GA"
/** Log模块控制开关*/

#define UTE_MODULE_BLE_NAME_FORMET1_SUPPORT 1

// 客制化关于界面
#define UTE_SW_CUSTOM_VERSION "V1.0.9" // 客制化版本号
#define UTE_CUSTOM_VERSION_LENTH 6     // 客制化版本号的长度
#define UTE_CUSTOM_DEVICE_MODEL "OSW-815N"

#define UTE_APP_READ_CUSTOM_SOFTWARE_VERSON_SUPPORT 1 //读取客户的版本号

/* 睡眠数据采样支持 zn.zeng 2021-12-29*/
#define UTE_MODULE_SLEEP_SAMPLE_DATA_SUPPORT 1
/*gesnsor 采集原始数据*/
#define APP_DBG_GSENSOR_DATA 1

/*! 心率sensor选择,wang.luo 2025-04-16 */
#define UTE_DRV_HR_SENSOR_SELECT       SENSOR_HR_VC30FX

/*! 心率活体检测,wang.luo 2025-08-19 */
#define UTE_MODULE_VCXX_HEART_BIO_CHECK_SUPPORT  1

/*! 活体默认Bio,打开活体功能必须采5个以上最终整机的bio值，取平均值填写默认bio,wang.luo 2025-08-19 */
#define DRV_HEART_VCXX_CFG_READ_ERR_WEAR_BIO_DEFAULT  300

#define UTE_CHIP_PACKAGE_SELECT        CHIP_5691G   //芯片选择

#define UTE_DRV_DSPI_FOR_SCREEN_SUPPORT 0
#define UTE_DRV_QSPI_FOR_SCREEN_SUPPORT 1

#define UTE_DRV_TFT_S240X284_NV3030B_HY201068AVC_QSPI_SUPPORT 0
#define DRV_BOE_S240X284_I183_JD9853_WV018LZQ_QSPI_SUPPORT 0
#define UTE_DRV_TFT_S240X284_NV3030B_ZD183G1196_QSPI_SUPPORT 0//长沙调试用屏幕
#define UTE_DRV_TFT_S360X360_NV3030B_HY139071A_QSPI_SUPPORT 0
#define UTE_DRV_TFT_S360X360_NV3030B_ZD138G1616_QSPI_SUPPORT 0
#define UTE_DRV_TFT_S240X284_I183_JD9853_0185A035_QSPI_SUPPORT 0 // 正式版本屏幕
#define UTE_DRV_TFT_S240X296_GC9309_JS202018A_QSPI_SUPPORT 0
#define UTE_DRV_TFT_S360X360_GC9B71_ZD138G1616_QSPI_SUPPORT 0
#define UTE_DRV_AMOLED_S368X448_GC3A71_HK0J1931972B03_QSPI_SUPPORT 0
#define UTE_DRV_AMOLED_S368X448_CH13620_193WY01012_QSPI_SUPPORT 0
#define UTE_DRV_AMOLED_S368X448_GC3A71_193WG2014V1_QSPI_SUPPORT 1
/*! 不同TE模式下的spiclk,用于优化撕裂,spiclk : baud = sys_clk / (div +1),wang.luo 2025-01-11 */
#define UTE_DRV_SCREEN_1TE_SPI_CLK 40000000
#define UTE_DRV_SCREEN_2TE_SPI_CLK 32000000

/*! ESD测试屏幕TE中断异常复位处理,wang.luo 2025-05-28 */
#define UTE_DRV_SCREEN_ESD_TE_INT_ERROR_RESET_SUPPORT 1

#define UTE_DRV_CTP_SELECT              CTP_SPT5113C

//TP 复用屏幕复位
#define UTE_DRV_CTP_SPT5113C_REUSE_SCREEN_RESET_SUPPORT 1

/*! 屏最大亮度百分比 dengli.lu, 2021-10-29  */
#define DEFAULT_BACK_LIGHT_PERCENT_MAX 100

/*! 屏最小亮度百分比 dengli.lu, 2021-10-29  */
#define DEFAULT_BACK_LIGHT_PERCENT_MIN 20

/*! 调节屏亮度时增加或者减少的百分比 dengli.lu, 2021-10-29  */
#define BACK_LIGHT_PERCENT_INCREASE_OR_INCREASE 20

/*! 默认背光百分比zn.zeng, 2021-09-24  */
#define DEFAULT_SCREEN_BACKLIGHT_PERCENT    (BACK_LIGHT_PERCENT_INCREASE_OR_INCREASE*3)
/*! 中科平台广播UUID,wang.luo 2025-02-13 */
#define UTE_SERVICE_APP_GLORY_ME_SUPPORT 0

//Gsensor
#define UTE_DRV_GSENSOR_SC7A20H_SUPPORT 1
#define UTE_DRV_STK8321_SUPPORT 0

/*! 抬手亮屏参数 zn.zeng, 2021-10-22  */
#define ROLLOVER_HAND_SCREEN_X_MIN  -40
#define ROLLOVER_HAND_SCREEN_X_MAX  40
#define ROLLOVER_HAND_SCREEN_Y_MIN  -46
#define ROLLOVER_HAND_SCREEN_Y_MAX  140
#define ROLLOVER_HAND_SCREEN_Z_MIN  -136
#define ROLLOVER_HAND_SCREEN_Z_MAX  128
#define ROLLOVER_HAND_SCREEN_ACC_DIFF_VALUE  30

#define QUICK_SWITCH_NOT_DISTURB_SUPPORT 1
#define QUICK_SWITCH_ANTILOST_SUPPORT   1
#define QUICK_SWITCH_DISPLAY_TIME_SUPPORT   1
#define QUICK_SWITCH_FINDBAND_SUPPORT 0
#define QUICK_SWITCH_TURNTHEWRIST_SUPPORT 1
#define QUICK_SWITCH_SHOCK_TIME_SUPPORT    1
#define QUICK_SWITCH_LOCAL_WURAO_SET_TIME_SUPPORT 1

/*! PWRKEY,wang.luo 2024-12-03 */
#define UTE_DRV_PWRKEY_SUPPORT 1
/*! PWRKEY按键最大数量,wang.luo 2024-12-03 */
#define UTE_DRV_PWRKEY_MAX_CNT 1

/*! KEY_MSG_USER 按键事件功能SOS,.quan.qi.cai 2025-05-29 */
#define UTE_THREE_KEY_EVENT_SOS 1

/*! 心率最大最小值数字显示跟随柱状图中的最大最小值 xjc, 2022-01-17  */
#define UTE_HEART_MAX_MIN_AVG_FOLLOW_HISTOGRAM_SUPPORT 1

/*! 心率警告功能 zn.zeng, 2021-10-22  */
#define UTE_MODULE_HEART_MIN_MAX_WARNING_VALUE_SUPPORT 1

#define UTE_MODULE_HEART_WEEK_STATIC_SUPPORT 1  //周的静息心率统计
/*! 静息心率上报,wuhuowang 2022-11-18*/
#define APP_MODULE_HEART_RESTING_HEARTRATE_SUPPORT   (1&UTE_MODULE_HEART_WEEK_STATIC_SUPPORT)
/*! 全天静息心率,wang.luo 2023-10-30 */
#define UTE_MODULE_HEART_STATIC_ALL_DAY_SUPPORT (1&UTE_MODULE_HEART_WEEK_STATIC_SUPPORT)

/*! 打开每隔5分钟保存心率和血氧值,wuhuowang 2022-11-18*/
#define APP_SAVE_HR_OXYGEN_EVERY_FIVE_MINUTES_SUPPORT   1
#if APP_SAVE_HR_OXYGEN_EVERY_FIVE_MINUTES_SUPPORT
#define UTE_MODULE_BLOODOXYGEN_AUTO_INTERVAL_MIN 5
#define UTE_MODULE_BLOODOXYGEN_SAVE_INTERVAL_MIN 5
#define UTE_MODULE_HEARTRATE_SAVE_INTERVAL_MIN 5
#endif

/*! 部分界面不显示消息提醒,wang.luo 2025-09-05 */
#define UTE_MODULE_GUI_TESTING_NOT_GOTO_NOTIFICATION_SCREEN_SUPPORT 1

/*! 更新版本号默认清除所有数据,xjc 2022-05-05*/
#define UTE_COMPARE_SOFTWARE_VERSION_AND_CLEAR_FLASH_SUPPORT 0

/*! 界面左右切换透明度,xjc 2022-05-05*/
#define UTE_MODULE_GUI_SCREEN_SWITCHING_LR_ALPHA 255

/*! 情绪压力模块,xjc 2022-02-15*/
#define UTE_MODULE_EMOTION_PRESSURE_SUPPORT 1

#define UTE_MODULE_PRESSURE_MAX_MIN_AVG_FOLLOW_HISTOGRAM_SUPPORT 1

/*! 活动界面列表形式,xjc 2022-02-15*/
#define UTE_GUI_SCREEN_ACTIVITY_LIST_SUPPORT 1
#define UTE_MODULE_SPORT_TODAY_ADD_KCAL_SPORT_DATA_SUPPORT 1
#define UTE_MODULE_SPORT_TODAY_ADD_ALL_SPORT_DATA_SUPPORT 1
/*! 未满足保存条件的运动数据（步数、卡路里、距离）也加到日常数据中*/
#define APP_MODULE_SPORT_TODAY_ADD_ALL_SPORT_OTHER_DATA_SUPPORT (1&UTE_MODULE_SPORT_TODAY_ADD_ALL_SPORT_DATA_SUPPORT)

#define APP_STAND_SPORT_STEP_KCAL_DISTANCE_NOTIFY_SUPPORT 1// 站立时长/卡路里/运动时长/距离/步数提醒
#define UTE_MODULE_ALL_TARGET_NOTIFY_SUPPORT 0
#define UTE_MODULE_KCAL_TARGET_NOTIFY_SUPPORT 1
#define UTE_MODULE_DISTANCE_TARGET_NOTIFY_SUPPORT 0
#define UTE_MODULE_STAND_TIME_TARGET_NOTIFY_SUPPORT 0
#define UTE_MODULE_SPORT_TIME_TARGET_NOTIFY_SUPPORT 0
#define DEFAULT_DRINK_WATER_OPNE false
#define DEFAULT_DRINK_WATER_TIME_INTERVAL 0x3c//60分钟
#define DEFAULT_DRINK_WATER_START_TIME  0x0900 //09:00
#define DEFAULT_DONOT_DISTURB_END_TIME  0x1500   //21:00
#define DEFAULT_DONOT_DISTURB_START_HOUR_MIN_VALUE  0x528 //22:00
#define DEFAULT_DONOT_DISTURB_END_HOUR_MIN_VALUE  0x1E0  //8:00
#define DEFAULT_HAND_WASHING_OPNE false
#define DEFAULT_HAND_WASHING_TIME_INTERVAL 0x3c//60分钟
#define DEFAULT_HAND_WASHING_START_TIME  0x0900 //09:00
#define DEFAULT_HAND_WASHING_END_TIME  0x1500   //21:00
#define DEFAULT_NOON_SLEEP_OPNE true
#define DEFAULT_NOON_SLEEP_START_TIME  0x0d00 //13:00
#define DEFAULT_NOON_SLEEP_END_TIME  0x0e00   //14:00
#define DEFAULT_SEDENTARY_NOTIFY_OPNE false
#define DEFAULT_SEDENTARY_NOTIFY_TIME_INTERVAL 0x3c//60分钟
#define DEFAULT_SEDENTARY_NOTIFY_START_TIME  0x0900 //09:00
#define DEFAULT_SEDENTARY_NOTIFY_END_TIME  0x1500   //21:00
#define DEFAULT_STEP_TARGET_CNT 8000
#define DEFAULT_STEP_TARGET_OPEN true
#define DEFAULT_KCAL_TARGET_CNT 430
#define DEFAULT_KCAL_TARGET_OPEN false
#define DEFAULT_DISTANCE_TARGET_CNT 5000
#define DEFAULT_DISTANCE_TARGET_OPEN false
#define DEFAULT_STAND_TIME_TARGET_OPEN false
#define DEFAULT_SPORE_TIME_TARGET_OPEN false
#define DEFAULT_EXERCISE_TIME_TARGET_CNT 30
#define DEFAULT_EXERCISE_TIME_TARGET_OPEN false

/*! 活动时长功能,wuhuowang 2022-10-19*/
#define APP_MODULE_SPORT_EXERCISE_TIME_SUPPORT              (1&APP_STAND_SPORT_STEP_KCAL_DISTANCE_NOTIFY_SUPPORT)

/*! 心率区间上报，运动数据包含配速,wuhuowang 2022-11-18*/
#define APP_MODULE_SPORT_HEARTRATE_RANGE_SUPPORT   1
/*! 支持GPS数据下发,wuhuowang 2022-11-18*/
#define APP_MODULE_SPORT_GPS_TRANSLATE_SUPPORT   (1&APP_MODULE_SPORT_HEARTRATE_RANGE_SUPPORT)
/*! 保存GPS数据，支持轨迹,wuhuowang 2022-11-18*/
#define APP_MODULE_SPORT_GPS_SAVE_SUPPORT   (1&APP_MODULE_SPORT_GPS_TRANSLATE_SUPPORT)
#define APP_TRAIL_RUNNING_WITH_STEP     1   //越野跑需要步数
#define APP_SPORT_VIB_AFTER_COUNT     1
#define APP_SPORT_SAVE_DATA_INTERVAL     5
#define APP_MODULE_SCREENS_MORE_SPORT_LIST_SUPPORT 0

#define UTE_DISPLAY_BLOODGXYGEN_HISTORY_HISTOGRAM_SUPPORT  1  //血氧柱形图

/*! 支持从APP接收buffer保存到文件系统，接收完再处理,wuhuowang 2022-12-16*/
#define APP_MODULE_RECEIVE_SAVE_TO_FILESYS_SUPPORT   1
#define UTE_MODULE_SCREENS_LOCAL_ALARM_LABEL_SUPPORT 1 //带标签的闹钟
#define APP_MODULE_ALARM_LABEL_SET_SUPPORT   (1&UTE_MODULE_SCREENS_LOCAL_ALARM_LABEL_SUPPORT)
#define SYSTEM_TIME_ALARMS_MAX_CNT 10   //允许设置的闹钟最大个数

#define UTE_MODULE_LOCAL_ALARM_REPEAT_REMIND_SUPPORT 1
#define ALARM_REPEAT_REMIND_DEFAULT_OPEN true//默认重复提醒开关
#define ALARM_REPEAT_REMIND_DEFAULT_TIME_MIN 10
#define ALARM_REPEAT_REMIND_DEFAULT_TIMES 4//默认重复提醒次数，未手动关闭时重复提醒5次后不再提醒

#define APP_MODULE_BT_DISCONNECT_NOTIFY_SUPPORT 1   //蓝牙断开提醒

/*! pwm控制马达震动强度 xjc, 2023-05-29  */
#define UTE_DRV_MOTOR_PWM_VIBRATION_HIGH 80
#define UTE_DRV_MOTOR_PWM_VIBRATION_MEDIUM 65
#define UTE_DRV_MOTOR_PWM_VIBRATION_LOW 50
#define UTE_DRV_MOTOR_PWM_VIBRATION_NONE 0

#define UTE_MODULE_MOTOR_VIBRATION_DEFAULT_LEVEL UTE_DRV_MOTOR_PWM_VIBRATION_HIGH

#define UTE_MODULE_LOCAL_SET_MENSTRUAL_CYCLE_SUPPORT 1
#if UTE_MODULE_LOCAL_SET_MENSTRUAL_CYCLE_SUPPORT
#define UTE_MODULE_MENSTRUALCYCLE_KEEP_DAYS 5
#define UTE_MODULE_MENSTRUALCYCLE_CYCLE_DAYS 30
#define DEFAULT_MENSTRUAL_REMIND_SWITCH true //月经期默认提醒开关
#define DEFAULT_OVULATION_REMIND_SWITCH true //排卵期默认提醒开关
#define DEFAULT_MENSTRUAL_REMIND_END_SWITCH true //月经期结束默认提醒开关
#define DEFAULT_OVULATION_REMIND_END_SWITCH true //排卵期结束默认提醒开关
#define DEFAULT_MENSTRUAL_REMIND_INADVANCE 2  //月经期默认提醒提前天数
#define DEFAULT_OVULATION_REMIND_INADVANCE 2  //排卵期默认提醒提前天数
#define DEFAULT_MENSTRUAL_REMIND_HOUR_MIN_VALUE 0X1400 //20：00
#define DEFAULT_OVULATION_REMIND_HOUR_MIN_VALUE 0X1400 //20：00
#endif
#define UTE_MODULE_SCREENS_MENSTRUAL_NOTIFY_SUPPORT 1 //生理周期提醒
#define APP_MODULE_MENSTRUAL_CYCLE_NOT_GENDER_SUPPORT 1 //女性生理周期不显示不区分性别

/*! 覆盖息屏,wang.luo 2025-06-19 */
#define UTE_MODULE_COVER_DISPLAY_OFF_SUPPORT 1
/*! 仅主界面允许落腕息屏，其他不允许，默认开启，dengli.lu 2022-08-31 */
#define UTE_MODULE_HAND_SCREEN_OFF_ONLY_WATCHMAIN_ID_SUPPORT 0

/*! 新工厂测试,xjc 2022-02-09*/
#define UTE_MODULE_NEW_FACTORY_TEST_SUPPORT 1

#if UTE_MODULE_NEW_FACTORY_TEST_SUPPORT
#define UTE_MODULE_SCREENS_NEW_FACTORY_MODE_SELECT_SUPPORT 1
#define UTE_MODULE_SCREENS_NEW_FACTORY_AGING_TEST_SUPPORT 1
#define UTE_MODULE_SCREENS_NEW_FACTORY_MODULE_TEST_SUPPORT 1

#define UTE_MODULE_NEW_FACTORY_TEST_JUST_HEART_CHECK_LIGHT_SUPPORT  0 //开机显示心率漏光界面
#define UTE_MODULE_NEW_FACTORY_MODULE_TEST_ALLOW_RETEST_SUPPORT 1 //fail项目允许在列表中点击重新测试
#define UTE_MODULE_NEW_FACTORY_AGING_REPORT_SUPPORT 0 //老化测试生成测试报告
#define UTE_MODULE_NEW_FACTORY_MODULE_4X5_TP_TEST_SUPPORT 1 //4*5 = 20宫格TP触摸测试
#define UTE_MODULE_NEW_FACTORY_MODULE_4X5_TP_TOTAL 20
// #define UTE_MODULE_NEW_FACTORY_MODULE_MAX 13
#define UTE_MODULE_NEW_FACTORY_MODULE_END_RESET_SUPPORT 1 //模块测试结束之后复位重启
#define UTE_MODULE_NEW_FACTORY_MODULE_HEART_CHECK_LIGHT_SUPPORT 1 //新工厂模块测试默认有心率漏光测试
#define UTE_DRV_NEW_FACTORY_TEST_BATTERY_CE_AUTH_ALLOW_TEMPERATURE 58.0f //工厂测试温度限制
#define UTE_DRV_NEW_FACTORY_TEST_BATTERY_CE_AUTH_NOT_ALLOW_TEMPERATURE 60.0f
#define UTE_MODULE_NEW_FACTORY_MODE_SELECT_SCREENS_STRING_ENLARGEMENT 2
#define UTE_MODULE_NEW_FACTORY_AGING_TEST_SCREENS_STRING_ENLARGEMENT 2
#define UTE_MODULE_NEW_FACTORY_MODULE_TEST_SCREENS_STRING_ENLARGEMENT 2
#define UTE_MODULE_NEW_FACTORY_TEST_CHAR_EN_SUPPORT  1
#define UTE_MODULE_NEW_FACTORY_TEST_RING_SUPPORT    1 //工厂测试音频测试
#endif

#define UTE_MODULE_SCREENS_TP_TEST   1 //TP调试功能，内部调试TP报点使用

/*! 船运模式,wang.luo 2025-08-06 */
#define UTE_MODULE_SHIP_MODE_SUPPORT 1

/* 电池容量 zn.zeng 2022-01-07*/
#define UTE_DRV_BATTERY_ELECTRICITY_POWER_MAH      260 //280 //mAh

/* 电池曲线 zn.zeng 2022-01-03*/
#define UTE_DRV_BATTERY_000      3500   //3564
#define UTE_DRV_BATTERY_010      3677   //3698
#define UTE_DRV_BATTERY_020      3727   //3744
#define UTE_DRV_BATTERY_030      3764   //3765
#define UTE_DRV_BATTERY_040      3799   //3780
#define UTE_DRV_BATTERY_050      3841   //3807
#define UTE_DRV_BATTERY_060      3902   //3856
#define UTE_DRV_BATTERY_070      4005   //3908
#define UTE_DRV_BATTERY_080      4100   //3964
#define UTE_DRV_BATTERY_090      4203   //4045
#define UTE_DRV_BATTERY_100      4315   //4128

#define UTE_DRV_BATTERY_MAX_VOLTAGE 4400

//两次低电提醒
#define UTE_DRV_BATTERY_LOW_POWER_FIRST_PERECNT 21
#define UTE_DRV_BATTERY_LOW_POWER_PERECNT 11

/* 充电CE认证 zn.zeng 2022-01-03*/
#define UTE_DRV_BATTERY_CE_AUTH_SUPPORT 1

/* 充电CE认证允许充电温度 zn.zeng 2022-01-03*/
#define UTE_DRV_BATTERY_CE_AUTH_ALLOW_TEMPERATURE 39.0f
#define UTE_DRV_BATTERY_CE_AUTH_NOT_ALLOW_TEMPERATURE 42.0f
#define UTE_DRV_BATTERY_CE_AUTH_ALLOW_LOW_TEMPERATURE 5.0f
#define UTE_DRV_BATTERY_CE_AUTH_NOT_ALLOW_LOW_TEMPERATURE 2.0f

// #define UTE_DRV_TP_X_AXIS_EXCHANGE 1 // 交换X轴左右坐标
// #define UTE_DRV_TP_Y_AXIS_EXCHANGE 1 // 交换Y轴上下坐标
// #define UTE_DRV_TP_SWAP_XY_AXIS_EXCHANGE 1 // 交换X轴Y轴坐标

/*! 血氧功能zn.zeng, 2021-07-23  */
#define UTE_MODULE_BLOODOXYGEN_SUPPORT 1

/*! 一键测量功能,wang.luo 2025-08-11 */
#define UTE_MODULE_ONE_CLICK_MEASURE_SUPPORT 1

/*! 默认切换样式,wang.luo 2025-07-25 */
#define DEFAULT_SWITCH_MODE SWITCH_MODE_ROTARY

/*! 一级界面默认排序,wang.luo 2024-11-16 */
#define UTE_CUI_SCREEN_TBL_SORT_CNT_DEFAULT 7
#define UTE_CUI_SCREEN_TBL_SORT_ARRAY_DEFAULT {FUNC_CLOCK, FUNC_ACTIVITY, FUNC_HEARTRATE,FUNC_BLOOD_OXYGEN, FUNC_PRESSURE,FUNC_SLEEP, FUNC_WEATHER}

/*! 小卡片默认排序,wang.luo 2024-11-16 */
#define UTE_GUI_MINI_CARD_TBL_SORT_CNT_DEFAULT 9
#define UTE_GUI_MINI_CARD_TBL_SORT_ARRAY_DEFAULT {FUNC_ACTIVITY, FUNC_BT, FUNC_HEARTRATE, FUNC_BLOOD_OXYGEN, FUNC_PRESSURE, FUNC_ALARM_CLOCK, FUNC_WEATHER, FUNC_SLEEP, FUNC_SPORT_HISTORY}

/*! 表盘左侧界面,wang.luo 2025-04-07 */
#define UTE_CUI_SCREEN_WATCHDIAL_LEFT FUNC_MINI_COMPO_CARD//FUNC_NULL
/*! 表盘上拉界面,wang.luo 2025-04-07 */
#define UTE_CUI_SCREEN_WATCHDIAL_PULLUP FUNC_MESSAGE
/*! 默认表盘索引 zn.zeng, 2021-10-25  */
#define DEFAULT_WATCH_INDEX 0
/*! 最大表盘数量，不包括在线表盘 zn.zeng, 2021-10-23  */
#define UTE_MODULE_SCREENS_WATCH_CNT_MAX 3
/*! 表盘排序地址数组,wang.luo 2024-11-26 */
#define UTE_MODULE_WATCHS_SORT_ADDRESS_ARRAYS {\
                                                UI_BUF_DIALPLATE_D20533001_BIN, \
                                                UI_BUF_DIALPLATE_D20534001_BIN, \
                                                UI_BUF_DIALPLATE_D20535001_BIN, \
                                              }
//     UI_BUF_DIALPLATE_CUBE_BIN

#define UTE_WATCHS_BUTTERFLY_DIAL_SUPPORT 0     // 使用蝴蝶表盘
#define UTE_WATCHS_CUBE_DIAL_SUPPORT 0          // 使用立方体表盘
#define UTE_WATCHS_LIGHT_CUBE_DIAL_SUPPORT 0    // 使用光束立方体表盘
#define UTE_WATCHS_DIALPLATE_BTF_INDEX 1        // 蝴蝶表盘索引
#define UTE_WATCHS_DIALPLATE_CUBE_INDEX 0       // 立方体表盘索引
#define UTE_WATCHS_DIALPLATE_LIGHT_CUBE_INDEX  0// 立方体光束表盘索引

/*! 表盘预览样式选择: 1 横向列表 2 堆叠 3 立体转盘,wang.luo 2025-05-29 */
#define UTE_MODULE_WATCH_PREVIEW_STYLE 1

/*! 多个在线表盘功能，最大表盘个数,默认值为1，在具体项目里面修改此值 zn.zeng, 2022-06-28  */
#define UTE_MODULE_WATCHONLINE_MULTIPLE_MAX_CNT 3
/*! 多个在线表盘功能，每个表盘的起始地址组 zn.zeng, 2022-06-28  */
#define UTE_MODULE_WATCHONLINE_ONE_SIZE (UTE_MODULE_WATCHONLINE_MAX_SIZE / UTE_MODULE_WATCHONLINE_MULTIPLE_MAX_CNT)
#define UTE_MODULE_WATCHONLINE_MULTIPLE_BASE_ADDRESS_ARRAYS {UTE_MODULE_WATCHONLINE_START_ADDRESS, UTE_MODULE_WATCHONLINE_START_ADDRESS + UTE_MODULE_WATCHONLINE_ONE_SIZE, UTE_MODULE_WATCHONLINE_START_ADDRESS + UTE_MODULE_WATCHONLINE_ONE_SIZE * 2}
/*! APP不下发表盘index，手表自己确认在线表盘同步index,wang.luo 2025-09-01 */
#define UTE_MODULE_WATCHONLINE_WRITE_INDEX_AUTO_SUPPORT 1

/*! 充电中下发表盘不需要显示同步界面,wang.luo 2025-09-11 */
#define UTE_MODULE_WATCHONLINE_NOT_SHOW_SYNC_WHEN_CHARGING_SUPPORT 1

/*! 充电中消息不提醒,wang.luo 2025-09-11 */
#define UTE_MODULE_NOTIFY_CHARGING_NOT_REMIND_SUPPORT 1

/*! 相册表盘时间数字字体,wang.luo 2025-06-24 */
#define UTE_WATCHS_PHOTO_TIME_NUM_FONT UI_BUF_0FONT_FONT_NUM_64_BIN

/*! 熄屏显示（时钟屏保）总开关 cxd 2022-05-03 */
#define UTE_MODULE_SCREENS_SCREEN_SAVER_SUPPORT 1
/*! 默认AMOLED息屏时间段  */
#define UTE_MODULE_SCREEN_SAVE_DEFAULT_TIME_BUCKET_OPEN 1
/*! 最大熄屏表盘数量  */
#define UTE_MODULE_SCREENS_DIAL_SCREEN_SAVER_CNT_MAX 2
/*! 默认熄屏表盘开关  */
#define UTE_MODULE_DIAL_SCREEN_DEFAULT_STATUS 0
/*! 熄屏表盘排序数组，写入表盘的资源地址   */
#define UTE_MODULE_DIAL_SCREEN_SAVER_SORT_ADDRESS_ARRAYS {UI_BUF_DIALPLATE_D20712001_BIN, UI_BUF_DIALPLATE_D21117001_BIN}

/*! 先进入IdleMode再设置背光,进入息屏表盘闪烁时打开,wang.luo 2025-09-04 */
#define UTE_MODULE_SCREENS_SET_BACK_LIGHT_AFTER_IDLE_MODE_SUPPORT (1&UTE_DRV_AMOLED_S368X448_GC3A71_193WG2014V1_QSPI_SUPPORT)

#define UTE_MENU_STYLE_CUM_RING1_FUNCTION 1    //传音定制风格
#define UTE_MENU_STYLE_CUM_RING2_FUNCTION 1
#define UTE_MENU_STYLE_DOUBLE_NEXT_ENABLE   1  //双击切换菜单
#define UTE_CUI_SCREEN_MENU_STYLE { \
    MENU_STYLE_HONEYCOMB,/* 蜂窝状菜单 */ \
    MENU_STYLE_LIST,     /* 列表式菜单 */ \
    MENU_STYLE_SUDOKU,   /* 九宫格式菜单 */ \
    MENU_STYLE_KALE,     /* 环形光晕菜单 */ \
    MENU_STYLE_CUM_RING2,/* 环形2定制菜单 */ \
    MENU_STYLE_CUM_RING1,/* 环形1定制菜单 */ \
    MENU_STYLE_WATERFALL /* 瀑布流式菜单 */ \
}

/*! APP设置本地表盘,wuhuowang 2022-11-18*/
#define APP_MODULE_DIAL_SET_WATCH_SUPPORT   1
#define UTE_MODULE_APP_CONTROL_RESTART_SUPPORT  1//app控制重启

/*! 本地铃声默认时长,根据铃声长度来定，超时之后重新开始播铃声 xjc, 2022-04-22  */
#define UTE_MODULE_BT_LOCAL_RINGTONE_DURATION 6
/*! 默认的本地铃声序号 xjc, 2022-04-19  */
#define UTE_MODULE_BT_RINGTONE_HF_CALL_IN_INDEX 0X00

/*! 查找手环支持铃声播放 xjc, 2022-05-12  */
#define UTE_MODULE_LOCAL_RINGTONE_FIND_SUPPORT 1
/*! 查找手环铃声时长,根据铃声长度来定，超时之后重新开始播铃声 xjc, 2022-05-12  */
#define UTE_MODULE_LOCAL_RINGTONE_FIND_DURATION 4
#define UTE_MODULE_LOCAL_RINGTONE_FIND_TIME 150
/*! 查找手环铃声的序号 xjc, 2022-05-12  */
#define UTE_MODULE_LOCAL_RINGTONE_FIND_INDEX 0x02

/*! 闹钟铃声时长,根据铃声长度来定，超时之后重新开始播铃声 xjc, 2022-05-12  */
#define UTE_MODULE_LOCAL_RINGTONE_ALARM_DURATION 4
/*! 闹钟铃声的序号 xjc, 2022-05-12  */
#define UTE_MODULE_LOCAL_RINGTONE_ALARM_INDEX 0x01

/*! 闹钟铃声使用最大音量播放,wang.luo 2025-09-24 */
#define UTE_MODULE_LOCAL_RINGTONE_MAX_VOLUME_SUPPORT 1

/*! 新工厂音频测试铃声时长,根据铃声长度来定，超时之后重新开始播铃声 xjc, 2022-05-16*/
#define UTE_MODULE_NEW_FACTORY_TEST_RING_DURATION 6
/*! 新工厂音频测试铃声响铃总时长 xjc, 2022-05-16  */
#define UTE_MODULE_NEW_FACTORY_TEST_RING_TIME 30
/*! 新工厂音频测试铃声的序号 xjc, 2022-05-16  */
#define UTE_MODULE_NEW_FACTORY_TEST_RING_INDEX 0X00

/*! SOS联系人拨号功能,xjc 2022-07-06  */
#define UTE_MODUEL_CALL_SOS_CONTACT_SUPPORT 1

/*电话本名字长度扩展到40byte(unicode)*/
#define UTE_MODUEL_CALL_ADDRESSBOOK_EXPANSION_LENGTH_SUPPORT 0 //开启后联系人只支持70个

/*! 快捷回复短信模块,xjc 2022-07-01  */
#define UTE_MODUEL_QUICK_REPLY_SUPPORT 1
// 界面相关暂时屏蔽
// #define UTE_MODULE_SCREENS_QUICK_REPLY_LIST_SUPPORT (1&UTE_MODUEL_QUICK_REPLY_SUPPORT)
#define UTE_MODULE_SCREEN_QUICK_MESSAGE_SEND_RESAULT_SUPPORT (1&UTE_MODUEL_QUICK_REPLY_SUPPORT)
#define APP_QUICK_REPLY_DISPLAY_RESAULT_SCREEN_NOW (1&UTE_MODUEL_QUICK_REPLY_SUPPORT)//快捷回复立刻显示结果

/*! APP设置紧急呼叫开关,wuhuowang 2022-11-18*/
#define APP_MODULE_CALL_SOS_SWITCH_SUPPORT   (1&UTE_MODUEL_CALL_SOS_CONTACT_SUPPORT)
/*! APP设置蓝牙断开提醒开关,wuhuowang 2022-11-18*/
#define APP_MODULE_BT_DISCONNECT_SWITCH_SUPPORT   1

/*! 床头钟模式(充电界面不息屏),wang.luo 2025-04-29 */
#define UTE_MODULE_BEDSIDE_MODE_SUPPORT 0

#define GUI_SCREEN_SIZE_368X448RGB_I341001_SUPPORT      0    //屏分辨率选择
#define GUI_SCREEN_SIZE_368X448RGB_I345001_SUPPORT      1

#define UTE_FLASH_128MBIT_1280K_MAP_SUPPORT 0                //使用128M flash
#define UTE_FLASH_128MBIT_1380K_MAP_SUPPORT 1

#define UTE_MODULE_LOCAL_SET_LIFT_WRIST_SUPPORT 1
#define UTE_MODULE_POWER_SAVING_SUPPORT     1
#define UTE_MODULE_DRINK_WATER_NOTIFY_SCREEN_SUPPORT 1
#define UTE_MODULE_SCREENS_SETTING_REMIND_SUPPORT 1
#define UTE_MODULE_SEDENTARY_NOTIFY_SET_NOONSLEEP_TIME 1

/*! 把协议解析放到UTE任务，防止阻塞Main线程影响性能,wang.luo 2025-09-23 */
#define UTE_MODULE_PROTOCOL_HANDLER_INTO_USER_TASK_SUPPORT 1

/*! 自动休眠时间大于UTE_BT30_RETRY_CONNECT_TIME_SECOND, zn.zeng 2022-06-30  */
#define UTE_BT30_AUTO_POWRER_OFF_TIME_SECOND (2*60)

#define APP_SYNC_RECORD_TIME_FLAG_SUPPORT 1 //同步数据打上时间tag，同步过的数据不再重复同步，除非数据有变化

//下拉新菜单
#define UTE_MODULE_SCREENS_NEW_DWON_MENU_SUPPORT 1
#define UTE_CUI_SCREEN_WATCHDIAL_DOWN FUNC_CLOCK_DROPDOWN_MENU
#define UTE_CLOCK_DWON_PAGE_NUM 1
#define UTE_MODULE_SCREENS_CLOCK_DWON_MENU_MOVE_MODE 0

#define UTE_TITLE_BAR_HIGH   38

//#define UTE_DRV_CTP_SELECT              CTP_CHSC6X
#define DEFAULT_TP_UPDATE_VER_CHECKOUT_OPEN 1
/*! TP固件升级功能开关*/
#define UTE_DRV_TP_COMMON_FW_UPDATE_SUPPORT 1

/*! TP多击，打开会影响单击速度,wang.luo 2025-04-16 */
#define UTE_DRV_TOUCH_MULTI_CLICK_SUPPORT 1

#define UTE_ALARM_NOTDISTURB_ALLOW_MOTOR_VIBRATION_SUPPORT 1 //勿扰模式闹钟开启马达震动

#define UTE_DRV_SCREEN_WIDTH 368
#define UTE_DRV_SCREEN_HEIGHT 448
#define UTE_DRV_SCREEN_VCI_EN_GPIO_PIN IO_PE3//amoled 时必须定义
#define UTE_DRV_SCREEN_VCI_EN_ACTIVE_LEVEL 1

#define UTE_DRV_SCREEN_BACKLIGHT_PWM_SUPPORT 0  //amoled 时没有背光

/*! 默认亮屏时间zn.zeng, 2021-08-20  */
#define DEFAULT_SCREEN_ON_TIME_SECOND 5

/*! 相同分辨率不同R角的在线表盘区分,R角范围0~255 xjc 2023-07-05 */
#define UTE_MODULE_WATCHONLINNE_R_VALUE 102

#define SWITCHING_LR_STEP               (UTE_DRV_SCREEN_WIDTH / 8)     //左右转场松手后自动切换单位步进
#define SWITCHING_UD_STEP               (UTE_DRV_SCREEN_HEIGHT / 8)    //上下转场松手后自动切换单位步进

/*! 天气增加紫外强度和湿度 2022-09-22  */
#define UTE_MODULE_WEATHER_HUMIDITY_ULTRAVIOLET_SUPPORT 1
/*! APP下发未来24小时天气,wuhuowang 2022-11-18*/
#define APP_MODULE_WEATHER_HOURS_INFO_SUPPORT (1 & UTE_MODULE_WEATHER_HUMIDITY_ULTRAVIOLET_SUPPORT)
/*! 支持天气类型扩展,wuhuowang 2022-12-10*/
#define APP_MODULE_WEATHER_TYPE_EXTEND_SUPPORT (1 & APP_MODULE_WEATHER_HOURS_INFO_SUPPORT)

#define UTE_MODULE_POWERON_LANGUAGE_SELECT_SUPPORT 1

#define UTE_MODULE_SCREENS_POWERON_SUPPORT            1 //开机logo界面
#define UTE_MODULE_SCREENS_UP_MENU_SUPPORT            0 //上拉菜单
#define UTE_MODULE_SCREENS_DWON_MENU_SUPPORT          0 //下拉菜单
#define UTE_MODULE_SCREENS_LINK_MAN_SUPPORT           1 //联系人
#define UTE_MODULE_SCREENS_TIMER_SUPPORT              1 //计时器
#define UTE_MODULE_SCREENS_CAMERA_SUPPORT             1 //遥控拍照
#define UTE_MODULE_SCREENS_STOPWATCH_SUPPORT          1 //秒表
#define UTE_MODULE_SCREENS_VOICE_SUPPORT              1 //语音
#define UTE_MODULE_SCREENS_ALARM_SUPPORT              1 //闹钟
#define UTE_MODULE_SCREENS_SYNC_WATCH_ONLINE_SUPPORT  1 //在线表盘同步界面
#define UTE_MODULE_SCREENS_LOW_BATTERY_NOTIFY_SUPPORT 1 //低电提醒
#define UTE_MODULE_SCREENS_WEATHER_SUPPORT            1 //天气
#define UTE_MODULE_SCREENS_GAME_SUPPORT               1 //游戏
#define UTE_MODULE_SCREENS_FIND_PHNOE_SUPPORT         1 //找手机
#define UTE_MODULE_SCREENS_RESFY_SUPPORT              1 //恢复出厂
#define UTE_MODULE_SCREENS_BLOOD_OXYGEN_SUPPORT       (1&UTE_MODULE_BLOODOXYGEN_SUPPORT) //血氧
#define UTE_MODULE_SCREENS_BLOOD_OXYGEN_INFO_SUPPORT  (1&UTE_MODULE_SCREENS_BLOOD_OXYGEN_SUPPORT) //血氧说明界面
#define UTE_MODULE_SCREENS_ACTIVITY_SUPPORT           1 //每日活动
#define UTE_MODULE_SCREENS_FLASHLIGHT_SUPPORT         1 //手电筒
#define UTE_MODULE_SCREENS_SPORT_SUPPORT              1 //运动
#define UTE_MODULE_SCREENS_LANGUAGE_SUPPORT           0 //语言
#define UTE_MODULE_SCREENS_BREATHE_SUPPORT            1 //呼吸
#define UTE_MODULE_SCREENS_HEARTRATE_SUPPORT          1 //心率
#define UTE_MODULE_SCREENS_HEARTRATE_INFO_SUPPORT     (0&UTE_MODULE_SCREENS_HEARTRATE_SUPPORT) //心率说明界面
#define UTE_MODULE_SCREENS_STYLE_SUPPORT              1 //主题
#define UTE_MODULE_SCREENS_SLEEP_SUPPORT              1 //睡眠
#define UTE_MODULE_SCREENS_LIGHT_SUPPORT              1 //亮度调节
#define UTE_MODULE_SCREENS_MUSIC_SUPPORT              1 //音乐
#define UTE_MODULE_SCREENS_MESSAGE_SUPPORT            1 //信息
#define UTE_MODULE_SCREENS_CALL_SUPPORT               1 //电话
#define UTE_MODULE_SCREENS_CALL_ABOUT_SUPPORT         1 //电话说明
#define UTE_MODULE_SCREENS_SETTING_SUPPORT            1 //设置
#define UTE_MODULE_SCREENS_CALCULATOR_SUPPORT         1 //计算器
#define UTE_MODULE_SCREENS_RESTART_SUPPORT            1 //重启
#define UTE_MODULE_SCREENS_CALENDAER_SUPPORT          0 //日历
#define UTE_MODULE_SCREENS_SCAN_SUPPORT               1 //二维码
#define UTE_MODULE_SCREENS_SCAN_ABOUT_SUPPORT         1 //开机二维码说明
#define UTE_MODULE_SCREENS_SCAN_EXPAND_SUPPORT        1 //开机二维码点击放大
#define UTE_MODULE_SCREENS_HEART_WARNING_SUPPORT      1 //心率预警
#define UTE_MODULE_SCREENS_SYSTEM_SUPPORT             1 //系统设置列表界面
#define UTE_MODULE_SCREENS_DIAL_AND_THEME_SUPPORT     0 //主题&表盘列表界面
#define UTE_MODULE_SCREENS_CLOCK_SUB_SIDE_SUPPORT     0 //表盘侧边栏
#define UTE_MODULE_SCREENS_ROTARY_MENUSTYLE_SUPPORT   0 //菜单样式预览旋转界面
#define UTE_MODULE_SCREENS_BRIGHT_SET_SUPPORT         1 //亮度设置列表界面
#define UTE_MODULE_SCREENS_SUB_SOS_SUPPORT            1 //SOS界面
#define UTE_MODULE_SCREENS_TOOLBOX_SUPPORT            0 //工具箱列表
#define UTE_MODULE_SCREENS_MOTOR_GRADE_SUPPORT        1 //震动强度
#if UTE_MODULE_EMOTION_PRESSURE_SUPPORT
#define UTE_MODULE_SCREENS_EMOTION_SUPPORT            0 //情绪界面
#define UTE_MODULE_SCREENS_EMOTION_ABOUT_SUPPORT      0 //情绪说明界面
#define UTE_MODULE_SCREENS_PRESSURE_SUPPORT           1 //压力界面
#define UTE_MODULE_SCREENS_PRESSURE_ABOUT_SUPPORT     1 //压力说明界面
#endif
#define UTE_MODULE_SCREENS_MINI_CARD_SUPPORT          1 //小组件
#define UTE_MODULE_SCREENS_QUICKLY_SET_SUPPORT        (1&UTE_MODULE_SCREENS_MINI_CARD_SUPPORT)//快捷设置
#define UTE_MODULE_SCREENS_WOMEN_HEALTH_SUPPORT       1 //女性健康
#if UTE_MODULE_SCREENS_GAME_SUPPORT
#define UTE_MODULE_SCREENS_BIRD_SUPPORT               (1) //飞扬小鸟
#define UTE_MODULE_SCREENS_TETRIS_SUPPORT             (1) //俄罗斯方块
#endif
#define UTE_MODULE_SCREENS_SCREEN_LIFT_WRIST_HANDLE_SUPPORT 1 //抬手亮屏设置

#define UTE_MODULE_SCREENS_VOLUME_SUPPORT              1 //媒体音频音量设置界面
#define UTE_MODULE_SCREENS_TBL_SORT_CUBE_SUPPORT       1 //快捷魔方界面

#define UTE_MODULE_SCREENS_WORLD_CLOCK_SUPPORT         1   //世界时钟
/*! 世界时钟时区设置模块,wang.luo 2025-07-07 */
#define UTE_MODULE_TIME_ZONE_SETTING_SUPPORT  UTE_MODULE_SCREENS_WORLD_CLOCK_SUPPORT
/*! 世界时钟支持四分之一时区,wuhuowang 2022-11-18*/
#define UTE_MODULE_WORLD_CLOCK_QUARTER_TIME_SUPPORT (1 & UTE_MODULE_TIME_ZONE_SETTING_SUPPORT)
#define UTE_MODULE_WORLD_CLOCK_TOTAL_CNT 6

#define UTE_MODULE_SCREENS_MEASURE_SUPPORT              1 //  一键测量

#define  UTE_MODULE_SCREENS_SPORT_SET_SUPPORT     (1 & UTE_MODULE_SCREENS_SPORT_SUPPORT)   //传音定制界面

/*! 最大心率设置,wuhuowang 2022-11-18*/
#define APP_MODULE_HEART_MAX_HEARTRATE_SET_SUPPORT   1
#define UTE_SPORTS_HEART_MAX_MIN_WARNING_NOTIFY_SUPPORT 1 //运动心率预警提醒
/*运动心率警告第一次提醒时间秒*/
#define UTE_MODULE_SPORT_HEART_MIN_MAX_WARNING_FRIST_SECOND_CNT 0
/*运动心率警告重复提醒时间*/
#define UTE_MODULE_SPORT_HEART_MIN_MAX_WARNING_RELOAD_SECOND_CNT 300

#define APP_MODULE_SPORT_SLIDE_NOT_PAUSE_SUPPORT   1
#define UTE_MODULE_SCREENS_SPORT_TARGET_NOTIFY_SUPPORT 1 //运动目标提醒界面
#define UTE_MODULE_SCREENS_TARGET_SELECT_SUPPORT 1       //运动目标选择界面
#define UTE_SPORTS_ONE_HOUR_TARGET_NOTIFY_SUPPORT 1 //运动1小时提醒
#define UTE_SPORTS_ONE_KM_TARGET_NOTIFY_SUPPORT 1 //运动1千米提醒
#define APP_MODULE_SCREENS_TARGET_MORE_SUPPORT (1&UTE_MODULE_SCREENS_SPORT_SET_SUPPORT) //每个运动对应一个目标
#define APP_MODULE_SCREENS_TARGET_MORE_REMIND_ONLY_ONE_TARGET 1 // 仅提醒一个运动目标
#define UTE_MODULE_SPORTS_HSTORY_RECORD_SUPPORT (1 &UTE_MODULE_SCREENS_SPORT_SUPPORT)  //运动历史记录
#define UTE_MORE_SPORTS_DEFAULT_DISTANCE_TARGET 3000//米
#define UTE_MORE_SPORTS_DEFAULT_KCAL_TARGET 300
#define UTE_MORE_SPORTS_DEFAULT_TIME_TARGET_MIN 30//min
#define UTE_MODULE_SPORT_MORE_SPORTS_DATA_MAX_CNT 20 //多运动保存最大条数

//未完善
#define UTE_MODULE_SCREENS_APP_BINDING_SUPPORT        1 /*绑定界面*/
#define UTE_MODULE_SCREENS_POWER_ON_LANGUAGE_SELECT_SUPPORT 1 /*开机选择语言界面*/
#define UTE_APP_BINDING_ONLY_ONCENOTIFY_SUPPORT 1

/*! 绑定功能宏 pcm, 2025-05-09  */
#define UTE_USER_ID_FOR_BINDING_SUPPORT 1
#define HAS_BEEN_CONNECTED 0x66
#define UTE_VERIFY_OUR_APP_APK_DEFUALT_TIMEOUT 60

#define UTE_QRCODE_BINDING_NO_CONFIRM_SUPPORT 1//扫码绑定不需要确认,此时二维码需要添加8位的随机码

/*! 传音绑定流程,wuhuowang 2022-11-18*/
#define APP_MODULE_ORAIMO_BINDING_SUPPORT   1
#define APP_RANDCODE_USERID_SUPPORT 1 //绑定同时下发user ID和随机码

/*! 未绑定APP自动关机,wang.luo 2025-08-06 */
#define UTE_MODULE_UNBOUND_AUTO_POWER_OFF_SUPPORT 1

/*! 未绑定APP自动关机时间,wang.luo 2025-08-06 */
#define UTE_MODULE_UNBOUND_AUTO_POWER_OFF_SECONDS 1800

#define UTE_MODULE_SCREENS_APP_BINDING_NOTIFY_SUPPORT 1

#define UTE_BINDING_QRENCODE_LINK "https://static-ie.oraimo.com/oh.htm"

#define APP_CUSTOM_REMIND_SETTING_SUPPORT 1 //支持祈祷提醒设置
#define APP_CUSTOM_REMIND_SETTING_MAX_CNT 7
#define APP_CUSTOM_REMIND_SETTING_DAY_CNT 5
#define APP_CUSTOM_REMIND_SETTING_DAY_SIZE 24
#define DEFAULT_APP_CUSTOM_REMIND_SUPPORT false

/*! 默认语言 zn.zeng, 2021-08-23  */
#ifndef DEFAULT_LANGUAGE
#define DEFAULT_LANGUAGE 0x02//ENGLISH_LANGUAGE_ID
#define SCREEN_TITLE_MULTIPLE_CHINESE_LANGUAGE_SUPPORT              1 //中文 1
#define SCREEN_TITLE_MULTIPLE_ENGLISH_LANGUAGE_SUPPORT              1 //英文 2
#define SCREEN_TITLE_MULTIPLE_KOREAN_LANGUAGE_SUPPORT               0 //韩文 3
#define SCREEN_TITLE_MULTIPLE_JAPANESE_LANGUAGE_SUPPORT             0 //日文 4
#define SCREEN_TITLE_MULTIPLE_GERMAN_LANGUAGE_SUPPORT               1 //德文 5
#define SCREEN_TITLE_MULTIPLE_SPANISH_LANGUAGE_SUPPORT              1 //西班牙文 6
#define SCREEN_TITLE_MULTIPLE_FRENCH_LANGUAGE_SUPPORT               1 //法文 7
#define SCREEN_TITLE_MULTIPLE_ITALIAN_LANGUAGE_SUPPORT              1 //意大利文 8
#define SCREEN_TITLE_MULTIPLE_PORTUGUESE_LANGUAGE_SUPPORT           1 //葡萄牙文 9
#define SCREEN_TITLE_MULTIPLE_ARABIC_LANGUAGE_SUPPORT               1 //阿拉伯文 A
#define SCREEN_TITLE_MULTIPLE_INDIA_LANGUAGE_SUPPORT                0 //India     B
#define SCREEN_TITLE_MULTIPLE_HINDI_LANGUAGE_SUPPORT                0 //印地语  C
#define SCREEN_TITLE_MULTIPLE_POLISH_LANGUAGE_SUPPORT               0 //波兰语  D
#define SCREEN_TITLE_MULTIPLE_RUSSIAN_LANGUAGE_SUPPORT              1 //俄语  E
#define SCREEN_TITLE_MULTIPLE_DUTCH_LANGUAGE_SUPPORT                0 //荷兰语 F
#define SCREEN_TITLE_MULTIPLE_TURKISH_LANGUAGE_SUPPORT              0 //土耳其语  10
#define SCREEN_TITLE_MULTIPLE_BENGALI_LANGUAGE_SUPPORT              0 //孟加拉语  11  Bengali
#define SCREEN_TITLE_MULTIPLE_URDU_LANGUAGE_SUPPORT                 0 //乌尔都语   12  Urdu
#define SCREEN_TITLE_MULTIPLE_INDONESUAN_LANGUAGE_SUPPORT           1 //印度尼西亚语（爪哇语）  13  Indonesian
#define SCREEN_TITLE_MULTIPLE_PUNJABI_LANGUAGE_SUPPORT              0 //旁遮普语  14   Punjabi
#define SCREEN_TITLE_MULTIPLE_THAI_LANGUAGE_SUPPORT                 1 //泰文  15   Thai
#define SCREEN_TITLE_MULTIPLE_CZECH_LANGUAGE_SUPPORT                0 //捷克语  16  Czech
#define SCREEN_TITLE_MULTIPLE_TRADITIONAL_CHINESE_LANGUAGE_SUPPORT  0 //繁体中文
#define SCREEN_TITLE_MULTIPLE_ROMANIAN_LANGUAGE_SUPPORT             0 //罗马尼亚语 limba 0x1B
#define SCREEN_TITLE_MULTIPLE_VIETNAMESE_LANGUAGE_SUPPORT           1 //越南语 0x63
#define SCREEN_TITLE_MULTIPLE_MALAYSIA_LANGUAGE_SUPPORT             0 //马来西亚语 0x40
#define SCREEN_TITLE_MULTIPLE_FARSI_LANGUAGE_SUPPORT                1 //波斯语（伊朗）
#endif // DEFAULT_LANGUAGE


/*! 多运动支持百种运动标志, xjc 2022-03-09  */
#define UTE_MODULE_SPORT_HUNDRED_SUPPORT 1
#define UTE_MODULE_SPORT_MAX_SPORT_NUM          116
#define UTE_MODULE_SPORT_DISPLAY_MIN_SPORT_NUM  9
#define UTE_MODULE_SPORT_DISPLAY_MAX_SPORT_NUM  (20)
/*! 具体的运动类型,支持的置1,不支持置0, xjc 2222-03-29*/
#define UTE_MODULE_SPORT_RUNNING_SUPPORT                1 //跑步
#define UTE_MODULE_SPORT_BIKE_SUPPORT                   1 //骑行
#define UTE_MODULE_SPORT_JUMP_ROPE_SUPPORT              1 //跳绳
#define UTE_MODULE_SPORT_SWIMMING_SUPPORT               1 //游泳
#define UTE_MODULE_SPORT_BADMINTION_SUPPORT             1 //羽毛球
#define UTE_MODULE_SPORT_TABLE_TENNIS_SUPPORT           1 //乒乓球
#define UTE_MODULE_SPORT_TENNIS_SUPPORT                 1 //网球
#define UTE_MODULE_SPORT_CLIMBING_SUPPORT               1 //登山
#define UTE_MODULE_SPORT_WALKING_SUPPORT                1 //徒步
#define UTE_MODULE_SPORT_BASKETBALL_SUPPORT             1 //篮球
#define UTE_MODULE_SPORT_FOOTBALL_SUPPORT               1 //足球
#define UTE_MODULE_SPORT_BASEBALL_SUPPORT               1 //棒球（或垒球）
#define UTE_MODULE_SPORT_VOLLEYBALL_SUPPORT             1 //排球
#define UTE_MODULE_SPORT_CRICKET_SUPPORT                1 //板球
#define UTE_MODULE_SPORT_RUGBY_SUPPORT                  1 //橄榄球（或美式足球）
#define UTE_MODULE_SPORT_HOCKEY_SUPPORT                 1 //曲棍球
#define UTE_MODULE_SPORT_DANCE_SUPPORT                  1 //跳舞
#define UTE_MODULE_SPORT_SPINNING_SUPPORT               1 //动感单车
#define UTE_MODULE_SPORT_YOGA_SUPPORT                   1 //瑜伽
#define UTE_MODULE_SPORT_SIT_UP_SUPPORT                 1 //仰卧起坐
#define UTE_MODULE_SPORT_TREADMILL_SUPPORT              1 //跑步机
#define UTE_MODULE_SPORT_GYMNASTICS_SUPPORT             1 //体操
#define UTE_MODULE_SPORT_BOATING_SUPPORT                1 //划船
#define UTE_MODULE_SPORT_JUMPING_JACK_SUPPORT           1 //开合跳
#define UTE_MODULE_SPORT_FREE_TRAINING_SUPPORT          1 //自由训练
#if UTE_MODULE_SPORT_HUNDRED_SUPPORT
#define UTE_MODULE_SPORT_INDOOR_WALK_SUPPORT            1 //0x1A,室内走路
#define UTE_MODULE_SPORT_INDOOR_RUN_SUPPORT             1 //0x1B,室内跑步
#define UTE_MODULE_SPORT_STRENGTH_TRAINING_SUPPORT      1 //0x1C,力量训练
#define UTE_MODULE_SPORT_STEP_TRAINING_SUPPORT          1 //0x1D,踏步
#define UTE_MODULE_SPORT_HORSE_RIDING_SUPPORT           1 //0x1E,骑马
#define UTE_MODULE_SPORT_ELLIPTICAL_TRAINER_SUPPORT     1 //0x1F,椭圆机
#define UTE_MODULE_SPORT_TAI_CHI_SUPPORT                1 //0x20,太极
#define UTE_MODULE_SPORT_SHUTTLECOCK_SUPPORT            1 //0x21,毽球
#define UTE_MODULE_SPORT_BOXING_SUPPORT                 1 //0x22,拳击
#define UTE_MODULE_SPORT_OUTDOOR_WALK_SUPPORT           1 //0x23,户外健走
#define UTE_MODULE_SPORT_TRAIL_RUNNING_SUPPORT          1 //0x24,越野跑
#define UTE_MODULE_SPORT_SKIING_SUPPORT                 1 //0x25,滑雪
#define UTE_MODULE_SPORT_ICE_HOCKEY_SUPPORT             1 //0x26,冰球
#define UTE_MODULE_SPORT_TAEKWONDO_SUPPORT              1 //0x27,跆拳道
#define UTE_MODULE_SPORT_VO2MAX_TEST_SUPPORT            1 //0x28,最大摄氧量测试
#define UTE_MODULE_SPORT_ROWING_MACHING_SUPPORT         1 //0x29,划船机
#define UTE_MODULE_SPORT_AIR_WALKER_SUPPORT             1 //0x2A,漫步机
#define UTE_MODULE_SPORT_HIKING_SUPPORT                 1 //0x2B,徒步
#define UTE_MODULE_SPORT_ATHLETICS_SUPPORT              1 //0x2C,田径
#define UTE_MODULE_SPORT_WAIST_TRAINING_SUPPORT         1 //0x2D,腰腹训练
#define UTE_MODULE_SPORT_KARATE_SUPPORT                 1 //0x2E,空手道
#define UTE_MODULE_SPORT_COOLDOWN_SUPPORT               1 //0x2F,整理放松
#define UTE_MODULE_SPORT_CROSS_TRAINING_SUPPORT         1 //0x30,交叉训练
#define UTE_MODULE_SPORT_PILATES_SUPPORT                1 //0x31,普拉提
#define UTE_MODULE_SPORT_CROSS_FIT_SUPPORT              1 //0x32,交叉配合
#define UTE_MODULE_SPORT_FUNCTIONAL_TRAINING_SUPPORT    1 //0x33,功能性训练
#define UTE_MODULE_SPORT_PHYSICAL_TRAINING_SUPPORT      1 //0x34,体能训练
#define UTE_MODULE_SPORT_ARCHERY_SUPPORT                1 //0x35,射箭
#define UTE_MODULE_SPORT_FLEXIBILITY_SUPPORT            1 //0x36,柔韧度
#define UTE_MODULE_SPORT_MIXED_CARDIO_SUPPORT           1 //0x37,混合有氧
#define UTE_MODULE_SPORT_LATIN_DANCE_SUPPORT            1 //0x38,拉丁舞
#define UTE_MODULE_SPORT_STREET_DANCE_SUPPORT           1 //0x39,街舞
#define UTE_MODULE_SPORT_KICKBOXING_SUPPORT             1 //0x3A,自由搏击
#define UTE_MODULE_SPORT_BARRE_SUPPORT                  1 //0x3B,芭蕾
#define UTE_MODULE_SPORT_AUSTRALIAN_FOOTBALL_SUPPORT    1 //0x3C,澳式足球
#define UTE_MODULE_SPORT_MARTIAL_ARTS_SUPPORT           1 //0x3D,武术
#define UTE_MODULE_SPORT_STAIRS_SUPPORT                 1 //0x3E,爬楼
#define UTE_MODULE_SPORT_HANDBALL_SUPPORT               1 //0x3F,手球
#define UTE_MODULE_SPORT_BOWLING_SUPPORT                1 //0x40,保龄球
#define UTE_MODULE_SPORT_RACQUETBALL_SUPPORT            1 //0x41,壁球
#define UTE_MODULE_SPORT_CURLING_SUPPORT                1 //0x42,冰壶
#define UTE_MODULE_SPORT_HUNTING_SUPPORT                1 //0x43,打猎
#define UTE_MODULE_SPORT_SNOWBOARDING_SUPPORT           1 //0x44,单板滑雪
#define UTE_MODULE_SPORT_PLAY_SUPPORT                   1 //0x45,休闲运动
#define UTE_MODULE_SPORT_AMERICAN_FOOTBALL_SUPPORT      1 //0x46,美式橄榄球
#define UTE_MODULE_SPORT_HAND_CYCLING_SUPPORT           1 //0x47,手摇车
#define UTE_MODULE_SPORT_FISHING_SUPPORT                1 //0x48,钓鱼
#define UTE_MODULE_SPORT_DISC_SPORTS_SUPPORT            1 //0x49,飞盘
#define UTE_MODULE_SPORT_RUGGER_SUPPORT                 1 //0x4A,橄榄球
#define UTE_MODULE_SPORT_GOLF_SUPPORT                   1 //0x4B,高尔夫
#define UTE_MODULE_SPORT_FOLK_DANCE_SUPPORT             1 //0x4C,民族舞
#define UTE_MODULE_SPORT_DOWNHILL_SKIING_SUPPORT        1 //0x4D,高山滑雪
#define UTE_MODULE_SPORT_SNOW_SPORTS_SUPPORT            1 //0x4E,雪上运动
#define UTE_MODULE_SPORT_MIND_BODY_SUPPORT              1 //0x4F,舒缓冥想类运动
#define UTE_MODULE_SPORT_CORE_TRAINING_SUPPORT          1 //0x50,核心训练
#define UTE_MODULE_SPORT_SKATING_SUPPORT                1 //0x51,滑冰
#define UTE_MODULE_SPORT_FITNESS_GAMING_SUPPORT         1 //0x52,健身游戏
#define UTE_MODULE_SPORT_AEROBICS_SUPPORT               1 //0x53,健身操
#define UTE_MODULE_SPORT_GROUP_TRAINING_SUPPORT         1 //0x54,团体操
#define UTE_MODULE_SPORT_KENDO_SUPPORT                  1 //0x55,搏击操
#define UTE_MODULE_SPORT_LACROSSE_SUPPORT               1 //0x56,长曲棍球
#define UTE_MODULE_SPORT_ROLLING_SUPPORT                1 //0x57,泡沫轴筋膜放松
#define UTE_MODULE_SPORT_WRESTLING_SUPPORT              1 //0x58,摔跤
#define UTE_MODULE_SPORT_FENCING_SUPPORT                1 //0x59,击剑
#define UTE_MODULE_SPORT_SOFTBALL_SUPPORT               1 //0x5A,垒球
#define UTE_MODULE_SPORT_SINGLE_BAR_SUPPORT             1 //0x5B,单杠
#define UTE_MODULE_SPORT_PARALLEL_BARS_SUPPORT          1 //0x5C,双杠
#define UTE_MODULE_SPORT_ROLLER_SKATING_SUPPORT         1 //0x5D,轮滑
#define UTE_MODULE_SPORT_HULA_HOOP_SUPPORT              1 //0x5E,呼啦圈
#define UTE_MODULE_SPORT_DARTS_SUPPORT                  1 //0x5F,飞镖
#define UTE_MODULE_SPORT_PICKLEBALL_SUPPORT             1 //0x60,匹克球
#define UTE_MODULE_SPORT_HIIT_SUPPORT                   1 //0x61,HIIT
#define UTE_MODULE_SPORT_SHOOTING_SUPPORT               1 //0x62,射击
#define UTE_MODULE_SPORT_JUDO_SUPPORT                   1 //0x63,柔道
#define UTE_MODULE_SPORT_TRAMPOLINE_SUPPORT             1 //0x64,蹦床
#define UTE_MODULE_SPORT_SKATEBOARDING_SUPPORT          1 //0x65,滑板
#define UTE_MODULE_SPORT_HOVERBOARD_SUPPORT             1 //0x66,平衡车
#define UTE_MODULE_SPORT_BLADING_SUPPORT                1 //0x67,溜旱冰
#define UTE_MODULE_SPORT_PARKOUR_SUPPORT                1 //0x68,跑酷
#define UTE_MODULE_SPORT_DIVING_SUPPORT                 1 //0x69,跳水
#define UTE_MODULE_SPORT_SURFING_SUPPORT                1 //0x6A,冲浪
#define UTE_MODULE_SPORT_SNORKELING_SUPPORT             1 //0x6B,浮潜
#define UTE_MODULE_SPORT_PULL_UP_SUPPORT                1 //0x6C,引体向上
#define UTE_MODULE_SPORT_PUSH_UP_SUPPORT                1 //0x6D,俯卧撑
#define UTE_MODULE_SPORT_PLANKING_SUPPORT               1 //0x6E,平板支撑
#define UTE_MODULE_SPORT_ROCK_CLIMBING_SUPPORT          1 //0x6F,攀岩
#define UTE_MODULE_SPORT_HIGHTJUMP_SUPPORT              1 //0x70,跳高
#define UTE_MODULE_SPORT_BUNGEE_JUMPING_SUPPORT         1 //0x71,蹦极
#define UTE_MODULE_SPORT_LONGJUMP_SUPPORT               1 //0x72,跳远
#define UTE_MODULE_SPORT_MARATHON_SUPPORT               1 //0x73,马拉松
/*! 运动显示开关,默认显示的置1,不显示置0, xjc 2222-03-29*/
#define UTE_MODULE_SPORT_RUNNING_ON_OFF                 1//跑步
#define UTE_MODULE_SPORT_BIKE_ON_OFF                    1//骑行
#define UTE_MODULE_SPORT_JUMP_ROPE_ON_OFF               0//跳绳
#define UTE_MODULE_SPORT_SWIMMING_ON_OFF                0//游泳
#define UTE_MODULE_SPORT_BADMINTION_ON_OFF              1//羽毛球
#define UTE_MODULE_SPORT_TABLE_TENNIS_ON_OFF            1//乒乓球
#define UTE_MODULE_SPORT_TENNIS_ON_OFF                  0//网球
#define UTE_MODULE_SPORT_CLIMBING_ON_OFF                1//登山
#define UTE_MODULE_SPORT_WALKING_ON_OFF                 1//徒步
#define UTE_MODULE_SPORT_BASKETBALL_ON_OFF              1//篮球
#define UTE_MODULE_SPORT_FOOTBALL_ON_OFF                1//足球
#define UTE_MODULE_SPORT_BASEBALL_ON_OFF                0//棒球（或垒球）
#define UTE_MODULE_SPORT_VOLLEYBALL_ON_OFF              0//排球
#define UTE_MODULE_SPORT_CRICKET_ON_OFF                 1//板球
#define UTE_MODULE_SPORT_RUGBY_ON_OFF                   0//橄榄球（或美式足球）
#define UTE_MODULE_SPORT_HOCKEY_ON_OFF                  0//曲棍球
#define UTE_MODULE_SPORT_DANCE_ON_OFF                   0//跳舞
#define UTE_MODULE_SPORT_SPINNING_ON_OFF                1//动感单车
#define UTE_MODULE_SPORT_YOGA_ON_OFF                    1//瑜伽
#define UTE_MODULE_SPORT_SIT_UP_ON_OFF                  0//仰卧起坐
#define UTE_MODULE_SPORT_TREADMILL_ON_OFF               1//跑步机
#define UTE_MODULE_SPORT_GYMNASTICS_ON_OFF              0//体操
#define UTE_MODULE_SPORT_BOATING_ON_OFF                 0//划船
#define UTE_MODULE_SPORT_JUMPING_JACK_ON_OFF            0//开合跳
#define UTE_MODULE_SPORT_FREE_TRAINING_ON_OFF           1//自由训练
#define UTE_MODULE_SPORT_INDOOR_WALK_ON_OFF             0//0x1A,室内走路
#define UTE_MODULE_SPORT_INDOOR_RUN_ON_OFF              0//0x1B,室内跑步
#define UTE_MODULE_SPORT_STRENGTH_TRAINING_ON_OFF       1//0x1C,力量训练
#define UTE_MODULE_SPORT_STEP_TRAINING_ON_OFF           0//0x1D,踏步
#define UTE_MODULE_SPORT_HORSE_RIDING_ON_OFF            0//0x1E,骑马
#define UTE_MODULE_SPORT_ELLIPTICAL_TRAINER_ON_OFF      1//0x1F,椭圆机
#define UTE_MODULE_SPORT_TAI_CHI_ON_OFF                 0//0x20,太极
#define UTE_MODULE_SPORT_SHUTTLECOCK_ON_OFF             0//0x21,毽球
#define UTE_MODULE_SPORT_BOXING_ON_OFF                  0//0x22,拳击
#define UTE_MODULE_SPORT_OUTDOOR_WALK_ON_OFF            1//0x23,户外健走
#define UTE_MODULE_SPORT_TRAIL_RUNNING_ON_OFF           1//0x24,越野跑
#define UTE_MODULE_SPORT_SKIING_ON_OFF                  0//0x25,滑雪
#define UTE_MODULE_SPORT_ICE_HOCKEY_ON_OFF              0//0x26,冰球
#define UTE_MODULE_SPORT_TAEKWONDO_ON_OFF               0//0x27,跆拳道
#define UTE_MODULE_SPORT_VO2MAX_TEST_ON_OFF             0//0x28,最大摄氧量测试
#define UTE_MODULE_SPORT_ROWING_MACHING_ON_OFF          0//0x29,划船机
#define UTE_MODULE_SPORT_AIR_WALKER_ON_OFF              0//0x2A,漫步机
#define UTE_MODULE_SPORT_HIKING_ON_OFF                  0//0x2B,徒步
#define UTE_MODULE_SPORT_ATHLETICS_ON_OFF               0//0x2C,田径
#define UTE_MODULE_SPORT_WAIST_TRAINING_ON_OFF          0//0x2D,腰腹训练
#define UTE_MODULE_SPORT_KARATE_ON_OFF                  0//0x2E,空手道
#define UTE_MODULE_SPORT_COOLDOWN_ON_OFF                0//0x2F,整理放松
#define UTE_MODULE_SPORT_CROSS_TRAINING_ON_OFF          0//0x30,交叉训练
#define UTE_MODULE_SPORT_PILATES_ON_OFF                 1//0x31,普拉提
#define UTE_MODULE_SPORT_CROSS_FIT_ON_OFF               0//0x32,交叉配合
#define UTE_MODULE_SPORT_FUNCTIONAL_TRAINING_ON_OFF     0//0x33,功能性训练
#define UTE_MODULE_SPORT_PHYSICAL_TRAINING_ON_OFF       0//0x34,体能训练
#define UTE_MODULE_SPORT_ARCHERY_ON_OFF                 0//0x35,射箭
#define UTE_MODULE_SPORT_FLEXIBILITY_ON_OFF             0//0x36,柔韧度
#define UTE_MODULE_SPORT_MIXED_CARDIO_ON_OFF            1//0x37,混合有氧
#define UTE_MODULE_SPORT_LATIN_DANCE_ON_OFF             0//0x38,拉丁舞
#define UTE_MODULE_SPORT_STREET_DANCE_ON_OFF            0//0x39,街舞
#define UTE_MODULE_SPORT_KICKBOXING_ON_OFF              0//0x3A,自由搏击
#define UTE_MODULE_SPORT_BARRE_ON_OFF                   0//0x3B,芭蕾
#define UTE_MODULE_SPORT_AUSTRALIAN_FOOTBALL_ON_OFF     0//0x3C,澳式足球
#define UTE_MODULE_SPORT_MARTIAL_ARTS_ON_OFF            0//0x3D,武术
#define UTE_MODULE_SPORT_STAIRS_ON_OFF                  0//0x3E,爬楼
#define UTE_MODULE_SPORT_HANDBALL_ON_OFF                0//0x3F,手球
#define UTE_MODULE_SPORT_BOWLING_ON_OFF                 0//0x40,保龄球
#define UTE_MODULE_SPORT_RACQUETBALL_ON_OFF             0//0x41,壁球
#define UTE_MODULE_SPORT_CURLING_ON_OFF                 0//0x42,冰壶
#define UTE_MODULE_SPORT_HUNTING_ON_OFF                 0//0x43,打猎
#define UTE_MODULE_SPORT_SNOWBOARDING_ON_OFF            0//0x44,单板滑雪
#define UTE_MODULE_SPORT_PLAY_ON_OFF                    0//0x45,休闲运动
#define UTE_MODULE_SPORT_AMERICAN_FOOTBALL_ON_OFF       0//0x46,美式橄榄球
#define UTE_MODULE_SPORT_HAND_CYCLING_ON_OFF            0//0x47,手摇车
#define UTE_MODULE_SPORT_FISHING_ON_OFF                 0//0x48,钓鱼
#define UTE_MODULE_SPORT_DISC_SPORTS_ON_OFF             0//0x49,飞盘
#define UTE_MODULE_SPORT_RUGGER_ON_OFF                  0//0x4A,橄榄球
#define UTE_MODULE_SPORT_GOLF_ON_OFF                    0//0x4B,高尔夫
#define UTE_MODULE_SPORT_FOLK_DANCE_ON_OFF              0//0x4C,民族舞
#define UTE_MODULE_SPORT_DOWNHILL_SKIING_ON_OFF         0//0x4D,高山滑雪
#define UTE_MODULE_SPORT_SNOW_SPORTS_ON_OFF             0//0x4E,雪上运动
#define UTE_MODULE_SPORT_MIND_BODY_ON_OFF               0//0x4F,舒缓冥想类运动
#define UTE_MODULE_SPORT_CORE_TRAINING_ON_OFF           1//0x50,核心训练
#define UTE_MODULE_SPORT_SKATING_ON_OFF                 0//0x51,滑冰
#define UTE_MODULE_SPORT_FITNESS_GAMING_ON_OFF          0//0x52,健身游戏
#define UTE_MODULE_SPORT_AEROBICS_ON_OFF                0//0x53,健身操
#define UTE_MODULE_SPORT_GROUP_TRAINING_ON_OFF          0//0x54,团体操
#define UTE_MODULE_SPORT_KENDO_ON_OFF                   0//0x55,搏击操
#define UTE_MODULE_SPORT_LACROSSE_ON_OFF                0//0x56,长曲棍球
#define UTE_MODULE_SPORT_ROLLING_ON_OFF                 0//0x57,泡沫轴筋膜放松
#define UTE_MODULE_SPORT_WRESTLING_ON_OFF               0//0x58,摔跤
#define UTE_MODULE_SPORT_FENCING_ON_OFF                 0//0x59,击剑
#define UTE_MODULE_SPORT_SOFTBALL_ON_OFF                0//0x5A,垒球
#define UTE_MODULE_SPORT_SINGLE_BAR_ON_OFF              0//0x5B,单杠
#define UTE_MODULE_SPORT_PARALLEL_BARS_ON_OFF           0//0x5C,双杠
#define UTE_MODULE_SPORT_ROLLER_SKATING_ON_OFF          0//0x5D,轮滑
#define UTE_MODULE_SPORT_HULA_HOOP_ON_OFF               0//0x5E,呼啦圈
#define UTE_MODULE_SPORT_DARTS_ON_OFF                   0//0x5F,飞镖
#define UTE_MODULE_SPORT_PICKLEBALL_ON_OFF              0//0x60,匹克球
#define UTE_MODULE_SPORT_HIIT_ON_OFF                    0//0x61,HIIT
#define UTE_MODULE_SPORT_SHOOTING_ON_OFF                0//0x62,射击
#define UTE_MODULE_SPORT_JUDO_ON_OFF                    0//0x63,柔道
#define UTE_MODULE_SPORT_TRAMPOLINE_ON_OFF              0//0x64,蹦床
#define UTE_MODULE_SPORT_SKATEBOARDING_ON_OFF           0//0x65,滑板
#define UTE_MODULE_SPORT_HOVERBOARD_ON_OFF              0//0x66,平衡车
#define UTE_MODULE_SPORT_BLADING_ON_OFF                 0//0x67,溜旱冰
#define UTE_MODULE_SPORT_PARKOUR_ON_OFF                 0//0x68,跑酷
#define UTE_MODULE_SPORT_DIVING_ON_OFF                  0//0x69,跳水
#define UTE_MODULE_SPORT_SURFING_ON_OFF                 0//0x6A,冲浪
#define UTE_MODULE_SPORT_SNORKELING_ON_OFF              0//0x6B,浮潜
#define UTE_MODULE_SPORT_PULL_UP_ON_OFF                 0//0x6C,引体向上
#define UTE_MODULE_SPORT_PUSH_UP_ON_OFF                 0//0x6D,俯卧撑
#define UTE_MODULE_SPORT_PLANKING_ON_OFF                0//0x6E,平板支撑
#define UTE_MODULE_SPORT_ROCK_CLIMBING_ON_OFF           0//0x6F,攀岩
#define UTE_MODULE_SPORT_HIGHTJUMP_ON_OFF               0//0x70,跳高
#define UTE_MODULE_SPORT_BUNGEE_JUMPING_ON_OFF          0//0x71,蹦极
#define UTE_MODULE_SPORT_LONGJUMP_ON_OFF                0//0x72,跳远
#define UTE_MODULE_SPORT_MARATHON_ON_OFF                0//0x73,马拉松

/*! 默认显示的运动的顺序,不要重复,不显示的置0, xjc 2222-03-29*/
#define UTE_MODULE_SPORT_RUNNING_ORDER                  1 //跑步
#define UTE_MODULE_SPORT_BIKE_ORDER                     6 //骑行
#define UTE_MODULE_SPORT_JUMP_ROPE_ORDER                0 //跳绳
#define UTE_MODULE_SPORT_SWIMMING_ORDER                 0 //游泳
#define UTE_MODULE_SPORT_BADMINTION_ORDER               12 //羽毛球
#define UTE_MODULE_SPORT_TABLE_TENNIS_ORDER             11 //乒乓球
#define UTE_MODULE_SPORT_TENNIS_ORDER                   0 //网球
#define UTE_MODULE_SPORT_CLIMBING_ORDER                 5 //登山
#define UTE_MODULE_SPORT_WALKING_ORDER                  13 //徒步
#define UTE_MODULE_SPORT_BASKETBALL_ORDER               9 //篮球
#define UTE_MODULE_SPORT_FOOTBALL_ORDER                 10 //足球
#define UTE_MODULE_SPORT_BASEBALL_ORDER                 0 //棒球（或垒球）
#define UTE_MODULE_SPORT_VOLLEYBALL_ORDER               0 //排球
#define UTE_MODULE_SPORT_CRICKET_ORDER                  20 //板球
#define UTE_MODULE_SPORT_RUGBY_ORDER                    0 //橄榄球（或美式足球）
#define UTE_MODULE_SPORT_HOCKEY_ORDER                   0 //曲棍球
#define UTE_MODULE_SPORT_DANCE_ORDER                    0 //跳舞
#define UTE_MODULE_SPORT_SPINNING_ORDER                 7 //动感单车
#define UTE_MODULE_SPORT_YOGA_ORDER                     19 //瑜伽
#define UTE_MODULE_SPORT_SIT_UP_ORDER                   0 //仰卧起坐
#define UTE_MODULE_SPORT_TREADMILL_ORDER                3 //跑步机
#define UTE_MODULE_SPORT_GYMNASTICS_ORDER               0 //体操
#define UTE_MODULE_SPORT_BOATING_ORDER                  0 //划船
#define UTE_MODULE_SPORT_JUMPING_JACK_ORDER             0 //开合跳
#define UTE_MODULE_SPORT_FREE_TRAINING_ORDER            8 //自由训练
#define UTE_MODULE_SPORT_INDOOR_WALK_ORDER              0 //0x1A,室内走路
#define UTE_MODULE_SPORT_INDOOR_RUN_ORDER               0 //0x1B,室内跑步
#define UTE_MODULE_SPORT_STRENGTH_TRAINING_ORDER        16 //0x1C,力量训练
#define UTE_MODULE_SPORT_STEP_TRAINING_ORDER            0 //0x1D,踏步
#define UTE_MODULE_SPORT_HORSE_RIDING_ORDER             0 //0x1E,骑马
#define UTE_MODULE_SPORT_ELLIPTICAL_TRAINER_ORDER       18 //0x1F,椭圆机
#define UTE_MODULE_SPORT_TAI_CHI_ORDER                  0 //0x20,太极
#define UTE_MODULE_SPORT_SHUTTLECOCK_ORDER              0 //0x21,毽球
#define UTE_MODULE_SPORT_BOXING_ORDER                   0 //0x22,拳击
#define UTE_MODULE_SPORT_OUTDOOR_WALK_ORDER             2 //0x23,户外健走
#define UTE_MODULE_SPORT_TRAIL_RUNNING_ORDER            4 //0x24,越野跑
#define UTE_MODULE_SPORT_SKIING_ORDER                   0 //0x25,滑雪
#define UTE_MODULE_SPORT_ICE_HOCKEY_ORDER               0 //0x26,冰球
#define UTE_MODULE_SPORT_TAEKWONDO_ORDER                0 //0x27,跆拳道
#define UTE_MODULE_SPORT_VO2MAX_TEST_ORDER              0 //0x28,最大摄氧量测试
#define UTE_MODULE_SPORT_ROWING_MACHING_ORDER           0 //0x29,划船机
#define UTE_MODULE_SPORT_AIR_WALKER_ORDER               0 //0x2A,漫步机
#define UTE_MODULE_SPORT_HIKING_ORDER                   0 //0x2B,徒步   no
#define UTE_MODULE_SPORT_ATHLETICS_ORDER                0 //0x2C,田径
#define UTE_MODULE_SPORT_WAIST_TRAINING_ORDER           0 //0x2D,腰腹训练
#define UTE_MODULE_SPORT_KARATE_ORDER                   0 //0x2E,空手道
#define UTE_MODULE_SPORT_COOLDOWN_ORDER                 0 //0x2F,整理放松
#define UTE_MODULE_SPORT_CROSS_TRAINING_ORDER           0 //0x30,交叉训练
#define UTE_MODULE_SPORT_PILATES_ORDER                  17 //0x31,普拉提
#define UTE_MODULE_SPORT_CROSS_FIT_ORDER                0 //0x32,交叉配合
#define UTE_MODULE_SPORT_FUNCTIONAL_TRAINING_ORDER      0 //0x33,功能性训练
#define UTE_MODULE_SPORT_PHYSICAL_TRAINING_ORDER        0 //0x34,体能训练
#define UTE_MODULE_SPORT_ARCHERY_ORDER                  0 //0x35,射箭
#define UTE_MODULE_SPORT_FLEXIBILITY_ORDER              0 //0x36,柔韧度
#define UTE_MODULE_SPORT_MIXED_CARDIO_ORDER             15 //0x37,混合有氧
#define UTE_MODULE_SPORT_LATIN_DANCE_ORDER              0 //0x38,拉丁舞
#define UTE_MODULE_SPORT_STREET_DANCE_ORDER             0 //0x39,街舞
#define UTE_MODULE_SPORT_KICKBOXING_ORDER               0 //0x3A,自由搏击
#define UTE_MODULE_SPORT_BARRE_ORDER                    0 //0x3B,芭蕾
#define UTE_MODULE_SPORT_AUSTRALIAN_FOOTBALL_ORDER      0 //0x3C,澳式足球
#define UTE_MODULE_SPORT_MARTIAL_ARTS_ORDER             0 //0x3D,武术
#define UTE_MODULE_SPORT_STAIRS_ORDER                   0 //0x3E,爬楼
#define UTE_MODULE_SPORT_HANDBALL_ORDER                 0 //0x3F,手球
#define UTE_MODULE_SPORT_BOWLING_ORDER                  0 //0x40,保龄球
#define UTE_MODULE_SPORT_RACQUETBALL_ORDER              0 //0x41,壁球
#define UTE_MODULE_SPORT_CURLING_ORDER                  0 //0x42,冰壶
#define UTE_MODULE_SPORT_HUNTING_ORDER                  0 //0x43,打猎
#define UTE_MODULE_SPORT_SNOWBOARDING_ORDER             0 //0x44,单板滑雪
#define UTE_MODULE_SPORT_PLAY_ORDER                     0//0x45,休闲运动
#define UTE_MODULE_SPORT_AMERICAN_FOOTBALL_ORDER        0 //0x46,美式橄榄球
#define UTE_MODULE_SPORT_HAND_CYCLING_ORDER             0 //0x47,手摇车
#define UTE_MODULE_SPORT_FISHING_ORDER                  0 //0x48,钓鱼
#define UTE_MODULE_SPORT_DISC_SPORTS_ORDER              0 //0x49,飞盘
#define UTE_MODULE_SPORT_RUGGER_ORDER                   0 //0x4A,橄榄球  no
#define UTE_MODULE_SPORT_GOLF_ORDER                     0 //0x4B,高尔夫
#define UTE_MODULE_SPORT_FOLK_DANCE_ORDER               0 //0x4C,民族舞
#define UTE_MODULE_SPORT_DOWNHILL_SKIING_ORDER          0 //0x4D,高山滑雪
#define UTE_MODULE_SPORT_SNOW_SPORTS_ORDER              0 //0x4E,雪上运动
#define UTE_MODULE_SPORT_MIND_BODY_ORDER                0 //0x4F,舒缓冥想类运动
#define UTE_MODULE_SPORT_CORE_TRAINING_ORDER            14 //0x50,核心训练
#define UTE_MODULE_SPORT_SKATING_ORDER                  0 //0x51,滑冰
#define UTE_MODULE_SPORT_FITNESS_GAMING_ORDER           0 //0x52,健身游戏
#define UTE_MODULE_SPORT_AEROBICS_ORDER                 0 //0x53,健身操
#define UTE_MODULE_SPORT_GROUP_TRAINING_ORDER           0 //0x54,团体操
#define UTE_MODULE_SPORT_KENDO_ORDER                    0 //0x55,搏击操
#define UTE_MODULE_SPORT_LACROSSE_ORDER                 0 //0x56,长曲棍球
#define UTE_MODULE_SPORT_ROLLING_ORDER                  0 //0x57,泡沫轴筋膜放松
#define UTE_MODULE_SPORT_WRESTLING_ORDER                0 //0x58,摔跤
#define UTE_MODULE_SPORT_FENCING_ORDER                  0 //0x59,击剑
#define UTE_MODULE_SPORT_SOFTBALL_ORDER                 0 //0x5A,垒球
#define UTE_MODULE_SPORT_SINGLE_BAR_ORDER               0 //0x5B,单杠
#define UTE_MODULE_SPORT_PARALLEL_BARS_ORDER            0 //0x5C,双杠
#define UTE_MODULE_SPORT_ROLLER_SKATING_ORDER           0 //0x5D,轮滑
#define UTE_MODULE_SPORT_HULA_HOOP_ORDER                0 //0x5E,呼啦圈
#define UTE_MODULE_SPORT_DARTS_ORDER                    0 //0x5F,飞镖
#define UTE_MODULE_SPORT_PICKLEBALL_ORDER               0 //0x60,匹克球
#define UTE_MODULE_SPORT_HIIT_ORDER                     0 //0x61,HIIT
#define UTE_MODULE_SPORT_SHOOTING_ORDER                 0 //0x62,射击
#define UTE_MODULE_SPORT_JUDO_ORDER                     0 //0x63,柔道
#define UTE_MODULE_SPORT_TRAMPOLINE_ORDER               0 //0x64,蹦床
#define UTE_MODULE_SPORT_SKATEBOARDING_ORDER            0 //0x65,滑板
#define UTE_MODULE_SPORT_HOVERBOARD_ORDER               0 //0x66,平衡车
#define UTE_MODULE_SPORT_BLADING_ORDER                  0 //0x67,溜旱冰
#define UTE_MODULE_SPORT_PARKOUR_ORDER                  0 //0x68,跑酷
#define UTE_MODULE_SPORT_DIVING_ORDER                   0 //0x69,跳水
#define UTE_MODULE_SPORT_SURFING_ORDER                  0 //0x6A,冲浪
#define UTE_MODULE_SPORT_SNORKELING_ORDER               0//0x6B,浮潜
#define UTE_MODULE_SPORT_PULL_UP_ORDER                  0 //0x6C,引体向上
#define UTE_MODULE_SPORT_PUSH_UP_ORDER                  0 //0x6D,俯卧撑
#define UTE_MODULE_SPORT_PLANKING_ORDER                 0 //0x6E,平板支撑
#define UTE_MODULE_SPORT_ROCK_CLIMBING_ORDER            0 //0x6F,攀岩
#define UTE_MODULE_SPORT_HIGHTJUMP_ORDER                0 //0x70,跳高
#define UTE_MODULE_SPORT_BUNGEE_JUMPING_ORDER           0 //0x71,蹦极
#define UTE_MODULE_SPORT_LONGJUMP_ORDER                 0 //0x72,跳远
#define UTE_MODULE_SPORT_MARATHON_ORDER                 0 //0x73,马拉松
#endif

#endif//_UTE_PROJECT_CONFIG_AB281_H_
