/**
*@file
*@brief     项目配置文件
*@details   ute 项目总配置文件
*@author        zn.zeng
*@date        2024-03-22
*@version       v1.0
*/
#ifndef _UTE_PROJECT_CONFIG_H_
#define _UTE_PROJECT_CONFIG_H_

#define PROJECT_AB281_SUPPORT       1

#if PROJECT_AB281_SUPPORT
#include"ute_project_config_ab281.h"
#endif
/** Log模块控制开关*/
#define UTE_MODULE_LOG_SUPPORT 1

/** 芯片选型 */
#define CHIP_5691G                      0           //QFN40
#define CHIP_5691C_F                    1           //QFN40
#define CHIP_5690G                      2           //QFN52
#define CHIP_5690F                      3           //QFN52

#define UTE_CHIP_PACKAGE_SELECT             CHIP_5691C_F                  //芯片封装选择 5691G/5691C_F

/*! 默认蓝牙名字 zn.zeng  modify Jul 05, 2021 */
#ifndef DEFAULT_BLE_DEV_NEME
#define DEFAULT_BLE_DEV_NEME "UTE"
#endif
#ifndef UTE_SW_VERSION
#define UTE_SW_VERSION "ABxxxV000001"
#endif
/*!默认公共协议服务开关，默认为关 zn.zeng  modify Jul 06, 2021 */
#ifndef UTE_SERVICE_PUBLIC_BLE_SUPPORT
#define UTE_SERVICE_PUBLIC_BLE_SUPPORT 1
#endif

/*! gloryfit 广播数据标识 zn.zeng  modify Jul 05, 2021 */
#define UTE_ADVERTISE_DATA      "\x33\x55"
/*! 应用端识别是否在搜索界面显示蓝牙名zn.zeng  modify Jul 05, 2021 */
#define UTE_APP_DISPLAY_BT_NAME_ADVERTISE_DATA       "\x22\x22"

/*! 显示蓝牙名蓝牙地址后4位 zn.zeng, 2021-12-08  */
#ifndef UTE_APP_DISPLAY_NAME_ID_SUPPORT
#define UTE_APP_DISPLAY_NAME_ID_SUPPORT 1
#endif

/*! PC工具烧录蓝牙名 wang.luo, 2022-07-14  */
#ifndef UTE_PC_TOOL_WIRTE_BT_NAME_SUPPORT
#define UTE_PC_TOOL_WIRTE_BT_NAME_SUPPORT 1
#endif

/** 默认系统支持是最大闹钟数量*/
#ifndef SYSTEM_TIME_ALARMS_MAX_CNT
#define SYSTEM_TIME_ALARMS_MAX_CNT 3
#endif
/** 默认系统时间*/
#ifndef DEFAULT_SYSTEM_TIME_YEAR
#define DEFAULT_SYSTEM_TIME_YEAR 2024
#define DEFAULT_SYSTEM_TIME_MONTH 1
#define DEFAULT_SYSTEM_TIME_DAY 1
#define DEFAULT_SYSTEM_TIME_HOUR 8
#define DEFAULT_SYSTEM_TIME_MIN 0
#define DEFAULT_SYSTEM_TIME_SEC 0
#endif
/*! 默认时间制zn.zeng, 2021-08-18  */
#ifndef DEFAULT_SYSTEM_TIME_FORMAT_12HOUR
#define DEFAULT_SYSTEM_TIME_FORMAT_12HOUR false
#define DEFAULT_SYSTEM_TIME_FORMAT_MI false
#endif
/*! 默认时区zn.zeng, 2021-08-18  */
#ifndef DEFAULT_SYSTEM_TIME_ZONE
#define DEFAULT_SYSTEM_TIME_ZONE 8
#endif
/*! 默认个人信息 personalInfo zn.zeng, 2021-08-19  */
#ifndef DEFAULT_PERSONALINFO_AGE
#define DEFAULT_PERSONALINFO_AGE 30
#define DEFAULT_PERSONALINFO_HIGHT 170
#define DEFAULT_PERSONALINFO_WEIGHT 60000 //60kg
#define DEFAULT_PERSONALINFO_ISMAN true
#endif
/** 默认系统最大的每秒函数注册数量*/
#ifndef UTE_MODULE_SYSTEMTEIM_REGISTER_MAX_CNT
#define UTE_MODULE_SYSTEMTEIM_REGISTER_MAX_CNT 24
#endif

/** 系统启动电压*/
#ifndef UTE_DRV_BATTERY_POWER_ON_VOLTAGE
#define UTE_DRV_BATTERY_POWER_ON_VOLTAGE     3000  //mv
#endif

/*! 电池电量分为几等份，默认5等份，即0 25 50 75 100  xjc, 2021-12-27  */
#ifndef UTE_DRV_BATTERY_TOTAL_INDEX
#define UTE_DRV_BATTERY_TOTAL_INDEX 5
#endif
/*! 低电提醒时电量  xjc, 2021-12-27  */
#ifndef UTE_DRV_BATTERY_LOW_POWER_PERECNT
#define UTE_DRV_BATTERY_LOW_POWER_PERECNT 13
#endif

/* 电池曲线 zn.zeng 2022-01-03*/
#ifndef UTE_DRV_BATTERY_000
#define UTE_DRV_BATTERY_000      3579
#define UTE_DRV_BATTERY_010      3691
#define UTE_DRV_BATTERY_020      3741
#define UTE_DRV_BATTERY_030      3781
#define UTE_DRV_BATTERY_040      3815
#define UTE_DRV_BATTERY_050      3858
#define UTE_DRV_BATTERY_060      3922
#define UTE_DRV_BATTERY_070      4023
#define UTE_DRV_BATTERY_080      4119
#define UTE_DRV_BATTERY_090      4221
#define UTE_DRV_BATTERY_100      4335
#endif

/*! 电池最大电压值zn.zeng, 2021-11-09  */
#ifndef UTE_DRV_BATTERY_MAX_VOLTAGE
#if UTE_DRV_BATTERY_100 > 4400
#define UTE_DRV_BATTERY_MAX_VOLTAGE 4450
#elif UTE_DRV_BATTERY_100 > 4350
#define UTE_DRV_BATTERY_MAX_VOLTAGE 4400
#elif UTE_DRV_BATTERY_100 >= 4300
#define UTE_DRV_BATTERY_MAX_VOLTAGE 4350
#else
#define UTE_DRV_BATTERY_MAX_VOLTAGE 4200
#endif
#endif

/*! 充电截止电压：0:4.2v；1:4.35v; 2:4.4v; 3:4.45v,wang.luo 2024-10-30 */
#if UTE_DRV_BATTERY_MAX_VOLTAGE > 4400
#define UTE_DRV_BATTERY_CHARGE_STOP_VOLT 3
#elif UTE_DRV_BATTERY_MAX_VOLTAGE > 4350
#define UTE_DRV_BATTERY_CHARGE_STOP_VOLT 2
#elif UTE_DRV_BATTERY_MAX_VOLTAGE > 4300
#define UTE_DRV_BATTERY_CHARGE_STOP_VOLT 1
#else
#define UTE_DRV_BATTERY_CHARGE_STOP_VOLT 0
#endif

/*! 默认发送历史数据定时器间隔zn.zeng, 2021-08-23  */
#ifndef UTE_SEND_DATA_TO_PHONE_INVTERVAL
#define UTE_SEND_DATA_TO_PHONE_INVTERVAL 60 // ms
#endif


/*! 使用自定义内存申请,wang.luo 2024-10-21 */
#ifndef UTE_MODULE_USER_MALLOC_SUPPORT
#define UTE_MODULE_USER_MALLOC_SUPPORT 1
#define UTE_MODULE_MEM_POOL_SIZE (1024*5) //内存池大小
#endif

/*! 屏宽度 zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_SCREEN_WIDTH
#define UTE_DRV_SCREEN_WIDTH 240
#endif
/*! 屏高度 zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_SCREEN_HEIGHT
#define UTE_DRV_SCREEN_HEIGHT 284
#endif
/*! 屏使用16bit色彩 zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_SCREEN_PIXEL_BYTES
#define UTE_DRV_SCREEN_PIXEL_BYTES 2
#endif

/*! 默认亮屏时间zn.zeng, 2021-08-20  */
#ifndef DEFAULT_SCREEN_ON_TIME_SECOND
#define DEFAULT_SCREEN_ON_TIME_SECOND 10
#endif

/*! 灭屏后延时清除显示深度，返回时间界面，默认时间 zn.zeng, 2021-11-03  */
#ifndef UTE_MODULE_GUI_CLEAR_DEPTH_AFTER_TIME_SECOND
#define UTE_MODULE_GUI_CLEAR_DEPTH_AFTER_TIME_SECOND 10
#endif

/*! 默认抬手亮屏开关zn.zeng, 2021-08-20  */
#ifndef DEFAULT_HAND_SCREEN_ON_OPEN
#define DEFAULT_HAND_SCREEN_ON_OPEN true
#endif

/*! 勿扰允许抬手亮屏dengli.lu, 2022-08-16  */
#ifndef UTE_NOTDISTURB_ALLOW_HAND_SCREEN_ON_SUPPORT
#define UTE_NOTDISTURB_ALLOW_HAND_SCREEN_ON_SUPPORT 0
#endif

/*! 默认温度单位为摄氏度 zn.zeng, 2021-08-20  */
#ifndef DEFAULT_TEMPERATURE_IS_FAHRENHEIT
#define DEFAULT_TEMPERATURE_IS_FAHRENHEIT false
#endif

/*! 屏最大亮度百分比 dengli.lu, 2021-10-29  */
#ifndef DEFAULT_BACK_LIGHT_PERCENT_MAX
#define DEFAULT_BACK_LIGHT_PERCENT_MAX 100
#endif

/*! 屏最小亮度百分比 dengli.lu, 2021-10-29  */
#ifndef DEFAULT_BACK_LIGHT_PERCENT_MIN
#define DEFAULT_BACK_LIGHT_PERCENT_MIN 25
#endif

/*! 调节屏亮度时增加或者减少的百分比 dengli.lu, 2021-10-29  */
#ifndef BACK_LIGHT_PERCENT_INCREASE_OR_INCREASE
#define BACK_LIGHT_PERCENT_INCREASE_OR_INCREASE 25
#endif

/*! 默认背光百分比zn.zeng, 2021-09-24  */
#ifndef DEFAULT_SCREEN_BACKLIGHT_PERCENT
#define DEFAULT_SCREEN_BACKLIGHT_PERCENT    (BACK_LIGHT_PERCENT_INCREASE_OR_INCREASE*2)
#endif

/*! 默认表盘索引 zn.zeng, 2021-10-25  */
#ifndef DEFAULT_WATCH_INDEX
#define DEFAULT_WATCH_INDEX                      0
#endif

/*! 最大表盘数量，包括在线表盘 zn.zeng, 2021-10-23  */
#ifndef UTE_MODULE_SCREENS_WATCH_CNT_MAX
#define UTE_MODULE_SCREENS_WATCH_CNT_MAX 5
#endif

/*! 默认打开通话模块 zn.zeng, 2021-10-27  */
#ifndef UTE_BT30_CALL_SUPPORT
#define UTE_BT30_CALL_SUPPORT 1
#endif

/*! 是否保存BK的PowerOn状态 xjc, 2022-04-07  */
#ifndef UTE_MODULE_BT_POWER_STATUS_SAVE_SUPPORT
#define UTE_MODULE_BT_POWER_STATUS_SAVE_SUPPORT 1
#endif

#ifndef UTE_MODULE_BT_POWER_DEFAULT_ON
#define UTE_MODULE_BT_POWER_DEFAULT_ON false
#endif

/*! 一次配对连接, casen 2022-02-14*/
#ifndef UTE_MODULE_BT_ONCE_PAIR_CONNECT_SUPPORT
#define UTE_MODULE_BT_ONCE_PAIR_CONNECT_SUPPORT 1
#endif

/*! 每次亮屏之前先清屏，防止闪烁 xjc, 2022-05-18  */
#ifndef UTE_DRV_CLEAR_SCREEN_BEFORE_BACKLIGHT_ON_SUPPORT
#define UTE_DRV_CLEAR_SCREEN_BEFORE_BACKLIGHT_ON_SUPPORT 0
#endif

// #define UTE_DRV_DSPI_FOR_SCREEN_SUPPORT 1
#ifndef UTE_DRV_SCREEN_TE_SIGNAL_SUPPORT
#define UTE_DRV_SCREEN_TE_SIGNAL_SUPPORT 1
#define UTE_DRV_SCREEN_TE_SIGNAL_INT_GPIO_VECTORn PORT_INT1_VECTOR
#define UTE_DRV_SCREEN_TE_SIGNAL_INT_GPIO_PIN IO_PA6
#define UTE_DRV_SCREEN_TE_SIGNAL_INT_GPIO_PULL 1
#define UTE_DRV_SCREEN_TE_SIGNAL_INT_GPIO_TRIGGER 1
#endif

/*! 屏复位管脚zn.zeng, 2021-10-21  */
#ifndef UTE_DRV_SCREEN_RST_GPIO_PIN
#define UTE_DRV_SCREEN_RST_GPIO_PIN      IO_PA7
#endif
/*! 屏cs管脚zn.zeng, 2021-10-21  */
#ifndef UTE_DRV_SCREEN_CS_GPIO_PIN
#define UTE_DRV_SCREEN_CS_GPIO_PIN      IO_PA5
#endif

#ifndef UTE_DRV_SCREEN_BACKLIGHT_PWM_SUPPORT
#define UTE_DRV_SCREEN_BACKLIGHT_PWM_SUPPORT 1
#endif
/*! 背光PWM控制输出的频率 zn.zeng, 2021-09-24  */
#ifndef UTE_DRV_SCREEN_BACKLIGHT_PWM_HZ
#define UTE_DRV_SCREEN_BACKLIGHT_PWM_HZ 200
#endif
/*! 背光PWM控制输出定时器索引 zn.zeng, 2021-09-24  */
#ifndef UTE_DRV_SCREEN_BACKLIGHT_PWM_ID
#if (UTE_CHIP_PACKAGE_SELECT == CHIP_5691C_F)
#define UTE_DRV_SCREEN_BACKLIGHT_PWM_ID GPIO_PE6
#elif (UTE_CHIP_PACKAGE_SELECT == CHIP_5691G)
#define UTE_DRV_SCREEN_BACKLIGHT_PWM_ID GPIO_PE3
#else
#error CHIP ERR
#endif
#endif
/*! 背光控制输出管脚 zn.zeng, 2021-09-24  */
#ifndef UTE_DRV_SCREEN_BACKLIGHT_GPIO_PIN
#if (UTE_CHIP_PACKAGE_SELECT == CHIP_5691C_F)
#define UTE_DRV_SCREEN_BACKLIGHT_GPIO_PIN   IO_PE6
#elif (UTE_CHIP_PACKAGE_SELECT == CHIP_5691G)
#define UTE_DRV_SCREEN_BACKLIGHT_GPIO_PIN   IO_PE3
#else
#error CHIP ERR
#endif
#endif

/*! 马达PWM控制输出定时器索引 zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_MOTOR_PWM_ID

#define UTE_DRV_MOTOR_PWM_ID GPIO_PE3
#endif

/*! 控制马达的gpio pin zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_MOTOR_GPIO_PIN
#if (UTE_CHIP_PACKAGE_SELECT == CHIP_5691C_F)
#define UTE_DRV_MOTOR_GPIO_PIN IO_PE3
#elif (UTE_CHIP_PACKAGE_SELECT == CHIP_5691G)
#define UTE_DRV_MOTOR_GPIO_PIN IO_PF3
#else
#error CHIP ERR
#endif
#endif

/*! pwm控制马达支持zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_MOTOR_PWM_MODE_SUPPORT
#define UTE_DRV_MOTOR_PWM_MODE_SUPPORT 0
#endif

/*! pwm控制马达的频率zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_MOTOR_PWM_RATE_HZ
#define UTE_DRV_MOTOR_PWM_RATE_HZ 177
#endif

//允许马达振动
#ifndef UTE_MOTOR_ALLOW_VIBRATION_DEFAULT_OPEN
#define UTE_MOTOR_ALLOW_VIBRATION_DEFAULT_OPEN true
#endif

/*! pwm控制马达震动强度 xjc, 2023-05-29  */
#ifndef UTE_DRV_MOTOR_PWM_VIBRATION_HIGH
#define UTE_DRV_MOTOR_PWM_VIBRATION_HIGH 90
#endif
#ifndef UTE_DRV_MOTOR_PWM_VIBRATION_MEDIUM
#define UTE_DRV_MOTOR_PWM_VIBRATION_MEDIUM 70
#endif
#ifndef UTE_DRV_MOTOR_PWM_VIBRATION_LOW
#define UTE_DRV_MOTOR_PWM_VIBRATION_LOW 50
#endif
#ifndef UTE_DRV_MOTOR_PWM_VIBRATION_NONE
#define UTE_DRV_MOTOR_PWM_VIBRATION_NONE 0
#endif

/*!默认震动强度 level 0-100, dengli.lu, 2022-06-16 */
#ifndef UTE_MODULE_MOTOR_VIBRATION_DEFAULT_LEVEL
#define UTE_MODULE_MOTOR_VIBRATION_DEFAULT_LEVEL UTE_DRV_MOTOR_PWM_VIBRATION_HIGH
#endif

/*!震动时长 unit:ms, lzc, 2022-01-20 */
#ifndef UTE_MOTOR_DURATION_TIME
#define UTE_MOTOR_DURATION_TIME 300
#endif
#ifndef UTE_MOTOR_INTERVAL_TIME
#define UTE_MOTOR_INTERVAL_TIME 600
#endif

#define DRV_TFT_S280X284_I18_ST7789P3_XHL183BA2401_DSPI_SUPPORT 0

/*! 默认语言 zn.zeng, 2021-08-23  */
#ifndef DEFAULT_LANGUAGE
#define DEFAULT_LANGUAGE 0x02//ENGLISH_LANGUAGE_ID
#define SCREEN_TITLE_MULTIPLE_CHINESE_LANGUAGE_SUPPORT        1
#define SCREEN_TITLE_MULTIPLE_ENGLISH_LANGUAGE_SUPPORT        1
#define SCREEN_TITLE_MULTIPLE_KOREAN_LANGUAGE_SUPPORT         0 //韩文 3
#define SCREEN_TITLE_MULTIPLE_JAPANESE_LANGUAGE_SUPPORT           0 //日文 4
#define SCREEN_TITLE_MULTIPLE_GERMAN_LANGUAGE_SUPPORT           0   //德文 5
#define SCREEN_TITLE_MULTIPLE_SPANISH_LANGUAGE_SUPPORT        0 //西班牙文 6
#define SCREEN_TITLE_MULTIPLE_FRENCH_LANGUAGE_SUPPORT                   0   //法文 7
#define SCREEN_TITLE_MULTIPLE_ITALIAN_LANGUAGE_SUPPORT            0 //意大利文 8
#define SCREEN_TITLE_MULTIPLE_PORTUGUESE_LANGUAGE_SUPPORT       0 //葡萄牙文 9
#define SCREEN_TITLE_MULTIPLE_ARABIC_LANGUAGE_SUPPORT           0   //阿拉伯文 A
#define SCREEN_TITLE_MULTIPLE_INDIA_LANGUAGE_SUPPORT            0 //India     B
#define SCREEN_TITLE_MULTIPLE_HINDI_LANGUAGE_SUPPORT          0 //印地语  C
#define SCREEN_TITLE_MULTIPLE_POLISH_LANGUAGE_SUPPORT         0 //波兰语  D
#define SCREEN_TITLE_MULTIPLE_RUSSIAN_LANGUAGE_SUPPORT        0//俄语  E
#define SCREEN_TITLE_MULTIPLE_DUTCH_LANGUAGE_SUPPORT          0//荷兰语 F
#define SCREEN_TITLE_MULTIPLE_TURKISH_LANGUAGE_SUPPORT        0//土耳其语  10
#define SCREEN_TITLE_MULTIPLE_BENGALI_LANGUAGE_SUPPORT       0 //孟加拉语  11  Bengali
#define SCREEN_TITLE_MULTIPLE_URDU_LANGUAGE_SUPPORT           0 //乌尔都语   12  Urdu
#define SCREEN_TITLE_MULTIPLE_INDONESUAN_LANGUAGE_SUPPORT     0 //印度尼西亚语（爪哇语）  13  Indonesian
#define SCREEN_TITLE_MULTIPLE_PUNJABI_LANGUAGE_SUPPORT        0 //旁遮普语  14   Punjabi
#define SCREEN_TITLE_MULTIPLE_THAI_LANGUAGE_SUPPORT           0 //泰文  15   Thai
#define SCREEN_TITLE_MULTIPLE_CZECH_LANGUAGE_SUPPORT          0 //捷克语  16  Czech
#define SCREEN_TITLE_MULTIPLE_TRADITIONAL_CHINESE_LANGUAGE_SUPPORT 0 //繁体中文
#define SCREEN_TITLE_MULTIPLE_ROMANIAN_LANGUAGE_SUPPORT                 0 //罗马尼亚语 limba 0x1B
#define SCREEN_TITLE_MULTIPLE_VIETNAMESE_LANGUAGE_SUPPORT           1 //越南语 0x63
#endif

#ifndef UTE_MODULE_LOCAL_ALARM_REPEAT_REMIND_SUPPORT
#define UTE_MODULE_LOCAL_ALARM_REPEAT_REMIND_SUPPORT 1
#define ALARM_REPEAT_REMIND_DEFAULT_OPEN true//默认重复提醒开关
#define ALARM_REPEAT_REMIND_DEFAULT_TIME_MIN 1
#define ALARM_REPEAT_REMIND_DEFAULT_TIMES 3//默认重复提醒次数，未手动关闭时重复提醒5次后不再提醒
#endif // UTE_MODULE_LOCAL_ALARM_REPEAT_REMIND_SUPPORT

/*! 本地闹钟默认振动次数 dengli.lu, 2022-08-10  */
#ifndef UTE_LOCAL_ALARM_DEFAULT_MOTOR_TIMES
#define UTE_LOCAL_ALARM_DEFAULT_MOTOR_TIMES 10
#endif

#ifndef UTE_LOCAL_ALARM_DEFAULT_RING_TIMES
#define UTE_LOCAL_ALARM_DEFAULT_RING_TIMES  20                  //闹钟默认响铃时间 20S
#endif // UTE_LOCAL_ALARM_DEFAULT_RING_TIMES

/*! 本地闹钟dengli.lu, 2021-11-25  */
#ifndef UTE_MODULE_LOCAL_ALARM_SUPPORT
#define UTE_MODULE_LOCAL_ALARM_SUPPORT 1
#endif

#ifndef UTE_NOTIFY_MSG_CONTENT_MAX_SIZE
#define UTE_NOTIFY_MSG_CONTENT_MAX_SIZE 240
#endif
/*! 消息推送保存的最大条数zn.zeng, 2021-08-25  */
#ifndef UTE_MODULE_NOTIFY_SAVE_CNT
#define UTE_MODULE_NOTIFY_SAVE_CNT 8
#endif

/* 支持应用通知选择显示功能 必须支持的三样 xjc, 2022-01-08 */
#define SOCIAL_APP_MMS_SUPPORT     1
#define SOCIAL_APP_CALL_SUPPORT    1
#define SOCIAL_APP_OTHER_SUPPORT   1
#ifndef SOCIAL_APP_QQ_SUPPORT
#define SOCIAL_APP_QQ_SUPPORT   1
#endif
#ifndef SOCIAL_APP_WECHAT_SUPPORT
#define SOCIAL_APP_WECHAT_SUPPORT   1
#endif
#ifndef SOCIAL_APP_FACEBOOK_SUPPORT
#define SOCIAL_APP_FACEBOOK_SUPPORT   1
#endif
#ifndef SOCIAL_APP_TWITTER_SUPPORT
#define SOCIAL_APP_TWITTER_SUPPORT   1
#endif
#ifndef SOCIAL_APP_WHATSAPP_SUPPORT
#define SOCIAL_APP_WHATSAPP_SUPPORT   1
#endif
#ifndef SOCIAL_APP_FACEBOOK_MESSENGER_SUPPORT
#define SOCIAL_APP_FACEBOOK_MESSENGER_SUPPORT   1
#endif
#ifndef SOCIAL_APP_LINE_SUPPORT
#define SOCIAL_APP_LINE_SUPPORT   1
#endif
#ifndef SOCIAL_APP_SKYPE_SUPPORT
#define SOCIAL_APP_SKYPE_SUPPORT   1
#endif
#ifndef SOCIAL_APP_HANGOUTS_SUPPORT
#define SOCIAL_APP_HANGOUTS_SUPPORT   1
#endif
#ifndef SOCIAL_APP_LINKED_IN_SUPPORT
#define SOCIAL_APP_LINKED_IN_SUPPORT   1
#endif
#ifndef SOCIAL_APP_INSTAGRAM_SUPPORT
#define SOCIAL_APP_INSTAGRAM_SUPPORT   1
#endif
#ifndef SOCIAL_APP_VIBER_SUPPORT
#define SOCIAL_APP_VIBER_SUPPORT   1
#endif
#ifndef SOCIAL_APP_KAKAO_TALK_SUPPORT
#define SOCIAL_APP_KAKAO_TALK_SUPPORT   1
#endif
#ifndef SOCIAL_APP_VKONTAKTE_SUPPORT
#define SOCIAL_APP_VKONTAKTE_SUPPORT   1
#endif
#ifndef SOCIAL_APP_SNAPCHAT_SUPPORT
#define SOCIAL_APP_SNAPCHAT_SUPPORT   1
#endif
#ifndef SOCIAL_APP_GOOGLE_PLUS_SUPPORT
#define SOCIAL_APP_GOOGLE_PLUS_SUPPORT   1
#endif
#ifndef SOCIAL_APP_GMAIL_SUPPORT
#define SOCIAL_APP_GMAIL_SUPPORT   1
#endif
#ifndef SOCIAL_APP_FLICKR_SUPPORT
#define SOCIAL_APP_FLICKR_SUPPORT   1
#endif
#ifndef SOCIAL_APP_TUMBLR_SUPPORT
#define SOCIAL_APP_TUMBLR_SUPPORT   1
#endif
#ifndef SOCIAL_APP_PINTEREST_SUPPORT
#define SOCIAL_APP_PINTEREST_SUPPORT   1
#endif
#ifndef SOCIAL_APP_YOUTUBE_SUPPORT
#define SOCIAL_APP_YOUTUBE_SUPPORT   1
#endif
#ifndef SOCIAL_APP_TELEGRAM_SUPPORT
#define SOCIAL_APP_TELEGRAM_SUPPORT   1
#endif
#ifndef SOCIAL_APP_PAYTM_SUPPORT
#define SOCIAL_APP_PAYTM_SUPPORT    0
#endif
#ifndef SOCIAL_APP_ZALO_SUPPORT
#define SOCIAL_APP_ZALO_SUPPORT 0
#endif
#ifndef SOCIAL_APP_IMO_SUPPORT
#define SOCIAL_APP_IMO_SUPPORT  0
#endif
#ifndef SOCIAL_APP_TRUECALLER_SUPPORT
#define SOCIAL_APP_TRUECALLER_SUPPORT   0
#endif
#ifndef SOCIAL_APP_MICROSOFT_TEAMS_SUPPORT
#define SOCIAL_APP_MICROSOFT_TEAMS_SUPPORT  0
#endif

#if APP_DYNAMIC_ADDITIONAL_SOCIAL_APP_SUPPORT

#ifndef SOCIAL_APP_OUTLOOK_SUPPORT
#define SOCIAL_APP_OUTLOOK_SUPPORT  0
#endif
#ifndef SOCIAL_APP_SWIGGY_SUPPORT
#define SOCIAL_APP_SWIGGY_SUPPORT   0
#endif
#ifndef SOCIAL_APP_ZOMATO_SUPPORT
#define SOCIAL_APP_ZOMATO_SUPPORT   0
#endif
#ifndef SOCIAL_APP_GPAY_SUPPORT
#define SOCIAL_APP_GPAY_SUPPORT 0
#endif
#ifndef SOCIAL_APP_PHONEPE_SUPPORT
#define SOCIAL_APP_PHONEPE_SUPPORT  0
#endif
#ifndef SOCIAL_APP_HOTSTAR_SUPPORT
#define SOCIAL_APP_HOTSTAR_SUPPORT  0
#endif
#ifndef SOCIAL_APP_PRIMEVIDEO_SUPPORT
#define SOCIAL_APP_PRIMEVIDEO_SUPPORT   0
#endif
#ifndef SOCIAL_APP_FLIPKART_SUPPORT
#define SOCIAL_APP_FLIPKART_SUPPORT 0
#endif
#ifndef SOCIAL_APP_AMAZON_SUPPORT
#define SOCIAL_APP_AMAZON_SUPPORT   0
#endif
#ifndef SOCIAL_APP_MYNTRA_SUPPORT
#define SOCIAL_APP_MYNTRA_SUPPORT   0
#endif
#ifndef SOCIAL_APP_NOISEAPP_SUPPORT
#define SOCIAL_APP_NOISEAPP_SUPPORT 0
#endif
#ifndef SOCIAL_APP_DAILYHUNT_SUPPORT
#define SOCIAL_APP_DAILYHUNT_SUPPORT    0
#endif
#ifndef SOCIAL_APP_INSHORTS_SUPPORT
#define SOCIAL_APP_INSHORTS_SUPPORT 0
#endif

#ifndef SOCIAL_APP_BOOKMYSHOW_SUPPORT
#define SOCIAL_APP_BOOKMYSHOW_SUPPORT   0
#endif

#ifndef SOCIAL_APP_CALENDAR_SUPPORT
#define SOCIAL_APP_CALENDAR_SUPPORT 0
#endif

#ifndef SOCIAL_APP_JIOTV_SUPPORT
#define SOCIAL_APP_JIOTV_SUPPORT    0
#endif

#ifndef SOCIAL_APP_MAKEMYTRIP_SUPPORT
#define SOCIAL_APP_MAKEMYTRIP_SUPPORT   0
#endif

#ifndef SOCIAL_APP_NETFLIX_SUPPORT
#define SOCIAL_APP_NETFLIX_SUPPORT  0
#endif

#ifndef SOCIAL_APP_OLA_SUPPORT
#define SOCIAL_APP_OLA_SUPPORT  0
#endif

#ifndef SOCIAL_APP_REFLEXAPP_SUPPORT
#define SOCIAL_APP_REFLEXAPP_SUPPORT    0
#endif

#ifndef SOCIAL_APP_UBER_SUPPORT
#define SOCIAL_APP_UBER_SUPPORT 0
#endif

#ifndef SOCIAL_APP_YTMUSIC_SUPPORT
#define SOCIAL_APP_YTMUSIC_SUPPORT  0
#endif

//add 2022-11-22
#ifndef SOCIAL_APP_WHATSAPP_BUSINESS_SUPPORT
#define SOCIAL_APP_WHATSAPP_BUSINESS_SUPPORT  0
#endif

#ifndef SOCIAL_APP_DUNZO_SUPPORT
#define SOCIAL_APP_DUNZO_SUPPORT    0
#endif

#ifndef SOCIAL_APP_GAANA_SUPPORT
#define SOCIAL_APP_GAANA_SUPPORT 0
#endif

#ifndef SOCIAL_APP_GOOGLE_DRIVE_SUPPORT
#define SOCIAL_APP_GOOGLE_DRIVE_SUPPORT  0
#endif

#ifndef SOCIAL_APP_GOOGLECHAT_SUPPORT
#define SOCIAL_APP_GOOGLECHAT_SUPPORT 0
#endif

#ifndef SOCIAL_APP_WYNKMUSIC_SUPPORT
#define SOCIAL_APP_WYNKMUSIC_SUPPORT  0
#endif

#ifndef SOCIAL_APP_YAHOO_SUPPORT
#define SOCIAL_APP_YAHOO_SUPPORT  0
#endif

#ifndef SOCIAL_APP_TITANSMARTWORLD_SUPPORT
#define SOCIAL_APP_TITANSMARTWORLD_SUPPORT    0
#endif

#ifndef SOCIAL_APP_SLACK_SUPPORT
#define SOCIAL_APP_SLACK_SUPPORT 0
#endif

#ifndef SOCIAL_APP_SPOTIFY_SUPPORT
#define SOCIAL_APP_SPOTIFY_SUPPORT  0
#endif
#endif

/*! 本地勿扰模式设置,casen 2022-08-26  */
#ifndef UTE_MODULE_LOCAL_SET_NOT_DISTURB_SUPPORT
#define UTE_MODULE_LOCAL_SET_NOT_DISTURB_SUPPORT            1
#endif
/*! 勿扰默认关闭 zn.zeng, 2021-10-22  */
#ifndef DEFAULT_DONOT_DISTURB_OPNE
#define DEFAULT_DONOT_DISTURB_OPNE false
#endif
#ifndef DEFAULT_DONOT_DISTURB_REJECT_CALL_OPNE
#define DEFAULT_DONOT_DISTURB_REJECT_CALL_OPNE false
#endif
#ifndef DEFAULT_DONOT_DISTURB_START_HOUR_MIN_VALUE
#define DEFAULT_DONOT_DISTURB_START_HOUR_MIN_VALUE  0x0001 //00:01
#endif
#ifndef DEFAULT_DONOT_DISTURB_END_HOUR_MIN_VALUE
#define DEFAULT_DONOT_DISTURB_END_HOUR_MIN_VALUE  0x173B   //23:59
#endif

/*! 天气增加紫外强度和湿度 2022-09-22  */
#ifndef UTE_MODULE_WEATHER_HUMIDITY_ULTRAVIOLET_SUPPORT
#define UTE_MODULE_WEATHER_HUMIDITY_ULTRAVIOLET_SUPPORT 0
#endif

/* 天气城市名支持  默认关闭 txj 2022-11-10*/
#ifndef UTE_MODULE_WEATHER_CITY_NAME_NEW_SUPPORT
#define UTE_MODULE_WEATHER_CITY_NAME_NEW_SUPPORT 0
#endif
#if UTE_MODULE_WEATHER_CITY_NAME_NEW_SUPPORT
/* 天气城市名支持最大字节大小 txj 2022-11-10 */
#ifndef UTE_WEATHER_CITY_NAME_TITLE_MAX_SIZE
#define UTE_WEATHER_CITY_NAME_TITLE_MAX_SIZE 100
#endif
#endif

#ifndef UTE_MODULE_HEART_SUPPORT
#define UTE_MODULE_HEART_SUPPORT 1
#endif
/*! 默认心率报警是否打开 zn.zeng, 2021-08-20  */
#ifndef DEFAULT_HEARTWARNING_IS_OPEN
#define DEFAULT_HEARTWARNING_IS_OPEN false
#define DEFAULT_HEARTWARNING_MIN_VALUE 40
#define DEFAULT_HEARTWARNING_MAX_VALUE 100
#endif
/*! 默认运动心率报警是否打开 dengli.lu, 2022-08-03  */
#ifndef DEFAULT_SPORT_MAX_HEARTWARNING_IS_OPEN
#define DEFAULT_SPORT_MAX_HEARTWARNING_IS_OPEN false
#define DEFAULT_SPORT_MIN_HEARTWARNING_IS_OPEN false
#define DEFAULT_SPORT_HEARTWARNING_MIN_VALUE 40
#define DEFAULT_SPORT_HEARTWARNING_MAX_VALUE 100
#endif
/*! 默认24小时自动心率打开 zn.zeng, 2021-08-30  */
#ifndef DEFAULT_HEART24AUTO_TEST_IS_OPEN
#define DEFAULT_HEART24AUTO_TEST_IS_OPEN true
#endif
/*! 心率警告功能 zn.zeng, 2021-10-22  */
#ifndef UTE_MODULE_HEART_MIN_MAX_WARNING_VALUE_SUPPORT
#define UTE_MODULE_HEART_MIN_MAX_WARNING_VALUE_SUPPORT 0
#endif
/*! 心率警告第一次提醒时间zn.zeng, 2021-10-22  */
#ifndef UTE_MODULE_HEART_MIN_MAX_WARNING_FRIST_SECOND_CNT
#define UTE_MODULE_HEART_MIN_MAX_WARNING_FRIST_SECOND_CNT 60
#endif
/*! 心率警告重复提醒时间zn.zeng, 2021-10-22  */
#ifndef UTE_MODULE_HEART_MIN_MAX_WARNING_RELOAD_SECOND_CNT
#define UTE_MODULE_HEART_MIN_MAX_WARNING_RELOAD_SECOND_CNT 300
#endif
/*! 心率数据保存最大天数zn.zeng, 2021-08-30  */
#ifndef UTE_MODULE_HEART_SAVE_DATA_MAX_DAYS
#define UTE_MODULE_HEART_SAVE_DATA_MAX_DAYS 7
#endif

//二维码链接内容
#ifndef UTE_BINDING_QRENCODE_LINK
#define UTE_BINDING_QRENCODE_LINK "https://app.help-document.com/gloryfit/download/index.html?MAC=12:34:56:78:90:1a"
#endif

#endif//_UTE_PROJECT_CONFIG_H_
