/**
*@file
*@brief     项目配置文件
*@details   ute 项目总配置文件
*@author        zn.zeng
*@date        2024-03-22
*@version       v1.0
*/
#ifndef _UTE_PROJECT_CONFIG_H_
#define _UTE_PROJECT_CONFIG_H_

#define PROJECT_AB281_SUPPORT       1

#if PROJECT_AB281_SUPPORT
#include"ute_project_config_ab281.h"
#endif
/** Log模块控制开关*/
#define UTE_MODULE_LOG_SUPPORT 1

/*! 默认蓝牙名字 zn.zeng  modify Jul 05, 2021 */
#ifndef DEFAULT_BLE_DEV_NEME
#define DEFAULT_BLE_DEV_NEME "UTE"
#endif
#ifndef UTE_SW_VERSION
#define UTE_SW_VERSION "ABxxxV000001"
#endif

/** 默认系统支持是最大闹钟数量*/
#ifndef SYSTEM_TIME_ALARMS_MAX_CNT
#define SYSTEM_TIME_ALARMS_MAX_CNT 3
#endif
/** 默认系统时间*/
#ifndef DEFAULT_SYSTEM_TIME_YEAR
#define DEFAULT_SYSTEM_TIME_YEAR 2024
#define DEFAULT_SYSTEM_TIME_MONTH 1
#define DEFAULT_SYSTEM_TIME_DAY 1
#define DEFAULT_SYSTEM_TIME_HOUR 8
#define DEFAULT_SYSTEM_TIME_MIN 0
#define DEFAULT_SYSTEM_TIME_SEC 0
#endif
/*! 默认时间制zn.zeng, 2021-08-18  */
#ifndef DEFAULT_SYSTEM_TIME_FORMAT_12HOUR
#define DEFAULT_SYSTEM_TIME_FORMAT_12HOUR false
#define DEFAULT_SYSTEM_TIME_FORMAT_MI false
#endif
/*! 默认时区zn.zeng, 2021-08-18  */
#ifndef DEFAULT_SYSTEM_TIME_ZONE
#define DEFAULT_SYSTEM_TIME_ZONE 8
#endif
/*! 默认个人信息 personalInfo zn.zeng, 2021-08-19  */
#ifndef DEFAULT_PERSONALINFO_AGE
#define DEFAULT_PERSONALINFO_AGE 30
#define DEFAULT_PERSONALINFO_HIGHT 170
#define DEFAULT_PERSONALINFO_WEIGHT 60000 //60kg
#define DEFAULT_PERSONALINFO_ISMAN true
#endif
/** 默认系统最大的每秒函数注册数量*/
#ifndef UTE_MODULE_SYSTEMTEIM_REGISTER_MAX_CNT
#define UTE_MODULE_SYSTEMTEIM_REGISTER_MAX_CNT 24
#endif

/** 系统启动电压*/
#ifndef UTE_DRV_BATTERY_POWER_ON_VOLTAGE
#define UTE_DRV_BATTERY_POWER_ON_VOLTAGE     3000  //mv
#endif

/*! 默认发送历史数据定时器间隔zn.zeng, 2021-08-23  */
#ifndef UTE_SEND_DATA_TO_PHONE_INVTERVAL
#define UTE_SEND_DATA_TO_PHONE_INVTERVAL 60 // ms
#endif

/*! 屏宽度 zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_SCREEN_WIDTH
#define UTE_DRV_SCREEN_WIDTH 240
#endif
/*! 屏高度 zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_SCREEN_HEIGHT
#define UTE_DRV_SCREEN_HEIGHT 284
#endif
/*! 屏使用16bit色彩 zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_SCREEN_PIXEL_BYTES
#define UTE_DRV_SCREEN_PIXEL_BYTES 2
#endif

/*! 每次亮屏之前先清屏，防止闪烁 xjc, 2022-05-18  */
#ifndef UTE_DRV_CLEAR_SCREEN_BEFORE_BACKLIGHT_ON_SUPPORT
#define UTE_DRV_CLEAR_SCREEN_BEFORE_BACKLIGHT_ON_SUPPORT 0
#endif

// #define UTE_DRV_DSPI_FOR_SCREEN_SUPPORT 1
#ifndef UTE_DRV_SCREEN_TE_SIGNAL_SUPPORT
#define UTE_DRV_SCREEN_TE_SIGNAL_SUPPORT 1
#define UTE_DRV_SCREEN_TE_SIGNAL_INT_GPIO_VECTORn PORT_INT1_VECTOR
#define UTE_DRV_SCREEN_TE_SIGNAL_INT_GPIO_PIN IO_PA6
#define UTE_DRV_SCREEN_TE_SIGNAL_INT_GPIO_PULL 1
#define UTE_DRV_SCREEN_TE_SIGNAL_INT_GPIO_TRIGGER 1
#endif

/*! 屏复位管脚zn.zeng, 2021-10-21  */
#ifndef UTE_DRV_SCREEN_RST_GPIO_PIN
#define UTE_DRV_SCREEN_RST_GPIO_PIN      IO_PA7
#endif
/*! 屏cs管脚zn.zeng, 2021-10-21  */
#ifndef UTE_DRV_SCREEN_CS_GPIO_PIN
#define UTE_DRV_SCREEN_CS_GPIO_PIN      IO_PA5
#endif

#ifndef UTE_DRV_SCREEN_BACKLIGHT_PWM_SUPPORT
#define UTE_DRV_SCREEN_BACKLIGHT_PWM_SUPPORT 1
#endif
/*! 背光PWM控制输出的频率 zn.zeng, 2021-09-24  */
#ifndef UTE_DRV_SCREEN_BACKLIGHT_PWM_HZ
#define UTE_DRV_SCREEN_BACKLIGHT_PWM_HZ 200
#endif
/*! 背光PWM控制输出定时器索引 zn.zeng, 2021-09-24  */
#ifndef UTE_DRV_SCREEN_BACKLIGHT_PWM_ID
#define UTE_DRV_SCREEN_BACKLIGHT_PWM_ID GPIO_PE6
#endif
/*! 背光控制输出管脚 zn.zeng, 2021-09-24  */
#ifndef UTE_DRV_SCREEN_BACKLIGHT_GPIO_PIN
#define UTE_DRV_SCREEN_BACKLIGHT_GPIO_PIN   IO_PE6
#endif

#define DRV_TFT_S280X284_I18_ST7789P3_XHL183BA2401_DSPI_SUPPORT 1

/*! 默认语言 zn.zeng, 2021-08-23  */
#ifndef DEFAULT_LANGUAGE
#define DEFAULT_LANGUAGE 0x02//ENGLISH_LANGUAGE_ID
#define SCREEN_TITLE_MULTIPLE_CHINESE_LANGUAGE_SUPPORT        1
#define SCREEN_TITLE_MULTIPLE_ENGLISH_LANGUAGE_SUPPORT        1
#define SCREEN_TITLE_MULTIPLE_KOREAN_LANGUAGE_SUPPORT         0 //韩文 3
#define SCREEN_TITLE_MULTIPLE_JAPANESE_LANGUAGE_SUPPORT           0 //日文 4
#define SCREEN_TITLE_MULTIPLE_GERMAN_LANGUAGE_SUPPORT           0   //德文 5
#define SCREEN_TITLE_MULTIPLE_SPANISH_LANGUAGE_SUPPORT        0 //西班牙文 6
#define SCREEN_TITLE_MULTIPLE_FRENCH_LANGUAGE_SUPPORT                   0   //法文 7
#define SCREEN_TITLE_MULTIPLE_ITALIAN_LANGUAGE_SUPPORT            0 //意大利文 8
#define SCREEN_TITLE_MULTIPLE_PORTUGUESE_LANGUAGE_SUPPORT       0 //葡萄牙文 9
#define SCREEN_TITLE_MULTIPLE_ARABIC_LANGUAGE_SUPPORT           0   //阿拉伯文 A
#define SCREEN_TITLE_MULTIPLE_INDIA_LANGUAGE_SUPPORT            0 //India     B
#define SCREEN_TITLE_MULTIPLE_HINDI_LANGUAGE_SUPPORT          0 //印地语  C
#define SCREEN_TITLE_MULTIPLE_POLISH_LANGUAGE_SUPPORT         0 //波兰语  D
#define SCREEN_TITLE_MULTIPLE_RUSSIAN_LANGUAGE_SUPPORT        0//俄语  E
#define SCREEN_TITLE_MULTIPLE_DUTCH_LANGUAGE_SUPPORT          0//荷兰语 F
#define SCREEN_TITLE_MULTIPLE_TURKISH_LANGUAGE_SUPPORT        0//土耳其语  10
#define SCREEN_TITLE_MULTIPLE_BENGALI_LANGUAGE_SUPPORT       0 //孟加拉语  11  Bengali
#define SCREEN_TITLE_MULTIPLE_URDU_LANGUAGE_SUPPORT           0 //乌尔都语   12  Urdu
#define SCREEN_TITLE_MULTIPLE_INDONESUAN_LANGUAGE_SUPPORT     0 //印度尼西亚语（爪哇语）  13  Indonesian
#define SCREEN_TITLE_MULTIPLE_PUNJABI_LANGUAGE_SUPPORT        0 //旁遮普语  14   Punjabi
#define SCREEN_TITLE_MULTIPLE_THAI_LANGUAGE_SUPPORT           0 //泰文  15   Thai
#define SCREEN_TITLE_MULTIPLE_CZECH_LANGUAGE_SUPPORT          0 //捷克语  16  Czech
#define SCREEN_TITLE_MULTIPLE_TRADITIONAL_CHINESE_LANGUAGE_SUPPORT 0 //繁体中文
#define SCREEN_TITLE_MULTIPLE_ROMANIAN_LANGUAGE_SUPPORT                 0 //罗马尼亚语 limba 0x1B
#define SCREEN_TITLE_MULTIPLE_VIETNAMESE_LANGUAGE_SUPPORT           1 //越南语 0x63
#endif

#endif//_UTE_PROJECT_CONFIG_H_
