//该头文件由软件自动生成，请勿随意修改！
#ifndef _UI_H
#define _UI_H

#define UI_BUF_0FONT_FONT_BIN                      UI_ADDR_BASE(0x0)
#define UI_LEN_0FONT_FONT_BIN                      0xcea18

#define UI_BUF_0FONT_FONT_NUM_24_BIN               UI_ADDR_BASE(0xcea18)
#define UI_LEN_0FONT_FONT_NUM_24_BIN               0x2c4d

#define UI_BUF_0FONT_FONT_NUM_38_BIN               UI_ADDR_BASE(0xd1665)
#define UI_LEN_0FONT_FONT_NUM_38_BIN               0x6168

#define UI_BUF_0FONT_FONT_NUM_46_BIN               UI_ADDR_BASE(0xd77cd)
#define UI_LEN_0FONT_FONT_NUM_46_BIN               0x8be4

#define UI_BUF_ACTIVITY_KCAL_BIN                   UI_ADDR_BASE(0xe03b1)
#define UI_LEN_ACTIVITY_KCAL_BIN                   0x7b7

#define UI_BUF_ACTIVITY_KM_BIN                     UI_ADDR_BASE(0xe0b68)
#define UI_LEN_ACTIVITY_KM_BIN                     0x70c

#define UI_BUF_ACTIVITY_STEP_BIN                   UI_ADDR_BASE(0xe1274)
#define UI_LEN_ACTIVITY_STEP_BIN                   0x7a8

#define UI_BUF_ALARM_CLOCK_ADD_BIN                 UI_ADDR_BASE(0xe1a1c)
#define UI_LEN_ALARM_CLOCK_ADD_BIN                 0xbdf

#define UI_BUF_ALARM_CLOCK_ADD_CLICK_BIN           UI_ADDR_BASE(0xe25fb)
#define UI_LEN_ALARM_CLOCK_ADD_CLICK_BIN           0xb8c

#define UI_BUF_ALARM_CLOCK_CONTINUE_BIN            UI_ADDR_BASE(0xe3187)
#define UI_LEN_ALARM_CLOCK_CONTINUE_BIN            0xba4

#define UI_BUF_ALARM_CLOCK_CONTINUE_CLICK_BIN      UI_ADDR_BASE(0xe3d2b)
#define UI_LEN_ALARM_CLOCK_CONTINUE_CLICK_BIN      0xb86

#define UI_BUF_ALARM_CLOCK_DELETE_BIN              UI_ADDR_BASE(0xe48b1)
#define UI_LEN_ALARM_CLOCK_DELETE_BIN              0x1073

#define UI_BUF_ALARM_CLOCK_DELETE_CLICK_BIN        UI_ADDR_BASE(0xe5924)
#define UI_LEN_ALARM_CLOCK_DELETE_CLICK_BIN        0x1015

#define UI_BUF_ALARM_CLOCK_NUM_BIN                 UI_ADDR_BASE(0xe6939)
#define UI_LEN_ALARM_CLOCK_NUM_BIN                 0x1743

#define UI_BUF_ALARM_CLOCK_OPEN_BIN                UI_ADDR_BASE(0xe807c)
#define UI_LEN_ALARM_CLOCK_OPEN_BIN                0x226

#define UI_BUF_ALARM_CLOCK_SELECT1_BIN             UI_ADDR_BASE(0xe82a2)
#define UI_LEN_ALARM_CLOCK_SELECT1_BIN             0x5c9

#define UI_BUF_ALARM_CLOCK_SELECT1_ON_BIN          UI_ADDR_BASE(0xe886b)
#define UI_LEN_ALARM_CLOCK_SELECT1_ON_BIN          0x495

#define UI_BUF_ALARM_CLOCK_YES_BIN                 UI_ADDR_BASE(0xe8d00)
#define UI_LEN_ALARM_CLOCK_YES_BIN                 0xbc0

#define UI_BUF_ALARM_CLOCK_YES_CLICK_BIN           UI_ADDR_BASE(0xe98c0)
#define UI_LEN_ALARM_CLOCK_YES_CLICK_BIN           0xba6

#define UI_BUF_BLOOD_OXYGEN_BLOOD_OXYGEN_BIN       UI_ADDR_BASE(0xea466)
#define UI_LEN_BLOOD_OXYGEN_BLOOD_OXYGEN_BIN       0x1fb7

#define UI_BUF_BLOOD_OXYGEN_EXPLAIN_BIN            UI_ADDR_BASE(0xec41d)
#define UI_LEN_BLOOD_OXYGEN_EXPLAIN_BIN            0xcfd

#define UI_BUF_BREATHE_BREATHE_BIN                 UI_ADDR_BASE(0xed11a)
#define UI_LEN_BREATHE_BREATHE_BIN                 0x4eeb

#define UI_BUF_BREATHE_MODE_BIN                    UI_ADDR_BASE(0xf2005)
#define UI_LEN_BREATHE_MODE_BIN                    0xbf5

#define UI_BUF_BREATHE_MODE_CLICK_BIN              UI_ADDR_BASE(0xf2bfa)
#define UI_LEN_BREATHE_MODE_CLICK_BIN              0xbe6

#define UI_BUF_BREATHE_TIME_BIN                    UI_ADDR_BASE(0xf37e0)
#define UI_LEN_BREATHE_TIME_BIN                    0xa50

#define UI_BUF_BREATHE_TIME_CLICK_BIN              UI_ADDR_BASE(0xf4230)
#define UI_LEN_BREATHE_TIME_CLICK_BIN              0xa29

#define UI_BUF_CALCULATOR_0_CLICK_BIN              UI_ADDR_BASE(0xf4c59)
#define UI_LEN_CALCULATOR_0_CLICK_BIN              0x610

#define UI_BUF_CALCULATOR_1_CLICK_BIN              UI_ADDR_BASE(0xf5269)
#define UI_LEN_CALCULATOR_1_CLICK_BIN              0x4f8

#define UI_BUF_CALCULATOR_2_CLICK_BIN              UI_ADDR_BASE(0xf5761)
#define UI_LEN_CALCULATOR_2_CLICK_BIN              0x55a

#define UI_BUF_CALCULATOR_3_CLICK_BIN              UI_ADDR_BASE(0xf5cbb)
#define UI_LEN_CALCULATOR_3_CLICK_BIN              0x598

#define UI_BUF_CALCULATOR_4_CLICK_BIN              UI_ADDR_BASE(0xf6253)
#define UI_LEN_CALCULATOR_4_CLICK_BIN              0x58f

#define UI_BUF_CALCULATOR_5_CLICK_BIN              UI_ADDR_BASE(0xf67e2)
#define UI_LEN_CALCULATOR_5_CLICK_BIN              0x565

#define UI_BUF_CALCULATOR_6_CLICK_BIN              UI_ADDR_BASE(0xf6d47)
#define UI_LEN_CALCULATOR_6_CLICK_BIN              0x5e2

#define UI_BUF_CALCULATOR_7_CLICK_BIN              UI_ADDR_BASE(0xf7329)
#define UI_LEN_CALCULATOR_7_CLICK_BIN              0x4fa

#define UI_BUF_CALCULATOR_8_CLICK_BIN              UI_ADDR_BASE(0xf7823)
#define UI_LEN_CALCULATOR_8_CLICK_BIN              0x621

#define UI_BUF_CALCULATOR_9_CLICK_BIN              UI_ADDR_BASE(0xf7e44)
#define UI_LEN_CALCULATOR_9_CLICK_BIN              0x61e

#define UI_BUF_CALCULATOR_ADD_CLICK_BIN            UI_ADDR_BASE(0xf8462)
#define UI_LEN_CALCULATOR_ADD_CLICK_BIN            0x516

#define UI_BUF_CALCULATOR_BG_BIN                   UI_ADDR_BASE(0xf8978)
#define UI_LEN_CALCULATOR_BG_BIN                   0x58a8

#define UI_BUF_CALCULATOR_CE_CLICK_BIN             UI_ADDR_BASE(0xfe220)
#define UI_LEN_CALCULATOR_CE_CLICK_BIN             0x5d6

#define UI_BUF_CALCULATOR_C_CLICK_BIN              UI_ADDR_BASE(0xfe7f6)
#define UI_LEN_CALCULATOR_C_CLICK_BIN              0x4eb

#define UI_BUF_CALCULATOR_DEL_CLICK_BIN            UI_ADDR_BASE(0xfece1)
#define UI_LEN_CALCULATOR_DEL_CLICK_BIN            0x62e

#define UI_BUF_CALCULATOR_DIVIDED_CLICK_BIN        UI_ADDR_BASE(0xff30f)
#define UI_LEN_CALCULATOR_DIVIDED_CLICK_BIN        0x476

#define UI_BUF_CALCULATOR_EQUAL_CLICK_BIN          UI_ADDR_BASE(0xff785)
#define UI_LEN_CALCULATOR_EQUAL_CLICK_BIN          0x440

#define UI_BUF_CALCULATOR_MINUS_CLICK_BIN          UI_ADDR_BASE(0xffbc5)
#define UI_LEN_CALCULATOR_MINUS_CLICK_BIN          0x5c6

#define UI_BUF_CALCULATOR_MULTIPLY_CLICK_BIN       UI_ADDR_BASE(0x10018b)
#define UI_LEN_CALCULATOR_MULTIPLY_CLICK_BIN       0x5be

#define UI_BUF_CALCULATOR_POINT_CLICK_BIN          UI_ADDR_BASE(0x100749)
#define UI_LEN_CALCULATOR_POINT_CLICK_BIN          0x422

#define UI_BUF_CALCULATOR_REDUCE_CLICK_BIN         UI_ADDR_BASE(0x100b6b)
#define UI_LEN_CALCULATOR_REDUCE_CLICK_BIN         0x408

#define UI_BUF_CALL_0_CLICK_BIN                    UI_ADDR_BASE(0x100f73)
#define UI_LEN_CALL_0_CLICK_BIN                    0x74c

#define UI_BUF_CALL_7_CLICK_BIN                    UI_ADDR_BASE(0x1016bf)
#define UI_LEN_CALL_7_CLICK_BIN                    0x66d

#define UI_BUF_CALL_9_CLICK_BIN                    UI_ADDR_BASE(0x101d2c)
#define UI_LEN_CALL_9_CLICK_BIN                    0x868

#define UI_BUF_CALL_ANSWER_BIN                     UI_ADDR_BASE(0x102594)
#define UI_LEN_CALL_ANSWER_BIN                     0xbde

#define UI_BUF_CALL_ANSWER_CLICK_BIN               UI_ADDR_BASE(0x103172)
#define UI_LEN_CALL_ANSWER_CLICK_BIN               0xbba

#define UI_BUF_CALL_BG1_BIN                        UI_ADDR_BASE(0x103d2c)
#define UI_LEN_CALL_BG1_BIN                        0x45d3

#define UI_BUF_CALL_CALL_CLICK_BIN                 UI_ADDR_BASE(0x1082ff)
#define UI_LEN_CALL_CALL_CLICK_BIN                 0x52c

#define UI_BUF_CALL_DEL_CLICK_BIN                  UI_ADDR_BASE(0x10882b)
#define UI_LEN_CALL_DEL_CLICK_BIN                  0x4e1

#define UI_BUF_CALL_MES_BIN                        UI_ADDR_BASE(0x108d0c)
#define UI_LEN_CALL_MES_BIN                        0x25a

#define UI_BUF_CALL_MES_CLICK_BIN                  UI_ADDR_BASE(0x108f66)
#define UI_LEN_CALL_MES_CLICK_BIN                  0x31f

#define UI_BUF_CALL_MUTE_BIN                       UI_ADDR_BASE(0x109285)
#define UI_LEN_CALL_MUTE_BIN                       0x856

#define UI_BUF_CALL_MUTE_CLICK_BIN                 UI_ADDR_BASE(0x109adb)
#define UI_LEN_CALL_MUTE_CLICK_BIN                 0x9ed

#define UI_BUF_CALL_MUTE_ON_BIN                    UI_ADDR_BASE(0x10a4c8)
#define UI_LEN_CALL_MUTE_ON_BIN                    0xc11

#define UI_BUF_CALL_REJECT_BIN                     UI_ADDR_BASE(0x10b0d9)
#define UI_LEN_CALL_REJECT_BIN                     0xc6c

#define UI_BUF_CALL_REJECT_CLICK_BIN               UI_ADDR_BASE(0x10bd45)
#define UI_LEN_CALL_REJECT_CLICK_BIN               0xc4b

#define UI_BUF_CALL_DIAL_NUM_0_BIN                 UI_ADDR_BASE(0x10c990)
#define UI_LEN_CALL_DIAL_NUM_0_BIN                 0x4aa

#define UI_BUF_CALL_DIAL_NUM_1_BIN                 UI_ADDR_BASE(0x10ce3a)
#define UI_LEN_CALL_DIAL_NUM_1_BIN                 0x2d8

#define UI_BUF_CALL_DIAL_NUM_2_BIN                 UI_ADDR_BASE(0x10d112)
#define UI_LEN_CALL_DIAL_NUM_2_BIN                 0x328

#define UI_BUF_CALL_DIAL_NUM_3_BIN                 UI_ADDR_BASE(0x10d43a)
#define UI_LEN_CALL_DIAL_NUM_3_BIN                 0x371

#define UI_BUF_CALL_DIAL_NUM_4_BIN                 UI_ADDR_BASE(0x10d7ab)
#define UI_LEN_CALL_DIAL_NUM_4_BIN                 0x33d

#define UI_BUF_CALL_DIAL_NUM_5_BIN                 UI_ADDR_BASE(0x10dae8)
#define UI_LEN_CALL_DIAL_NUM_5_BIN                 0x343

#define UI_BUF_CALL_DIAL_NUM_6_BIN                 UI_ADDR_BASE(0x10de2b)
#define UI_LEN_CALL_DIAL_NUM_6_BIN                 0x3af

#define UI_BUF_CALL_DIAL_NUM_7_BIN                 UI_ADDR_BASE(0x10e1da)
#define UI_LEN_CALL_DIAL_NUM_7_BIN                 0x40d

#define UI_BUF_CALL_DIAL_NUM_8_BIN                 UI_ADDR_BASE(0x10e5e7)
#define UI_LEN_CALL_DIAL_NUM_8_BIN                 0x3fc

#define UI_BUF_CALL_DIAL_NUM_9_BIN                 UI_ADDR_BASE(0x10e9e3)
#define UI_LEN_CALL_DIAL_NUM_9_BIN                 0x5e7

#define UI_BUF_CAMERA_CAMERA_BIN                   UI_ADDR_BASE(0x10efca)
#define UI_LEN_CAMERA_CAMERA_BIN                   0x1bd9

#define UI_BUF_CHARGE_CHARGE1_BIN                  UI_ADDR_BASE(0x110ba3)
#define UI_LEN_CHARGE_CHARGE1_BIN                  0x7d8

#define UI_BUF_CHARGE_CHARGE2_BIN                  UI_ADDR_BASE(0x11137b)
#define UI_LEN_CHARGE_CHARGE2_BIN                  0x1240

#define UI_BUF_CHARGE_LOW_POWER_BIN                UI_ADDR_BASE(0x1125bb)
#define UI_LEN_CHARGE_LOW_POWER_BIN                0x1210

#define UI_BUF_CLOCK_DOWN_MENU_BLE_ICON_OFF_BIN    UI_ADDR_BASE(0x1137cb)
#define UI_LEN_CLOCK_DOWN_MENU_BLE_ICON_OFF_BIN    0x177

#define UI_BUF_CLOCK_DOWN_MENU_BLE_ICON_ON_BIN     UI_ADDR_BASE(0x113942)
#define UI_LEN_CLOCK_DOWN_MENU_BLE_ICON_ON_BIN     0x180

#define UI_BUF_CLOCK_DOWN_MENU_BT_ICON_OFF_BIN     UI_ADDR_BASE(0x113ac2)
#define UI_LEN_CLOCK_DOWN_MENU_BT_ICON_OFF_BIN     0x111

#define UI_BUF_CLOCK_DOWN_MENU_BT_ICON_ON_BIN      UI_ADDR_BASE(0x113bd3)
#define UI_LEN_CLOCK_DOWN_MENU_BT_ICON_ON_BIN      0x11b

#define UI_BUF_CLOCK_DOWN_MENU_BT_OFF_BIN          UI_ADDR_BASE(0x113cee)
#define UI_LEN_CLOCK_DOWN_MENU_BT_OFF_BIN          0x5d2

#define UI_BUF_CLOCK_DOWN_MENU_BT_ON_BIN           UI_ADDR_BASE(0x1142c0)
#define UI_LEN_CLOCK_DOWN_MENU_BT_ON_BIN           0x650

#define UI_BUF_CLOCK_DOWN_MENU_DND_OFF_BIN         UI_ADDR_BASE(0x114910)
#define UI_LEN_CLOCK_DOWN_MENU_DND_OFF_BIN         0x5a7

#define UI_BUF_CLOCK_DOWN_MENU_DND_ON_BIN          UI_ADDR_BASE(0x114eb7)
#define UI_LEN_CLOCK_DOWN_MENU_DND_ON_BIN          0x628

#define UI_BUF_CLOCK_DOWN_MENU_LIGHT_1_BIN         UI_ADDR_BASE(0x1154df)
#define UI_LEN_CLOCK_DOWN_MENU_LIGHT_1_BIN         0x713

#define UI_BUF_CLOCK_DOWN_MENU_LIGHT_2_BIN         UI_ADDR_BASE(0x115bf2)
#define UI_LEN_CLOCK_DOWN_MENU_LIGHT_2_BIN         0x75a

#define UI_BUF_CLOCK_DOWN_MENU_LIGHT_3_BIN         UI_ADDR_BASE(0x11634c)
#define UI_LEN_CLOCK_DOWN_MENU_LIGHT_3_BIN         0x774

#define UI_BUF_CLOCK_DOWN_MENU_LIGHT_4_BIN         UI_ADDR_BASE(0x116ac0)
#define UI_LEN_CLOCK_DOWN_MENU_LIGHT_4_BIN         0x790

#define UI_BUF_CLOCK_DOWN_MENU_LIGHT_5_BIN         UI_ADDR_BASE(0x117250)
#define UI_LEN_CLOCK_DOWN_MENU_LIGHT_5_BIN         0x7b6

#define UI_BUF_CLOCK_DOWN_MENU_MUTE_OFF_BIN        UI_ADDR_BASE(0x117a06)
#define UI_LEN_CLOCK_DOWN_MENU_MUTE_OFF_BIN        0x59f

#define UI_BUF_CLOCK_DOWN_MENU_MUTE_ON_BIN         UI_ADDR_BASE(0x117fa5)
#define UI_LEN_CLOCK_DOWN_MENU_MUTE_ON_BIN         0x78e

#define UI_BUF_CLOCK_DOWN_MENU_SETTING_BIN         UI_ADDR_BASE(0x118733)
#define UI_LEN_CLOCK_DOWN_MENU_SETTING_BIN         0x743

#define UI_BUF_CLOCK_DOWN_MENU_TOUCH_BIN           UI_ADDR_BASE(0x118e76)
#define UI_LEN_CLOCK_DOWN_MENU_TOUCH_BIN           0x61a

#define UI_BUF_COMMON_1_CLICK_BIN                  UI_ADDR_BASE(0x119490)
#define UI_LEN_COMMON_1_CLICK_BIN                  0x4cb

#define UI_BUF_COMMON_2_CLICK_BIN                  UI_ADDR_BASE(0x11995b)
#define UI_LEN_COMMON_2_CLICK_BIN                  0x511

#define UI_BUF_COMMON_3_CLICK_BIN                  UI_ADDR_BASE(0x119e6c)
#define UI_LEN_COMMON_3_CLICK_BIN                  0x557

#define UI_BUF_COMMON_4_CLICK_BIN                  UI_ADDR_BASE(0x11a3c3)
#define UI_LEN_COMMON_4_CLICK_BIN                  0x531

#define UI_BUF_COMMON_5_CLICK_BIN                  UI_ADDR_BASE(0x11a8f4)
#define UI_LEN_COMMON_5_CLICK_BIN                  0x53b

#define UI_BUF_COMMON_6_CLICK_BIN                  UI_ADDR_BASE(0x11ae2f)
#define UI_LEN_COMMON_6_CLICK_BIN                  0x5ce

#define UI_BUF_COMMON_8_CLICK_BIN                  UI_ADDR_BASE(0x11b3fd)
#define UI_LEN_COMMON_8_CLICK_BIN                  0x607

#define UI_BUF_COMMON_BG_BIN                       UI_ADDR_BASE(0x11ba04)
#define UI_LEN_COMMON_BG_BIN                       0x726

#define UI_BUF_COMMON_BG1_BIN                      UI_ADDR_BASE(0x11c12a)
#define UI_LEN_COMMON_BG1_BIN                      0x2ff

#define UI_BUF_COMMON_BG2_BIN                      UI_ADDR_BASE(0x11c429)
#define UI_LEN_COMMON_BG2_BIN                      0x8f

#define UI_BUF_COMMON_BUTTON_BIN                   UI_ADDR_BASE(0x11c4b8)
#define UI_LEN_COMMON_BUTTON_BIN                   0xaea

#define UI_BUF_COMMON_BUTTON_CLICK_BIN             UI_ADDR_BASE(0x11cfa2)
#define UI_LEN_COMMON_BUTTON_CLICK_BIN             0xaea

#define UI_BUF_COMMON_COLON_NUM_130_46_BIN         UI_ADDR_BASE(0x11da8c)
#define UI_LEN_COMMON_COLON_NUM_130_46_BIN         0x18f

#define UI_BUF_COMMON_COLON_NUM_16_24_BIN          UI_ADDR_BASE(0x11dc1b)
#define UI_LEN_COMMON_COLON_NUM_16_24_BIN          0x89

#define UI_BUF_COMMON_COLON_NUM_30_46_BIN          UI_ADDR_BASE(0x11dca4)
#define UI_LEN_COMMON_COLON_NUM_30_46_BIN          0x1cd

#define UI_BUF_COMMON_FIND_PHONE_BIN               UI_ADDR_BASE(0x11de71)
#define UI_LEN_COMMON_FIND_PHONE_BIN               0x25e5

#define UI_BUF_COMMON_FIND_PHONE_START_BIN         UI_ADDR_BASE(0x120456)
#define UI_LEN_COMMON_FIND_PHONE_START_BIN         0x511

#define UI_BUF_COMMON_FIND_PHONE_STOP_BIN          UI_ADDR_BASE(0x120967)
#define UI_LEN_COMMON_FIND_PHONE_STOP_BIN          0x3a5

#define UI_BUF_COMMON_INCREASE_BIN                 UI_ADDR_BASE(0x120d0c)
#define UI_LEN_COMMON_INCREASE_BIN                 0x67f

#define UI_BUF_COMMON_INCREASE_CLICK_BIN           UI_ADDR_BASE(0x12138b)
#define UI_LEN_COMMON_INCREASE_CLICK_BIN           0x67f

#define UI_BUF_COMMON_NO_BIN                       UI_ADDR_BASE(0x121a0a)
#define UI_LEN_COMMON_NO_BIN                       0xcf7

#define UI_BUF_COMMON_NO_CLICK_BIN                 UI_ADDR_BASE(0x122701)
#define UI_LEN_COMMON_NO_CLICK_BIN                 0xcc8

#define UI_BUF_COMMON_NUM_16_24_BIN                UI_ADDR_BASE(0x1233c9)
#define UI_LEN_COMMON_NUM_16_24_BIN                0x1a0f

#define UI_BUF_COMMON_NUM_24_38_BIN                UI_ADDR_BASE(0x124dd8)
#define UI_LEN_COMMON_NUM_24_38_BIN                0x2abe

#define UI_BUF_COMMON_NUM_30_46_BIN                UI_ADDR_BASE(0x127896)
#define UI_LEN_COMMON_NUM_30_46_BIN                0x359b

#define UI_BUF_COMMON_NUM_LEFT_18_18_BIN           UI_ADDR_BASE(0x12ae31)
#define UI_LEN_COMMON_NUM_LEFT_18_18_BIN           0xf1a

#define UI_BUF_COMMON_NUM_RIGHT_18_18_BIN          UI_ADDR_BASE(0x12bd4b)
#define UI_LEN_COMMON_NUM_RIGHT_18_18_BIN          0xef4

#define UI_BUF_COMMON_OFF_BIN                      UI_ADDR_BASE(0x12cc3f)
#define UI_LEN_COMMON_OFF_BIN                      0x357

#define UI_BUF_COMMON_ON_BIN                       UI_ADDR_BASE(0x12cf96)
#define UI_LEN_COMMON_ON_BIN                       0x334

#define UI_BUF_COMMON_PAUSE_BIN                    UI_ADDR_BASE(0x12d2ca)
#define UI_LEN_COMMON_PAUSE_BIN                    0xc53

#define UI_BUF_COMMON_PAUSE_CLICK_BIN              UI_ADDR_BASE(0x12df1d)
#define UI_LEN_COMMON_PAUSE_CLICK_BIN              0xc4a

#define UI_BUF_COMMON_PERCENT_BIN                  UI_ADDR_BASE(0x12eb67)
#define UI_LEN_COMMON_PERCENT_BIN                  0x4fb

#define UI_BUF_COMMON_POINT_NUM_16_24_BIN          UI_ADDR_BASE(0x12f062)
#define UI_LEN_COMMON_POINT_NUM_16_24_BIN          0x37

#define UI_BUF_COMMON_POINT_NUM_30_46_BIN          UI_ADDR_BASE(0x12f099)
#define UI_LEN_COMMON_POINT_NUM_30_46_BIN          0x85

#define UI_BUF_COMMON_REDUCE_BIN                   UI_ADDR_BASE(0x12f11e)
#define UI_LEN_COMMON_REDUCE_BIN                   0x572

#define UI_BUF_COMMON_REDUCE_CLICK_BIN             UI_ADDR_BASE(0x12f690)
#define UI_LEN_COMMON_REDUCE_CLICK_BIN             0x56f

#define UI_BUF_COMMON_SELECT_BIN                   UI_ADDR_BASE(0x12fbff)
#define UI_LEN_COMMON_SELECT_BIN                   0x6da

#define UI_BUF_COMMON_SELECT_ON_BIN                UI_ADDR_BASE(0x1302d9)
#define UI_LEN_COMMON_SELECT_ON_BIN                0x649

#define UI_BUF_COMMON_START_BIN                    UI_ADDR_BASE(0x130922)
#define UI_LEN_COMMON_START_BIN                    0xd8a

#define UI_BUF_COMMON_START_CLICK_BIN              UI_ADDR_BASE(0x1316ac)
#define UI_LEN_COMMON_START_CLICK_BIN              0xdb5

#define UI_BUF_COMPO_SELECT_ADD_BIN                UI_ADDR_BASE(0x132461)
#define UI_LEN_COMPO_SELECT_ADD_BIN                0x235

#define UI_BUF_COMPO_SELECT_ADD_DEL_BIN            UI_ADDR_BASE(0x132696)
#define UI_LEN_COMPO_SELECT_ADD_DEL_BIN            0x54b

#define UI_BUF_COMPO_SELECT_BG_BIN                 UI_ADDR_BASE(0x132be1)
#define UI_LEN_COMPO_SELECT_BG_BIN                 0x138c

#define UI_BUF_DIALPLATE_1_BIN                     UI_ADDR_BASE(0x133f6d)
#define UI_LEN_DIALPLATE_1_BIN                     0x1046e

#define UI_BUF_DIALPLATE_4_BIN                     UI_ADDR_BASE(0x1443db)
#define UI_LEN_DIALPLATE_4_BIN                     0xe160

#define UI_BUF_DIALPLATE_BTF_BIN                   UI_ADDR_BASE(0x15253b)
#define UI_LEN_DIALPLATE_BTF_BIN                   0x2eae

#define UI_BUF_DIALPLATE_CUBE_BIN                  UI_ADDR_BASE(0x1553e9)
#define UI_LEN_DIALPLATE_CUBE_BIN                  0x2720

#define UI_BUF_DIALPLATE_BUTTERFLY_BG_BIN          UI_ADDR_BASE(0x157b09)
#define UI_LEN_DIALPLATE_BUTTERFLY_BG_BIN          0x11e8

#define UI_BUF_DIALPLATE_BUTTERFLY_BODY_BIN        UI_ADDR_BASE(0x158cf1)
#define UI_LEN_DIALPLATE_BUTTERFLY_BODY_BIN        0xc38

#define UI_BUF_DIALPLATE_BUTTERFLY_DOWN_BIN        UI_ADDR_BASE(0x159929)
#define UI_LEN_DIALPLATE_BUTTERFLY_DOWN_BIN        0x4623

#define UI_BUF_DIALPLATE_BUTTERFLY_LIGHT_BIN       UI_ADDR_BASE(0x15df4c)
#define UI_LEN_DIALPLATE_BUTTERFLY_LIGHT_BIN       0x2c8

#define UI_BUF_DIALPLATE_BUTTERFLY_UP_BIN          UI_ADDR_BASE(0x15e214)
#define UI_LEN_DIALPLATE_BUTTERFLY_UP_BIN          0x40b6

#define UI_BUF_DIALPLATE_CUBE_BG_BIN               UI_ADDR_BASE(0x1622ca)
#define UI_LEN_DIALPLATE_CUBE_BG_BIN               0x6342

#define UI_BUF_DIALPLATE_CUBE_CALL_BIN             UI_ADDR_BASE(0x16860c)
#define UI_LEN_DIALPLATE_CUBE_CALL_BIN             0x978

#define UI_BUF_DIALPLATE_CUBE_HEART_RATE_BIN       UI_ADDR_BASE(0x168f84)
#define UI_LEN_DIALPLATE_CUBE_HEART_RATE_BIN       0x9ae

#define UI_BUF_DIALPLATE_CUBE_MUSIC_BIN            UI_ADDR_BASE(0x169932)
#define UI_LEN_DIALPLATE_CUBE_MUSIC_BIN            0xb51

#define UI_BUF_DIALPLATE_CUBE_SLEEP_BIN            UI_ADDR_BASE(0x16a483)
#define UI_LEN_DIALPLATE_CUBE_SLEEP_BIN            0xad0

#define UI_BUF_DIALPLATE_CUBE_SPORT_BIN            UI_ADDR_BASE(0x16af53)
#define UI_LEN_DIALPLATE_CUBE_SPORT_BIN            0xad1

#define UI_BUF_DIALPLATE_CUBE_STEP_BIN             UI_ADDR_BASE(0x16ba24)
#define UI_LEN_DIALPLATE_CUBE_STEP_BIN             0xb8f

#define UI_BUF_DROPDOWN_BATTERY_0_BIN              UI_ADDR_BASE(0x16c5b3)
#define UI_LEN_DROPDOWN_BATTERY_0_BIN              0x10a

#define UI_BUF_DROPDOWN_BATTERY_1_BIN              UI_ADDR_BASE(0x16c6bd)
#define UI_LEN_DROPDOWN_BATTERY_1_BIN              0x154

#define UI_BUF_DROPDOWN_BATTERY_2_BIN              UI_ADDR_BASE(0x16c811)
#define UI_LEN_DROPDOWN_BATTERY_2_BIN              0x154

#define UI_BUF_DROPDOWN_BATTERY_3_BIN              UI_ADDR_BASE(0x16c965)
#define UI_LEN_DROPDOWN_BATTERY_3_BIN              0x154

#define UI_BUF_DROPDOWN_BATTERY_4_BIN              UI_ADDR_BASE(0x16cab9)
#define UI_LEN_DROPDOWN_BATTERY_4_BIN              0x154

#define UI_BUF_DROPDOWN_BATTERY_5_BIN              UI_ADDR_BASE(0x16cc0d)
#define UI_LEN_DROPDOWN_BATTERY_5_BIN              0x154

#define UI_BUF_DROPDOWN_BATTERY_6_BIN              UI_ADDR_BASE(0x16cd61)
#define UI_LEN_DROPDOWN_BATTERY_6_BIN              0x143

#define UI_BUF_DROPDOWN_BLUETOOTH_CONNECT_OFF_BIN    UI_ADDR_BASE(0x16cea4)
#define UI_LEN_DROPDOWN_BLUETOOTH_CONNECT_OFF_BIN    0x20b

#define UI_BUF_DROPDOWN_BLUETOOTH_CONNECT_ON_BIN    UI_ADDR_BASE(0x16d0af)
#define UI_LEN_DROPDOWN_BLUETOOTH_CONNECT_ON_BIN    0x255

#define UI_BUF_DROPDOWN_BLUETOOTH_OFF_BIN          UI_ADDR_BASE(0x16d304)
#define UI_LEN_DROPDOWN_BLUETOOTH_OFF_BIN          0xb98

#define UI_BUF_DROPDOWN_BLUETOOTH_ON_BIN           UI_ADDR_BASE(0x16de9c)
#define UI_LEN_DROPDOWN_BLUETOOTH_ON_BIN           0xbca

#define UI_BUF_DROPDOWN_CONNECT_OFF_BIN            UI_ADDR_BASE(0x16ea66)
#define UI_LEN_DROPDOWN_CONNECT_OFF_BIN            0xb23

#define UI_BUF_DROPDOWN_CONNECT_ON_BIN             UI_ADDR_BASE(0x16f589)
#define UI_LEN_DROPDOWN_CONNECT_ON_BIN             0xa88

#define UI_BUF_DROPDOWN_DISTURB_OFF_BIN            UI_ADDR_BASE(0x170011)
#define UI_LEN_DROPDOWN_DISTURB_OFF_BIN            0x9db

#define UI_BUF_DROPDOWN_DISTURB_ON_BIN             UI_ADDR_BASE(0x1709ec)
#define UI_LEN_DROPDOWN_DISTURB_ON_BIN             0x9cf

#define UI_BUF_DROPDOWN_FIND_PHONE_OFF_BIN         UI_ADDR_BASE(0x1713bb)
#define UI_LEN_DROPDOWN_FIND_PHONE_OFF_BIN         0xd70

#define UI_BUF_DROPDOWN_FIND_PHONE_ON_BIN          UI_ADDR_BASE(0x17212b)
#define UI_LEN_DROPDOWN_FIND_PHONE_ON_BIN          0xd7e

#define UI_BUF_DROPDOWN_FLASHLIGHT_OFF_BIN         UI_ADDR_BASE(0x172ea9)
#define UI_LEN_DROPDOWN_FLASHLIGHT_OFF_BIN         0xb0c

#define UI_BUF_DROPDOWN_FLASHLIGHT_ON_BIN          UI_ADDR_BASE(0x1739b5)
#define UI_LEN_DROPDOWN_FLASHLIGHT_ON_BIN          0xb06

#define UI_BUF_DROPDOWN_LIGHT_1_BIN                UI_ADDR_BASE(0x1744bb)
#define UI_LEN_DROPDOWN_LIGHT_1_BIN                0xcb4

#define UI_BUF_DROPDOWN_LIGHT_2_BIN                UI_ADDR_BASE(0x17516f)
#define UI_LEN_DROPDOWN_LIGHT_2_BIN                0xcc7

#define UI_BUF_DROPDOWN_MUTE_OFF_BIN               UI_ADDR_BASE(0x175e36)
#define UI_LEN_DROPDOWN_MUTE_OFF_BIN               0xb83

#define UI_BUF_DROPDOWN_MUTE_ON_BIN                UI_ADDR_BASE(0x1769b9)
#define UI_LEN_DROPDOWN_MUTE_ON_BIN                0xc14

#define UI_BUF_DROPDOWN_POWER1_BIN                 UI_ADDR_BASE(0x1775cd)
#define UI_LEN_DROPDOWN_POWER1_BIN                 0x1a7

#define UI_BUF_DROPDOWN_POWER2_BIN                 UI_ADDR_BASE(0x177774)
#define UI_LEN_DROPDOWN_POWER2_BIN                 0x1fb

#define UI_BUF_DROPDOWN_POWER3_BIN                 UI_ADDR_BASE(0x17796f)
#define UI_LEN_DROPDOWN_POWER3_BIN                 0x260

#define UI_BUF_DROPDOWN_POWER4_BIN                 UI_ADDR_BASE(0x177bcf)
#define UI_LEN_DROPDOWN_POWER4_BIN                 0x2d9

#define UI_BUF_DROPDOWN_POWER5_BIN                 UI_ADDR_BASE(0x177ea8)
#define UI_LEN_DROPDOWN_POWER5_BIN                 0x33b

#define UI_BUF_DROPDOWN_POWER6_BIN                 UI_ADDR_BASE(0x1781e3)
#define UI_LEN_DROPDOWN_POWER6_BIN                 0x1c7

#define UI_BUF_DROPDOWN_POWER_BG_BIN               UI_ADDR_BASE(0x1783aa)
#define UI_LEN_DROPDOWN_POWER_BG_BIN               0xae3

#define UI_BUF_DROPDOWN_SCAN_1_BIN                 UI_ADDR_BASE(0x178e8d)
#define UI_LEN_DROPDOWN_SCAN_1_BIN                 0xaa3

#define UI_BUF_DROPDOWN_SCAN_2_BIN                 UI_ADDR_BASE(0x179930)
#define UI_LEN_DROPDOWN_SCAN_2_BIN                 0xaa6

#define UI_BUF_GAME_GAMEOVER_BIN                   UI_ADDR_BASE(0x17a3d6)
#define UI_LEN_GAME_GAMEOVER_BIN                   0x349c

#define UI_BUF_GAME_GAME_BG_BIN                    UI_ADDR_BASE(0x17d872)
#define UI_LEN_GAME_GAME_BG_BIN                    0x3f80

#define UI_BUF_GAME_GAME_BIRD_BIN                  UI_ADDR_BASE(0x1817f2)
#define UI_LEN_GAME_GAME_BIRD_BIN                  0x11de

#define UI_BUF_GAME_GAME_FINISH_BIN                UI_ADDR_BASE(0x1829d0)
#define UI_LEN_GAME_GAME_FINISH_BIN                0x2cb9

#define UI_BUF_GAME_GAME_PIPE_DOWN_BIN             UI_ADDR_BASE(0x185689)
#define UI_LEN_GAME_GAME_PIPE_DOWN_BIN             0x1705

#define UI_BUF_GAME_GAME_PIPE_UP_BIN               UI_ADDR_BASE(0x186d8e)
#define UI_LEN_GAME_GAME_PIPE_UP_BIN               0x166b

#define UI_BUF_GAME_GAME_START_BIN                 UI_ADDR_BASE(0x1883f9)
#define UI_LEN_GAME_GAME_START_BIN                 0xc24

#define UI_BUF_HEART_RATE_CHART_BG_BIN             UI_ADDR_BASE(0x18901d)
#define UI_LEN_HEART_RATE_CHART_BG_BIN             0x2e92

#define UI_BUF_HEART_RATE_CHART_BG2_BIN            UI_ADDR_BASE(0x18beaf)
#define UI_LEN_HEART_RATE_CHART_BG2_BIN            0x1f67

#define UI_BUF_HEART_RATE_DOWN_BIN                 UI_ADDR_BASE(0x18de16)
#define UI_LEN_HEART_RATE_DOWN_BIN                 0x1fe

#define UI_BUF_HEART_RATE_HR_BIN                   UI_ADDR_BASE(0x18e014)
#define UI_LEN_HEART_RATE_HR_BIN                   0x1000

#define UI_BUF_HEART_RATE_HR_BG_BIN                UI_ADDR_BASE(0x18f014)
#define UI_LEN_HEART_RATE_HR_BG_BIN                0x133f

#define UI_BUF_HEART_RATE_UP_BIN                   UI_ADDR_BASE(0x190353)
#define UI_LEN_HEART_RATE_UP_BIN                   0x1fe

#define UI_BUF_I330001_BLOODOXYGEN_GIF_BIN         UI_ADDR_BASE(0x190551)
#define UI_LEN_I330001_BLOODOXYGEN_GIF_BIN         0x23820

#define UI_BUF_I330001_BLOODOXYGEN_ICON_DETECTION_BIN    UI_ADDR_BASE(0x1b3d71)
#define UI_LEN_I330001_BLOODOXYGEN_ICON_DETECTION_BIN    0x974

#define UI_BUF_I330001_BLOODOXYGEN_PERCENT_BIN     UI_ADDR_BASE(0x1b46e5)
#define UI_LEN_I330001_BLOODOXYGEN_PERCENT_BIN     0x363

#define UI_BUF_I330001_CALL_CALLRECORDS_BIN        UI_ADDR_BASE(0x1b4a48)
#define UI_LEN_I330001_CALL_CALLRECORDS_BIN        0x3b5

#define UI_BUF_I330001_CALL_CONTACTS_BIN           UI_ADDR_BASE(0x1b4dfd)
#define UI_LEN_I330001_CALL_CONTACTS_BIN           0x405

#define UI_BUF_I330001_CALL_DIALPAD_BIN            UI_ADDR_BASE(0x1b5202)
#define UI_LEN_I330001_CALL_DIALPAD_BIN            0x613

#define UI_BUF_I330001_FIRSTORDER_00_BIN           UI_ADDR_BASE(0x1b5815)
#define UI_LEN_I330001_FIRSTORDER_00_BIN           0x10af

#define UI_BUF_I330001_FIRSTORDER_ADD_BIN          UI_ADDR_BASE(0x1b68c4)
#define UI_LEN_I330001_FIRSTORDER_ADD_BIN          0x2e3

#define UI_BUF_I330001_FIRSTORDER_DELETE_BIN       UI_ADDR_BASE(0x1b6ba7)
#define UI_LEN_I330001_FIRSTORDER_DELETE_BIN       0x26d

#define UI_BUF_I330001_FIRSTORDER_ACTIVITY_CALORIES_BIN    UI_ADDR_BASE(0x1b6e14)
#define UI_LEN_I330001_FIRSTORDER_ACTIVITY_CALORIES_BIN    0x1f3

#define UI_BUF_I330001_FIRSTORDER_ACTIVITY_DIS_BIN    UI_ADDR_BASE(0x1b7007)
#define UI_LEN_I330001_FIRSTORDER_ACTIVITY_DIS_BIN    0x1dc

#define UI_BUF_I330001_FIRSTORDER_ACTIVITY_STEPT_BIN    UI_ADDR_BASE(0x1b71e3)
#define UI_LEN_I330001_FIRSTORDER_ACTIVITY_STEPT_BIN    0x237

#define UI_BUF_I330001_FIRSTORDER_FIXED_CALL_BIN    UI_ADDR_BASE(0x1b741a)
#define UI_LEN_I330001_FIRSTORDER_FIXED_CALL_BIN    0x73b

#define UI_BUF_I330001_FIRSTORDER_FIXED_MSM_BIN    UI_ADDR_BASE(0x1b7b55)
#define UI_LEN_I330001_FIRSTORDER_FIXED_MSM_BIN    0x96e

#define UI_BUF_I330001_FIRSTORDER_FIXED_SPORT_BIN    UI_ADDR_BASE(0x1b84c3)
#define UI_LEN_I330001_FIRSTORDER_FIXED_SPORT_BIN    0x8db

#define UI_BUF_I330001_FIRSTORDER_MUSIC_NEXT00_BIN    UI_ADDR_BASE(0x1b8d9e)
#define UI_LEN_I330001_FIRSTORDER_MUSIC_NEXT00_BIN    0x3dd

#define UI_BUF_I330001_FIRSTORDER_MUSIC_NEXT01_BIN    UI_ADDR_BASE(0x1b917b)
#define UI_LEN_I330001_FIRSTORDER_MUSIC_NEXT01_BIN    0x3dd

#define UI_BUF_I330001_FIRSTORDER_MUSIC_PAUSED_BIN    UI_ADDR_BASE(0x1b9558)
#define UI_LEN_I330001_FIRSTORDER_MUSIC_PAUSED_BIN    0x88a

#define UI_BUF_I330001_FIRSTORDER_MUSIC_PLAY00_BIN    UI_ADDR_BASE(0x1b9de2)
#define UI_LEN_I330001_FIRSTORDER_MUSIC_PLAY00_BIN    0x74d

#define UI_BUF_I330001_FIRSTORDER_MUSIC_PLAY01_BIN    UI_ADDR_BASE(0x1ba52f)
#define UI_LEN_I330001_FIRSTORDER_MUSIC_PLAY01_BIN    0x74d

#define UI_BUF_I330001_FIRSTORDER_MUSIC_UP00_BIN    UI_ADDR_BASE(0x1bac7c)
#define UI_LEN_I330001_FIRSTORDER_MUSIC_UP00_BIN    0x3dd

#define UI_BUF_I330001_FIRSTORDER_MUSIC_UP01_BIN    UI_ADDR_BASE(0x1bb059)
#define UI_LEN_I330001_FIRSTORDER_MUSIC_UP01_BIN    0x3dd

#define UI_BUF_I330001_FIRSTORDER_TIME_BG_BIN      UI_ADDR_BASE(0x1bb436)
#define UI_LEN_I330001_FIRSTORDER_TIME_BG_BIN      0x2e59

#define UI_BUF_I330001_FIRSTORDER_TIME_H_BIN       UI_ADDR_BASE(0x1be28f)
#define UI_LEN_I330001_FIRSTORDER_TIME_H_BIN       0x6c3

#define UI_BUF_I330001_FIRSTORDER_TIME_M_BIN       UI_ADDR_BASE(0x1be952)
#define UI_LEN_I330001_FIRSTORDER_TIME_M_BIN       0x86b

#define UI_BUF_I330001_HEART_ICON_BIN              UI_ADDR_BASE(0x1bf1bd)
#define UI_LEN_I330001_HEART_ICON_BIN              0x2ecd

#define UI_BUF_I330001_HEART_MAP_BIN               UI_ADDR_BASE(0x1c208a)
#define UI_LEN_I330001_HEART_MAP_BIN               0x2ce2

#define UI_BUF_I330001_KAIJI_ICON_LOGO_HELLO_BIN    UI_ADDR_BASE(0x1c4d6c)
#define UI_LEN_I330001_KAIJI_ICON_LOGO_HELLO_BIN    0x10c2

#define UI_BUF_I330001_MUSIC_BG_BIN                UI_ADDR_BASE(0x1c5e2e)
#define UI_LEN_I330001_MUSIC_BG_BIN                0x7e18

#define UI_BUF_I330001_MUSIC_NEXTSONG01_BIN        UI_ADDR_BASE(0x1cdc46)
#define UI_LEN_I330001_MUSIC_NEXTSONG01_BIN        0x257

#define UI_BUF_I330001_MUSIC_NEXTSONG02_BIN        UI_ADDR_BASE(0x1cde9d)
#define UI_LEN_I330001_MUSIC_NEXTSONG02_BIN        0x257

#define UI_BUF_I330001_MUSIC_PAUSED_BIN            UI_ADDR_BASE(0x1ce0f4)
#define UI_LEN_I330001_MUSIC_PAUSED_BIN            0xe14

#define UI_BUF_I330001_MUSIC_PLAY01_BIN            UI_ADDR_BASE(0x1cef08)
#define UI_LEN_I330001_MUSIC_PLAY01_BIN            0xcc3

#define UI_BUF_I330001_MUSIC_PLAY02_BIN            UI_ADDR_BASE(0x1cfbcb)
#define UI_LEN_I330001_MUSIC_PLAY02_BIN            0xc8f

#define UI_BUF_I330001_MUSIC_PREVIOUSSONG01_BIN    UI_ADDR_BASE(0x1d085a)
#define UI_LEN_I330001_MUSIC_PREVIOUSSONG01_BIN    0x24e

#define UI_BUF_I330001_MUSIC_PREVIOUSSONG02_BIN    UI_ADDR_BASE(0x1d0aa8)
#define UI_LEN_I330001_MUSIC_PREVIOUSSONG02_BIN    0x252

#define UI_BUF_I330001_MUSIC_VOLUME01_BIN          UI_ADDR_BASE(0x1d0cfa)
#define UI_LEN_I330001_MUSIC_VOLUME01_BIN          0x289

#define UI_BUF_I330001_MUSIC_VOLUME02_BIN          UI_ADDR_BASE(0x1d0f83)
#define UI_LEN_I330001_MUSIC_VOLUME02_BIN          0x289

#define UI_BUF_I330001_MUSIC_VOLUME03_BIN          UI_ADDR_BASE(0x1d120c)
#define UI_LEN_I330001_MUSIC_VOLUME03_BIN          0x3c4

#define UI_BUF_I330001_MUSIC_VOLUME04_BIN          UI_ADDR_BASE(0x1d15d0)
#define UI_LEN_I330001_MUSIC_VOLUME04_BIN          0x3c4

#define UI_BUF_I330001_NOTIFICATION_ICON_BUTTON_BIN    UI_ADDR_BASE(0x1d1994)
#define UI_LEN_I330001_NOTIFICATION_ICON_BUTTON_BIN    0x80e

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_FACEBOOK_BIN    UI_ADDR_BASE(0x1d21a2)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_FACEBOOK_BIN    0x4c9

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_FACEBOOKMESSENGER_BIN    UI_ADDR_BASE(0x1d266b)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_FACEBOOKMESSENGER_BIN    0x68a

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_FLICKR_BIN    UI_ADDR_BASE(0x1d2cf5)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_FLICKR_BIN    0x490

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_GMAIL_BIN    UI_ADDR_BASE(0x1d3185)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_GMAIL_BIN    0x572

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_GOOGLEPLUS_BIN    UI_ADDR_BASE(0x1d36f7)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_GOOGLEPLUS_BIN    0x57c

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_HANGOUTS_BIN    UI_ADDR_BASE(0x1d3c73)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_HANGOUTS_BIN    0x5ff

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_INSTAGRAM_BIN    UI_ADDR_BASE(0x1d4272)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_INSTAGRAM_BIN    0x881

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_KAKAOTAKTE_BIN    UI_ADDR_BASE(0x1d4af3)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_KAKAOTAKTE_BIN    0x5d8

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_LINE_BIN    UI_ADDR_BASE(0x1d50cb)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_LINE_BIN    0x57f

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_LINKEDIN_BIN    UI_ADDR_BASE(0x1d564a)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_LINKEDIN_BIN    0x53f

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_MMS_BIN    UI_ADDR_BASE(0x1d5b89)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_MMS_BIN    0x523

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_OTHER_BIN    UI_ADDR_BASE(0x1d60ac)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_OTHER_BIN    0x517

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_PAYTM_BIN    UI_ADDR_BASE(0x1d65c3)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_PAYTM_BIN    0x558

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_PINTEREST_BIN    UI_ADDR_BASE(0x1d6b1b)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_PINTEREST_BIN    0x60f

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_QQ_BIN    UI_ADDR_BASE(0x1d712a)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_QQ_BIN    0x5e7

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_SKYPE_BIN    UI_ADDR_BASE(0x1d7711)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_SKYPE_BIN    0x5d6

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_SNAPCHAT_BIN    UI_ADDR_BASE(0x1d7ce7)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_SNAPCHAT_BIN    0x560

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_TELEGRAM_BIN    UI_ADDR_BASE(0x1d8247)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_TELEGRAM_BIN    0x4cc

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_TRUECALLER_BIN    UI_ADDR_BASE(0x1d8713)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_TRUECALLER_BIN    0x603

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_TUMBLR_BIN    UI_ADDR_BASE(0x1d8d16)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_TUMBLR_BIN    0x487

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_TWITTER_BIN    UI_ADDR_BASE(0x1d919d)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_TWITTER_BIN    0x5bd

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_VIBER_BIN    UI_ADDR_BASE(0x1d975a)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_VIBER_BIN    0x6ac

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_VKONTAKTE_BIN    UI_ADDR_BASE(0x1d9e06)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_VKONTAKTE_BIN    0x58f

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_WECHAT_BIN    UI_ADDR_BASE(0x1da395)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_WECHAT_BIN    0x71f

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_WHATSAPP_BIN    UI_ADDR_BASE(0x1daab4)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_WHATSAPP_BIN    0x70a

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_YOUTUBE_BIN    UI_ADDR_BASE(0x1db1be)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_YOUTUBE_BIN    0x4a8

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_ZALO_BIN    UI_ADDR_BASE(0x1db666)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_ZALO_BIN    0x551

#define UI_BUF_I330001_POWEROFF_ICON_RESTART_BIN    UI_ADDR_BASE(0x1dbbb7)
#define UI_LEN_I330001_POWEROFF_ICON_RESTART_BIN    0x779

#define UI_BUF_I330001_POWEROFF_ICON_SHUTDOWN_BIN    UI_ADDR_BASE(0x1dc330)
#define UI_LEN_I330001_POWEROFF_ICON_SHUTDOWN_BIN    0x815

#define UI_BUF_I330001_POWEROFF_ICON_SOS_BIN       UI_ADDR_BASE(0x1dcb45)
#define UI_LEN_I330001_POWEROFF_ICON_SOS_BIN       0x97f

#define UI_BUF_I330001_PUBLIC_CLOSE00_BIN          UI_ADDR_BASE(0x1dd4c4)
#define UI_LEN_I330001_PUBLIC_CLOSE00_BIN          0x6ee

#define UI_BUF_I330001_PUBLIC_CLOSE01_BIN          UI_ADDR_BASE(0x1ddbb2)
#define UI_LEN_I330001_PUBLIC_CLOSE01_BIN          0x88e

#define UI_BUF_I330001_PUBLIC_END_BIN              UI_ADDR_BASE(0x1de440)
#define UI_LEN_I330001_PUBLIC_END_BIN              0x501

#define UI_BUF_I330001_PUBLIC_JICI_BIN             UI_ADDR_BASE(0x1de941)
#define UI_LEN_I330001_PUBLIC_JICI_BIN             0x645

#define UI_BUF_I330001_PUBLIC_OK00_BIN             UI_ADDR_BASE(0x1def86)
#define UI_LEN_I330001_PUBLIC_OK00_BIN             0x704

#define UI_BUF_I330001_PUBLIC_OK01_BIN             UI_ADDR_BASE(0x1df68a)
#define UI_LEN_I330001_PUBLIC_OK01_BIN             0x705

#define UI_BUF_I330001_PUBLIC_PAUSED_BIN           UI_ADDR_BASE(0x1dfd8f)
#define UI_LEN_I330001_PUBLIC_PAUSED_BIN           0x981

#define UI_BUF_I330001_PUBLIC_PLAY_BIN             UI_ADDR_BASE(0x1e0710)
#define UI_LEN_I330001_PUBLIC_PLAY_BIN             0x7be

#define UI_BUF_I330001_PUBLIC_RECTANGLE00_BIN      UI_ADDR_BASE(0x1e0ece)
#define UI_LEN_I330001_PUBLIC_RECTANGLE00_BIN      0x80e

#define UI_BUF_I330001_PUBLIC_RECTANGLE01_BIN      UI_ADDR_BASE(0x1e16dc)
#define UI_LEN_I330001_PUBLIC_RECTANGLE01_BIN      0x812

#define UI_BUF_I330001_PUBLIC_RECTANGLE02_BIN      UI_ADDR_BASE(0x1e1eee)
#define UI_LEN_I330001_PUBLIC_RECTANGLE02_BIN      0x80e

#define UI_BUF_I330001_PUBLIC_SOON_BIN             UI_ADDR_BASE(0x1e26fc)
#define UI_LEN_I330001_PUBLIC_SOON_BIN             0x779

#define UI_BUF_I330001_SLEEP_BG_BIN                UI_ADDR_BASE(0x1e2e75)
#define UI_LEN_I330001_SLEEP_BG_BIN                0x8292

#define UI_BUF_I330001_SLEEP_DOT1_BIN              UI_ADDR_BASE(0x1eb107)
#define UI_LEN_I330001_SLEEP_DOT1_BIN              0xe9

#define UI_BUF_I330001_SLEEP_DOT2_BIN              UI_ADDR_BASE(0x1eb1f0)
#define UI_LEN_I330001_SLEEP_DOT2_BIN              0xe9

#define UI_BUF_I330001_SLEEP_DOT3_BIN              UI_ADDR_BASE(0x1eb2d9)
#define UI_LEN_I330001_SLEEP_DOT3_BIN              0xe9

#define UI_BUF_I330001_SLEEP_DOT4_BIN              UI_ADDR_BASE(0x1eb3c2)
#define UI_LEN_I330001_SLEEP_DOT4_BIN              0xe9

#define UI_BUF_I330001_SLIDEMENU_ICON_BRIGHTNESS_BIN    UI_ADDR_BASE(0x1eb4ab)
#define UI_LEN_I330001_SLIDEMENU_ICON_BRIGHTNESS_BIN    0xa41

#define UI_BUF_I330001_SLIDEMENU_ICON_CALL00_BIN    UI_ADDR_BASE(0x1ebeec)
#define UI_LEN_I330001_SLIDEMENU_ICON_CALL00_BIN    0x829

#define UI_BUF_I330001_SLIDEMENU_ICON_CALL01_BIN    UI_ADDR_BASE(0x1ec715)
#define UI_LEN_I330001_SLIDEMENU_ICON_CALL01_BIN    0x82e

#define UI_BUF_I330001_SLIDEMENU_ICON_DND00_BIN    UI_ADDR_BASE(0x1ecf43)
#define UI_LEN_I330001_SLIDEMENU_ICON_DND00_BIN    0x7ab

#define UI_BUF_I330001_SLIDEMENU_ICON_DND01_BIN    UI_ADDR_BASE(0x1ed6ee)
#define UI_LEN_I330001_SLIDEMENU_ICON_DND01_BIN    0x7ae

#define UI_BUF_I330001_SLIDEMENU_ICON_FINDPHONE_BIN    UI_ADDR_BASE(0x1ede9c)
#define UI_LEN_I330001_SLIDEMENU_ICON_FINDPHONE_BIN    0xa25

#define UI_BUF_I330001_SLIDEMENU_ICON_SETTINGS_BIN    UI_ADDR_BASE(0x1ee8c1)
#define UI_LEN_I330001_SLIDEMENU_ICON_SETTINGS_BIN    0x941

#define UI_BUF_I330001_SLIDEMENU_ICON_SHOUDIAN00_BIN    UI_ADDR_BASE(0x1ef202)
#define UI_LEN_I330001_SLIDEMENU_ICON_SHOUDIAN00_BIN    0x8c5

#define UI_BUF_I330001_SLIDEMENU_ICON_TAIWAN00_BIN    UI_ADDR_BASE(0x1efac7)
#define UI_LEN_I330001_SLIDEMENU_ICON_TAIWAN00_BIN    0x8a1

#define UI_BUF_I330001_SLIDEMENU_ICON_TAIWAN01_BIN    UI_ADDR_BASE(0x1f0368)
#define UI_LEN_I330001_SLIDEMENU_ICON_TAIWAN01_BIN    0x8a6

#define UI_BUF_I330001_SLIDEMENU_ICON_THEME00_BIN    UI_ADDR_BASE(0x1f0c0e)
#define UI_LEN_I330001_SLIDEMENU_ICON_THEME00_BIN    0xae6

#define UI_BUF_I330001_SLIDEMENU_ICON_THEME01_BIN    UI_ADDR_BASE(0x1f16f4)
#define UI_LEN_I330001_SLIDEMENU_ICON_THEME01_BIN    0x9c8

#define UI_BUF_I330001_SLIDEMENU_ICON_THEME02_BIN    UI_ADDR_BASE(0x1f20bc)
#define UI_LEN_I330001_SLIDEMENU_ICON_THEME02_BIN    0xa26

#define UI_BUF_I330001_SLIDEMENU_ICON_THEME03_BIN    UI_ADDR_BASE(0x1f2ae2)
#define UI_LEN_I330001_SLIDEMENU_ICON_THEME03_BIN    0x838

#define UI_BUF_I330001_SLIDEMENU_ICON_THEME04_BIN    UI_ADDR_BASE(0x1f331a)
#define UI_LEN_I330001_SLIDEMENU_ICON_THEME04_BIN    0x9e0

#define UI_BUF_I330001_SLIDEMENU_ICON_THEME05_BIN    UI_ADDR_BASE(0x1f3cfa)
#define UI_LEN_I330001_SLIDEMENU_ICON_THEME05_BIN    0x9f2

#define UI_BUF_I330001_SLIDEMENU_ICON_THEME06_BIN    UI_ADDR_BASE(0x1f46ec)
#define UI_LEN_I330001_SLIDEMENU_ICON_THEME06_BIN    0xb54

#define UI_BUF_I330001_SLIDEMENU_ICON_THEME07_BIN    UI_ADDR_BASE(0x1f5240)
#define UI_LEN_I330001_SLIDEMENU_ICON_THEME07_BIN    0xa96

#define UI_BUF_I330001_SLIDEMENU_ICON_THEME08_BIN    UI_ADDR_BASE(0x1f5cd6)
#define UI_LEN_I330001_SLIDEMENU_ICON_THEME08_BIN    0xa65

#define UI_BUF_I330001_SLIDEMENU_ICON_THEME09_BIN    UI_ADDR_BASE(0x1f673b)
#define UI_LEN_I330001_SLIDEMENU_ICON_THEME09_BIN    0xa4f

#define UI_BUF_I330001_SLIDEMENU_ICON_VOLUMES00_BIN    UI_ADDR_BASE(0x1f718a)
#define UI_LEN_I330001_SLIDEMENU_ICON_VOLUMES00_BIN    0x945

#define UI_BUF_I330001_SLIDEMENU_ICON_VOLUMES01_BIN    UI_ADDR_BASE(0x1f7acf)
#define UI_LEN_I330001_SLIDEMENU_ICON_VOLUMES01_BIN    0xa1c

#define UI_BUF_I330001_SLIDEMENU_ICON_BATT_00_BIN    UI_ADDR_BASE(0x1f84eb)
#define UI_LEN_I330001_SLIDEMENU_ICON_BATT_00_BIN    0x149

#define UI_BUF_I330001_SLIDEMENU_ICON_BATT_01_BIN    UI_ADDR_BASE(0x1f8634)
#define UI_LEN_I330001_SLIDEMENU_ICON_BATT_01_BIN    0x1a1

#define UI_BUF_I330001_SLIDEMENU_ICON_BATT_02_BIN    UI_ADDR_BASE(0x1f87d5)
#define UI_LEN_I330001_SLIDEMENU_ICON_BATT_02_BIN    0x1a1

#define UI_BUF_I330001_SLIDEMENU_ICON_BATT_03_BIN    UI_ADDR_BASE(0x1f8976)
#define UI_LEN_I330001_SLIDEMENU_ICON_BATT_03_BIN    0x1a1

#define UI_BUF_I330001_SLIDEMENU_ICON_BATT_04_BIN    UI_ADDR_BASE(0x1f8b17)
#define UI_LEN_I330001_SLIDEMENU_ICON_BATT_04_BIN    0x199

#define UI_BUF_I330001_SLIDEMENU_ICON_CONNECT_FRAME_1390_BIN    UI_ADDR_BASE(0x1f8cb0)
#define UI_LEN_I330001_SLIDEMENU_ICON_CONNECT_FRAME_1390_BIN    0x1a1

#define UI_BUF_I330001_SLIDEMENU_ICON_CONNECT_GROUP_899_BIN    UI_ADDR_BASE(0x1f8e51)
#define UI_LEN_I330001_SLIDEMENU_ICON_CONNECT_GROUP_899_BIN    0x1a1

#define UI_BUF_I330001_SLIDEMENU_ICON_TELEPHONE_FRAME_1389_BIN    UI_ADDR_BASE(0x1f8ff2)
#define UI_LEN_I330001_SLIDEMENU_ICON_TELEPHONE_FRAME_1389_BIN    0x13e

#define UI_BUF_I330001_SLIDEMENU_ICON_TELEPHONE_GROUP_898_BIN    UI_ADDR_BASE(0x1f9130)
#define UI_LEN_I330001_SLIDEMENU_ICON_TELEPHONE_GROUP_898_BIN    0x13e

#define UI_BUF_I330001_SPORT_BTN_CLOSE_BIN         UI_ADDR_BASE(0x1f926e)
#define UI_LEN_I330001_SPORT_BTN_CLOSE_BIN         0x9ea

#define UI_BUF_I330001_SPORT_BTN_PLAY_BIN          UI_ADDR_BASE(0x1f9c58)
#define UI_LEN_I330001_SPORT_BTN_PLAY_BIN          0x945

#define UI_BUF_I330001_SPORT_BTN_PUSED_BIN         UI_ADDR_BASE(0x1fa59d)
#define UI_LEN_I330001_SPORT_BTN_PUSED_BIN         0xb06

#define UI_BUF_I330001_SPORT_COUNTDOWN_01_BIN      UI_ADDR_BASE(0x1fb0a3)
#define UI_LEN_I330001_SPORT_COUNTDOWN_01_BIN      0x83e

#define UI_BUF_I330001_SPORT_COUNTDOWN_02_BIN      UI_ADDR_BASE(0x1fb8e1)
#define UI_LEN_I330001_SPORT_COUNTDOWN_02_BIN      0x942

#define UI_BUF_I330001_SPORT_COUNTDOWN_03_BIN      UI_ADDR_BASE(0x1fc223)
#define UI_LEN_I330001_SPORT_COUNTDOWN_03_BIN      0x9ff

#define UI_BUF_I330001_SPORT_ICON_00_PAOBU_BIN     UI_ADDR_BASE(0x1fcc22)
#define UI_LEN_I330001_SPORT_ICON_00_PAOBU_BIN     0x97a

#define UI_BUF_I330001_SPORT_ICON_01_QIXING_BIN    UI_ADDR_BASE(0x1fd59c)
#define UI_LEN_I330001_SPORT_ICON_01_QIXING_BIN    0xea4

#define UI_BUF_I330001_SPORT_ICON_02_TIAOSHEN_BIN    UI_ADDR_BASE(0x1fe440)
#define UI_LEN_I330001_SPORT_ICON_02_TIAOSHEN_BIN    0xc36

#define UI_BUF_I330001_SPORT_ICON_03_YOUYONG_BIN    UI_ADDR_BASE(0x1ff076)
#define UI_LEN_I330001_SPORT_ICON_03_YOUYONG_BIN    0xb16

#define UI_BUF_I330001_SPORT_ICON_04_YUMAOQIU_BIN    UI_ADDR_BASE(0x1ffb8c)
#define UI_LEN_I330001_SPORT_ICON_04_YUMAOQIU_BIN    0xae2

#define UI_BUF_I330001_SPORT_ICON_05_PINGPANGQIU_BIN    UI_ADDR_BASE(0x20066e)
#define UI_LEN_I330001_SPORT_ICON_05_PINGPANGQIU_BIN    0xa66

#define UI_BUF_I330001_SPORT_ICON_06_WANGQIU_BIN    UI_ADDR_BASE(0x2010d4)
#define UI_LEN_I330001_SPORT_ICON_06_WANGQIU_BIN    0xbb6

#define UI_BUF_I330001_SPORT_ICON_07_PASHAN_BIN    UI_ADDR_BASE(0x201c8a)
#define UI_LEN_I330001_SPORT_ICON_07_PASHAN_BIN    0xb6c

#define UI_BUF_I330001_SPORT_ICON_08_TUBU_BIN      UI_ADDR_BASE(0x2027f6)
#define UI_LEN_I330001_SPORT_ICON_08_TUBU_BIN      0xad3

#define UI_BUF_I330001_SPORT_ICON_09_LANQIU_BIN    UI_ADDR_BASE(0x2032c9)
#define UI_LEN_I330001_SPORT_ICON_09_LANQIU_BIN    0xb57

#define UI_BUF_I330001_SPORT_ICON_10_ZUQIU_BIN     UI_ADDR_BASE(0x203e20)
#define UI_LEN_I330001_SPORT_ICON_10_ZUQIU_BIN     0xad4

#define UI_BUF_I330001_SPORT_ICON_11_BANGQIU_BIN    UI_ADDR_BASE(0x2048f4)
#define UI_LEN_I330001_SPORT_ICON_11_BANGQIU_BIN    0x9b1

#define UI_BUF_I330001_SPORT_ICON_12_PAIQIU_BIN    UI_ADDR_BASE(0x2052a5)
#define UI_LEN_I330001_SPORT_ICON_12_PAIQIU_BIN    0xa60

#define UI_BUF_I330001_SPORT_ICON_13_BANQIU_BIN    UI_ADDR_BASE(0x205d05)
#define UI_LEN_I330001_SPORT_ICON_13_BANQIU_BIN    0x941

#define UI_BUF_I330001_SPORT_ICON_14_GANLANQIU_BIN    UI_ADDR_BASE(0x206646)
#define UI_LEN_I330001_SPORT_ICON_14_GANLANQIU_BIN    0x9cb

#define UI_BUF_I330001_SPORT_ICON_15_QUGUNQIU_BIN    UI_ADDR_BASE(0x207011)
#define UI_LEN_I330001_SPORT_ICON_15_QUGUNQIU_BIN    0xa3d

#define UI_BUF_I330001_SPORT_ICON_16_TIAOWU_BIN    UI_ADDR_BASE(0x207a4e)
#define UI_LEN_I330001_SPORT_ICON_16_TIAOWU_BIN    0x8dd

#define UI_BUF_I330001_SPORT_ICON_17_DONGGANDANCHE_BIN    UI_ADDR_BASE(0x20832b)
#define UI_LEN_I330001_SPORT_ICON_17_DONGGANDANCHE_BIN    0xdb9

#define UI_BUF_I330001_SPORT_ICON_18_YUJIA_BIN     UI_ADDR_BASE(0x2090e4)
#define UI_LEN_I330001_SPORT_ICON_18_YUJIA_BIN     0x93c

#define UI_BUF_I330001_SPORT_ICON_19_YANGWOQIZUO_BIN    UI_ADDR_BASE(0x209a20)
#define UI_LEN_I330001_SPORT_ICON_19_YANGWOQIZUO_BIN    0x791

#define UI_BUF_I330001_SPORT_ICON_20_PAOBUJI_BIN    UI_ADDR_BASE(0x20a1b1)
#define UI_LEN_I330001_SPORT_ICON_20_PAOBUJI_BIN    0xb58

#define UI_BUF_I330001_SPORT_ICON_21_TICAO_BIN     UI_ADDR_BASE(0x20ad09)
#define UI_LEN_I330001_SPORT_ICON_21_TICAO_BIN     0x857

#define UI_BUF_I330001_SPORT_ICON_22_HUACHUAN_BIN    UI_ADDR_BASE(0x20b560)
#define UI_LEN_I330001_SPORT_ICON_22_HUACHUAN_BIN    0xf05

#define UI_BUF_I330001_SPORT_ICON_23_KAIHETIAO_BIN    UI_ADDR_BASE(0x20c465)
#define UI_LEN_I330001_SPORT_ICON_23_KAIHETIAO_BIN    0xa16

#define UI_BUF_I330001_SPORT_ICON_24_ZIYOUXUNLIAN_BIN    UI_ADDR_BASE(0x20ce7b)
#define UI_LEN_I330001_SPORT_ICON_24_ZIYOUXUNLIAN_BIN    0x921

#define UI_BUF_I330001_SPORT_ICON_25_CAIDAN_BIN    UI_ADDR_BASE(0x20d79c)
#define UI_LEN_I330001_SPORT_ICON_25_CAIDAN_BIN    0x6fa

#define UI_BUF_I330001_WEATHER_BG_BIN              UI_ADDR_BASE(0x20de96)
#define UI_LEN_I330001_WEATHER_BG_BIN              0x8405

#define UI_BUF_I330001_WEATHER_DC_BIN              UI_ADDR_BASE(0x21629b)
#define UI_LEN_I330001_WEATHER_DC_BIN              0x364

#define UI_BUF_I330001_WEATHER_DF_BIN              UI_ADDR_BASE(0x2165ff)
#define UI_LEN_I330001_WEATHER_DF_BIN              0x2b4

#define UI_BUF_I330001_WEATHER_NUM_BIN             UI_ADDR_BASE(0x2168b3)
#define UI_LEN_I330001_WEATHER_NUM_BIN             0x7262

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_00_BIN    UI_ADDR_BASE(0x21db15)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_00_BIN    0x1289

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_01_BIN    UI_ADDR_BASE(0x21ed9e)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_01_BIN    0x162b

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_02_BIN    UI_ADDR_BASE(0x2203c9)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_02_BIN    0x11bd

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_03_BIN    UI_ADDR_BASE(0x221586)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_03_BIN    0xe1e

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_04_BIN    UI_ADDR_BASE(0x2223a4)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_04_BIN    0x13aa

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_05_BIN    UI_ADDR_BASE(0x22374e)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_05_BIN    0x14be

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_06_BIN    UI_ADDR_BASE(0x224c0c)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_06_BIN    0x16f7

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_07_BIN    UI_ADDR_BASE(0x226303)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_07_BIN    0x108f

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_08_BIN    UI_ADDR_BASE(0x227392)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_08_BIN    0x12ca

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_09_BIN    UI_ADDR_BASE(0x22865c)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_09_BIN    0x113a

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_10_BIN    UI_ADDR_BASE(0x229796)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_10_BIN    0x13b3

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_11_BIN    UI_ADDR_BASE(0x22ab49)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_11_BIN    0x1437

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_12_BIN    UI_ADDR_BASE(0x22bf80)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_12_BIN    0x1163

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_13_BIN    UI_ADDR_BASE(0x22d0e3)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_13_BIN    0x1190

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_14_BIN    UI_ADDR_BASE(0x22e273)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_14_BIN    0x1229

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_15_BIN    UI_ADDR_BASE(0x22f49c)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_15_BIN    0x12a2

#define UI_BUF_ICON_ACTIVITY_BIN                   UI_ADDR_BASE(0x23073e)
#define UI_LEN_ICON_ACTIVITY_BIN                   0x1026

#define UI_BUF_ICON_ADDRESS_BOOK_BIN               UI_ADDR_BASE(0x231764)
#define UI_LEN_ICON_ADDRESS_BOOK_BIN               0xbd1

#define UI_BUF_ICON_ALARM_CLOCK_BIN                UI_ADDR_BASE(0x232335)
#define UI_LEN_ICON_ALARM_CLOCK_BIN                0xbd3

#define UI_BUF_ICON_ALIPAY_BIN                     UI_ADDR_BASE(0x232f08)
#define UI_LEN_ICON_ALIPAY_BIN                     0xba5

#define UI_BUF_ICON_ALTITUDE_BIN                   UI_ADDR_BASE(0x233aad)
#define UI_LEN_ICON_ALTITUDE_BIN                   0xd34

#define UI_BUF_ICON_BLOODSUGAR_BIN                 UI_ADDR_BASE(0x2347e1)
#define UI_LEN_ICON_BLOODSUGAR_BIN                 0xba3

#define UI_BUF_ICON_BLOOD_OXYGEN_BIN               UI_ADDR_BASE(0x235384)
#define UI_LEN_ICON_BLOOD_OXYGEN_BIN               0xcd1

#define UI_BUF_ICON_BLOOD_PRESSURE_BIN             UI_ADDR_BASE(0x236055)
#define UI_LEN_ICON_BLOOD_PRESSURE_BIN             0xbf2

#define UI_BUF_ICON_BREATHE_BIN                    UI_ADDR_BASE(0x236c47)
#define UI_LEN_ICON_BREATHE_BIN                    0x9e7

#define UI_BUF_ICON_CALCULATOR_BIN                 UI_ADDR_BASE(0x23762e)
#define UI_LEN_ICON_CALCULATOR_BIN                 0xe5d

#define UI_BUF_ICON_CALENDAR_BIN                   UI_ADDR_BASE(0x23848b)
#define UI_LEN_ICON_CALENDAR_BIN                   0xb03

#define UI_BUF_ICON_CALL_BIN                       UI_ADDR_BASE(0x238f8e)
#define UI_LEN_ICON_CALL_BIN                       0x996

#define UI_BUF_ICON_CALL_NUM_BIN                   UI_ADDR_BASE(0x239924)
#define UI_LEN_ICON_CALL_NUM_BIN                   0x91f

#define UI_BUF_ICON_CAMERA_BIN                     UI_ADDR_BASE(0x23a243)
#define UI_LEN_ICON_CAMERA_BIN                     0xd46

#define UI_BUF_ICON_CLOCK_BIN                      UI_ADDR_BASE(0x23af89)
#define UI_LEN_ICON_CLOCK_BIN                      0xac2

#define UI_BUF_ICON_CLOCK_BG_BIN                   UI_ADDR_BASE(0x23ba4b)
#define UI_LEN_ICON_CLOCK_BG_BIN                   0x792

#define UI_BUF_ICON_CLOCK_H_BIN                    UI_ADDR_BASE(0x23c1dd)
#define UI_LEN_ICON_CLOCK_H_BIN                    0xa0

#define UI_BUF_ICON_CLOCK_M_BIN                    UI_ADDR_BASE(0x23c27d)
#define UI_LEN_ICON_CLOCK_M_BIN                    0xc9

#define UI_BUF_ICON_CLOCK_S_BIN                    UI_ADDR_BASE(0x23c346)
#define UI_LEN_ICON_CLOCK_S_BIN                    0x103

#define UI_BUF_ICON_COMPASS_BIN                    UI_ADDR_BASE(0x23c449)
#define UI_LEN_ICON_COMPASS_BIN                    0xe3e

#define UI_BUF_ICON_CONNECT_PHONE_BIN              UI_ADDR_BASE(0x23d287)
#define UI_LEN_ICON_CONNECT_PHONE_BIN              0xb56

#define UI_BUF_ICON_FINDPHONE_BIN                  UI_ADDR_BASE(0x23dddd)
#define UI_LEN_ICON_FINDPHONE_BIN                  0xcd7

#define UI_BUF_ICON_FLASHLIGHT_BIN                 UI_ADDR_BASE(0x23eab4)
#define UI_LEN_ICON_FLASHLIGHT_BIN                 0xc04

#define UI_BUF_ICON_GAME_BIN                       UI_ADDR_BASE(0x23f6b8)
#define UI_LEN_ICON_GAME_BIN                       0xd73

#define UI_BUF_ICON_HEART_RATE_BIN                 UI_ADDR_BASE(0x24042b)
#define UI_LEN_ICON_HEART_RATE_BIN                 0xb81

#define UI_BUF_ICON_LANGUAGE_BIN                   UI_ADDR_BASE(0x240fac)
#define UI_LEN_ICON_LANGUAGE_BIN                   0x1048

#define UI_BUF_ICON_LIGHT_BIN                      UI_ADDR_BASE(0x241ff4)
#define UI_LEN_ICON_LIGHT_BIN                      0xd8a

#define UI_BUF_ICON_MAP_BIN                        UI_ADDR_BASE(0x242d7e)
#define UI_LEN_ICON_MAP_BIN                        0xd5c

#define UI_BUF_ICON_MENU_BIN                       UI_ADDR_BASE(0x243ada)
#define UI_LEN_ICON_MENU_BIN                       0xa62

#define UI_BUF_ICON_MESSAGE_BIN                    UI_ADDR_BASE(0x24453c)
#define UI_LEN_ICON_MESSAGE_BIN                    0x9cb

#define UI_BUF_ICON_MUSIC_BIN                      UI_ADDR_BASE(0x244f07)
#define UI_LEN_ICON_MUSIC_BIN                      0xb1a

#define UI_BUF_ICON_OFF_BIN                        UI_ADDR_BASE(0x245a21)
#define UI_LEN_ICON_OFF_BIN                        0xd03

#define UI_BUF_ICON_PRESSURE_BIN                   UI_ADDR_BASE(0x246724)
#define UI_LEN_ICON_PRESSURE_BIN                   0x7ee

#define UI_BUF_ICON_RESTART_BIN                    UI_ADDR_BASE(0x246f12)
#define UI_LEN_ICON_RESTART_BIN                    0xc3e

#define UI_BUF_ICON_RESTORE_FACTORY_BIN            UI_ADDR_BASE(0x247b50)
#define UI_LEN_ICON_RESTORE_FACTORY_BIN            0xb71

#define UI_BUF_ICON_SCAN_BIN                       UI_ADDR_BASE(0x2486c1)
#define UI_LEN_ICON_SCAN_BIN                       0xa5b

#define UI_BUF_ICON_SETTING_BIN                    UI_ADDR_BASE(0x24911c)
#define UI_LEN_ICON_SETTING_BIN                    0xb12

#define UI_BUF_ICON_SLEEP_BIN                      UI_ADDR_BASE(0x249c2e)
#define UI_LEN_ICON_SLEEP_BIN                      0xa54

#define UI_BUF_ICON_SPORT_BIN                      UI_ADDR_BASE(0x24a682)
#define UI_LEN_ICON_SPORT_BIN                      0xb55

#define UI_BUF_ICON_STEP_BIN                       UI_ADDR_BASE(0x24b1d7)
#define UI_LEN_ICON_STEP_BIN                       0xb33

#define UI_BUF_ICON_STOPWATCH_BIN                  UI_ADDR_BASE(0x24bd0a)
#define UI_LEN_ICON_STOPWATCH_BIN                  0xaac

#define UI_BUF_ICON_TIMER_BIN                      UI_ADDR_BASE(0x24c7b6)
#define UI_LEN_ICON_TIMER_BIN                      0xdcc

#define UI_BUF_ICON_VOICE_BIN                      UI_ADDR_BASE(0x24d582)
#define UI_LEN_ICON_VOICE_BIN                      0xdcf

#define UI_BUF_ICON_VOLUME_BIN                     UI_ADDR_BASE(0x24e351)
#define UI_LEN_ICON_VOLUME_BIN                     0xb95

#define UI_BUF_ICON_WEATHER_BIN                    UI_ADDR_BASE(0x24eee6)
#define UI_LEN_ICON_WEATHER_BIN                    0xb9a

#define UI_BUF_ICON_FOOTBALL_ALARM_CLOCK_BIN       UI_ADDR_BASE(0x24fa80)
#define UI_LEN_ICON_FOOTBALL_ALARM_CLOCK_BIN       0x1576

#define UI_BUF_ICON_FOOTBALL_ALIPAY_BIN            UI_ADDR_BASE(0x250ff6)
#define UI_LEN_ICON_FOOTBALL_ALIPAY_BIN            0x16ed

#define UI_BUF_ICON_FOOTBALL_BG_BIN                UI_ADDR_BASE(0x2526e3)
#define UI_LEN_ICON_FOOTBALL_BG_BIN                0xfd1b

#define UI_BUF_ICON_FOOTBALL_BLOOD_OXYGEN_BIN      UI_ADDR_BASE(0x2623fe)
#define UI_LEN_ICON_FOOTBALL_BLOOD_OXYGEN_BIN      0x1553

#define UI_BUF_ICON_FOOTBALL_CALCULATOR_BIN        UI_ADDR_BASE(0x263951)
#define UI_LEN_ICON_FOOTBALL_CALCULATOR_BIN        0x14d7

#define UI_BUF_ICON_FOOTBALL_CALENDAR_BIN          UI_ADDR_BASE(0x264e28)
#define UI_LEN_ICON_FOOTBALL_CALENDAR_BIN          0x1529

#define UI_BUF_ICON_FOOTBALL_CALL_BIN              UI_ADDR_BASE(0x266351)
#define UI_LEN_ICON_FOOTBALL_CALL_BIN              0x1501

#define UI_BUF_ICON_FOOTBALL_COMPASS_BIN           UI_ADDR_BASE(0x267852)
#define UI_LEN_ICON_FOOTBALL_COMPASS_BIN           0x17bc

#define UI_BUF_ICON_FOOTBALL_FLASHLIGHT_BIN        UI_ADDR_BASE(0x26900e)
#define UI_LEN_ICON_FOOTBALL_FLASHLIGHT_BIN        0x12fd

#define UI_BUF_ICON_FOOTBALL_GAME_BIN              UI_ADDR_BASE(0x26a30b)
#define UI_LEN_ICON_FOOTBALL_GAME_BIN              0x14af

#define UI_BUF_ICON_FOOTBALL_HEART_RATE_BIN        UI_ADDR_BASE(0x26b7ba)
#define UI_LEN_ICON_FOOTBALL_HEART_RATE_BIN        0x15fd

#define UI_BUF_ICON_FOOTBALL_LANGUAGE_BIN          UI_ADDR_BASE(0x26cdb7)
#define UI_LEN_ICON_FOOTBALL_LANGUAGE_BIN          0x1d3a

#define UI_BUF_ICON_FOOTBALL_MAP_BIN               UI_ADDR_BASE(0x26eaf1)
#define UI_LEN_ICON_FOOTBALL_MAP_BIN               0x169a

#define UI_BUF_ICON_FOOTBALL_MUSIC_BIN             UI_ADDR_BASE(0x27018b)
#define UI_LEN_ICON_FOOTBALL_MUSIC_BIN             0x1526

#define UI_BUF_ICON_FOOTBALL_SETTING_BIN           UI_ADDR_BASE(0x2716b1)
#define UI_LEN_ICON_FOOTBALL_SETTING_BIN           0x1689

#define UI_BUF_ICON_FOOTBALL_SLEEP_BIN             UI_ADDR_BASE(0x272d3a)
#define UI_LEN_ICON_FOOTBALL_SLEEP_BIN             0x1426

#define UI_BUF_ICON_FOOTBALL_SPORT_BIN             UI_ADDR_BASE(0x274160)
#define UI_LEN_ICON_FOOTBALL_SPORT_BIN             0x1370

#define UI_BUF_ICON_FOOTBALL_STOPWATCH_BIN         UI_ADDR_BASE(0x2754d0)
#define UI_LEN_ICON_FOOTBALL_STOPWATCH_BIN         0x1537

#define UI_BUF_ICON_FOOTBALL_STYLE_BIN             UI_ADDR_BASE(0x276a07)
#define UI_LEN_ICON_FOOTBALL_STYLE_BIN             0x113a

#define UI_BUF_ICON_FOOTBALL_TIMER_BIN             UI_ADDR_BASE(0x277b41)
#define UI_LEN_ICON_FOOTBALL_TIMER_BIN             0x1310

#define UI_BUF_ICON_FOOTBALL_VOLUME_BIN            UI_ADDR_BASE(0x278e51)
#define UI_LEN_ICON_FOOTBALL_VOLUME_BIN            0x1521

#define UI_BUF_ICON_FOOTBALL_WEATHER_BIN           UI_ADDR_BASE(0x27a372)
#define UI_LEN_ICON_FOOTBALL_WEATHER_BIN           0x150e

#define UI_BUF_LONG_PRESS_OFF_BIN                  UI_ADDR_BASE(0x27b880)
#define UI_LEN_LONG_PRESS_OFF_BIN                  0x988

#define UI_BUF_LONG_PRESS_RESTART_BIN              UI_ADDR_BASE(0x27c208)
#define UI_LEN_LONG_PRESS_RESTART_BIN              0x8c3

#define UI_BUF_LONG_PRESS_SOS_BIN                  UI_ADDR_BASE(0x27cacb)
#define UI_LEN_LONG_PRESS_SOS_BIN                  0xb17

#define UI_BUF_MENU_GEAR_BIN                       UI_ADDR_BASE(0x27d5e2)
#define UI_LEN_MENU_GEAR_BIN                       0x6b3d

#define UI_BUF_MENUSTYLE_CUM_GRID_BIN              UI_ADDR_BASE(0x28411f)
#define UI_LEN_MENUSTYLE_CUM_GRID_BIN              0x389a

#define UI_BUF_MENUSTYLE_CUM_SUDOKU_BIN            UI_ADDR_BASE(0x2879b9)
#define UI_LEN_MENUSTYLE_CUM_SUDOKU_BIN            0x2ff0

#define UI_BUF_MENUSTYLE_DISK_BIN                  UI_ADDR_BASE(0x28a9a9)
#define UI_LEN_MENUSTYLE_DISK_BIN                  0x2a2c

#define UI_BUF_MENUSTYLE_FOOTBALL_BIN              UI_ADDR_BASE(0x28d3d5)
#define UI_LEN_MENUSTYLE_FOOTBALL_BIN              0x2f0f

#define UI_BUF_MENUSTYLE_GRID_BIN                  UI_ADDR_BASE(0x2902e4)
#define UI_LEN_MENUSTYLE_GRID_BIN                  0x3bd1

#define UI_BUF_MENUSTYLE_HEXAGON_BIN               UI_ADDR_BASE(0x293eb5)
#define UI_LEN_MENUSTYLE_HEXAGON_BIN               0x3314

#define UI_BUF_MENUSTYLE_HONEYCOMB_BIN             UI_ADDR_BASE(0x2971c9)
#define UI_LEN_MENUSTYLE_HONEYCOMB_BIN             0x3bfe

#define UI_BUF_MENUSTYLE_KALEIDOSCOPE_BIN          UI_ADDR_BASE(0x29adc7)
#define UI_LEN_MENUSTYLE_KALEIDOSCOPE_BIN          0x32ca

#define UI_BUF_MENUSTYLE_LIST_BIN                  UI_ADDR_BASE(0x29e091)
#define UI_LEN_MENUSTYLE_LIST_BIN                  0x2278

#define UI_BUF_MENUSTYLE_LIST_FOURGRID_BIN         UI_ADDR_BASE(0x2a0309)
#define UI_LEN_MENUSTYLE_LIST_FOURGRID_BIN         0x2dac

#define UI_BUF_MENUSTYLE_RING_BIN                  UI_ADDR_BASE(0x2a30b5)
#define UI_LEN_MENUSTYLE_RING_BIN                  0x38d7

#define UI_BUF_MENUSTYLE_SKYRER_BIN                UI_ADDR_BASE(0x2a698c)
#define UI_LEN_MENUSTYLE_SKYRER_BIN                0x3648

#define UI_BUF_MENUSTYLE_SUDOKU_BIN                UI_ADDR_BASE(0x2a9fd4)
#define UI_LEN_MENUSTYLE_SUDOKU_BIN                0x2edd

#define UI_BUF_MENUSTYLE_WATERFALL_BIN             UI_ADDR_BASE(0x2aceb1)
#define UI_LEN_MENUSTYLE_WATERFALL_BIN             0x3a25

#define UI_BUF_MSG_ICON_FACEBOOK_BIN               UI_ADDR_BASE(0x2b08d6)
#define UI_LEN_MSG_ICON_FACEBOOK_BIN               0x14d9

#define UI_BUF_MSG_ICON_FLICKR_BIN                 UI_ADDR_BASE(0x2b1daf)
#define UI_LEN_MSG_ICON_FLICKR_BIN                 0x906

#define UI_BUF_MSG_ICON_GMAIL_BIN                  UI_ADDR_BASE(0x2b26b5)
#define UI_LEN_MSG_ICON_GMAIL_BIN                  0xbe9

#define UI_BUF_MSG_ICON_GOOGLEPLUS_BIN             UI_ADDR_BASE(0x2b329e)
#define UI_LEN_MSG_ICON_GOOGLEPLUS_BIN             0xc91

#define UI_BUF_MSG_ICON_HANGOUTS_BIN               UI_ADDR_BASE(0x2b3f2f)
#define UI_LEN_MSG_ICON_HANGOUTS_BIN               0x1611

#define UI_BUF_MSG_ICON_INS_BIN                    UI_ADDR_BASE(0x2b5540)
#define UI_LEN_MSG_ICON_INS_BIN                    0x1491

#define UI_BUF_MSG_ICON_KAKAO_BIN                  UI_ADDR_BASE(0x2b69d1)
#define UI_LEN_MSG_ICON_KAKAO_BIN                  0xfa1

#define UI_BUF_MSG_ICON_LINE_BIN                   UI_ADDR_BASE(0x2b7972)
#define UI_LEN_MSG_ICON_LINE_BIN                   0xca3

#define UI_BUF_MSG_ICON_LINK_BIN                   UI_ADDR_BASE(0x2b8615)
#define UI_LEN_MSG_ICON_LINK_BIN                   0xbf9

#define UI_BUF_MSG_ICON_MESSAGE_BIN                UI_ADDR_BASE(0x2b920e)
#define UI_LEN_MSG_ICON_MESSAGE_BIN                0x12b4

#define UI_BUF_MSG_ICON_MESSENGER_BIN              UI_ADDR_BASE(0x2ba4c2)
#define UI_LEN_MSG_ICON_MESSENGER_BIN              0xddb

#define UI_BUF_MSG_ICON_OTHER_BIN                  UI_ADDR_BASE(0x2bb29d)
#define UI_LEN_MSG_ICON_OTHER_BIN                  0xc89

#define UI_BUF_MSG_ICON_PAYTM_BIN                  UI_ADDR_BASE(0x2bbf26)
#define UI_LEN_MSG_ICON_PAYTM_BIN                  0xb33

#define UI_BUF_MSG_ICON_PINTEREST_BIN              UI_ADDR_BASE(0x2bca59)
#define UI_LEN_MSG_ICON_PINTEREST_BIN              0xd25

#define UI_BUF_MSG_ICON_QQ_BIN                     UI_ADDR_BASE(0x2bd77e)
#define UI_LEN_MSG_ICON_QQ_BIN                     0xc10

#define UI_BUF_MSG_ICON_SKYPE_BIN                  UI_ADDR_BASE(0x2be38e)
#define UI_LEN_MSG_ICON_SKYPE_BIN                  0xc8c

#define UI_BUF_MSG_ICON_SNAPCHAT_BIN               UI_ADDR_BASE(0x2bf01a)
#define UI_LEN_MSG_ICON_SNAPCHAT_BIN               0xc8e

#define UI_BUF_MSG_ICON_TELEGRAM_BIN               UI_ADDR_BASE(0x2bfca8)
#define UI_LEN_MSG_ICON_TELEGRAM_BIN               0xb00

#define UI_BUF_MSG_ICON_TRUECALLER_BIN             UI_ADDR_BASE(0x2c07a8)
#define UI_LEN_MSG_ICON_TRUECALLER_BIN             0xee8

#define UI_BUF_MSG_ICON_TUMBLR_BIN                 UI_ADDR_BASE(0x2c1690)
#define UI_LEN_MSG_ICON_TUMBLR_BIN                 0xaa6

#define UI_BUF_MSG_ICON_VIBER_BIN                  UI_ADDR_BASE(0x2c2136)
#define UI_LEN_MSG_ICON_VIBER_BIN                  0x1026

#define UI_BUF_MSG_ICON_VKONTAKTE_BIN              UI_ADDR_BASE(0x2c315c)
#define UI_LEN_MSG_ICON_VKONTAKTE_BIN              0xbbf

#define UI_BUF_MSG_ICON_WECHAT_BIN                 UI_ADDR_BASE(0x2c3d1b)
#define UI_LEN_MSG_ICON_WECHAT_BIN                 0x171c

#define UI_BUF_MSG_ICON_WHATSAPP_BIN               UI_ADDR_BASE(0x2c5437)
#define UI_LEN_MSG_ICON_WHATSAPP_BIN               0x189a

#define UI_BUF_MSG_ICON_X_BIN                      UI_ADDR_BASE(0x2c6cd1)
#define UI_LEN_MSG_ICON_X_BIN                      0xc03

#define UI_BUF_MSG_ICON_YOUTUBE_BIN                UI_ADDR_BASE(0x2c78d4)
#define UI_LEN_MSG_ICON_YOUTUBE_BIN                0x885

#define UI_BUF_MSG_ICON_ZALO_BIN                   UI_ADDR_BASE(0x2c8159)
#define UI_LEN_MSG_ICON_ZALO_BIN                   0xd48

#define UI_BUF_MUSIC_NEXT_BIN                      UI_ADDR_BASE(0x2c8ea1)
#define UI_LEN_MUSIC_NEXT_BIN                      0x4ce

#define UI_BUF_MUSIC_NEXT_CLICK_BIN                UI_ADDR_BASE(0x2c936f)
#define UI_LEN_MUSIC_NEXT_CLICK_BIN                0x84a

#define UI_BUF_MUSIC_PAUSE_BIN                     UI_ADDR_BASE(0x2c9bb9)
#define UI_LEN_MUSIC_PAUSE_BIN                     0xd96

#define UI_BUF_MUSIC_PAUSE_CLICK_BIN               UI_ADDR_BASE(0x2ca94f)
#define UI_LEN_MUSIC_PAUSE_CLICK_BIN               0xd75

#define UI_BUF_MUSIC_PLAY_BIN                      UI_ADDR_BASE(0x2cb6c4)
#define UI_LEN_MUSIC_PLAY_BIN                      0xb7e

#define UI_BUF_MUSIC_PREV_BIN                      UI_ADDR_BASE(0x2cc242)
#define UI_LEN_MUSIC_PREV_BIN                      0x4da

#define UI_BUF_MUSIC_PREV_CLICK_BIN                UI_ADDR_BASE(0x2cc71c)
#define UI_LEN_MUSIC_PREV_CLICK_BIN                0x889

#define UI_BUF_MUSIC_VOLUME1_BIN                   UI_ADDR_BASE(0x2ccfa5)
#define UI_LEN_MUSIC_VOLUME1_BIN                   0x55

#define UI_BUF_MUSIC_VOLUME2_BIN                   UI_ADDR_BASE(0x2ccffa)
#define UI_LEN_MUSIC_VOLUME2_BIN                   0x45

#define UI_BUF_MUSIC_VOLUME3_BIN                   UI_ADDR_BASE(0x2cd03f)
#define UI_LEN_MUSIC_VOLUME3_BIN                   0x35

#define UI_BUF_MUSIC_VOLUME4_BIN                   UI_ADDR_BASE(0x2cd074)
#define UI_LEN_MUSIC_VOLUME4_BIN                   0x35

#define UI_BUF_MUSIC_VOLUME5_BIN                   UI_ADDR_BASE(0x2cd0a9)
#define UI_LEN_MUSIC_VOLUME5_BIN                   0x45

#define UI_BUF_MUSIC_VOLUME_BG_BIN                 UI_ADDR_BASE(0x2cd0ee)
#define UI_LEN_MUSIC_VOLUME_BG_BIN                 0x3f

#define UI_BUF_MUSIC_VOLUME_DOWN_BIN               UI_ADDR_BASE(0x2cd12d)
#define UI_LEN_MUSIC_VOLUME_DOWN_BIN               0x3d8

#define UI_BUF_MUSIC_VOLUME_DOWN_CLICK_BIN         UI_ADDR_BASE(0x2cd505)
#define UI_LEN_MUSIC_VOLUME_DOWN_CLICK_BIN         0x725

#define UI_BUF_MUSIC_VOLUME_UP_BIN                 UI_ADDR_BASE(0x2cdc2a)
#define UI_LEN_MUSIC_VOLUME_UP_BIN                 0x4c4

#define UI_BUF_MUSIC_VOLUME_UP_CLICK_BIN           UI_ADDR_BASE(0x2ce0ee)
#define UI_LEN_MUSIC_VOLUME_UP_CLICK_BIN           0x7b1

#define UI_BUF_PRESSURE_CHART_BIN                  UI_ADDR_BASE(0x2ce89f)
#define UI_LEN_PRESSURE_CHART_BIN                  0x2308

#define UI_BUF_PRESSURE_EXPLAIN_BIN                UI_ADDR_BASE(0x2d0ba7)
#define UI_LEN_PRESSURE_EXPLAIN_BIN                0x22b

#define UI_BUF_PULLUP_DIALPLATE_BG_BIN             UI_ADDR_BASE(0x2d0dd2)
#define UI_LEN_PULLUP_DIALPLATE_BG_BIN             0x1177

#define UI_BUF_PULLUP_HOUR_BIN                     UI_ADDR_BASE(0x2d1f49)
#define UI_LEN_PULLUP_HOUR_BIN                     0xc6

#define UI_BUF_PULLUP_MIN_BIN                      UI_ADDR_BASE(0x2d200f)
#define UI_LEN_PULLUP_MIN_BIN                      0x107

#define UI_BUF_REMIND_ALARM_CLOCK_BIN              UI_ADDR_BASE(0x2d2116)
#define UI_LEN_REMIND_ALARM_CLOCK_BIN              0xca4

#define UI_BUF_REMIND_APP_CONNECTION_BIN           UI_ADDR_BASE(0x2d2dba)
#define UI_LEN_REMIND_APP_CONNECTION_BIN           0x1583

#define UI_BUF_REMIND_BLUETOOTH_CONNECTION_BIN     UI_ADDR_BASE(0x2d433d)
#define UI_LEN_REMIND_BLUETOOTH_CONNECTION_BIN     0x1755

#define UI_BUF_REMIND_CLOSE_BIN                    UI_ADDR_BASE(0x2d5a92)
#define UI_LEN_REMIND_CLOSE_BIN                    0x757

#define UI_BUF_REMIND_FINDWATCH_BIN                UI_ADDR_BASE(0x2d61e9)
#define UI_LEN_REMIND_FINDWATCH_BIN                0x10c5

#define UI_BUF_REMIND_FIND_WATCH_BIN               UI_ADDR_BASE(0x2d72ae)
#define UI_LEN_REMIND_FIND_WATCH_BIN               0x1bc6

#define UI_BUF_REMIND_GOAL_ACHIEVEMENT_BIN         UI_ADDR_BASE(0x2d8e74)
#define UI_LEN_REMIND_GOAL_ACHIEVEMENT_BIN         0x14ca

#define UI_BUF_REMIND_REMIND_LATER_BIN             UI_ADDR_BASE(0x2da33e)
#define UI_LEN_REMIND_REMIND_LATER_BIN             0xe0d

#define UI_BUF_REMIND_SEDENTARY_CLOCK_BIN          UI_ADDR_BASE(0x2db14b)
#define UI_LEN_REMIND_SEDENTARY_CLOCK_BIN          0x8de

#define UI_BUF_REMIND_SLEEPING_CLOCK_BIN           UI_ADDR_BASE(0x2dba29)
#define UI_LEN_REMIND_SLEEPING_CLOCK_BIN           0xecd

#define UI_BUF_REMIND_WATER_CLOCK_BIN              UI_ADDR_BASE(0x2dc8f6)
#define UI_LEN_REMIND_WATER_CLOCK_BIN              0xacf

#define UI_BUF_SETTING_ABOUT_BIN                   UI_ADDR_BASE(0x2dd3c5)
#define UI_LEN_SETTING_ABOUT_BIN                   0x38e

#define UI_BUF_SETTING_ABOUT_CLICK_BIN             UI_ADDR_BASE(0x2dd753)
#define UI_LEN_SETTING_ABOUT_CLICK_BIN             0x392

#define UI_BUF_SETTING_BREATHING_SCREEN_BIN        UI_ADDR_BASE(0x2ddae5)
#define UI_LEN_SETTING_BREATHING_SCREEN_BIN        0x4cf

#define UI_BUF_SETTING_BREATHING_SCREEN_CLICK_BIN    UI_ADDR_BASE(0x2ddfb4)
#define UI_LEN_SETTING_BREATHING_SCREEN_CLICK_BIN    0x4a8

#define UI_BUF_SETTING_CALENDAR_BIN                UI_ADDR_BASE(0x2de45c)
#define UI_LEN_SETTING_CALENDAR_BIN                0x3a3

#define UI_BUF_SETTING_CALENDAR_CLICK_BIN          UI_ADDR_BASE(0x2de7ff)
#define UI_LEN_SETTING_CALENDAR_CLICK_BIN          0x394

#define UI_BUF_SETTING_DISTURB_BIN                 UI_ADDR_BASE(0x2deb93)
#define UI_LEN_SETTING_DISTURB_BIN                 0x3c4

#define UI_BUF_SETTING_DISTURB_CLICK_BIN           UI_ADDR_BASE(0x2def57)
#define UI_LEN_SETTING_DISTURB_CLICK_BIN           0x3ab

#define UI_BUF_SETTING_LANGUAGE_BIN                UI_ADDR_BASE(0x2df302)
#define UI_LEN_SETTING_LANGUAGE_BIN                0x441

#define UI_BUF_SETTING_LANGUAGE_CLICK_BIN          UI_ADDR_BASE(0x2df743)
#define UI_LEN_SETTING_LANGUAGE_CLICK_BIN          0x425

#define UI_BUF_SETTING_LIGHT_BIN                   UI_ADDR_BASE(0x2dfb68)
#define UI_LEN_SETTING_LIGHT_BIN                   0x43e

#define UI_BUF_SETTING_LIGHT_CLICK_BIN             UI_ADDR_BASE(0x2dffa6)
#define UI_LEN_SETTING_LIGHT_CLICK_BIN             0x437

#define UI_BUF_SETTING_OFF_BIN                     UI_ADDR_BASE(0x2e03dd)
#define UI_LEN_SETTING_OFF_BIN                     0x422

#define UI_BUF_SETTING_OFF_CLICK_BIN               UI_ADDR_BASE(0x2e07ff)
#define UI_LEN_SETTING_OFF_CLICK_BIN               0x411

#define UI_BUF_SETTING_PASSWORD_BIN                UI_ADDR_BASE(0x2e0c10)
#define UI_LEN_SETTING_PASSWORD_BIN                0x3e4

#define UI_BUF_SETTING_PASSWORD_CLICK_BIN          UI_ADDR_BASE(0x2e0ff4)
#define UI_LEN_SETTING_PASSWORD_CLICK_BIN          0x3df

#define UI_BUF_SETTING_RESTART_BIN                 UI_ADDR_BASE(0x2e13d3)
#define UI_LEN_SETTING_RESTART_BIN                 0x3ea

#define UI_BUF_SETTING_RESTART_CLICK_BIN           UI_ADDR_BASE(0x2e17bd)
#define UI_LEN_SETTING_RESTART_CLICK_BIN           0x3db

#define UI_BUF_SETTING_RESTORE_FACTORY_BIN         UI_ADDR_BASE(0x2e1b98)
#define UI_LEN_SETTING_RESTORE_FACTORY_BIN         0x3f3

#define UI_BUF_SETTING_RESTORE_FACTORY_CLICK_BIN    UI_ADDR_BASE(0x2e1f8b)
#define UI_LEN_SETTING_RESTORE_FACTORY_CLICK_BIN    0x3dc

#define UI_BUF_SETTING_SOUND_AND_VIBRATION_BIN     UI_ADDR_BASE(0x2e2367)
#define UI_LEN_SETTING_SOUND_AND_VIBRATION_BIN     0x390

#define UI_BUF_SETTING_SOUND_AND_VIBRATION_CLICK_BIN    UI_ADDR_BASE(0x2e26f7)
#define UI_LEN_SETTING_SOUND_AND_VIBRATION_CLICK_BIN    0x370

#define UI_BUF_SETTING_TIME_BIN                    UI_ADDR_BASE(0x2e2a67)
#define UI_LEN_SETTING_TIME_BIN                    0x394

#define UI_BUF_SETTING_TIME_CLICK_BIN              UI_ADDR_BASE(0x2e2dfb)
#define UI_LEN_SETTING_TIME_CLICK_BIN              0x38e

#define UI_BUF_SETTING_WRIST_BIN                   UI_ADDR_BASE(0x2e3189)
#define UI_LEN_SETTING_WRIST_BIN                   0x409

#define UI_BUF_SETTING_WRIST_CLICK_BIN             UI_ADDR_BASE(0x2e3592)
#define UI_LEN_SETTING_WRIST_CLICK_BIN             0x3e2

#define UI_BUF_SETTING_LIGHT_LIGHT_BIN             UI_ADDR_BASE(0x2e3974)
#define UI_LEN_SETTING_LIGHT_LIGHT_BIN             0x14ba

#define UI_BUF_SETTING_PASSWORD_7_CLICK_BIN        UI_ADDR_BASE(0x2e4e2e)
#define UI_LEN_SETTING_PASSWORD_7_CLICK_BIN        0x4a8

#define UI_BUF_SETTING_PASSWORD_9_CLICK_BIN        UI_ADDR_BASE(0x2e52d6)
#define UI_LEN_SETTING_PASSWORD_9_CLICK_BIN        0x5ee

#define UI_BUF_SETTING_PASSWORD_BG_BIN             UI_ADDR_BASE(0x2e58c4)
#define UI_LEN_SETTING_PASSWORD_BG_BIN             0x3ef9

#define UI_BUF_SETTING_PASSWORD_BG_NUM_BIN         UI_ADDR_BASE(0x2e97bd)
#define UI_LEN_SETTING_PASSWORD_BG_NUM_BIN         0x896

#define UI_BUF_SETTING_PASSWORD_DEL_CLICK_BIN      UI_ADDR_BASE(0x2ea053)
#define UI_LEN_SETTING_PASSWORD_DEL_CLICK_BIN      0x60d

#define UI_BUF_SETTING_PASSWORD_FRAME_755_BIN      UI_ADDR_BASE(0x2ea660)
#define UI_LEN_SETTING_PASSWORD_FRAME_755_BIN      0x5c3

#define UI_BUF_SETTING_PASSWORD_NUM_BIN            UI_ADDR_BASE(0x2eac23)
#define UI_LEN_SETTING_PASSWORD_NUM_BIN            0x210

#define UI_BUF_SETTING_PASSWORD_OPEN_BIN           UI_ADDR_BASE(0x2eae33)
#define UI_LEN_SETTING_PASSWORD_OPEN_BIN           0x222

#define UI_BUF_SIDEBAR_BG_146_146_BIN              UI_ADDR_BASE(0x2eb055)
#define UI_LEN_SIDEBAR_BG_146_146_BIN              0xa82

#define UI_BUF_SIDEBAR_BG_146_146_0_BIN            UI_ADDR_BASE(0x2ebad7)
#define UI_LEN_SIDEBAR_BG_146_146_0_BIN            0xa82

#define UI_BUF_SIDEBAR_BG_146_146_1_BIN            UI_ADDR_BASE(0x2ec559)
#define UI_LEN_SIDEBAR_BG_146_146_1_BIN            0xa82

#define UI_BUF_SIDEBAR_BG_308_156_BIN              UI_ADDR_BASE(0x2ecfdb)
#define UI_LEN_SIDEBAR_BG_308_156_BIN              0x100e

#define UI_BUF_SIDEBAR_BG_308_156_1_BIN            UI_ADDR_BASE(0x2edfe9)
#define UI_LEN_SIDEBAR_BG_308_156_1_BIN            0x100e

#define UI_BUF_SIDEBAR_BG_308_156_2_BIN            UI_ADDR_BASE(0x2eeff7)
#define UI_LEN_SIDEBAR_BG_308_156_2_BIN            0x100e

#define UI_BUF_SIDEBAR_BG_308_156_3_BIN            UI_ADDR_BASE(0x2f0005)
#define UI_LEN_SIDEBAR_BG_308_156_3_BIN            0x100e

#define UI_BUF_SIDEBAR_BG_308_156_4_BIN            UI_ADDR_BASE(0x2f1013)
#define UI_LEN_SIDEBAR_BG_308_156_4_BIN            0x100e

#define UI_BUF_SIDEBAR_DEGREE_BIN                  UI_ADDR_BASE(0x2f2021)
#define UI_LEN_SIDEBAR_DEGREE_BIN                  0x3ad

#define UI_BUF_SIDEBAR_SLAS_BIN                    UI_ADDR_BASE(0x2f23ce)
#define UI_LEN_SIDEBAR_SLAS_BIN                    0x1cc

#define UI_BUF_SIDEBAR_TOP_308_50_BIN              UI_ADDR_BASE(0x2f259a)
#define UI_LEN_SIDEBAR_TOP_308_50_BIN              0x429

#define UI_BUF_SLEEP_LIGHT_SLEEP_BIN               UI_ADDR_BASE(0x2f29c3)
#define UI_LEN_SLEEP_LIGHT_SLEEP_BIN               0x5db

#define UI_BUF_SLEEP_SLEEP_BIN                     UI_ADDR_BASE(0x2f2f9e)
#define UI_LEN_SLEEP_SLEEP_BIN                     0xff1

#define UI_BUF_SLEEP_SLEEP_BG_BIN                  UI_ADDR_BASE(0x2f3f8f)
#define UI_LEN_SLEEP_SLEEP_BG_BIN                  0x1407

#define UI_BUF_SLEEP_SLEEP_DATE_BG_BIN             UI_ADDR_BASE(0x2f5396)
#define UI_LEN_SLEEP_SLEEP_DATE_BG_BIN             0x7a7

#define UI_BUF_SLEEP_SLEEP_DOWN_BIN                UI_ADDR_BASE(0x2f5b3d)
#define UI_LEN_SLEEP_SLEEP_DOWN_BIN                0x328

#define UI_BUF_SLEEP_SLEEP_STATE1_BIN              UI_ADDR_BASE(0x2f5e65)
#define UI_LEN_SLEEP_SLEEP_STATE1_BIN              0x354

#define UI_BUF_SLEEP_SLEEP_STATE2_BIN              UI_ADDR_BASE(0x2f61b9)
#define UI_LEN_SLEEP_SLEEP_STATE2_BIN              0x354

#define UI_BUF_SLEEP_SLEEP_STATE3_BIN              UI_ADDR_BASE(0x2f650d)
#define UI_LEN_SLEEP_SLEEP_STATE3_BIN              0x354

#define UI_BUF_SLEEP_SLEEP_STATE4_BIN              UI_ADDR_BASE(0x2f6861)
#define UI_LEN_SLEEP_SLEEP_STATE4_BIN              0x354

#define UI_BUF_SLEEP_SLEEP_UP_BIN                  UI_ADDR_BASE(0x2f6bb5)
#define UI_LEN_SLEEP_SLEEP_UP_BIN                  0x509

#define UI_BUF_SMARTSTACK_BG_BIN                   UI_ADDR_BASE(0x2f70be)
#define UI_LEN_SMARTSTACK_BG_BIN                   0x1fc4

#define UI_BUF_SMARTSTACK_DELET_BIN                UI_ADDR_BASE(0x2f9082)
#define UI_LEN_SMARTSTACK_DELET_BIN                0x4bc

#define UI_BUF_SMARTSTACK_NULL_BIN                 UI_ADDR_BASE(0x2f953e)
#define UI_LEN_SMARTSTACK_NULL_BIN                 0x5a1

#define UI_BUF_SPORT_BEFORE_EXERCISE_BG_BIN        UI_ADDR_BASE(0x2f9adf)
#define UI_LEN_SPORT_BEFORE_EXERCISE_BG_BIN        0x115f

#define UI_BUF_SPORT_BEFORE_EXERCISE_FOOTBALL_BIN    UI_ADDR_BASE(0x2fac3e)
#define UI_LEN_SPORT_BEFORE_EXERCISE_FOOTBALL_BIN    0xdc5

#define UI_BUF_SPORT_BEFORE_EXERCISE_INDOOR_CYCLING_BIN    UI_ADDR_BASE(0x2fba03)
#define UI_LEN_SPORT_BEFORE_EXERCISE_INDOOR_CYCLING_BIN    0x1103

#define UI_BUF_SPORT_BEFORE_EXERCISE_INDOOR_RUNNING_BIN    UI_ADDR_BASE(0x2fcb06)
#define UI_LEN_SPORT_BEFORE_EXERCISE_INDOOR_RUNNING_BIN    0x103f

#define UI_BUF_SPORT_BEFORE_EXERCISE_KCAL_BG_BIN    UI_ADDR_BASE(0x2fdb45)
#define UI_LEN_SPORT_BEFORE_EXERCISE_KCAL_BG_BIN    0x1a98

#define UI_BUF_SPORT_BEFORE_EXERCISE_KCAL_NUM_BIN    UI_ADDR_BASE(0x2ff5dd)
#define UI_LEN_SPORT_BEFORE_EXERCISE_KCAL_NUM_BIN    0xd73

#define UI_BUF_SPORT_BEFORE_EXERCISE_KM_BG_BIN     UI_ADDR_BASE(0x300350)
#define UI_LEN_SPORT_BEFORE_EXERCISE_KM_BG_BIN     0x1a31

#define UI_BUF_SPORT_BEFORE_EXERCISE_KM_NUM_BIN    UI_ADDR_BASE(0x301d81)
#define UI_LEN_SPORT_BEFORE_EXERCISE_KM_NUM_BIN    0xd7f

#define UI_BUF_SPORT_BEFORE_EXERCISE_OUTDOOR_CYCLING_BIN    UI_ADDR_BASE(0x302b00)
#define UI_LEN_SPORT_BEFORE_EXERCISE_OUTDOOR_CYCLING_BIN    0x148d

#define UI_BUF_SPORT_BEFORE_EXERCISE_RUN_BIN       UI_ADDR_BASE(0x303f8d)
#define UI_LEN_SPORT_BEFORE_EXERCISE_RUN_BIN       0xd0c

#define UI_BUF_SPORT_BEFORE_EXERCISE_STEP_BG_BIN    UI_ADDR_BASE(0x304c99)
#define UI_LEN_SPORT_BEFORE_EXERCISE_STEP_BG_BIN    0x186d

#define UI_BUF_SPORT_BEFORE_EXERCISE_STEP_NUM_BIN    UI_ADDR_BASE(0x306506)
#define UI_LEN_SPORT_BEFORE_EXERCISE_STEP_NUM_BIN    0x1003

#define UI_BUF_SPORT_BEFORE_EXERCISE_SWIM_BIN      UI_ADDR_BASE(0x307509)
#define UI_LEN_SPORT_BEFORE_EXERCISE_SWIM_BIN      0xda1

#define UI_BUF_SPORT_BEFORE_EXERCISE_TIME_BG_BIN    UI_ADDR_BASE(0x3082aa)
#define UI_LEN_SPORT_BEFORE_EXERCISE_TIME_BG_BIN    0x19c2

#define UI_BUF_SPORT_BEFORE_EXERCISE_TIME_NUM_BIN    UI_ADDR_BASE(0x309c6c)
#define UI_LEN_SPORT_BEFORE_EXERCISE_TIME_NUM_BIN    0xd7d

#define UI_BUF_SPORT_BEFORE_EXERCISE_WALK_BIN      UI_ADDR_BASE(0x30a9e9)
#define UI_LEN_SPORT_BEFORE_EXERCISE_WALK_BIN      0xce8

#define UI_BUF_SPORT_EXERCISING_1_BIN              UI_ADDR_BASE(0x30b6d1)
#define UI_LEN_SPORT_EXERCISING_1_BIN              0x5c9

#define UI_BUF_SPORT_EXERCISING_2_BIN              UI_ADDR_BASE(0x30bc9a)
#define UI_LEN_SPORT_EXERCISING_2_BIN              0xa4a

#define UI_BUF_SPORT_EXERCISING_3_BIN              UI_ADDR_BASE(0x30c6e4)
#define UI_LEN_SPORT_EXERCISING_3_BIN              0xb57

#define UI_BUF_SPORT_EXERCISING_BG_HR_BIN          UI_ADDR_BASE(0x30d23b)
#define UI_LEN_SPORT_EXERCISING_BG_HR_BIN          0x855

#define UI_BUF_SPORT_EXERCISING_CANCEL_BIN         UI_ADDR_BASE(0x30da90)
#define UI_LEN_SPORT_EXERCISING_CANCEL_BIN         0x10a7

#define UI_BUF_SPORT_EXERCISING_DOU2_BIN           UI_ADDR_BASE(0x30eb37)
#define UI_LEN_SPORT_EXERCISING_DOU2_BIN           0x1bf

#define UI_BUF_SPORT_EXERCISING_KCAL_BIN           UI_ADDR_BASE(0x30ecf6)
#define UI_LEN_SPORT_EXERCISING_KCAL_BIN           0x7b7

#define UI_BUF_SPORT_EXERCISING_KM_BIN             UI_ADDR_BASE(0x30f4ad)
#define UI_LEN_SPORT_EXERCISING_KM_BIN             0x70c

#define UI_BUF_SPORT_EXERCISING_PAUSE_BIN          UI_ADDR_BASE(0x30fbb9)
#define UI_LEN_SPORT_EXERCISING_PAUSE_BIN          0x10e0

#define UI_BUF_SPORT_EXERCISING_STEP_BIN           UI_ADDR_BASE(0x310c99)
#define UI_LEN_SPORT_EXERCISING_STEP_BIN           0x50b

#define UI_BUF_SPORT_EXERCISING_TIME_BIN           UI_ADDR_BASE(0x3111a4)
#define UI_LEN_SPORT_EXERCISING_TIME_BIN           0x655

#define UI_BUF_SPORT_ICON_BADMINTON_BIN            UI_ADDR_BASE(0x3117f9)
#define UI_LEN_SPORT_ICON_BADMINTON_BIN            0xb04

#define UI_BUF_SPORT_ICON_BASEBALL_BIN             UI_ADDR_BASE(0x3122fd)
#define UI_LEN_SPORT_ICON_BASEBALL_BIN             0xa62

#define UI_BUF_SPORT_ICON_BASKETBALL_BIN           UI_ADDR_BASE(0x312d5f)
#define UI_LEN_SPORT_ICON_BASKETBALL_BIN           0xb9d

#define UI_BUF_SPORT_ICON_BOATING_BIN              UI_ADDR_BASE(0x3138fc)
#define UI_LEN_SPORT_ICON_BOATING_BIN              0xfb0

#define UI_BUF_SPORT_ICON_CLIMBING_BIN             UI_ADDR_BASE(0x3148ac)
#define UI_LEN_SPORT_ICON_CLIMBING_BIN             0xba8

#define UI_BUF_SPORT_ICON_CRICKET_BIN              UI_ADDR_BASE(0x315454)
#define UI_LEN_SPORT_ICON_CRICKET_BIN              0x962

#define UI_BUF_SPORT_ICON_DANCE_BIN                UI_ADDR_BASE(0x315db6)
#define UI_LEN_SPORT_ICON_DANCE_BIN                0x916

#define UI_BUF_SPORT_ICON_FOOTBALL_BIN             UI_ADDR_BASE(0x3166cc)
#define UI_LEN_SPORT_ICON_FOOTBALL_BIN             0xb24

#define UI_BUF_SPORT_ICON_FREE_TRAINING_BIN        UI_ADDR_BASE(0x3171f0)
#define UI_LEN_SPORT_ICON_FREE_TRAINING_BIN        0x92a

#define UI_BUF_SPORT_ICON_GYMNASTICS_BIN           UI_ADDR_BASE(0x317b1a)
#define UI_LEN_SPORT_ICON_GYMNASTICS_BIN           0x888

#define UI_BUF_SPORT_ICON_HOCKEY_BIN               UI_ADDR_BASE(0x3183a2)
#define UI_LEN_SPORT_ICON_HOCKEY_BIN               0xa88

#define UI_BUF_SPORT_ICON_JUMPING_JACK_BIN         UI_ADDR_BASE(0x318e2a)
#define UI_LEN_SPORT_ICON_JUMPING_JACK_BIN         0xa20

#define UI_BUF_SPORT_ICON_JUMP_ROPE_BIN            UI_ADDR_BASE(0x31984a)
#define UI_LEN_SPORT_ICON_JUMP_ROPE_BIN            0xc00

#define UI_BUF_SPORT_ICON_RIDE_BIKE_BIN            UI_ADDR_BASE(0x31a44a)
#define UI_LEN_SPORT_ICON_RIDE_BIKE_BIN            0xece

#define UI_BUF_SPORT_ICON_RUGBY_BIN                UI_ADDR_BASE(0x31b318)
#define UI_LEN_SPORT_ICON_RUGBY_BIN                0xa71

#define UI_BUF_SPORT_ICON_RUN_BIN                  UI_ADDR_BASE(0x31bd89)
#define UI_LEN_SPORT_ICON_RUN_BIN                  0x9a0

#define UI_BUF_SPORT_ICON_SIT_UP_BIN               UI_ADDR_BASE(0x31c729)
#define UI_LEN_SPORT_ICON_SIT_UP_BIN               0x78e

#define UI_BUF_SPORT_ICON_SPINNING_BIN             UI_ADDR_BASE(0x31ceb7)
#define UI_LEN_SPORT_ICON_SPINNING_BIN             0xe3e

#define UI_BUF_SPORT_ICON_SWIMMING_BIN             UI_ADDR_BASE(0x31dcf5)
#define UI_LEN_SPORT_ICON_SWIMMING_BIN             0xbb4

#define UI_BUF_SPORT_ICON_TABLE_TENNIS_BIN         UI_ADDR_BASE(0x31e8a9)
#define UI_LEN_SPORT_ICON_TABLE_TENNIS_BIN         0xb2e

#define UI_BUF_SPORT_ICON_TENNIS_BIN               UI_ADDR_BASE(0x31f3d7)
#define UI_LEN_SPORT_ICON_TENNIS_BIN               0xbe8

#define UI_BUF_SPORT_ICON_TREADMILL_BIN            UI_ADDR_BASE(0x31ffbf)
#define UI_LEN_SPORT_ICON_TREADMILL_BIN            0xb8e

#define UI_BUF_SPORT_ICON_VOLLEYBALL_BIN           UI_ADDR_BASE(0x320b4d)
#define UI_LEN_SPORT_ICON_VOLLEYBALL_BIN           0xa81

#define UI_BUF_SPORT_ICON_WALKING_BIN              UI_ADDR_BASE(0x3215ce)
#define UI_LEN_SPORT_ICON_WALKING_BIN              0xa9c

#define UI_BUF_SPORT_ICON_YOGA_BIN                 UI_ADDR_BASE(0x32206a)
#define UI_LEN_SPORT_ICON_YOGA_BIN                 0x968

#define UI_BUF_STOPWATCH_AFRESH_BIN                UI_ADDR_BASE(0x3229d2)
#define UI_LEN_STOPWATCH_AFRESH_BIN                0x833

#define UI_BUF_STOPWATCH_AFRESH_CLICK_BIN          UI_ADDR_BASE(0x323205)
#define UI_LEN_STOPWATCH_AFRESH_CLICK_BIN          0x81e

#define UI_BUF_STOPWATCH_NUM1_12_18_BIN            UI_ADDR_BASE(0x323a23)
#define UI_LEN_STOPWATCH_NUM1_12_18_BIN            0x17ee

#define UI_BUF_STOPWATCH_NUM1_12_18_CLICK_BIN      UI_ADDR_BASE(0x325211)
#define UI_LEN_STOPWATCH_NUM1_12_18_CLICK_BIN      0x17ef

#define UI_BUF_STOPWATCH_NUM1_16_24_BIN            UI_ADDR_BASE(0x326a00)
#define UI_LEN_STOPWATCH_NUM1_16_24_BIN            0x1a28

#define UI_BUF_STOPWATCH_NUM1_16_24_CLICK_BIN      UI_ADDR_BASE(0x328428)
#define UI_LEN_STOPWATCH_NUM1_16_24_CLICK_BIN      0x1a29

#define UI_BUF_STOPWATCH_RECORD_BIN                UI_ADDR_BASE(0x329e51)
#define UI_LEN_STOPWATCH_RECORD_BIN                0x83b

#define UI_BUF_STOPWATCH_RECORD1_BIN               UI_ADDR_BASE(0x32a68c)
#define UI_LEN_STOPWATCH_RECORD1_BIN               0x57b

#define UI_BUF_STOPWATCH_RECORD1_CLICK_BIN         UI_ADDR_BASE(0x32ac07)
#define UI_LEN_STOPWATCH_RECORD1_CLICK_BIN         0x56b

#define UI_BUF_STOPWATCH_RECORD_CLICK_BIN          UI_ADDR_BASE(0x32b172)
#define UI_LEN_STOPWATCH_RECORD_CLICK_BIN          0x81b

#define UI_BUF_STYLE_01_BIN                        UI_ADDR_BASE(0x32b98d)
#define UI_LEN_STYLE_01_BIN                        0x492

#define UI_BUF_STYLE_02_BIN                        UI_ADDR_BASE(0x32be1f)
#define UI_LEN_STYLE_02_BIN                        0x4c6

#define UI_BUF_STYLE_03_BIN                        UI_ADDR_BASE(0x32c2e5)
#define UI_LEN_STYLE_03_BIN                        0x677

#define UI_BUF_STYLE_04_BIN                        UI_ADDR_BASE(0x32c95c)
#define UI_LEN_STYLE_04_BIN                        0x595

#define UI_BUF_STYLE_05_BIN                        UI_ADDR_BASE(0x32cef1)
#define UI_LEN_STYLE_05_BIN                        0x4e6

#define UI_BUF_STYLE_06_BIN                        UI_ADDR_BASE(0x32d3d7)
#define UI_LEN_STYLE_06_BIN                        0x59b

#define UI_BUF_STYLE_07_BIN                        UI_ADDR_BASE(0x32d972)
#define UI_LEN_STYLE_07_BIN                        0x637

#define UI_BUF_STYLE_08_BIN                        UI_ADDR_BASE(0x32dfa9)
#define UI_LEN_STYLE_08_BIN                        0x34d

#define UI_BUF_STYLE_09_BIN                        UI_ADDR_BASE(0x32e2f6)
#define UI_LEN_STYLE_09_BIN                        0x5e0

#define UI_BUF_STYLE_10_BIN                        UI_ADDR_BASE(0x32e8d6)
#define UI_LEN_STYLE_10_BIN                        0x5b2

#define UI_BUF_STYLE_11_BIN                        UI_ADDR_BASE(0x32ee88)
#define UI_LEN_STYLE_11_BIN                        0x4c1

#define UI_BUF_STYLE_12_BIN                        UI_ADDR_BASE(0x32f349)
#define UI_LEN_STYLE_12_BIN                        0x68d

#define UI_BUF_STYLE_13_BIN                        UI_ADDR_BASE(0x32f9d6)
#define UI_LEN_STYLE_13_BIN                        0x442

#define UI_BUF_STYLE_14_BIN                        UI_ADDR_BASE(0x32fe18)
#define UI_LEN_STYLE_14_BIN                        0x499

#define UI_BUF_TETRIS__S_BJ_START_BIN              UI_ADDR_BASE(0x3302b1)
#define UI_LEN_TETRIS__S_BJ_START_BIN              0x93bd

#define UI_BUF_TETRIS__S_FRAME_BIN                 UI_ADDR_BASE(0x33966e)
#define UI_LEN_TETRIS__S_FRAME_BIN                 0xa4ed

#define UI_BUF_TETRIS__S_NO_BIN                    UI_ADDR_BASE(0x343b5b)
#define UI_LEN_TETRIS__S_NO_BIN                    0x6e5

#define UI_BUF_TETRIS__S_REMIND_BIN                UI_ADDR_BASE(0x344240)
#define UI_LEN_TETRIS__S_REMIND_BIN                0x9c5

#define UI_BUF_TETRIS__S_START_BIN                 UI_ADDR_BASE(0x344c05)
#define UI_LEN_TETRIS__S_START_BIN                 0x92d

#define UI_BUF_TETRIS__S_SUSPEND_BIN               UI_ADDR_BASE(0x345532)
#define UI_LEN_TETRIS__S_SUSPEND_BIN               0xa35

#define UI_BUF_TETRIS__S_YES_BIN                   UI_ADDR_BASE(0x345f67)
#define UI_LEN_TETRIS__S_YES_BIN                   0x6cb

#define UI_BUF_TETRIS_16_1_BIN                     UI_ADDR_BASE(0x346632)
#define UI_LEN_TETRIS_16_1_BIN                     0x1fe

#define UI_BUF_TETRIS_16_2_BIN                     UI_ADDR_BASE(0x346830)
#define UI_LEN_TETRIS_16_2_BIN                     0x1d1

#define UI_BUF_TETRIS_16_3_BIN                     UI_ADDR_BASE(0x346a01)
#define UI_LEN_TETRIS_16_3_BIN                     0x1dc

#define UI_BUF_TETRIS_16_4_BIN                     UI_ADDR_BASE(0x346bdd)
#define UI_LEN_TETRIS_16_4_BIN                     0x1de

#define UI_BUF_TETRIS_16_5_BIN                     UI_ADDR_BASE(0x346dbb)
#define UI_LEN_TETRIS_16_5_BIN                     0x1e6

#define UI_BUF_TETRIS_16_6_BIN                     UI_ADDR_BASE(0x346fa1)
#define UI_LEN_TETRIS_16_6_BIN                     0x1f0

#define UI_BUF_TETRIS_BJ_BIN                       UI_ADDR_BASE(0x347191)
#define UI_LEN_TETRIS_BJ_BIN                       0x9f68

#define UI_BUF_TETRIS_BZ_BIN                       UI_ADDR_BASE(0x3510f9)
#define UI_LEN_TETRIS_BZ_BIN                       0xcbf5

#define UI_BUF_TETRIS_BZ2_BIN                      UI_ADDR_BASE(0x35dcee)
#define UI_LEN_TETRIS_BZ2_BIN                      0x4bde

#define UI_BUF_TETRIS_FALL_1_BIN                   UI_ADDR_BASE(0x3628cc)
#define UI_LEN_TETRIS_FALL_1_BIN                   0x184

#define UI_BUF_TETRIS_FALL_2_BIN                   UI_ADDR_BASE(0x362a50)
#define UI_LEN_TETRIS_FALL_2_BIN                   0x176

#define UI_BUF_TETRIS_FALL_3_BIN                   UI_ADDR_BASE(0x362bc6)
#define UI_LEN_TETRIS_FALL_3_BIN                   0x18b

#define UI_BUF_TETRIS_FALL_4_BIN                   UI_ADDR_BASE(0x362d51)
#define UI_LEN_TETRIS_FALL_4_BIN                   0x186

#define UI_BUF_TETRIS_FALL_5_BIN                   UI_ADDR_BASE(0x362ed7)
#define UI_LEN_TETRIS_FALL_5_BIN                   0x180

#define UI_BUF_TETRIS_FALL_6_BIN                   UI_ADDR_BASE(0x363057)
#define UI_LEN_TETRIS_FALL_6_BIN                   0x180

#define UI_BUF_TETRIS_GAMEOVER_BIN                 UI_ADDR_BASE(0x3631d7)
#define UI_LEN_TETRIS_GAMEOVER_BIN                 0x662d

#define UI_BUF_TETRIS_GAME_TETRIS_BIN              UI_ADDR_BASE(0x369804)
#define UI_LEN_TETRIS_GAME_TETRIS_BIN              0xb941

#define UI_BUF_TETRIS_GAME_TETRIS_ENTER_BIN        UI_ADDR_BASE(0x375145)
#define UI_LEN_TETRIS_GAME_TETRIS_ENTER_BIN        0x9c84

#define UI_BUF_TETRIS_GAME_TETRIS_EXITNOTICE_BIN    UI_ADDR_BASE(0x37edc9)
#define UI_LEN_TETRIS_GAME_TETRIS_EXITNOTICE_BIN    0x36bf

#define UI_BUF_TETRIS_GAME_TETRIS_OVER_BIN         UI_ADDR_BASE(0x382488)
#define UI_LEN_TETRIS_GAME_TETRIS_OVER_BIN         0xc1d7

#define UI_BUF_TETRIS_GAME_TETRIS_STOP_BIN         UI_ADDR_BASE(0x38e65f)
#define UI_LEN_TETRIS_GAME_TETRIS_STOP_BIN         0xb991

#define UI_BUF_TIMER_AGAIN_BIN                     UI_ADDR_BASE(0x399ff0)
#define UI_LEN_TIMER_AGAIN_BIN                     0xe43

#define UI_BUF_TIMER_BG_BIN                        UI_ADDR_BASE(0x39ae33)
#define UI_LEN_TIMER_BG_BIN                        0x792

#define UI_BUF_UPGRADE_ROCKET_BIN                  UI_ADDR_BASE(0x39b5c5)
#define UI_LEN_UPGRADE_ROCKET_BIN                  0xae2

#define UI_BUF_UPGRADE_ROCKET_BASE_BIN             UI_ADDR_BASE(0x39c0a7)
#define UI_LEN_UPGRADE_ROCKET_BASE_BIN             0xf53

#define UI_BUF_VOICE_320_86_BIN                    UI_ADDR_BASE(0x39cffa)
#define UI_LEN_VOICE_320_86_BIN                    0x3302

#define UI_BUF_WEATHER_CLOUDY_BIN                  UI_ADDR_BASE(0x3a02fc)
#define UI_LEN_WEATHER_CLOUDY_BIN                  0x1c5a

#define UI_BUF_WEATHER_CLOUDY_NIGHT_BIN            UI_ADDR_BASE(0x3a1f56)
#define UI_LEN_WEATHER_CLOUDY_NIGHT_BIN            0x1b14

#define UI_BUF_WEATHER_DRIZZLE_BIN                 UI_ADDR_BASE(0x3a3a6a)
#define UI_LEN_WEATHER_DRIZZLE_BIN                 0x1e0e

#define UI_BUF_WEATHER_HAZE_BIN                    UI_ADDR_BASE(0x3a5878)
#define UI_LEN_WEATHER_HAZE_BIN                    0xfc2

#define UI_BUF_WEATHER_HEAVY_RAIN_BIN              UI_ADDR_BASE(0x3a683a)
#define UI_LEN_WEATHER_HEAVY_RAIN_BIN              0x1f02

#define UI_BUF_WEATHER_MODERATE_RAIN_BIN           UI_ADDR_BASE(0x3a873c)
#define UI_LEN_WEATHER_MODERATE_RAIN_BIN           0x1df2

#define UI_BUF_WEATHER_OVERCAST_BIN                UI_ADDR_BASE(0x3aa52e)
#define UI_LEN_WEATHER_OVERCAST_BIN                0x1cf6

#define UI_BUF_WEATHER_RAINY_BIN                   UI_ADDR_BASE(0x3ac224)
#define UI_LEN_WEATHER_RAINY_BIN                   0x2136

#define UI_BUF_WEATHER_RAINY_NIGHT_BIN             UI_ADDR_BASE(0x3ae35a)
#define UI_LEN_WEATHER_RAINY_NIGHT_BIN             0x1c86

#define UI_BUF_WEATHER_RAINY_SHOWERS_BIN           UI_ADDR_BASE(0x3affe0)
#define UI_LEN_WEATHER_RAINY_SHOWERS_BIN           0x2002

#define UI_BUF_WEATHER_SAND_AND_DUST_BIN           UI_ADDR_BASE(0x3b1fe2)
#define UI_LEN_WEATHER_SAND_AND_DUST_BIN           0xfe6

#define UI_BUF_WEATHER_SLEET_BIN                   UI_ADDR_BASE(0x3b2fc8)
#define UI_LEN_WEATHER_SLEET_BIN                   0x1f9e

#define UI_BUF_WEATHER_SUNNY_BIN                   UI_ADDR_BASE(0x3b4f66)
#define UI_LEN_WEATHER_SUNNY_BIN                   0xb2e

#define UI_BUF_WEATHER_TOMORROW_NIGHT_BIN          UI_ADDR_BASE(0x3b5a94)
#define UI_LEN_WEATHER_TOMORROW_NIGHT_BIN          0x81b

#define UI_BUF_WEATHER_UNKNOWN_BIN                 UI_ADDR_BASE(0x3b62af)
#define UI_LEN_WEATHER_UNKNOWN_BIN                 0x1bab

#define UI_BUF_WEATHER_WEATHER_LIST_BIN            UI_ADDR_BASE(0x3b7e5a)
#define UI_LEN_WEATHER_WEATHER_LIST_BIN            0x869c

#define UI_BUF_WEATHER_WINDY_BIN                   UI_ADDR_BASE(0x3c04f6)
#define UI_LEN_WEATHER_WINDY_BIN                   0xfb6

#endif
