//该头文件由软件自动生成，请勿随意修改！
#ifndef _UI_H
#define _UI_H

#define UI_BUF_0FONT_FONT_BIN                      UI_ADDR_BASE(0x0)
#define UI_LEN_0FONT_FONT_BIN                      0xcea18

#define UI_BUF_0FONT_FONT_NUM_20_BIN               UI_ADDR_BASE(0xcea18)
#define UI_LEN_0FONT_FONT_NUM_20_BIN               0x1c64

#define UI_BUF_0FONT_FONT_NUM_22_BIN               UI_ADDR_BASE(0xd067c)
#define UI_LEN_0FONT_FONT_NUM_22_BIN               0x1fb0

#define UI_BUF_0FONT_FONT_NUM_24_BIN               UI_ADDR_BASE(0xd262c)
#define UI_LEN_0FONT_FONT_NUM_24_BIN               0x2c4d

#define UI_BUF_0FONT_FONT_NUM_28_BIN               UI_ADDR_BASE(0xd5279)
#define UI_LEN_0FONT_FONT_NUM_28_BIN               0x336d

#define UI_BUF_0FONT_FONT_NUM_32_BIN               UI_ADDR_BASE(0xd85e6)
#define UI_LEN_0FONT_FONT_NUM_32_BIN               0x4213

#define UI_BUF_0FONT_FONT_NUM_38_BIN               UI_ADDR_BASE(0xdc7f9)
#define UI_LEN_0FONT_FONT_NUM_38_BIN               0x5658

#define UI_BUF_0FONT_FONT_NUM_46_BIN               UI_ADDR_BASE(0xe1e51)
#define UI_LEN_0FONT_FONT_NUM_46_BIN               0x8be4

#define UI_BUF_0FONT_FONT_NUM_48_BIN               UI_ADDR_BASE(0xeaa35)
#define UI_LEN_0FONT_FONT_NUM_48_BIN               0x8e34

#define UI_BUF_ACTIVITY_KCAL_BIN                   UI_ADDR_BASE(0xf3869)
#define UI_LEN_ACTIVITY_KCAL_BIN                   0x7b7

#define UI_BUF_ACTIVITY_KM_BIN                     UI_ADDR_BASE(0xf4020)
#define UI_LEN_ACTIVITY_KM_BIN                     0x70c

#define UI_BUF_ACTIVITY_STEP_BIN                   UI_ADDR_BASE(0xf472c)
#define UI_LEN_ACTIVITY_STEP_BIN                   0x7a8

#define UI_BUF_ALARM_CLOCK_ADD_BIN                 UI_ADDR_BASE(0xf4ed4)
#define UI_LEN_ALARM_CLOCK_ADD_BIN                 0xbdf

#define UI_BUF_ALARM_CLOCK_ADD_CLICK_BIN           UI_ADDR_BASE(0xf5ab3)
#define UI_LEN_ALARM_CLOCK_ADD_CLICK_BIN           0xb8c

#define UI_BUF_ALARM_CLOCK_CONTINUE_BIN            UI_ADDR_BASE(0xf663f)
#define UI_LEN_ALARM_CLOCK_CONTINUE_BIN            0xba4

#define UI_BUF_ALARM_CLOCK_CONTINUE_CLICK_BIN      UI_ADDR_BASE(0xf71e3)
#define UI_LEN_ALARM_CLOCK_CONTINUE_CLICK_BIN      0xb86

#define UI_BUF_ALARM_CLOCK_DELETE_BIN              UI_ADDR_BASE(0xf7d69)
#define UI_LEN_ALARM_CLOCK_DELETE_BIN              0x1073

#define UI_BUF_ALARM_CLOCK_DELETE_CLICK_BIN        UI_ADDR_BASE(0xf8ddc)
#define UI_LEN_ALARM_CLOCK_DELETE_CLICK_BIN        0x1015

#define UI_BUF_ALARM_CLOCK_NUM_BIN                 UI_ADDR_BASE(0xf9df1)
#define UI_LEN_ALARM_CLOCK_NUM_BIN                 0x1743

#define UI_BUF_ALARM_CLOCK_OPEN_BIN                UI_ADDR_BASE(0xfb534)
#define UI_LEN_ALARM_CLOCK_OPEN_BIN                0x226

#define UI_BUF_ALARM_CLOCK_SELECT1_BIN             UI_ADDR_BASE(0xfb75a)
#define UI_LEN_ALARM_CLOCK_SELECT1_BIN             0x5c9

#define UI_BUF_ALARM_CLOCK_SELECT1_ON_BIN          UI_ADDR_BASE(0xfbd23)
#define UI_LEN_ALARM_CLOCK_SELECT1_ON_BIN          0x495

#define UI_BUF_ALARM_CLOCK_YES_BIN                 UI_ADDR_BASE(0xfc1b8)
#define UI_LEN_ALARM_CLOCK_YES_BIN                 0xbc0

#define UI_BUF_ALARM_CLOCK_YES_CLICK_BIN           UI_ADDR_BASE(0xfcd78)
#define UI_LEN_ALARM_CLOCK_YES_CLICK_BIN           0xba6

#define UI_BUF_BREATHE_BREATHE_BIN                 UI_ADDR_BASE(0xfd91e)
#define UI_LEN_BREATHE_BREATHE_BIN                 0x4eeb

#define UI_BUF_BREATHE_MODE_BIN                    UI_ADDR_BASE(0x102809)
#define UI_LEN_BREATHE_MODE_BIN                    0xbf5

#define UI_BUF_BREATHE_MODE_CLICK_BIN              UI_ADDR_BASE(0x1033fe)
#define UI_LEN_BREATHE_MODE_CLICK_BIN              0xbe6

#define UI_BUF_BREATHE_TIME_BIN                    UI_ADDR_BASE(0x103fe4)
#define UI_LEN_BREATHE_TIME_BIN                    0xa50

#define UI_BUF_BREATHE_TIME_CLICK_BIN              UI_ADDR_BASE(0x104a34)
#define UI_LEN_BREATHE_TIME_CLICK_BIN              0xa29

#define UI_BUF_CALCULATOR_0_CLICK_BIN              UI_ADDR_BASE(0x10545d)
#define UI_LEN_CALCULATOR_0_CLICK_BIN              0x610

#define UI_BUF_CALCULATOR_1_CLICK_BIN              UI_ADDR_BASE(0x105a6d)
#define UI_LEN_CALCULATOR_1_CLICK_BIN              0x4f8

#define UI_BUF_CALCULATOR_2_CLICK_BIN              UI_ADDR_BASE(0x105f65)
#define UI_LEN_CALCULATOR_2_CLICK_BIN              0x55a

#define UI_BUF_CALCULATOR_3_CLICK_BIN              UI_ADDR_BASE(0x1064bf)
#define UI_LEN_CALCULATOR_3_CLICK_BIN              0x598

#define UI_BUF_CALCULATOR_4_CLICK_BIN              UI_ADDR_BASE(0x106a57)
#define UI_LEN_CALCULATOR_4_CLICK_BIN              0x58f

#define UI_BUF_CALCULATOR_5_CLICK_BIN              UI_ADDR_BASE(0x106fe6)
#define UI_LEN_CALCULATOR_5_CLICK_BIN              0x565

#define UI_BUF_CALCULATOR_6_CLICK_BIN              UI_ADDR_BASE(0x10754b)
#define UI_LEN_CALCULATOR_6_CLICK_BIN              0x5e2

#define UI_BUF_CALCULATOR_7_CLICK_BIN              UI_ADDR_BASE(0x107b2d)
#define UI_LEN_CALCULATOR_7_CLICK_BIN              0x4fa

#define UI_BUF_CALCULATOR_8_CLICK_BIN              UI_ADDR_BASE(0x108027)
#define UI_LEN_CALCULATOR_8_CLICK_BIN              0x621

#define UI_BUF_CALCULATOR_9_CLICK_BIN              UI_ADDR_BASE(0x108648)
#define UI_LEN_CALCULATOR_9_CLICK_BIN              0x61e

#define UI_BUF_CALCULATOR_ADD_CLICK_BIN            UI_ADDR_BASE(0x108c66)
#define UI_LEN_CALCULATOR_ADD_CLICK_BIN            0x516

#define UI_BUF_CALCULATOR_BG_BIN                   UI_ADDR_BASE(0x10917c)
#define UI_LEN_CALCULATOR_BG_BIN                   0x58a8

#define UI_BUF_CALCULATOR_CE_CLICK_BIN             UI_ADDR_BASE(0x10ea24)
#define UI_LEN_CALCULATOR_CE_CLICK_BIN             0x5d6

#define UI_BUF_CALCULATOR_C_CLICK_BIN              UI_ADDR_BASE(0x10effa)
#define UI_LEN_CALCULATOR_C_CLICK_BIN              0x4eb

#define UI_BUF_CALCULATOR_DEL_CLICK_BIN            UI_ADDR_BASE(0x10f4e5)
#define UI_LEN_CALCULATOR_DEL_CLICK_BIN            0x62e

#define UI_BUF_CALCULATOR_DIVIDED_CLICK_BIN        UI_ADDR_BASE(0x10fb13)
#define UI_LEN_CALCULATOR_DIVIDED_CLICK_BIN        0x476

#define UI_BUF_CALCULATOR_EQUAL_CLICK_BIN          UI_ADDR_BASE(0x10ff89)
#define UI_LEN_CALCULATOR_EQUAL_CLICK_BIN          0x440

#define UI_BUF_CALCULATOR_MINUS_CLICK_BIN          UI_ADDR_BASE(0x1103c9)
#define UI_LEN_CALCULATOR_MINUS_CLICK_BIN          0x5c6

#define UI_BUF_CALCULATOR_MULTIPLY_CLICK_BIN       UI_ADDR_BASE(0x11098f)
#define UI_LEN_CALCULATOR_MULTIPLY_CLICK_BIN       0x5be

#define UI_BUF_CALCULATOR_POINT_CLICK_BIN          UI_ADDR_BASE(0x110f4d)
#define UI_LEN_CALCULATOR_POINT_CLICK_BIN          0x422

#define UI_BUF_CALCULATOR_REDUCE_CLICK_BIN         UI_ADDR_BASE(0x11136f)
#define UI_LEN_CALCULATOR_REDUCE_CLICK_BIN         0x408

#define UI_BUF_CALL_0_CLICK_BIN                    UI_ADDR_BASE(0x111777)
#define UI_LEN_CALL_0_CLICK_BIN                    0x74c

#define UI_BUF_CALL_7_CLICK_BIN                    UI_ADDR_BASE(0x111ec3)
#define UI_LEN_CALL_7_CLICK_BIN                    0x66d

#define UI_BUF_CALL_9_CLICK_BIN                    UI_ADDR_BASE(0x112530)
#define UI_LEN_CALL_9_CLICK_BIN                    0x868

#define UI_BUF_CALL_ANSWER_BIN                     UI_ADDR_BASE(0x112d98)
#define UI_LEN_CALL_ANSWER_BIN                     0xbde

#define UI_BUF_CALL_ANSWER_CLICK_BIN               UI_ADDR_BASE(0x113976)
#define UI_LEN_CALL_ANSWER_CLICK_BIN               0xbba

#define UI_BUF_CALL_BG1_BIN                        UI_ADDR_BASE(0x114530)
#define UI_LEN_CALL_BG1_BIN                        0x45d3

#define UI_BUF_CALL_CALL_CLICK_BIN                 UI_ADDR_BASE(0x118b03)
#define UI_LEN_CALL_CALL_CLICK_BIN                 0x52c

#define UI_BUF_CALL_DEL_CLICK_BIN                  UI_ADDR_BASE(0x11902f)
#define UI_LEN_CALL_DEL_CLICK_BIN                  0x4e1

#define UI_BUF_CALL_MES_BIN                        UI_ADDR_BASE(0x119510)
#define UI_LEN_CALL_MES_BIN                        0x25a

#define UI_BUF_CALL_MES_CLICK_BIN                  UI_ADDR_BASE(0x11976a)
#define UI_LEN_CALL_MES_CLICK_BIN                  0x31f

#define UI_BUF_CALL_MUTE_BIN                       UI_ADDR_BASE(0x119a89)
#define UI_LEN_CALL_MUTE_BIN                       0x856

#define UI_BUF_CALL_MUTE_CLICK_BIN                 UI_ADDR_BASE(0x11a2df)
#define UI_LEN_CALL_MUTE_CLICK_BIN                 0x9ed

#define UI_BUF_CALL_MUTE_ON_BIN                    UI_ADDR_BASE(0x11accc)
#define UI_LEN_CALL_MUTE_ON_BIN                    0xc11

#define UI_BUF_CALL_REJECT_BIN                     UI_ADDR_BASE(0x11b8dd)
#define UI_LEN_CALL_REJECT_BIN                     0xc6c

#define UI_BUF_CALL_REJECT_CLICK_BIN               UI_ADDR_BASE(0x11c549)
#define UI_LEN_CALL_REJECT_CLICK_BIN               0xc4b

#define UI_BUF_CALL_DIAL_NUM_0_BIN                 UI_ADDR_BASE(0x11d194)
#define UI_LEN_CALL_DIAL_NUM_0_BIN                 0x4aa

#define UI_BUF_CALL_DIAL_NUM_1_BIN                 UI_ADDR_BASE(0x11d63e)
#define UI_LEN_CALL_DIAL_NUM_1_BIN                 0x2d8

#define UI_BUF_CALL_DIAL_NUM_2_BIN                 UI_ADDR_BASE(0x11d916)
#define UI_LEN_CALL_DIAL_NUM_2_BIN                 0x328

#define UI_BUF_CALL_DIAL_NUM_3_BIN                 UI_ADDR_BASE(0x11dc3e)
#define UI_LEN_CALL_DIAL_NUM_3_BIN                 0x371

#define UI_BUF_CALL_DIAL_NUM_4_BIN                 UI_ADDR_BASE(0x11dfaf)
#define UI_LEN_CALL_DIAL_NUM_4_BIN                 0x33d

#define UI_BUF_CALL_DIAL_NUM_5_BIN                 UI_ADDR_BASE(0x11e2ec)
#define UI_LEN_CALL_DIAL_NUM_5_BIN                 0x343

#define UI_BUF_CALL_DIAL_NUM_6_BIN                 UI_ADDR_BASE(0x11e62f)
#define UI_LEN_CALL_DIAL_NUM_6_BIN                 0x3af

#define UI_BUF_CALL_DIAL_NUM_7_BIN                 UI_ADDR_BASE(0x11e9de)
#define UI_LEN_CALL_DIAL_NUM_7_BIN                 0x40d

#define UI_BUF_CALL_DIAL_NUM_8_BIN                 UI_ADDR_BASE(0x11edeb)
#define UI_LEN_CALL_DIAL_NUM_8_BIN                 0x3fc

#define UI_BUF_CALL_DIAL_NUM_9_BIN                 UI_ADDR_BASE(0x11f1e7)
#define UI_LEN_CALL_DIAL_NUM_9_BIN                 0x5e7

#define UI_BUF_CAMERA_CAMERA_BIN                   UI_ADDR_BASE(0x11f7ce)
#define UI_LEN_CAMERA_CAMERA_BIN                   0x1bd9

#define UI_BUF_CLOCK_DOWN_MENU_BLE_ICON_OFF_BIN    UI_ADDR_BASE(0x1213a7)
#define UI_LEN_CLOCK_DOWN_MENU_BLE_ICON_OFF_BIN    0x177

#define UI_BUF_CLOCK_DOWN_MENU_BLE_ICON_ON_BIN     UI_ADDR_BASE(0x12151e)
#define UI_LEN_CLOCK_DOWN_MENU_BLE_ICON_ON_BIN     0x180

#define UI_BUF_CLOCK_DOWN_MENU_BT_ICON_OFF_BIN     UI_ADDR_BASE(0x12169e)
#define UI_LEN_CLOCK_DOWN_MENU_BT_ICON_OFF_BIN     0x111

#define UI_BUF_CLOCK_DOWN_MENU_BT_ICON_ON_BIN      UI_ADDR_BASE(0x1217af)
#define UI_LEN_CLOCK_DOWN_MENU_BT_ICON_ON_BIN      0x11b

#define UI_BUF_CLOCK_DOWN_MENU_BT_OFF_BIN          UI_ADDR_BASE(0x1218ca)
#define UI_LEN_CLOCK_DOWN_MENU_BT_OFF_BIN          0x5d2

#define UI_BUF_CLOCK_DOWN_MENU_BT_ON_BIN           UI_ADDR_BASE(0x121e9c)
#define UI_LEN_CLOCK_DOWN_MENU_BT_ON_BIN           0x650

#define UI_BUF_CLOCK_DOWN_MENU_DND_OFF_BIN         UI_ADDR_BASE(0x1224ec)
#define UI_LEN_CLOCK_DOWN_MENU_DND_OFF_BIN         0x5a7

#define UI_BUF_CLOCK_DOWN_MENU_DND_ON_BIN          UI_ADDR_BASE(0x122a93)
#define UI_LEN_CLOCK_DOWN_MENU_DND_ON_BIN          0x628

#define UI_BUF_CLOCK_DOWN_MENU_LIGHT_1_BIN         UI_ADDR_BASE(0x1230bb)
#define UI_LEN_CLOCK_DOWN_MENU_LIGHT_1_BIN         0x713

#define UI_BUF_CLOCK_DOWN_MENU_LIGHT_2_BIN         UI_ADDR_BASE(0x1237ce)
#define UI_LEN_CLOCK_DOWN_MENU_LIGHT_2_BIN         0x75a

#define UI_BUF_CLOCK_DOWN_MENU_LIGHT_3_BIN         UI_ADDR_BASE(0x123f28)
#define UI_LEN_CLOCK_DOWN_MENU_LIGHT_3_BIN         0x774

#define UI_BUF_CLOCK_DOWN_MENU_LIGHT_4_BIN         UI_ADDR_BASE(0x12469c)
#define UI_LEN_CLOCK_DOWN_MENU_LIGHT_4_BIN         0x790

#define UI_BUF_CLOCK_DOWN_MENU_LIGHT_5_BIN         UI_ADDR_BASE(0x124e2c)
#define UI_LEN_CLOCK_DOWN_MENU_LIGHT_5_BIN         0x7b6

#define UI_BUF_CLOCK_DOWN_MENU_MUTE_OFF_BIN        UI_ADDR_BASE(0x1255e2)
#define UI_LEN_CLOCK_DOWN_MENU_MUTE_OFF_BIN        0x59f

#define UI_BUF_CLOCK_DOWN_MENU_MUTE_ON_BIN         UI_ADDR_BASE(0x125b81)
#define UI_LEN_CLOCK_DOWN_MENU_MUTE_ON_BIN         0x78e

#define UI_BUF_CLOCK_DOWN_MENU_SETTING_BIN         UI_ADDR_BASE(0x12630f)
#define UI_LEN_CLOCK_DOWN_MENU_SETTING_BIN         0x743

#define UI_BUF_CLOCK_DOWN_MENU_TOUCH_BIN           UI_ADDR_BASE(0x126a52)
#define UI_LEN_CLOCK_DOWN_MENU_TOUCH_BIN           0x61a

#define UI_BUF_COMMON_1_CLICK_BIN                  UI_ADDR_BASE(0x12706c)
#define UI_LEN_COMMON_1_CLICK_BIN                  0x4cb

#define UI_BUF_COMMON_2_CLICK_BIN                  UI_ADDR_BASE(0x127537)
#define UI_LEN_COMMON_2_CLICK_BIN                  0x511

#define UI_BUF_COMMON_3_CLICK_BIN                  UI_ADDR_BASE(0x127a48)
#define UI_LEN_COMMON_3_CLICK_BIN                  0x557

#define UI_BUF_COMMON_4_CLICK_BIN                  UI_ADDR_BASE(0x127f9f)
#define UI_LEN_COMMON_4_CLICK_BIN                  0x531

#define UI_BUF_COMMON_5_CLICK_BIN                  UI_ADDR_BASE(0x1284d0)
#define UI_LEN_COMMON_5_CLICK_BIN                  0x53b

#define UI_BUF_COMMON_6_CLICK_BIN                  UI_ADDR_BASE(0x128a0b)
#define UI_LEN_COMMON_6_CLICK_BIN                  0x5ce

#define UI_BUF_COMMON_8_CLICK_BIN                  UI_ADDR_BASE(0x128fd9)
#define UI_LEN_COMMON_8_CLICK_BIN                  0x607

#define UI_BUF_COMMON_BG_BIN                       UI_ADDR_BASE(0x1295e0)
#define UI_LEN_COMMON_BG_BIN                       0x726

#define UI_BUF_COMMON_BG1_BIN                      UI_ADDR_BASE(0x129d06)
#define UI_LEN_COMMON_BG1_BIN                      0x2ff

#define UI_BUF_COMMON_BG2_BIN                      UI_ADDR_BASE(0x12a005)
#define UI_LEN_COMMON_BG2_BIN                      0x8f

#define UI_BUF_COMMON_BUTTON_BIN                   UI_ADDR_BASE(0x12a094)
#define UI_LEN_COMMON_BUTTON_BIN                   0xaea

#define UI_BUF_COMMON_BUTTON_CLICK_BIN             UI_ADDR_BASE(0x12ab7e)
#define UI_LEN_COMMON_BUTTON_CLICK_BIN             0xaea

#define UI_BUF_COMMON_COLON_NUM_130_46_BIN         UI_ADDR_BASE(0x12b668)
#define UI_LEN_COMMON_COLON_NUM_130_46_BIN         0x18f

#define UI_BUF_COMMON_COLON_NUM_16_24_BIN          UI_ADDR_BASE(0x12b7f7)
#define UI_LEN_COMMON_COLON_NUM_16_24_BIN          0x89

#define UI_BUF_COMMON_COLON_NUM_30_46_BIN          UI_ADDR_BASE(0x12b880)
#define UI_LEN_COMMON_COLON_NUM_30_46_BIN          0x1cd

#define UI_BUF_COMMON_FIND_PHONE_BIN               UI_ADDR_BASE(0x12ba4d)
#define UI_LEN_COMMON_FIND_PHONE_BIN               0x25e5

#define UI_BUF_COMMON_FIND_PHONE_START_BIN         UI_ADDR_BASE(0x12e032)
#define UI_LEN_COMMON_FIND_PHONE_START_BIN         0x511

#define UI_BUF_COMMON_FIND_PHONE_STOP_BIN          UI_ADDR_BASE(0x12e543)
#define UI_LEN_COMMON_FIND_PHONE_STOP_BIN          0x3a5

#define UI_BUF_COMMON_INCREASE_BIN                 UI_ADDR_BASE(0x12e8e8)
#define UI_LEN_COMMON_INCREASE_BIN                 0x67f

#define UI_BUF_COMMON_INCREASE_CLICK_BIN           UI_ADDR_BASE(0x12ef67)
#define UI_LEN_COMMON_INCREASE_CLICK_BIN           0x67f

#define UI_BUF_COMMON_NO_BIN                       UI_ADDR_BASE(0x12f5e6)
#define UI_LEN_COMMON_NO_BIN                       0xcf7

#define UI_BUF_COMMON_NO_CLICK_BIN                 UI_ADDR_BASE(0x1302dd)
#define UI_LEN_COMMON_NO_CLICK_BIN                 0xcc8

#define UI_BUF_COMMON_NUM_16_24_BIN                UI_ADDR_BASE(0x130fa5)
#define UI_LEN_COMMON_NUM_16_24_BIN                0x1a0f

#define UI_BUF_COMMON_NUM_24_38_BIN                UI_ADDR_BASE(0x1329b4)
#define UI_LEN_COMMON_NUM_24_38_BIN                0x2abe

#define UI_BUF_COMMON_NUM_30_46_BIN                UI_ADDR_BASE(0x135472)
#define UI_LEN_COMMON_NUM_30_46_BIN                0x359b

#define UI_BUF_COMMON_NUM_LEFT_18_18_BIN           UI_ADDR_BASE(0x138a0d)
#define UI_LEN_COMMON_NUM_LEFT_18_18_BIN           0xf1a

#define UI_BUF_COMMON_NUM_RIGHT_18_18_BIN          UI_ADDR_BASE(0x139927)
#define UI_LEN_COMMON_NUM_RIGHT_18_18_BIN          0xef4

#define UI_BUF_COMMON_OFF_BIN                      UI_ADDR_BASE(0x13a81b)
#define UI_LEN_COMMON_OFF_BIN                      0x357

#define UI_BUF_COMMON_ON_BIN                       UI_ADDR_BASE(0x13ab72)
#define UI_LEN_COMMON_ON_BIN                       0x334

#define UI_BUF_COMMON_PAUSE_BIN                    UI_ADDR_BASE(0x13aea6)
#define UI_LEN_COMMON_PAUSE_BIN                    0xc53

#define UI_BUF_COMMON_PAUSE_CLICK_BIN              UI_ADDR_BASE(0x13baf9)
#define UI_LEN_COMMON_PAUSE_CLICK_BIN              0xc4a

#define UI_BUF_COMMON_PERCENT_BIN                  UI_ADDR_BASE(0x13c743)
#define UI_LEN_COMMON_PERCENT_BIN                  0x4fb

#define UI_BUF_COMMON_POINT_NUM_16_24_BIN          UI_ADDR_BASE(0x13cc3e)
#define UI_LEN_COMMON_POINT_NUM_16_24_BIN          0x37

#define UI_BUF_COMMON_POINT_NUM_30_46_BIN          UI_ADDR_BASE(0x13cc75)
#define UI_LEN_COMMON_POINT_NUM_30_46_BIN          0x85

#define UI_BUF_COMMON_REDUCE_BIN                   UI_ADDR_BASE(0x13ccfa)
#define UI_LEN_COMMON_REDUCE_BIN                   0x572

#define UI_BUF_COMMON_REDUCE_CLICK_BIN             UI_ADDR_BASE(0x13d26c)
#define UI_LEN_COMMON_REDUCE_CLICK_BIN             0x56f

#define UI_BUF_COMMON_SELECT_BIN                   UI_ADDR_BASE(0x13d7db)
#define UI_LEN_COMMON_SELECT_BIN                   0x6da

#define UI_BUF_COMMON_SELECT_ON_BIN                UI_ADDR_BASE(0x13deb5)
#define UI_LEN_COMMON_SELECT_ON_BIN                0x649

#define UI_BUF_COMMON_START_BIN                    UI_ADDR_BASE(0x13e4fe)
#define UI_LEN_COMMON_START_BIN                    0xd8a

#define UI_BUF_COMMON_START_CLICK_BIN              UI_ADDR_BASE(0x13f288)
#define UI_LEN_COMMON_START_CLICK_BIN              0xdb5

#define UI_BUF_COMPO_SELECT_ADD_BIN                UI_ADDR_BASE(0x14003d)
#define UI_LEN_COMPO_SELECT_ADD_BIN                0x235

#define UI_BUF_COMPO_SELECT_ADD_DEL_BIN            UI_ADDR_BASE(0x140272)
#define UI_LEN_COMPO_SELECT_ADD_DEL_BIN            0x54b

#define UI_BUF_COMPO_SELECT_BG_BIN                 UI_ADDR_BASE(0x1407bd)
#define UI_LEN_COMPO_SELECT_BG_BIN                 0x138c

#define UI_BUF_DIALPLATE_1_BIN                     UI_ADDR_BASE(0x141b49)
#define UI_LEN_DIALPLATE_1_BIN                     0x1046e

#define UI_BUF_DIALPLATE_4_BIN                     UI_ADDR_BASE(0x151fb7)
#define UI_LEN_DIALPLATE_4_BIN                     0xe160

#define UI_BUF_DIALPLATE_BTF_BIN                   UI_ADDR_BASE(0x160117)
#define UI_LEN_DIALPLATE_BTF_BIN                   0x2eae

#define UI_BUF_DIALPLATE_CUBE_BIN                  UI_ADDR_BASE(0x162fc5)
#define UI_LEN_DIALPLATE_CUBE_BIN                  0x2720

#define UI_BUF_DIALPLATE_BUTTERFLY_BG_BIN          UI_ADDR_BASE(0x1656e5)
#define UI_LEN_DIALPLATE_BUTTERFLY_BG_BIN          0x11e8

#define UI_BUF_DIALPLATE_BUTTERFLY_BODY_BIN        UI_ADDR_BASE(0x1668cd)
#define UI_LEN_DIALPLATE_BUTTERFLY_BODY_BIN        0xc38

#define UI_BUF_DIALPLATE_BUTTERFLY_DOWN_BIN        UI_ADDR_BASE(0x167505)
#define UI_LEN_DIALPLATE_BUTTERFLY_DOWN_BIN        0x4623

#define UI_BUF_DIALPLATE_BUTTERFLY_LIGHT_BIN       UI_ADDR_BASE(0x16bb28)
#define UI_LEN_DIALPLATE_BUTTERFLY_LIGHT_BIN       0x2c8

#define UI_BUF_DIALPLATE_BUTTERFLY_UP_BIN          UI_ADDR_BASE(0x16bdf0)
#define UI_LEN_DIALPLATE_BUTTERFLY_UP_BIN          0x40b6

#define UI_BUF_DIALPLATE_CUBE_BG_BIN               UI_ADDR_BASE(0x16fea6)
#define UI_LEN_DIALPLATE_CUBE_BG_BIN               0x6342

#define UI_BUF_DIALPLATE_CUBE_CALL_BIN             UI_ADDR_BASE(0x1761e8)
#define UI_LEN_DIALPLATE_CUBE_CALL_BIN             0x978

#define UI_BUF_DIALPLATE_CUBE_HEART_RATE_BIN       UI_ADDR_BASE(0x176b60)
#define UI_LEN_DIALPLATE_CUBE_HEART_RATE_BIN       0x9ae

#define UI_BUF_DIALPLATE_CUBE_MUSIC_BIN            UI_ADDR_BASE(0x17750e)
#define UI_LEN_DIALPLATE_CUBE_MUSIC_BIN            0xb51

#define UI_BUF_DIALPLATE_CUBE_SLEEP_BIN            UI_ADDR_BASE(0x17805f)
#define UI_LEN_DIALPLATE_CUBE_SLEEP_BIN            0xad0

#define UI_BUF_DIALPLATE_CUBE_SPORT_BIN            UI_ADDR_BASE(0x178b2f)
#define UI_LEN_DIALPLATE_CUBE_SPORT_BIN            0xad1

#define UI_BUF_DIALPLATE_CUBE_STEP_BIN             UI_ADDR_BASE(0x179600)
#define UI_LEN_DIALPLATE_CUBE_STEP_BIN             0xb8f

#define UI_BUF_DROPDOWN_BATTERY_0_BIN              UI_ADDR_BASE(0x17a18f)
#define UI_LEN_DROPDOWN_BATTERY_0_BIN              0x10a

#define UI_BUF_DROPDOWN_BATTERY_1_BIN              UI_ADDR_BASE(0x17a299)
#define UI_LEN_DROPDOWN_BATTERY_1_BIN              0x154

#define UI_BUF_DROPDOWN_BATTERY_2_BIN              UI_ADDR_BASE(0x17a3ed)
#define UI_LEN_DROPDOWN_BATTERY_2_BIN              0x154

#define UI_BUF_DROPDOWN_BATTERY_3_BIN              UI_ADDR_BASE(0x17a541)
#define UI_LEN_DROPDOWN_BATTERY_3_BIN              0x154

#define UI_BUF_DROPDOWN_BATTERY_4_BIN              UI_ADDR_BASE(0x17a695)
#define UI_LEN_DROPDOWN_BATTERY_4_BIN              0x154

#define UI_BUF_DROPDOWN_BATTERY_5_BIN              UI_ADDR_BASE(0x17a7e9)
#define UI_LEN_DROPDOWN_BATTERY_5_BIN              0x154

#define UI_BUF_DROPDOWN_BATTERY_6_BIN              UI_ADDR_BASE(0x17a93d)
#define UI_LEN_DROPDOWN_BATTERY_6_BIN              0x143

#define UI_BUF_DROPDOWN_BLUETOOTH_CONNECT_OFF_BIN    UI_ADDR_BASE(0x17aa80)
#define UI_LEN_DROPDOWN_BLUETOOTH_CONNECT_OFF_BIN    0x20b

#define UI_BUF_DROPDOWN_BLUETOOTH_CONNECT_ON_BIN    UI_ADDR_BASE(0x17ac8b)
#define UI_LEN_DROPDOWN_BLUETOOTH_CONNECT_ON_BIN    0x255

#define UI_BUF_DROPDOWN_BLUETOOTH_OFF_BIN          UI_ADDR_BASE(0x17aee0)
#define UI_LEN_DROPDOWN_BLUETOOTH_OFF_BIN          0xb98

#define UI_BUF_DROPDOWN_BLUETOOTH_ON_BIN           UI_ADDR_BASE(0x17ba78)
#define UI_LEN_DROPDOWN_BLUETOOTH_ON_BIN           0xbca

#define UI_BUF_DROPDOWN_CONNECT_OFF_BIN            UI_ADDR_BASE(0x17c642)
#define UI_LEN_DROPDOWN_CONNECT_OFF_BIN            0xb23

#define UI_BUF_DROPDOWN_CONNECT_ON_BIN             UI_ADDR_BASE(0x17d165)
#define UI_LEN_DROPDOWN_CONNECT_ON_BIN             0xa88

#define UI_BUF_DROPDOWN_DISTURB_OFF_BIN            UI_ADDR_BASE(0x17dbed)
#define UI_LEN_DROPDOWN_DISTURB_OFF_BIN            0x9db

#define UI_BUF_DROPDOWN_DISTURB_ON_BIN             UI_ADDR_BASE(0x17e5c8)
#define UI_LEN_DROPDOWN_DISTURB_ON_BIN             0x9cf

#define UI_BUF_DROPDOWN_FIND_PHONE_OFF_BIN         UI_ADDR_BASE(0x17ef97)
#define UI_LEN_DROPDOWN_FIND_PHONE_OFF_BIN         0xd70

#define UI_BUF_DROPDOWN_FIND_PHONE_ON_BIN          UI_ADDR_BASE(0x17fd07)
#define UI_LEN_DROPDOWN_FIND_PHONE_ON_BIN          0xd7e

#define UI_BUF_DROPDOWN_FLASHLIGHT_OFF_BIN         UI_ADDR_BASE(0x180a85)
#define UI_LEN_DROPDOWN_FLASHLIGHT_OFF_BIN         0xb0c

#define UI_BUF_DROPDOWN_FLASHLIGHT_ON_BIN          UI_ADDR_BASE(0x181591)
#define UI_LEN_DROPDOWN_FLASHLIGHT_ON_BIN          0xb06

#define UI_BUF_DROPDOWN_LIGHT_1_BIN                UI_ADDR_BASE(0x182097)
#define UI_LEN_DROPDOWN_LIGHT_1_BIN                0xcb4

#define UI_BUF_DROPDOWN_LIGHT_2_BIN                UI_ADDR_BASE(0x182d4b)
#define UI_LEN_DROPDOWN_LIGHT_2_BIN                0xcc7

#define UI_BUF_DROPDOWN_MUTE_OFF_BIN               UI_ADDR_BASE(0x183a12)
#define UI_LEN_DROPDOWN_MUTE_OFF_BIN               0xb83

#define UI_BUF_DROPDOWN_MUTE_ON_BIN                UI_ADDR_BASE(0x184595)
#define UI_LEN_DROPDOWN_MUTE_ON_BIN                0xc14

#define UI_BUF_DROPDOWN_POWER1_BIN                 UI_ADDR_BASE(0x1851a9)
#define UI_LEN_DROPDOWN_POWER1_BIN                 0x1a7

#define UI_BUF_DROPDOWN_POWER2_BIN                 UI_ADDR_BASE(0x185350)
#define UI_LEN_DROPDOWN_POWER2_BIN                 0x1fb

#define UI_BUF_DROPDOWN_POWER3_BIN                 UI_ADDR_BASE(0x18554b)
#define UI_LEN_DROPDOWN_POWER3_BIN                 0x260

#define UI_BUF_DROPDOWN_POWER4_BIN                 UI_ADDR_BASE(0x1857ab)
#define UI_LEN_DROPDOWN_POWER4_BIN                 0x2d9

#define UI_BUF_DROPDOWN_POWER5_BIN                 UI_ADDR_BASE(0x185a84)
#define UI_LEN_DROPDOWN_POWER5_BIN                 0x33b

#define UI_BUF_DROPDOWN_POWER6_BIN                 UI_ADDR_BASE(0x185dbf)
#define UI_LEN_DROPDOWN_POWER6_BIN                 0x1c7

#define UI_BUF_DROPDOWN_POWER_BG_BIN               UI_ADDR_BASE(0x185f86)
#define UI_LEN_DROPDOWN_POWER_BG_BIN               0xae3

#define UI_BUF_DROPDOWN_SCAN_1_BIN                 UI_ADDR_BASE(0x186a69)
#define UI_LEN_DROPDOWN_SCAN_1_BIN                 0xaa3

#define UI_BUF_DROPDOWN_SCAN_2_BIN                 UI_ADDR_BASE(0x18750c)
#define UI_LEN_DROPDOWN_SCAN_2_BIN                 0xaa6

#define UI_BUF_GAME_GAMEOVER_BIN                   UI_ADDR_BASE(0x187fb2)
#define UI_LEN_GAME_GAMEOVER_BIN                   0x349c

#define UI_BUF_GAME_GAME_BG_BIN                    UI_ADDR_BASE(0x18b44e)
#define UI_LEN_GAME_GAME_BG_BIN                    0x3f80

#define UI_BUF_GAME_GAME_BIRD_BIN                  UI_ADDR_BASE(0x18f3ce)
#define UI_LEN_GAME_GAME_BIRD_BIN                  0x11de

#define UI_BUF_GAME_GAME_FINISH_BIN                UI_ADDR_BASE(0x1905ac)
#define UI_LEN_GAME_GAME_FINISH_BIN                0x2cb9

#define UI_BUF_GAME_GAME_PIPE_DOWN_BIN             UI_ADDR_BASE(0x193265)
#define UI_LEN_GAME_GAME_PIPE_DOWN_BIN             0x1705

#define UI_BUF_GAME_GAME_PIPE_UP_BIN               UI_ADDR_BASE(0x19496a)
#define UI_LEN_GAME_GAME_PIPE_UP_BIN               0x166b

#define UI_BUF_GAME_GAME_START_BIN                 UI_ADDR_BASE(0x195fd5)
#define UI_LEN_GAME_GAME_START_BIN                 0xc24

#define UI_BUF_HEART_RATE_CHART_BG_BIN             UI_ADDR_BASE(0x196bf9)
#define UI_LEN_HEART_RATE_CHART_BG_BIN             0x2e92

#define UI_BUF_HEART_RATE_DOWN_BIN                 UI_ADDR_BASE(0x199a8b)
#define UI_LEN_HEART_RATE_DOWN_BIN                 0x1fe

#define UI_BUF_HEART_RATE_HR_BG_BIN                UI_ADDR_BASE(0x199c89)
#define UI_LEN_HEART_RATE_HR_BG_BIN                0x133f

#define UI_BUF_HEART_RATE_UP_BIN                   UI_ADDR_BASE(0x19afc8)
#define UI_LEN_HEART_RATE_UP_BIN                   0x1fe

#define UI_BUF_I330001_BLOODOXYGEN_GIF_BIN         UI_ADDR_BASE(0x19b1c6)
#define UI_LEN_I330001_BLOODOXYGEN_GIF_BIN         0x23820

#define UI_BUF_I330001_BLOODOXYGEN_ICON_DETECTION_BIN    UI_ADDR_BASE(0x1be9e6)
#define UI_LEN_I330001_BLOODOXYGEN_ICON_DETECTION_BIN    0x974

#define UI_BUF_I330001_BLOODOXYGEN_PERCENT_BIN     UI_ADDR_BASE(0x1bf35a)
#define UI_LEN_I330001_BLOODOXYGEN_PERCENT_BIN     0x363

#define UI_BUF_I330001_CALL_CALLRECORDS_BIN        UI_ADDR_BASE(0x1bf6bd)
#define UI_LEN_I330001_CALL_CALLRECORDS_BIN        0x3b5

#define UI_BUF_I330001_CALL_CONTACTS_BIN           UI_ADDR_BASE(0x1bfa72)
#define UI_LEN_I330001_CALL_CONTACTS_BIN           0x405

#define UI_BUF_I330001_CALL_DIALPAD_BIN            UI_ADDR_BASE(0x1bfe77)
#define UI_LEN_I330001_CALL_DIALPAD_BIN            0x613

#define UI_BUF_I330001_CHARGE_COLON1_BIN           UI_ADDR_BASE(0x1c048a)
#define UI_LEN_I330001_CHARGE_COLON1_BIN           0x2d6

#define UI_BUF_I330001_CHARGE_COLON2_BIN           UI_ADDR_BASE(0x1c0760)
#define UI_LEN_I330001_CHARGE_COLON2_BIN           0x2d6

#define UI_BUF_I330001_CHARGE_PERCENT_BIN          UI_ADDR_BASE(0x1c0a36)
#define UI_LEN_I330001_CHARGE_PERCENT_BIN          0x746

#define UI_BUF_I330001_CHARGE_POWER_BIN            UI_ADDR_BASE(0x1c117c)
#define UI_LEN_I330001_CHARGE_POWER_BIN            0x2821

#define UI_BUF_I330001_CHARGE_TIME_BIN             UI_ADDR_BASE(0x1c399d)
#define UI_LEN_I330001_CHARGE_TIME_BIN             0x4f0c

#define UI_BUF_I330001_FIRSTORDER_00_BIN           UI_ADDR_BASE(0x1c88a9)
#define UI_LEN_I330001_FIRSTORDER_00_BIN           0x10af

#define UI_BUF_I330001_FIRSTORDER_ADD_BIN          UI_ADDR_BASE(0x1c9958)
#define UI_LEN_I330001_FIRSTORDER_ADD_BIN          0x2e3

#define UI_BUF_I330001_FIRSTORDER_DELETE_BIN       UI_ADDR_BASE(0x1c9c3b)
#define UI_LEN_I330001_FIRSTORDER_DELETE_BIN       0x26d

#define UI_BUF_I330001_FIRSTORDER_ACTIVITY_CALORIES_BIN    UI_ADDR_BASE(0x1c9ea8)
#define UI_LEN_I330001_FIRSTORDER_ACTIVITY_CALORIES_BIN    0x1f3

#define UI_BUF_I330001_FIRSTORDER_ACTIVITY_DIS_BIN    UI_ADDR_BASE(0x1ca09b)
#define UI_LEN_I330001_FIRSTORDER_ACTIVITY_DIS_BIN    0x1dc

#define UI_BUF_I330001_FIRSTORDER_ACTIVITY_STEPT_BIN    UI_ADDR_BASE(0x1ca277)
#define UI_LEN_I330001_FIRSTORDER_ACTIVITY_STEPT_BIN    0x237

#define UI_BUF_I330001_FIRSTORDER_FIXED_CALL_BIN    UI_ADDR_BASE(0x1ca4ae)
#define UI_LEN_I330001_FIRSTORDER_FIXED_CALL_BIN    0x73b

#define UI_BUF_I330001_FIRSTORDER_FIXED_MSM_BIN    UI_ADDR_BASE(0x1cabe9)
#define UI_LEN_I330001_FIRSTORDER_FIXED_MSM_BIN    0x96e

#define UI_BUF_I330001_FIRSTORDER_FIXED_SPORT_BIN    UI_ADDR_BASE(0x1cb557)
#define UI_LEN_I330001_FIRSTORDER_FIXED_SPORT_BIN    0x8db

#define UI_BUF_I330001_FIRSTORDER_MUSIC_NEXT00_BIN    UI_ADDR_BASE(0x1cbe32)
#define UI_LEN_I330001_FIRSTORDER_MUSIC_NEXT00_BIN    0x3dd

#define UI_BUF_I330001_FIRSTORDER_MUSIC_NEXT01_BIN    UI_ADDR_BASE(0x1cc20f)
#define UI_LEN_I330001_FIRSTORDER_MUSIC_NEXT01_BIN    0x3dd

#define UI_BUF_I330001_FIRSTORDER_MUSIC_PLAY00_BIN    UI_ADDR_BASE(0x1cc5ec)
#define UI_LEN_I330001_FIRSTORDER_MUSIC_PLAY00_BIN    0x74d

#define UI_BUF_I330001_FIRSTORDER_MUSIC_PLAY01_BIN    UI_ADDR_BASE(0x1ccd39)
#define UI_LEN_I330001_FIRSTORDER_MUSIC_PLAY01_BIN    0x74d

#define UI_BUF_I330001_FIRSTORDER_TIME_BG_BIN      UI_ADDR_BASE(0x1cd486)
#define UI_LEN_I330001_FIRSTORDER_TIME_BG_BIN      0x2e59

#define UI_BUF_I330001_FIRSTORDER_TIME_H_BIN       UI_ADDR_BASE(0x1d02df)
#define UI_LEN_I330001_FIRSTORDER_TIME_H_BIN       0x6c3

#define UI_BUF_I330001_FIRSTORDER_TIME_M_BIN       UI_ADDR_BASE(0x1d09a2)
#define UI_LEN_I330001_FIRSTORDER_TIME_M_BIN       0x86b

#define UI_BUF_I330001_HEART_ICON_BIN              UI_ADDR_BASE(0x1d120d)
#define UI_LEN_I330001_HEART_ICON_BIN              0x2ecd

#define UI_BUF_I330001_HEART_MAP_BIN               UI_ADDR_BASE(0x1d40da)
#define UI_LEN_I330001_HEART_MAP_BIN               0x2ce2

#define UI_BUF_I330001_KAIJI_ICON_LOGO_HELLO_BIN    UI_ADDR_BASE(0x1d6dbc)
#define UI_LEN_I330001_KAIJI_ICON_LOGO_HELLO_BIN    0x10c2

#define UI_BUF_I330001_MUSIC_BG_BIN                UI_ADDR_BASE(0x1d7e7e)
#define UI_LEN_I330001_MUSIC_BG_BIN                0x7e18

#define UI_BUF_I330001_MUSIC_NEXTSONG01_BIN        UI_ADDR_BASE(0x1dfc96)
#define UI_LEN_I330001_MUSIC_NEXTSONG01_BIN        0x257

#define UI_BUF_I330001_MUSIC_NEXTSONG02_BIN        UI_ADDR_BASE(0x1dfeed)
#define UI_LEN_I330001_MUSIC_NEXTSONG02_BIN        0x257

#define UI_BUF_I330001_MUSIC_PAUSED_BIN            UI_ADDR_BASE(0x1e0144)
#define UI_LEN_I330001_MUSIC_PAUSED_BIN            0xe14

#define UI_BUF_I330001_MUSIC_PLAY01_BIN            UI_ADDR_BASE(0x1e0f58)
#define UI_LEN_I330001_MUSIC_PLAY01_BIN            0xcc3

#define UI_BUF_I330001_MUSIC_PLAY02_BIN            UI_ADDR_BASE(0x1e1c1b)
#define UI_LEN_I330001_MUSIC_PLAY02_BIN            0xc8f

#define UI_BUF_I330001_MUSIC_PREVIOUSSONG01_BIN    UI_ADDR_BASE(0x1e28aa)
#define UI_LEN_I330001_MUSIC_PREVIOUSSONG01_BIN    0x24e

#define UI_BUF_I330001_MUSIC_PREVIOUSSONG02_BIN    UI_ADDR_BASE(0x1e2af8)
#define UI_LEN_I330001_MUSIC_PREVIOUSSONG02_BIN    0x252

#define UI_BUF_I330001_MUSIC_VOLUME01_BIN          UI_ADDR_BASE(0x1e2d4a)
#define UI_LEN_I330001_MUSIC_VOLUME01_BIN          0x289

#define UI_BUF_I330001_MUSIC_VOLUME02_BIN          UI_ADDR_BASE(0x1e2fd3)
#define UI_LEN_I330001_MUSIC_VOLUME02_BIN          0x289

#define UI_BUF_I330001_MUSIC_VOLUME03_BIN          UI_ADDR_BASE(0x1e325c)
#define UI_LEN_I330001_MUSIC_VOLUME03_BIN          0x3c4

#define UI_BUF_I330001_MUSIC_VOLUME04_BIN          UI_ADDR_BASE(0x1e3620)
#define UI_LEN_I330001_MUSIC_VOLUME04_BIN          0x3c4

#define UI_BUF_I330001_NOTIFICATION_ICON_BUTTON_BIN    UI_ADDR_BASE(0x1e39e4)
#define UI_LEN_I330001_NOTIFICATION_ICON_BUTTON_BIN    0x80e

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_FACEBOOK_BIN    UI_ADDR_BASE(0x1e41f2)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_FACEBOOK_BIN    0x4c9

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_FACEBOOKMESSENGER_BIN    UI_ADDR_BASE(0x1e46bb)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_FACEBOOKMESSENGER_BIN    0x68a

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_FLICKR_BIN    UI_ADDR_BASE(0x1e4d45)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_FLICKR_BIN    0x490

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_GMAIL_BIN    UI_ADDR_BASE(0x1e51d5)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_GMAIL_BIN    0x572

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_GOOGLEPLUS_BIN    UI_ADDR_BASE(0x1e5747)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_GOOGLEPLUS_BIN    0x57c

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_HANGOUTS_BIN    UI_ADDR_BASE(0x1e5cc3)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_HANGOUTS_BIN    0x5ff

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_INSTAGRAM_BIN    UI_ADDR_BASE(0x1e62c2)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_INSTAGRAM_BIN    0x881

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_KAKAOTAKTE_BIN    UI_ADDR_BASE(0x1e6b43)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_KAKAOTAKTE_BIN    0x5d8

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_LINE_BIN    UI_ADDR_BASE(0x1e711b)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_LINE_BIN    0x57f

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_LINKEDIN_BIN    UI_ADDR_BASE(0x1e769a)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_LINKEDIN_BIN    0x53f

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_MMS_BIN    UI_ADDR_BASE(0x1e7bd9)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_MMS_BIN    0x523

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_OTHER_BIN    UI_ADDR_BASE(0x1e80fc)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_OTHER_BIN    0x517

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_PAYTM_BIN    UI_ADDR_BASE(0x1e8613)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_PAYTM_BIN    0x558

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_PINTEREST_BIN    UI_ADDR_BASE(0x1e8b6b)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_PINTEREST_BIN    0x60f

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_QQ_BIN    UI_ADDR_BASE(0x1e917a)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_QQ_BIN    0x5e7

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_SKYPE_BIN    UI_ADDR_BASE(0x1e9761)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_SKYPE_BIN    0x5d6

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_SNAPCHAT_BIN    UI_ADDR_BASE(0x1e9d37)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_SNAPCHAT_BIN    0x560

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_TELEGRAM_BIN    UI_ADDR_BASE(0x1ea297)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_TELEGRAM_BIN    0x4cc

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_TRUECALLER_BIN    UI_ADDR_BASE(0x1ea763)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_TRUECALLER_BIN    0x603

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_TUMBLR_BIN    UI_ADDR_BASE(0x1ead66)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_TUMBLR_BIN    0x487

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_TWITTER_BIN    UI_ADDR_BASE(0x1eb1ed)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_TWITTER_BIN    0x5bd

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_VIBER_BIN    UI_ADDR_BASE(0x1eb7aa)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_VIBER_BIN    0x6ac

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_VKONTAKTE_BIN    UI_ADDR_BASE(0x1ebe56)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_VKONTAKTE_BIN    0x58f

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_WECHAT_BIN    UI_ADDR_BASE(0x1ec3e5)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_WECHAT_BIN    0x71f

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_WHATSAPP_BIN    UI_ADDR_BASE(0x1ecb04)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_WHATSAPP_BIN    0x70a

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_YOUTUBE_BIN    UI_ADDR_BASE(0x1ed20e)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_YOUTUBE_BIN    0x4a8

#define UI_BUF_I330001_NOTIFICATION_ICON_MSG_MSG_ZALO_BIN    UI_ADDR_BASE(0x1ed6b6)
#define UI_LEN_I330001_NOTIFICATION_ICON_MSG_MSG_ZALO_BIN    0x551

#define UI_BUF_I330001_POWEROFF_ICON_RESTART_BIN    UI_ADDR_BASE(0x1edc07)
#define UI_LEN_I330001_POWEROFF_ICON_RESTART_BIN    0x779

#define UI_BUF_I330001_POWEROFF_ICON_SHUTDOWN_BIN    UI_ADDR_BASE(0x1ee380)
#define UI_LEN_I330001_POWEROFF_ICON_SHUTDOWN_BIN    0x815

#define UI_BUF_I330001_POWEROFF_ICON_SOS_BIN       UI_ADDR_BASE(0x1eeb95)
#define UI_LEN_I330001_POWEROFF_ICON_SOS_BIN       0x97f

#define UI_BUF_I330001_PUBLIC_CLOSE00_BIN          UI_ADDR_BASE(0x1ef514)
#define UI_LEN_I330001_PUBLIC_CLOSE00_BIN          0x6ee

#define UI_BUF_I330001_PUBLIC_CLOSE01_BIN          UI_ADDR_BASE(0x1efc02)
#define UI_LEN_I330001_PUBLIC_CLOSE01_BIN          0x88e

#define UI_BUF_I330001_PUBLIC_END_BIN              UI_ADDR_BASE(0x1f0490)
#define UI_LEN_I330001_PUBLIC_END_BIN              0x501

#define UI_BUF_I330001_PUBLIC_JICI_BIN             UI_ADDR_BASE(0x1f0991)
#define UI_LEN_I330001_PUBLIC_JICI_BIN             0x645

#define UI_BUF_I330001_PUBLIC_OK00_BIN             UI_ADDR_BASE(0x1f0fd6)
#define UI_LEN_I330001_PUBLIC_OK00_BIN             0x704

#define UI_BUF_I330001_PUBLIC_OK01_BIN             UI_ADDR_BASE(0x1f16da)
#define UI_LEN_I330001_PUBLIC_OK01_BIN             0x705

#define UI_BUF_I330001_PUBLIC_PAUSED_BIN           UI_ADDR_BASE(0x1f1ddf)
#define UI_LEN_I330001_PUBLIC_PAUSED_BIN           0x981

#define UI_BUF_I330001_PUBLIC_PLAY_BIN             UI_ADDR_BASE(0x1f2760)
#define UI_LEN_I330001_PUBLIC_PLAY_BIN             0x7be

#define UI_BUF_I330001_PUBLIC_RECTANGLE00_BIN      UI_ADDR_BASE(0x1f2f1e)
#define UI_LEN_I330001_PUBLIC_RECTANGLE00_BIN      0x80e

#define UI_BUF_I330001_PUBLIC_RECTANGLE01_BIN      UI_ADDR_BASE(0x1f372c)
#define UI_LEN_I330001_PUBLIC_RECTANGLE01_BIN      0x812

#define UI_BUF_I330001_PUBLIC_RECTANGLE02_BIN      UI_ADDR_BASE(0x1f3f3e)
#define UI_LEN_I330001_PUBLIC_RECTANGLE02_BIN      0x80e

#define UI_BUF_I330001_PUBLIC_SOON_BIN             UI_ADDR_BASE(0x1f474c)
#define UI_LEN_I330001_PUBLIC_SOON_BIN             0x779

#define UI_BUF_I330001_SLEEP_BG_BIN                UI_ADDR_BASE(0x1f4ec5)
#define UI_LEN_I330001_SLEEP_BG_BIN                0x8292

#define UI_BUF_I330001_SLEEP_DOT1_BIN              UI_ADDR_BASE(0x1fd157)
#define UI_LEN_I330001_SLEEP_DOT1_BIN              0xe9

#define UI_BUF_I330001_SLEEP_DOT2_BIN              UI_ADDR_BASE(0x1fd240)
#define UI_LEN_I330001_SLEEP_DOT2_BIN              0xe9

#define UI_BUF_I330001_SLEEP_DOT3_BIN              UI_ADDR_BASE(0x1fd329)
#define UI_LEN_I330001_SLEEP_DOT3_BIN              0xe9

#define UI_BUF_I330001_SLEEP_DOT4_BIN              UI_ADDR_BASE(0x1fd412)
#define UI_LEN_I330001_SLEEP_DOT4_BIN              0xe9

#define UI_BUF_I330001_SLIDEMENU_ICON_BRIGHTNESS_BIN    UI_ADDR_BASE(0x1fd4fb)
#define UI_LEN_I330001_SLIDEMENU_ICON_BRIGHTNESS_BIN    0xa41

#define UI_BUF_I330001_SLIDEMENU_ICON_CALL00_BIN    UI_ADDR_BASE(0x1fdf3c)
#define UI_LEN_I330001_SLIDEMENU_ICON_CALL00_BIN    0x829

#define UI_BUF_I330001_SLIDEMENU_ICON_CALL01_BIN    UI_ADDR_BASE(0x1fe765)
#define UI_LEN_I330001_SLIDEMENU_ICON_CALL01_BIN    0x82e

#define UI_BUF_I330001_SLIDEMENU_ICON_DND00_BIN    UI_ADDR_BASE(0x1fef93)
#define UI_LEN_I330001_SLIDEMENU_ICON_DND00_BIN    0x7ab

#define UI_BUF_I330001_SLIDEMENU_ICON_DND01_BIN    UI_ADDR_BASE(0x1ff73e)
#define UI_LEN_I330001_SLIDEMENU_ICON_DND01_BIN    0x7ae

#define UI_BUF_I330001_SLIDEMENU_ICON_FINDPHONE_BIN    UI_ADDR_BASE(0x1ffeec)
#define UI_LEN_I330001_SLIDEMENU_ICON_FINDPHONE_BIN    0xa25

#define UI_BUF_I330001_SLIDEMENU_ICON_SETTINGS_BIN    UI_ADDR_BASE(0x200911)
#define UI_LEN_I330001_SLIDEMENU_ICON_SETTINGS_BIN    0x941

#define UI_BUF_I330001_SLIDEMENU_ICON_SHOUDIAN00_BIN    UI_ADDR_BASE(0x201252)
#define UI_LEN_I330001_SLIDEMENU_ICON_SHOUDIAN00_BIN    0x8c5

#define UI_BUF_I330001_SLIDEMENU_ICON_TAIWAN00_BIN    UI_ADDR_BASE(0x201b17)
#define UI_LEN_I330001_SLIDEMENU_ICON_TAIWAN00_BIN    0x8a1

#define UI_BUF_I330001_SLIDEMENU_ICON_TAIWAN01_BIN    UI_ADDR_BASE(0x2023b8)
#define UI_LEN_I330001_SLIDEMENU_ICON_TAIWAN01_BIN    0x8a6

#define UI_BUF_I330001_SLIDEMENU_ICON_THEME00_BIN    UI_ADDR_BASE(0x202c5e)
#define UI_LEN_I330001_SLIDEMENU_ICON_THEME00_BIN    0xae6

#define UI_BUF_I330001_SLIDEMENU_ICON_THEME01_BIN    UI_ADDR_BASE(0x203744)
#define UI_LEN_I330001_SLIDEMENU_ICON_THEME01_BIN    0x9c8

#define UI_BUF_I330001_SLIDEMENU_ICON_THEME02_BIN    UI_ADDR_BASE(0x20410c)
#define UI_LEN_I330001_SLIDEMENU_ICON_THEME02_BIN    0xa26

#define UI_BUF_I330001_SLIDEMENU_ICON_THEME03_BIN    UI_ADDR_BASE(0x204b32)
#define UI_LEN_I330001_SLIDEMENU_ICON_THEME03_BIN    0x838

#define UI_BUF_I330001_SLIDEMENU_ICON_THEME04_BIN    UI_ADDR_BASE(0x20536a)
#define UI_LEN_I330001_SLIDEMENU_ICON_THEME04_BIN    0x9e0

#define UI_BUF_I330001_SLIDEMENU_ICON_THEME05_BIN    UI_ADDR_BASE(0x205d4a)
#define UI_LEN_I330001_SLIDEMENU_ICON_THEME05_BIN    0x9f2

#define UI_BUF_I330001_SLIDEMENU_ICON_THEME06_BIN    UI_ADDR_BASE(0x20673c)
#define UI_LEN_I330001_SLIDEMENU_ICON_THEME06_BIN    0xb54

#define UI_BUF_I330001_SLIDEMENU_ICON_THEME07_BIN    UI_ADDR_BASE(0x207290)
#define UI_LEN_I330001_SLIDEMENU_ICON_THEME07_BIN    0xa96

#define UI_BUF_I330001_SLIDEMENU_ICON_THEME08_BIN    UI_ADDR_BASE(0x207d26)
#define UI_LEN_I330001_SLIDEMENU_ICON_THEME08_BIN    0xa65

#define UI_BUF_I330001_SLIDEMENU_ICON_THEME09_BIN    UI_ADDR_BASE(0x20878b)
#define UI_LEN_I330001_SLIDEMENU_ICON_THEME09_BIN    0xa4f

#define UI_BUF_I330001_SLIDEMENU_ICON_VOLUMES00_BIN    UI_ADDR_BASE(0x2091da)
#define UI_LEN_I330001_SLIDEMENU_ICON_VOLUMES00_BIN    0x945

#define UI_BUF_I330001_SLIDEMENU_ICON_VOLUMES01_BIN    UI_ADDR_BASE(0x209b1f)
#define UI_LEN_I330001_SLIDEMENU_ICON_VOLUMES01_BIN    0xa1c

#define UI_BUF_I330001_SLIDEMENU_ICON_BATT_00_BIN    UI_ADDR_BASE(0x20a53b)
#define UI_LEN_I330001_SLIDEMENU_ICON_BATT_00_BIN    0x149

#define UI_BUF_I330001_SLIDEMENU_ICON_BATT_01_BIN    UI_ADDR_BASE(0x20a684)
#define UI_LEN_I330001_SLIDEMENU_ICON_BATT_01_BIN    0x1a1

#define UI_BUF_I330001_SLIDEMENU_ICON_BATT_02_BIN    UI_ADDR_BASE(0x20a825)
#define UI_LEN_I330001_SLIDEMENU_ICON_BATT_02_BIN    0x1a1

#define UI_BUF_I330001_SLIDEMENU_ICON_BATT_03_BIN    UI_ADDR_BASE(0x20a9c6)
#define UI_LEN_I330001_SLIDEMENU_ICON_BATT_03_BIN    0x1a1

#define UI_BUF_I330001_SLIDEMENU_ICON_BATT_04_BIN    UI_ADDR_BASE(0x20ab67)
#define UI_LEN_I330001_SLIDEMENU_ICON_BATT_04_BIN    0x199

#define UI_BUF_I330001_SLIDEMENU_ICON_CONNECT_FRAME_1390_BIN    UI_ADDR_BASE(0x20ad00)
#define UI_LEN_I330001_SLIDEMENU_ICON_CONNECT_FRAME_1390_BIN    0x1a1

#define UI_BUF_I330001_SLIDEMENU_ICON_CONNECT_GROUP_899_BIN    UI_ADDR_BASE(0x20aea1)
#define UI_LEN_I330001_SLIDEMENU_ICON_CONNECT_GROUP_899_BIN    0x1a1

#define UI_BUF_I330001_SLIDEMENU_ICON_TELEPHONE_FRAME_1389_BIN    UI_ADDR_BASE(0x20b042)
#define UI_LEN_I330001_SLIDEMENU_ICON_TELEPHONE_FRAME_1389_BIN    0x13e

#define UI_BUF_I330001_SLIDEMENU_ICON_TELEPHONE_GROUP_898_BIN    UI_ADDR_BASE(0x20b180)
#define UI_LEN_I330001_SLIDEMENU_ICON_TELEPHONE_GROUP_898_BIN    0x13e

#define UI_BUF_I330001_SPORT_BTN_CLOSE_BIN         UI_ADDR_BASE(0x20b2be)
#define UI_LEN_I330001_SPORT_BTN_CLOSE_BIN         0x9ea

#define UI_BUF_I330001_SPORT_BTN_PLAY_BIN          UI_ADDR_BASE(0x20bca8)
#define UI_LEN_I330001_SPORT_BTN_PLAY_BIN          0x945

#define UI_BUF_I330001_SPORT_BTN_PUSED_BIN         UI_ADDR_BASE(0x20c5ed)
#define UI_LEN_I330001_SPORT_BTN_PUSED_BIN         0xb06

#define UI_BUF_I330001_SPORT_COUNTDOWN_01_BIN      UI_ADDR_BASE(0x20d0f3)
#define UI_LEN_I330001_SPORT_COUNTDOWN_01_BIN      0x83e

#define UI_BUF_I330001_SPORT_COUNTDOWN_02_BIN      UI_ADDR_BASE(0x20d931)
#define UI_LEN_I330001_SPORT_COUNTDOWN_02_BIN      0x942

#define UI_BUF_I330001_SPORT_COUNTDOWN_03_BIN      UI_ADDR_BASE(0x20e273)
#define UI_LEN_I330001_SPORT_COUNTDOWN_03_BIN      0x9ff

#define UI_BUF_I330001_SPORT_ICON_00_PAOBU_BIN     UI_ADDR_BASE(0x20ec72)
#define UI_LEN_I330001_SPORT_ICON_00_PAOBU_BIN     0x97a

#define UI_BUF_I330001_SPORT_ICON_01_QIXING_BIN    UI_ADDR_BASE(0x20f5ec)
#define UI_LEN_I330001_SPORT_ICON_01_QIXING_BIN    0xea4

#define UI_BUF_I330001_SPORT_ICON_02_TIAOSHEN_BIN    UI_ADDR_BASE(0x210490)
#define UI_LEN_I330001_SPORT_ICON_02_TIAOSHEN_BIN    0xc36

#define UI_BUF_I330001_SPORT_ICON_03_YOUYONG_BIN    UI_ADDR_BASE(0x2110c6)
#define UI_LEN_I330001_SPORT_ICON_03_YOUYONG_BIN    0xb16

#define UI_BUF_I330001_SPORT_ICON_04_YUMAOQIU_BIN    UI_ADDR_BASE(0x211bdc)
#define UI_LEN_I330001_SPORT_ICON_04_YUMAOQIU_BIN    0xae2

#define UI_BUF_I330001_SPORT_ICON_05_PINGPANGQIU_BIN    UI_ADDR_BASE(0x2126be)
#define UI_LEN_I330001_SPORT_ICON_05_PINGPANGQIU_BIN    0xa66

#define UI_BUF_I330001_SPORT_ICON_06_WANGQIU_BIN    UI_ADDR_BASE(0x213124)
#define UI_LEN_I330001_SPORT_ICON_06_WANGQIU_BIN    0xbb6

#define UI_BUF_I330001_SPORT_ICON_07_PASHAN_BIN    UI_ADDR_BASE(0x213cda)
#define UI_LEN_I330001_SPORT_ICON_07_PASHAN_BIN    0xb6c

#define UI_BUF_I330001_SPORT_ICON_08_TUBU_BIN      UI_ADDR_BASE(0x214846)
#define UI_LEN_I330001_SPORT_ICON_08_TUBU_BIN      0xad3

#define UI_BUF_I330001_SPORT_ICON_09_LANQIU_BIN    UI_ADDR_BASE(0x215319)
#define UI_LEN_I330001_SPORT_ICON_09_LANQIU_BIN    0xb57

#define UI_BUF_I330001_SPORT_ICON_10_ZUQIU_BIN     UI_ADDR_BASE(0x215e70)
#define UI_LEN_I330001_SPORT_ICON_10_ZUQIU_BIN     0xad4

#define UI_BUF_I330001_SPORT_ICON_11_BANGQIU_BIN    UI_ADDR_BASE(0x216944)
#define UI_LEN_I330001_SPORT_ICON_11_BANGQIU_BIN    0x9b1

#define UI_BUF_I330001_SPORT_ICON_12_PAIQIU_BIN    UI_ADDR_BASE(0x2172f5)
#define UI_LEN_I330001_SPORT_ICON_12_PAIQIU_BIN    0xa60

#define UI_BUF_I330001_SPORT_ICON_13_BANQIU_BIN    UI_ADDR_BASE(0x217d55)
#define UI_LEN_I330001_SPORT_ICON_13_BANQIU_BIN    0x941

#define UI_BUF_I330001_SPORT_ICON_14_GANLANQIU_BIN    UI_ADDR_BASE(0x218696)
#define UI_LEN_I330001_SPORT_ICON_14_GANLANQIU_BIN    0x9cb

#define UI_BUF_I330001_SPORT_ICON_15_QUGUNQIU_BIN    UI_ADDR_BASE(0x219061)
#define UI_LEN_I330001_SPORT_ICON_15_QUGUNQIU_BIN    0xa3d

#define UI_BUF_I330001_SPORT_ICON_16_TIAOWU_BIN    UI_ADDR_BASE(0x219a9e)
#define UI_LEN_I330001_SPORT_ICON_16_TIAOWU_BIN    0x8dd

#define UI_BUF_I330001_SPORT_ICON_17_DONGGANDANCHE_BIN    UI_ADDR_BASE(0x21a37b)
#define UI_LEN_I330001_SPORT_ICON_17_DONGGANDANCHE_BIN    0xdb9

#define UI_BUF_I330001_SPORT_ICON_18_YUJIA_BIN     UI_ADDR_BASE(0x21b134)
#define UI_LEN_I330001_SPORT_ICON_18_YUJIA_BIN     0x93c

#define UI_BUF_I330001_SPORT_ICON_19_YANGWOQIZUO_BIN    UI_ADDR_BASE(0x21ba70)
#define UI_LEN_I330001_SPORT_ICON_19_YANGWOQIZUO_BIN    0x791

#define UI_BUF_I330001_SPORT_ICON_20_PAOBUJI_BIN    UI_ADDR_BASE(0x21c201)
#define UI_LEN_I330001_SPORT_ICON_20_PAOBUJI_BIN    0xb58

#define UI_BUF_I330001_SPORT_ICON_21_TICAO_BIN     UI_ADDR_BASE(0x21cd59)
#define UI_LEN_I330001_SPORT_ICON_21_TICAO_BIN     0x857

#define UI_BUF_I330001_SPORT_ICON_22_HUACHUAN_BIN    UI_ADDR_BASE(0x21d5b0)
#define UI_LEN_I330001_SPORT_ICON_22_HUACHUAN_BIN    0xf05

#define UI_BUF_I330001_SPORT_ICON_23_KAIHETIAO_BIN    UI_ADDR_BASE(0x21e4b5)
#define UI_LEN_I330001_SPORT_ICON_23_KAIHETIAO_BIN    0xa16

#define UI_BUF_I330001_SPORT_ICON_24_ZIYOUXUNLIAN_BIN    UI_ADDR_BASE(0x21eecb)
#define UI_LEN_I330001_SPORT_ICON_24_ZIYOUXUNLIAN_BIN    0x921

#define UI_BUF_I330001_SPORT_ICON_25_CAIDAN_BIN    UI_ADDR_BASE(0x21f7ec)
#define UI_LEN_I330001_SPORT_ICON_25_CAIDAN_BIN    0x6fa

#define UI_BUF_I330001_WEATHER_BG_BIN              UI_ADDR_BASE(0x21fee6)
#define UI_LEN_I330001_WEATHER_BG_BIN              0x8405

#define UI_BUF_I330001_WEATHER_DC_BIN              UI_ADDR_BASE(0x2282eb)
#define UI_LEN_I330001_WEATHER_DC_BIN              0x364

#define UI_BUF_I330001_WEATHER_DF_BIN              UI_ADDR_BASE(0x22864f)
#define UI_LEN_I330001_WEATHER_DF_BIN              0x2b4

#define UI_BUF_I330001_WEATHER_NUM_BIN             UI_ADDR_BASE(0x228903)
#define UI_LEN_I330001_WEATHER_NUM_BIN             0x7262

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_00_BIN    UI_ADDR_BASE(0x22fb65)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_00_BIN    0x1289

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_01_BIN    UI_ADDR_BASE(0x230dee)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_01_BIN    0x162b

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_02_BIN    UI_ADDR_BASE(0x232419)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_02_BIN    0x11bd

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_03_BIN    UI_ADDR_BASE(0x2335d6)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_03_BIN    0xe1e

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_04_BIN    UI_ADDR_BASE(0x2343f4)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_04_BIN    0x13aa

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_05_BIN    UI_ADDR_BASE(0x23579e)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_05_BIN    0x14be

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_06_BIN    UI_ADDR_BASE(0x236c5c)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_06_BIN    0x16f7

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_07_BIN    UI_ADDR_BASE(0x238353)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_07_BIN    0x108f

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_08_BIN    UI_ADDR_BASE(0x2393e2)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_08_BIN    0x12ca

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_09_BIN    UI_ADDR_BASE(0x23a6ac)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_09_BIN    0x113a

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_10_BIN    UI_ADDR_BASE(0x23b7e6)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_10_BIN    0x13b3

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_11_BIN    UI_ADDR_BASE(0x23cb99)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_11_BIN    0x1437

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_12_BIN    UI_ADDR_BASE(0x23dfd0)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_12_BIN    0x1163

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_13_BIN    UI_ADDR_BASE(0x23f133)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_13_BIN    0x1190

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_14_BIN    UI_ADDR_BASE(0x2402c3)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_14_BIN    0x1229

#define UI_BUF_I330001_WEATHER_ICON_WEATHER_15_BIN    UI_ADDR_BASE(0x2414ec)
#define UI_LEN_I330001_WEATHER_ICON_WEATHER_15_BIN    0x12a2

#define UI_BUF_ICON_ACTIVITY_BIN                   UI_ADDR_BASE(0x24278e)
#define UI_LEN_ICON_ACTIVITY_BIN                   0x1026

#define UI_BUF_ICON_ADDRESS_BOOK_BIN               UI_ADDR_BASE(0x2437b4)
#define UI_LEN_ICON_ADDRESS_BOOK_BIN               0xbd1

#define UI_BUF_ICON_ALARM_CLOCK_BIN                UI_ADDR_BASE(0x244385)
#define UI_LEN_ICON_ALARM_CLOCK_BIN                0xbd3

#define UI_BUF_ICON_ALIPAY_BIN                     UI_ADDR_BASE(0x244f58)
#define UI_LEN_ICON_ALIPAY_BIN                     0xba5

#define UI_BUF_ICON_ALTITUDE_BIN                   UI_ADDR_BASE(0x245afd)
#define UI_LEN_ICON_ALTITUDE_BIN                   0xd34

#define UI_BUF_ICON_BLOODSUGAR_BIN                 UI_ADDR_BASE(0x246831)
#define UI_LEN_ICON_BLOODSUGAR_BIN                 0xba3

#define UI_BUF_ICON_BLOOD_OXYGEN_BIN               UI_ADDR_BASE(0x2473d4)
#define UI_LEN_ICON_BLOOD_OXYGEN_BIN               0xcd1

#define UI_BUF_ICON_BLOOD_PRESSURE_BIN             UI_ADDR_BASE(0x2480a5)
#define UI_LEN_ICON_BLOOD_PRESSURE_BIN             0xbf2

#define UI_BUF_ICON_BREATHE_BIN                    UI_ADDR_BASE(0x248c97)
#define UI_LEN_ICON_BREATHE_BIN                    0x9e7

#define UI_BUF_ICON_CALCULATOR_BIN                 UI_ADDR_BASE(0x24967e)
#define UI_LEN_ICON_CALCULATOR_BIN                 0xe5d

#define UI_BUF_ICON_CALENDAR_BIN                   UI_ADDR_BASE(0x24a4db)
#define UI_LEN_ICON_CALENDAR_BIN                   0xb03

#define UI_BUF_ICON_CALL_BIN                       UI_ADDR_BASE(0x24afde)
#define UI_LEN_ICON_CALL_BIN                       0x996

#define UI_BUF_ICON_CALL_NUM_BIN                   UI_ADDR_BASE(0x24b974)
#define UI_LEN_ICON_CALL_NUM_BIN                   0x91f

#define UI_BUF_ICON_CAMERA_BIN                     UI_ADDR_BASE(0x24c293)
#define UI_LEN_ICON_CAMERA_BIN                     0xd46

#define UI_BUF_ICON_CLOCK_BIN                      UI_ADDR_BASE(0x24cfd9)
#define UI_LEN_ICON_CLOCK_BIN                      0xac2

#define UI_BUF_ICON_CLOCK_BG_BIN                   UI_ADDR_BASE(0x24da9b)
#define UI_LEN_ICON_CLOCK_BG_BIN                   0x792

#define UI_BUF_ICON_CLOCK_H_BIN                    UI_ADDR_BASE(0x24e22d)
#define UI_LEN_ICON_CLOCK_H_BIN                    0xa0

#define UI_BUF_ICON_CLOCK_M_BIN                    UI_ADDR_BASE(0x24e2cd)
#define UI_LEN_ICON_CLOCK_M_BIN                    0xc9

#define UI_BUF_ICON_CLOCK_S_BIN                    UI_ADDR_BASE(0x24e396)
#define UI_LEN_ICON_CLOCK_S_BIN                    0x103

#define UI_BUF_ICON_COMPASS_BIN                    UI_ADDR_BASE(0x24e499)
#define UI_LEN_ICON_COMPASS_BIN                    0xe3e

#define UI_BUF_ICON_CONNECT_PHONE_BIN              UI_ADDR_BASE(0x24f2d7)
#define UI_LEN_ICON_CONNECT_PHONE_BIN              0xb56

#define UI_BUF_ICON_FINDPHONE_BIN                  UI_ADDR_BASE(0x24fe2d)
#define UI_LEN_ICON_FINDPHONE_BIN                  0xcd7

#define UI_BUF_ICON_FLASHLIGHT_BIN                 UI_ADDR_BASE(0x250b04)
#define UI_LEN_ICON_FLASHLIGHT_BIN                 0xc04

#define UI_BUF_ICON_GAME_BIN                       UI_ADDR_BASE(0x251708)
#define UI_LEN_ICON_GAME_BIN                       0xd73

#define UI_BUF_ICON_HEART_RATE_BIN                 UI_ADDR_BASE(0x25247b)
#define UI_LEN_ICON_HEART_RATE_BIN                 0xb81

#define UI_BUF_ICON_LANGUAGE_BIN                   UI_ADDR_BASE(0x252ffc)
#define UI_LEN_ICON_LANGUAGE_BIN                   0x1048

#define UI_BUF_ICON_LIGHT_BIN                      UI_ADDR_BASE(0x254044)
#define UI_LEN_ICON_LIGHT_BIN                      0xd8a

#define UI_BUF_ICON_MAP_BIN                        UI_ADDR_BASE(0x254dce)
#define UI_LEN_ICON_MAP_BIN                        0xd5c

#define UI_BUF_ICON_MENU_BIN                       UI_ADDR_BASE(0x255b2a)
#define UI_LEN_ICON_MENU_BIN                       0xa62

#define UI_BUF_ICON_MESSAGE_BIN                    UI_ADDR_BASE(0x25658c)
#define UI_LEN_ICON_MESSAGE_BIN                    0x9cb

#define UI_BUF_ICON_MUSIC_BIN                      UI_ADDR_BASE(0x256f57)
#define UI_LEN_ICON_MUSIC_BIN                      0xb1a

#define UI_BUF_ICON_OFF_BIN                        UI_ADDR_BASE(0x257a71)
#define UI_LEN_ICON_OFF_BIN                        0xd03

#define UI_BUF_ICON_PRESSURE_BIN                   UI_ADDR_BASE(0x258774)
#define UI_LEN_ICON_PRESSURE_BIN                   0x7ee

#define UI_BUF_ICON_RESTART_BIN                    UI_ADDR_BASE(0x258f62)
#define UI_LEN_ICON_RESTART_BIN                    0xc3e

#define UI_BUF_ICON_RESTORE_FACTORY_BIN            UI_ADDR_BASE(0x259ba0)
#define UI_LEN_ICON_RESTORE_FACTORY_BIN            0xb71

#define UI_BUF_ICON_SCAN_BIN                       UI_ADDR_BASE(0x25a711)
#define UI_LEN_ICON_SCAN_BIN                       0xa5b

#define UI_BUF_ICON_SETTING_BIN                    UI_ADDR_BASE(0x25b16c)
#define UI_LEN_ICON_SETTING_BIN                    0xb12

#define UI_BUF_ICON_SLEEP_BIN                      UI_ADDR_BASE(0x25bc7e)
#define UI_LEN_ICON_SLEEP_BIN                      0xa54

#define UI_BUF_ICON_SPORT_BIN                      UI_ADDR_BASE(0x25c6d2)
#define UI_LEN_ICON_SPORT_BIN                      0xb55

#define UI_BUF_ICON_STEP_BIN                       UI_ADDR_BASE(0x25d227)
#define UI_LEN_ICON_STEP_BIN                       0xb33

#define UI_BUF_ICON_STOPWATCH_BIN                  UI_ADDR_BASE(0x25dd5a)
#define UI_LEN_ICON_STOPWATCH_BIN                  0xaac

#define UI_BUF_ICON_TIMER_BIN                      UI_ADDR_BASE(0x25e806)
#define UI_LEN_ICON_TIMER_BIN                      0xdcc

#define UI_BUF_ICON_VOICE_BIN                      UI_ADDR_BASE(0x25f5d2)
#define UI_LEN_ICON_VOICE_BIN                      0xdcf

#define UI_BUF_ICON_VOLUME_BIN                     UI_ADDR_BASE(0x2603a1)
#define UI_LEN_ICON_VOLUME_BIN                     0xb95

#define UI_BUF_ICON_WEATHER_BIN                    UI_ADDR_BASE(0x260f36)
#define UI_LEN_ICON_WEATHER_BIN                    0xb9a

#define UI_BUF_ICON_FOOTBALL_ALARM_CLOCK_BIN       UI_ADDR_BASE(0x261ad0)
#define UI_LEN_ICON_FOOTBALL_ALARM_CLOCK_BIN       0x1576

#define UI_BUF_ICON_FOOTBALL_ALIPAY_BIN            UI_ADDR_BASE(0x263046)
#define UI_LEN_ICON_FOOTBALL_ALIPAY_BIN            0x16ed

#define UI_BUF_ICON_FOOTBALL_BG_BIN                UI_ADDR_BASE(0x264733)
#define UI_LEN_ICON_FOOTBALL_BG_BIN                0xfd1b

#define UI_BUF_ICON_FOOTBALL_BLOOD_OXYGEN_BIN      UI_ADDR_BASE(0x27444e)
#define UI_LEN_ICON_FOOTBALL_BLOOD_OXYGEN_BIN      0x1553

#define UI_BUF_ICON_FOOTBALL_CALCULATOR_BIN        UI_ADDR_BASE(0x2759a1)
#define UI_LEN_ICON_FOOTBALL_CALCULATOR_BIN        0x14d7

#define UI_BUF_ICON_FOOTBALL_CALENDAR_BIN          UI_ADDR_BASE(0x276e78)
#define UI_LEN_ICON_FOOTBALL_CALENDAR_BIN          0x1529

#define UI_BUF_ICON_FOOTBALL_CALL_BIN              UI_ADDR_BASE(0x2783a1)
#define UI_LEN_ICON_FOOTBALL_CALL_BIN              0x1501

#define UI_BUF_ICON_FOOTBALL_COMPASS_BIN           UI_ADDR_BASE(0x2798a2)
#define UI_LEN_ICON_FOOTBALL_COMPASS_BIN           0x17bc

#define UI_BUF_ICON_FOOTBALL_FLASHLIGHT_BIN        UI_ADDR_BASE(0x27b05e)
#define UI_LEN_ICON_FOOTBALL_FLASHLIGHT_BIN        0x12fd

#define UI_BUF_ICON_FOOTBALL_GAME_BIN              UI_ADDR_BASE(0x27c35b)
#define UI_LEN_ICON_FOOTBALL_GAME_BIN              0x14af

#define UI_BUF_ICON_FOOTBALL_HEART_RATE_BIN        UI_ADDR_BASE(0x27d80a)
#define UI_LEN_ICON_FOOTBALL_HEART_RATE_BIN        0x15fd

#define UI_BUF_ICON_FOOTBALL_LANGUAGE_BIN          UI_ADDR_BASE(0x27ee07)
#define UI_LEN_ICON_FOOTBALL_LANGUAGE_BIN          0x1d3a

#define UI_BUF_ICON_FOOTBALL_MAP_BIN               UI_ADDR_BASE(0x280b41)
#define UI_LEN_ICON_FOOTBALL_MAP_BIN               0x169a

#define UI_BUF_ICON_FOOTBALL_MUSIC_BIN             UI_ADDR_BASE(0x2821db)
#define UI_LEN_ICON_FOOTBALL_MUSIC_BIN             0x1526

#define UI_BUF_ICON_FOOTBALL_SETTING_BIN           UI_ADDR_BASE(0x283701)
#define UI_LEN_ICON_FOOTBALL_SETTING_BIN           0x1689

#define UI_BUF_ICON_FOOTBALL_SLEEP_BIN             UI_ADDR_BASE(0x284d8a)
#define UI_LEN_ICON_FOOTBALL_SLEEP_BIN             0x1426

#define UI_BUF_ICON_FOOTBALL_SPORT_BIN             UI_ADDR_BASE(0x2861b0)
#define UI_LEN_ICON_FOOTBALL_SPORT_BIN             0x1370

#define UI_BUF_ICON_FOOTBALL_STOPWATCH_BIN         UI_ADDR_BASE(0x287520)
#define UI_LEN_ICON_FOOTBALL_STOPWATCH_BIN         0x1537

#define UI_BUF_ICON_FOOTBALL_STYLE_BIN             UI_ADDR_BASE(0x288a57)
#define UI_LEN_ICON_FOOTBALL_STYLE_BIN             0x113a

#define UI_BUF_ICON_FOOTBALL_TIMER_BIN             UI_ADDR_BASE(0x289b91)
#define UI_LEN_ICON_FOOTBALL_TIMER_BIN             0x1310

#define UI_BUF_ICON_FOOTBALL_VOLUME_BIN            UI_ADDR_BASE(0x28aea1)
#define UI_LEN_ICON_FOOTBALL_VOLUME_BIN            0x1521

#define UI_BUF_ICON_FOOTBALL_WEATHER_BIN           UI_ADDR_BASE(0x28c3c2)
#define UI_LEN_ICON_FOOTBALL_WEATHER_BIN           0x150e

#define UI_BUF_LONG_PRESS_OFF_BIN                  UI_ADDR_BASE(0x28d8d0)
#define UI_LEN_LONG_PRESS_OFF_BIN                  0x988

#define UI_BUF_LONG_PRESS_RESTART_BIN              UI_ADDR_BASE(0x28e258)
#define UI_LEN_LONG_PRESS_RESTART_BIN              0x8c3

#define UI_BUF_LONG_PRESS_SOS_BIN                  UI_ADDR_BASE(0x28eb1b)
#define UI_LEN_LONG_PRESS_SOS_BIN                  0xb17

#define UI_BUF_MENU_GEAR_BIN                       UI_ADDR_BASE(0x28f632)
#define UI_LEN_MENU_GEAR_BIN                       0x6b3d

#define UI_BUF_MENUSTYLE_CUM_GRID_BIN              UI_ADDR_BASE(0x29616f)
#define UI_LEN_MENUSTYLE_CUM_GRID_BIN              0x389a

#define UI_BUF_MENUSTYLE_CUM_SUDOKU_BIN            UI_ADDR_BASE(0x299a09)
#define UI_LEN_MENUSTYLE_CUM_SUDOKU_BIN            0x2ff0

#define UI_BUF_MENUSTYLE_DISK_BIN                  UI_ADDR_BASE(0x29c9f9)
#define UI_LEN_MENUSTYLE_DISK_BIN                  0x2a2c

#define UI_BUF_MENUSTYLE_FOOTBALL_BIN              UI_ADDR_BASE(0x29f425)
#define UI_LEN_MENUSTYLE_FOOTBALL_BIN              0x2f0f

#define UI_BUF_MENUSTYLE_GRID_BIN                  UI_ADDR_BASE(0x2a2334)
#define UI_LEN_MENUSTYLE_GRID_BIN                  0x3bd1

#define UI_BUF_MENUSTYLE_HEXAGON_BIN               UI_ADDR_BASE(0x2a5f05)
#define UI_LEN_MENUSTYLE_HEXAGON_BIN               0x3314

#define UI_BUF_MENUSTYLE_HONEYCOMB_BIN             UI_ADDR_BASE(0x2a9219)
#define UI_LEN_MENUSTYLE_HONEYCOMB_BIN             0x3bfe

#define UI_BUF_MENUSTYLE_KALEIDOSCOPE_BIN          UI_ADDR_BASE(0x2ace17)
#define UI_LEN_MENUSTYLE_KALEIDOSCOPE_BIN          0x32ca

#define UI_BUF_MENUSTYLE_LIST_BIN                  UI_ADDR_BASE(0x2b00e1)
#define UI_LEN_MENUSTYLE_LIST_BIN                  0x2278

#define UI_BUF_MENUSTYLE_LIST_FOURGRID_BIN         UI_ADDR_BASE(0x2b2359)
#define UI_LEN_MENUSTYLE_LIST_FOURGRID_BIN         0x2dac

#define UI_BUF_MENUSTYLE_RING_BIN                  UI_ADDR_BASE(0x2b5105)
#define UI_LEN_MENUSTYLE_RING_BIN                  0x38d7

#define UI_BUF_MENUSTYLE_SKYRER_BIN                UI_ADDR_BASE(0x2b89dc)
#define UI_LEN_MENUSTYLE_SKYRER_BIN                0x3648

#define UI_BUF_MENUSTYLE_SUDOKU_BIN                UI_ADDR_BASE(0x2bc024)
#define UI_LEN_MENUSTYLE_SUDOKU_BIN                0x2edd

#define UI_BUF_MENUSTYLE_WATERFALL_BIN             UI_ADDR_BASE(0x2bef01)
#define UI_LEN_MENUSTYLE_WATERFALL_BIN             0x3a25

#define UI_BUF_MSG_ICON_FACEBOOK_BIN               UI_ADDR_BASE(0x2c2926)
#define UI_LEN_MSG_ICON_FACEBOOK_BIN               0x14d9

#define UI_BUF_MSG_ICON_FLICKR_BIN                 UI_ADDR_BASE(0x2c3dff)
#define UI_LEN_MSG_ICON_FLICKR_BIN                 0x906

#define UI_BUF_MSG_ICON_GMAIL_BIN                  UI_ADDR_BASE(0x2c4705)
#define UI_LEN_MSG_ICON_GMAIL_BIN                  0xbe9

#define UI_BUF_MSG_ICON_GOOGLEPLUS_BIN             UI_ADDR_BASE(0x2c52ee)
#define UI_LEN_MSG_ICON_GOOGLEPLUS_BIN             0xc91

#define UI_BUF_MSG_ICON_HANGOUTS_BIN               UI_ADDR_BASE(0x2c5f7f)
#define UI_LEN_MSG_ICON_HANGOUTS_BIN               0x1611

#define UI_BUF_MSG_ICON_INS_BIN                    UI_ADDR_BASE(0x2c7590)
#define UI_LEN_MSG_ICON_INS_BIN                    0x1491

#define UI_BUF_MSG_ICON_KAKAO_BIN                  UI_ADDR_BASE(0x2c8a21)
#define UI_LEN_MSG_ICON_KAKAO_BIN                  0xfa1

#define UI_BUF_MSG_ICON_LINE_BIN                   UI_ADDR_BASE(0x2c99c2)
#define UI_LEN_MSG_ICON_LINE_BIN                   0xca3

#define UI_BUF_MSG_ICON_LINK_BIN                   UI_ADDR_BASE(0x2ca665)
#define UI_LEN_MSG_ICON_LINK_BIN                   0xbf9

#define UI_BUF_MSG_ICON_MESSAGE_BIN                UI_ADDR_BASE(0x2cb25e)
#define UI_LEN_MSG_ICON_MESSAGE_BIN                0x12b4

#define UI_BUF_MSG_ICON_MESSENGER_BIN              UI_ADDR_BASE(0x2cc512)
#define UI_LEN_MSG_ICON_MESSENGER_BIN              0xddb

#define UI_BUF_MSG_ICON_OTHER_BIN                  UI_ADDR_BASE(0x2cd2ed)
#define UI_LEN_MSG_ICON_OTHER_BIN                  0xc89

#define UI_BUF_MSG_ICON_PAYTM_BIN                  UI_ADDR_BASE(0x2cdf76)
#define UI_LEN_MSG_ICON_PAYTM_BIN                  0xb33

#define UI_BUF_MSG_ICON_PINTEREST_BIN              UI_ADDR_BASE(0x2ceaa9)
#define UI_LEN_MSG_ICON_PINTEREST_BIN              0xd25

#define UI_BUF_MSG_ICON_QQ_BIN                     UI_ADDR_BASE(0x2cf7ce)
#define UI_LEN_MSG_ICON_QQ_BIN                     0xc10

#define UI_BUF_MSG_ICON_SKYPE_BIN                  UI_ADDR_BASE(0x2d03de)
#define UI_LEN_MSG_ICON_SKYPE_BIN                  0xc8c

#define UI_BUF_MSG_ICON_SNAPCHAT_BIN               UI_ADDR_BASE(0x2d106a)
#define UI_LEN_MSG_ICON_SNAPCHAT_BIN               0xc8e

#define UI_BUF_MSG_ICON_TELEGRAM_BIN               UI_ADDR_BASE(0x2d1cf8)
#define UI_LEN_MSG_ICON_TELEGRAM_BIN               0xb00

#define UI_BUF_MSG_ICON_TRUECALLER_BIN             UI_ADDR_BASE(0x2d27f8)
#define UI_LEN_MSG_ICON_TRUECALLER_BIN             0xee8

#define UI_BUF_MSG_ICON_TUMBLR_BIN                 UI_ADDR_BASE(0x2d36e0)
#define UI_LEN_MSG_ICON_TUMBLR_BIN                 0xaa6

#define UI_BUF_MSG_ICON_VIBER_BIN                  UI_ADDR_BASE(0x2d4186)
#define UI_LEN_MSG_ICON_VIBER_BIN                  0x1026

#define UI_BUF_MSG_ICON_VKONTAKTE_BIN              UI_ADDR_BASE(0x2d51ac)
#define UI_LEN_MSG_ICON_VKONTAKTE_BIN              0xbbf

#define UI_BUF_MSG_ICON_WECHAT_BIN                 UI_ADDR_BASE(0x2d5d6b)
#define UI_LEN_MSG_ICON_WECHAT_BIN                 0x171c

#define UI_BUF_MSG_ICON_WHATSAPP_BIN               UI_ADDR_BASE(0x2d7487)
#define UI_LEN_MSG_ICON_WHATSAPP_BIN               0x189a

#define UI_BUF_MSG_ICON_X_BIN                      UI_ADDR_BASE(0x2d8d21)
#define UI_LEN_MSG_ICON_X_BIN                      0xc03

#define UI_BUF_MSG_ICON_YOUTUBE_BIN                UI_ADDR_BASE(0x2d9924)
#define UI_LEN_MSG_ICON_YOUTUBE_BIN                0x885

#define UI_BUF_MSG_ICON_ZALO_BIN                   UI_ADDR_BASE(0x2da1a9)
#define UI_LEN_MSG_ICON_ZALO_BIN                   0xd48

#define UI_BUF_MUSIC_NEXT_BIN                      UI_ADDR_BASE(0x2daef1)
#define UI_LEN_MUSIC_NEXT_BIN                      0x4ce

#define UI_BUF_MUSIC_NEXT_CLICK_BIN                UI_ADDR_BASE(0x2db3bf)
#define UI_LEN_MUSIC_NEXT_CLICK_BIN                0x84a

#define UI_BUF_MUSIC_PAUSE_BIN                     UI_ADDR_BASE(0x2dbc09)
#define UI_LEN_MUSIC_PAUSE_BIN                     0xd96

#define UI_BUF_MUSIC_PAUSE_CLICK_BIN               UI_ADDR_BASE(0x2dc99f)
#define UI_LEN_MUSIC_PAUSE_CLICK_BIN               0xd75

#define UI_BUF_MUSIC_PLAY_BIN                      UI_ADDR_BASE(0x2dd714)
#define UI_LEN_MUSIC_PLAY_BIN                      0xb7e

#define UI_BUF_MUSIC_PREV_BIN                      UI_ADDR_BASE(0x2de292)
#define UI_LEN_MUSIC_PREV_BIN                      0x4da

#define UI_BUF_MUSIC_PREV_CLICK_BIN                UI_ADDR_BASE(0x2de76c)
#define UI_LEN_MUSIC_PREV_CLICK_BIN                0x889

#define UI_BUF_MUSIC_VOLUME1_BIN                   UI_ADDR_BASE(0x2deff5)
#define UI_LEN_MUSIC_VOLUME1_BIN                   0x55

#define UI_BUF_MUSIC_VOLUME2_BIN                   UI_ADDR_BASE(0x2df04a)
#define UI_LEN_MUSIC_VOLUME2_BIN                   0x45

#define UI_BUF_MUSIC_VOLUME3_BIN                   UI_ADDR_BASE(0x2df08f)
#define UI_LEN_MUSIC_VOLUME3_BIN                   0x35

#define UI_BUF_MUSIC_VOLUME4_BIN                   UI_ADDR_BASE(0x2df0c4)
#define UI_LEN_MUSIC_VOLUME4_BIN                   0x35

#define UI_BUF_MUSIC_VOLUME5_BIN                   UI_ADDR_BASE(0x2df0f9)
#define UI_LEN_MUSIC_VOLUME5_BIN                   0x45

#define UI_BUF_MUSIC_VOLUME_BG_BIN                 UI_ADDR_BASE(0x2df13e)
#define UI_LEN_MUSIC_VOLUME_BG_BIN                 0x3f

#define UI_BUF_MUSIC_VOLUME_DOWN_BIN               UI_ADDR_BASE(0x2df17d)
#define UI_LEN_MUSIC_VOLUME_DOWN_BIN               0x3d8

#define UI_BUF_MUSIC_VOLUME_DOWN_CLICK_BIN         UI_ADDR_BASE(0x2df555)
#define UI_LEN_MUSIC_VOLUME_DOWN_CLICK_BIN         0x725

#define UI_BUF_MUSIC_VOLUME_UP_BIN                 UI_ADDR_BASE(0x2dfc7a)
#define UI_LEN_MUSIC_VOLUME_UP_BIN                 0x4c4

#define UI_BUF_MUSIC_VOLUME_UP_CLICK_BIN           UI_ADDR_BASE(0x2e013e)
#define UI_LEN_MUSIC_VOLUME_UP_CLICK_BIN           0x7b1

#define UI_BUF_PRESSURE_CHART_BIN                  UI_ADDR_BASE(0x2e08ef)
#define UI_LEN_PRESSURE_CHART_BIN                  0x2308

#define UI_BUF_PRESSURE_EXPLAIN_BIN                UI_ADDR_BASE(0x2e2bf7)
#define UI_LEN_PRESSURE_EXPLAIN_BIN                0x22b

#define UI_BUF_PULLUP_DIALPLATE_BG_BIN             UI_ADDR_BASE(0x2e2e22)
#define UI_LEN_PULLUP_DIALPLATE_BG_BIN             0x1177

#define UI_BUF_PULLUP_HOUR_BIN                     UI_ADDR_BASE(0x2e3f99)
#define UI_LEN_PULLUP_HOUR_BIN                     0xc6

#define UI_BUF_PULLUP_MIN_BIN                      UI_ADDR_BASE(0x2e405f)
#define UI_LEN_PULLUP_MIN_BIN                      0x107

#define UI_BUF_REMIND_ALARM_CLOCK_BIN              UI_ADDR_BASE(0x2e4166)
#define UI_LEN_REMIND_ALARM_CLOCK_BIN              0xca4

#define UI_BUF_REMIND_APP_CONNECTION_BIN           UI_ADDR_BASE(0x2e4e0a)
#define UI_LEN_REMIND_APP_CONNECTION_BIN           0x1583

#define UI_BUF_REMIND_BLUETOOTH_CONNECTION_BIN     UI_ADDR_BASE(0x2e638d)
#define UI_LEN_REMIND_BLUETOOTH_CONNECTION_BIN     0x1755

#define UI_BUF_REMIND_CLOSE_BIN                    UI_ADDR_BASE(0x2e7ae2)
#define UI_LEN_REMIND_CLOSE_BIN                    0x757

#define UI_BUF_REMIND_FINDWATCH_BIN                UI_ADDR_BASE(0x2e8239)
#define UI_LEN_REMIND_FINDWATCH_BIN                0x10c5

#define UI_BUF_REMIND_FIND_WATCH_BIN               UI_ADDR_BASE(0x2e92fe)
#define UI_LEN_REMIND_FIND_WATCH_BIN               0x1bc6

#define UI_BUF_REMIND_GOAL_ACHIEVEMENT_BIN         UI_ADDR_BASE(0x2eaec4)
#define UI_LEN_REMIND_GOAL_ACHIEVEMENT_BIN         0x14ca

#define UI_BUF_REMIND_REMIND_LATER_BIN             UI_ADDR_BASE(0x2ec38e)
#define UI_LEN_REMIND_REMIND_LATER_BIN             0xe0d

#define UI_BUF_REMIND_SEDENTARY_CLOCK_BIN          UI_ADDR_BASE(0x2ed19b)
#define UI_LEN_REMIND_SEDENTARY_CLOCK_BIN          0x8de

#define UI_BUF_REMIND_SLEEPING_CLOCK_BIN           UI_ADDR_BASE(0x2eda79)
#define UI_LEN_REMIND_SLEEPING_CLOCK_BIN           0xecd

#define UI_BUF_REMIND_WATER_CLOCK_BIN              UI_ADDR_BASE(0x2ee946)
#define UI_LEN_REMIND_WATER_CLOCK_BIN              0xacf

#define UI_BUF_SETTING_ABOUT_BIN                   UI_ADDR_BASE(0x2ef415)
#define UI_LEN_SETTING_ABOUT_BIN                   0x38e

#define UI_BUF_SETTING_ABOUT_CLICK_BIN             UI_ADDR_BASE(0x2ef7a3)
#define UI_LEN_SETTING_ABOUT_CLICK_BIN             0x392

#define UI_BUF_SETTING_BREATHING_SCREEN_BIN        UI_ADDR_BASE(0x2efb35)
#define UI_LEN_SETTING_BREATHING_SCREEN_BIN        0x4cf

#define UI_BUF_SETTING_BREATHING_SCREEN_CLICK_BIN    UI_ADDR_BASE(0x2f0004)
#define UI_LEN_SETTING_BREATHING_SCREEN_CLICK_BIN    0x4a8

#define UI_BUF_SETTING_CALENDAR_BIN                UI_ADDR_BASE(0x2f04ac)
#define UI_LEN_SETTING_CALENDAR_BIN                0x3a3

#define UI_BUF_SETTING_CALENDAR_CLICK_BIN          UI_ADDR_BASE(0x2f084f)
#define UI_LEN_SETTING_CALENDAR_CLICK_BIN          0x394

#define UI_BUF_SETTING_DISTURB_BIN                 UI_ADDR_BASE(0x2f0be3)
#define UI_LEN_SETTING_DISTURB_BIN                 0x3c4

#define UI_BUF_SETTING_DISTURB_CLICK_BIN           UI_ADDR_BASE(0x2f0fa7)
#define UI_LEN_SETTING_DISTURB_CLICK_BIN           0x3ab

#define UI_BUF_SETTING_LANGUAGE_BIN                UI_ADDR_BASE(0x2f1352)
#define UI_LEN_SETTING_LANGUAGE_BIN                0x441

#define UI_BUF_SETTING_LANGUAGE_CLICK_BIN          UI_ADDR_BASE(0x2f1793)
#define UI_LEN_SETTING_LANGUAGE_CLICK_BIN          0x425

#define UI_BUF_SETTING_LIGHT_BIN                   UI_ADDR_BASE(0x2f1bb8)
#define UI_LEN_SETTING_LIGHT_BIN                   0x43e

#define UI_BUF_SETTING_LIGHT_CLICK_BIN             UI_ADDR_BASE(0x2f1ff6)
#define UI_LEN_SETTING_LIGHT_CLICK_BIN             0x437

#define UI_BUF_SETTING_OFF_BIN                     UI_ADDR_BASE(0x2f242d)
#define UI_LEN_SETTING_OFF_BIN                     0x422

#define UI_BUF_SETTING_OFF_CLICK_BIN               UI_ADDR_BASE(0x2f284f)
#define UI_LEN_SETTING_OFF_CLICK_BIN               0x411

#define UI_BUF_SETTING_PASSWORD_BIN                UI_ADDR_BASE(0x2f2c60)
#define UI_LEN_SETTING_PASSWORD_BIN                0x3e4

#define UI_BUF_SETTING_PASSWORD_CLICK_BIN          UI_ADDR_BASE(0x2f3044)
#define UI_LEN_SETTING_PASSWORD_CLICK_BIN          0x3df

#define UI_BUF_SETTING_RESTART_BIN                 UI_ADDR_BASE(0x2f3423)
#define UI_LEN_SETTING_RESTART_BIN                 0x3ea

#define UI_BUF_SETTING_RESTART_CLICK_BIN           UI_ADDR_BASE(0x2f380d)
#define UI_LEN_SETTING_RESTART_CLICK_BIN           0x3db

#define UI_BUF_SETTING_RESTORE_FACTORY_BIN         UI_ADDR_BASE(0x2f3be8)
#define UI_LEN_SETTING_RESTORE_FACTORY_BIN         0x3f3

#define UI_BUF_SETTING_RESTORE_FACTORY_CLICK_BIN    UI_ADDR_BASE(0x2f3fdb)
#define UI_LEN_SETTING_RESTORE_FACTORY_CLICK_BIN    0x3dc

#define UI_BUF_SETTING_SOUND_AND_VIBRATION_BIN     UI_ADDR_BASE(0x2f43b7)
#define UI_LEN_SETTING_SOUND_AND_VIBRATION_BIN     0x390

#define UI_BUF_SETTING_SOUND_AND_VIBRATION_CLICK_BIN    UI_ADDR_BASE(0x2f4747)
#define UI_LEN_SETTING_SOUND_AND_VIBRATION_CLICK_BIN    0x370

#define UI_BUF_SETTING_TIME_BIN                    UI_ADDR_BASE(0x2f4ab7)
#define UI_LEN_SETTING_TIME_BIN                    0x394

#define UI_BUF_SETTING_TIME_CLICK_BIN              UI_ADDR_BASE(0x2f4e4b)
#define UI_LEN_SETTING_TIME_CLICK_BIN              0x38e

#define UI_BUF_SETTING_WRIST_BIN                   UI_ADDR_BASE(0x2f51d9)
#define UI_LEN_SETTING_WRIST_BIN                   0x409

#define UI_BUF_SETTING_WRIST_CLICK_BIN             UI_ADDR_BASE(0x2f55e2)
#define UI_LEN_SETTING_WRIST_CLICK_BIN             0x3e2

#define UI_BUF_SETTING_LIGHT_LIGHT_BIN             UI_ADDR_BASE(0x2f59c4)
#define UI_LEN_SETTING_LIGHT_LIGHT_BIN             0x14ba

#define UI_BUF_SETTING_PASSWORD_7_CLICK_BIN        UI_ADDR_BASE(0x2f6e7e)
#define UI_LEN_SETTING_PASSWORD_7_CLICK_BIN        0x4a8

#define UI_BUF_SETTING_PASSWORD_9_CLICK_BIN        UI_ADDR_BASE(0x2f7326)
#define UI_LEN_SETTING_PASSWORD_9_CLICK_BIN        0x5ee

#define UI_BUF_SETTING_PASSWORD_BG_BIN             UI_ADDR_BASE(0x2f7914)
#define UI_LEN_SETTING_PASSWORD_BG_BIN             0x3ef9

#define UI_BUF_SETTING_PASSWORD_BG_NUM_BIN         UI_ADDR_BASE(0x2fb80d)
#define UI_LEN_SETTING_PASSWORD_BG_NUM_BIN         0x896

#define UI_BUF_SETTING_PASSWORD_DEL_CLICK_BIN      UI_ADDR_BASE(0x2fc0a3)
#define UI_LEN_SETTING_PASSWORD_DEL_CLICK_BIN      0x60d

#define UI_BUF_SETTING_PASSWORD_FRAME_755_BIN      UI_ADDR_BASE(0x2fc6b0)
#define UI_LEN_SETTING_PASSWORD_FRAME_755_BIN      0x5c3

#define UI_BUF_SETTING_PASSWORD_NUM_BIN            UI_ADDR_BASE(0x2fcc73)
#define UI_LEN_SETTING_PASSWORD_NUM_BIN            0x210

#define UI_BUF_SETTING_PASSWORD_OPEN_BIN           UI_ADDR_BASE(0x2fce83)
#define UI_LEN_SETTING_PASSWORD_OPEN_BIN           0x222

#define UI_BUF_SIDEBAR_BG_146_146_BIN              UI_ADDR_BASE(0x2fd0a5)
#define UI_LEN_SIDEBAR_BG_146_146_BIN              0xa82

#define UI_BUF_SIDEBAR_BG_146_146_0_BIN            UI_ADDR_BASE(0x2fdb27)
#define UI_LEN_SIDEBAR_BG_146_146_0_BIN            0xa82

#define UI_BUF_SIDEBAR_BG_146_146_1_BIN            UI_ADDR_BASE(0x2fe5a9)
#define UI_LEN_SIDEBAR_BG_146_146_1_BIN            0xa82

#define UI_BUF_SIDEBAR_BG_308_156_BIN              UI_ADDR_BASE(0x2ff02b)
#define UI_LEN_SIDEBAR_BG_308_156_BIN              0x100e

#define UI_BUF_SIDEBAR_BG_308_156_1_BIN            UI_ADDR_BASE(0x300039)
#define UI_LEN_SIDEBAR_BG_308_156_1_BIN            0x100e

#define UI_BUF_SIDEBAR_BG_308_156_2_BIN            UI_ADDR_BASE(0x301047)
#define UI_LEN_SIDEBAR_BG_308_156_2_BIN            0x100e

#define UI_BUF_SIDEBAR_BG_308_156_3_BIN            UI_ADDR_BASE(0x302055)
#define UI_LEN_SIDEBAR_BG_308_156_3_BIN            0x100e

#define UI_BUF_SIDEBAR_BG_308_156_4_BIN            UI_ADDR_BASE(0x303063)
#define UI_LEN_SIDEBAR_BG_308_156_4_BIN            0x100e

#define UI_BUF_SIDEBAR_DEGREE_BIN                  UI_ADDR_BASE(0x304071)
#define UI_LEN_SIDEBAR_DEGREE_BIN                  0x3ad

#define UI_BUF_SIDEBAR_SLAS_BIN                    UI_ADDR_BASE(0x30441e)
#define UI_LEN_SIDEBAR_SLAS_BIN                    0x1cc

#define UI_BUF_SIDEBAR_TOP_308_50_BIN              UI_ADDR_BASE(0x3045ea)
#define UI_LEN_SIDEBAR_TOP_308_50_BIN              0x429

#define UI_BUF_SLEEP_LIGHT_SLEEP_BIN               UI_ADDR_BASE(0x304a13)
#define UI_LEN_SLEEP_LIGHT_SLEEP_BIN               0x5db

#define UI_BUF_SLEEP_SLEEP_BIN                     UI_ADDR_BASE(0x304fee)
#define UI_LEN_SLEEP_SLEEP_BIN                     0xff1

#define UI_BUF_SMARTSTACK_BG_BIN                   UI_ADDR_BASE(0x305fdf)
#define UI_LEN_SMARTSTACK_BG_BIN                   0x1fc4

#define UI_BUF_SMARTSTACK_DELET_BIN                UI_ADDR_BASE(0x307fa3)
#define UI_LEN_SMARTSTACK_DELET_BIN                0x4bc

#define UI_BUF_SMARTSTACK_NULL_BIN                 UI_ADDR_BASE(0x30845f)
#define UI_LEN_SMARTSTACK_NULL_BIN                 0x5a1

#define UI_BUF_SPORT_BEFORE_EXERCISE_BG_BIN        UI_ADDR_BASE(0x308a00)
#define UI_LEN_SPORT_BEFORE_EXERCISE_BG_BIN        0x115f

#define UI_BUF_SPORT_BEFORE_EXERCISE_FOOTBALL_BIN    UI_ADDR_BASE(0x309b5f)
#define UI_LEN_SPORT_BEFORE_EXERCISE_FOOTBALL_BIN    0xdc5

#define UI_BUF_SPORT_BEFORE_EXERCISE_INDOOR_CYCLING_BIN    UI_ADDR_BASE(0x30a924)
#define UI_LEN_SPORT_BEFORE_EXERCISE_INDOOR_CYCLING_BIN    0x1103

#define UI_BUF_SPORT_BEFORE_EXERCISE_INDOOR_RUNNING_BIN    UI_ADDR_BASE(0x30ba27)
#define UI_LEN_SPORT_BEFORE_EXERCISE_INDOOR_RUNNING_BIN    0x103f

#define UI_BUF_SPORT_BEFORE_EXERCISE_KCAL_BG_BIN    UI_ADDR_BASE(0x30ca66)
#define UI_LEN_SPORT_BEFORE_EXERCISE_KCAL_BG_BIN    0x1a98

#define UI_BUF_SPORT_BEFORE_EXERCISE_KCAL_NUM_BIN    UI_ADDR_BASE(0x30e4fe)
#define UI_LEN_SPORT_BEFORE_EXERCISE_KCAL_NUM_BIN    0xd73

#define UI_BUF_SPORT_BEFORE_EXERCISE_KM_BG_BIN     UI_ADDR_BASE(0x30f271)
#define UI_LEN_SPORT_BEFORE_EXERCISE_KM_BG_BIN     0x1a31

#define UI_BUF_SPORT_BEFORE_EXERCISE_KM_NUM_BIN    UI_ADDR_BASE(0x310ca2)
#define UI_LEN_SPORT_BEFORE_EXERCISE_KM_NUM_BIN    0xd7f

#define UI_BUF_SPORT_BEFORE_EXERCISE_OUTDOOR_CYCLING_BIN    UI_ADDR_BASE(0x311a21)
#define UI_LEN_SPORT_BEFORE_EXERCISE_OUTDOOR_CYCLING_BIN    0x148d

#define UI_BUF_SPORT_BEFORE_EXERCISE_RUN_BIN       UI_ADDR_BASE(0x312eae)
#define UI_LEN_SPORT_BEFORE_EXERCISE_RUN_BIN       0xd0c

#define UI_BUF_SPORT_BEFORE_EXERCISE_STEP_BG_BIN    UI_ADDR_BASE(0x313bba)
#define UI_LEN_SPORT_BEFORE_EXERCISE_STEP_BG_BIN    0x186d

#define UI_BUF_SPORT_BEFORE_EXERCISE_STEP_NUM_BIN    UI_ADDR_BASE(0x315427)
#define UI_LEN_SPORT_BEFORE_EXERCISE_STEP_NUM_BIN    0x1003

#define UI_BUF_SPORT_BEFORE_EXERCISE_SWIM_BIN      UI_ADDR_BASE(0x31642a)
#define UI_LEN_SPORT_BEFORE_EXERCISE_SWIM_BIN      0xda1

#define UI_BUF_SPORT_BEFORE_EXERCISE_TIME_BG_BIN    UI_ADDR_BASE(0x3171cb)
#define UI_LEN_SPORT_BEFORE_EXERCISE_TIME_BG_BIN    0x19c2

#define UI_BUF_SPORT_BEFORE_EXERCISE_TIME_NUM_BIN    UI_ADDR_BASE(0x318b8d)
#define UI_LEN_SPORT_BEFORE_EXERCISE_TIME_NUM_BIN    0xd7d

#define UI_BUF_SPORT_BEFORE_EXERCISE_WALK_BIN      UI_ADDR_BASE(0x31990a)
#define UI_LEN_SPORT_BEFORE_EXERCISE_WALK_BIN      0xce8

#define UI_BUF_SPORT_EXERCISING_1_BIN              UI_ADDR_BASE(0x31a5f2)
#define UI_LEN_SPORT_EXERCISING_1_BIN              0x5c9

#define UI_BUF_SPORT_EXERCISING_2_BIN              UI_ADDR_BASE(0x31abbb)
#define UI_LEN_SPORT_EXERCISING_2_BIN              0xa4a

#define UI_BUF_SPORT_EXERCISING_3_BIN              UI_ADDR_BASE(0x31b605)
#define UI_LEN_SPORT_EXERCISING_3_BIN              0xb57

#define UI_BUF_SPORT_EXERCISING_BG_HR_BIN          UI_ADDR_BASE(0x31c15c)
#define UI_LEN_SPORT_EXERCISING_BG_HR_BIN          0x855

#define UI_BUF_SPORT_EXERCISING_CANCEL_BIN         UI_ADDR_BASE(0x31c9b1)
#define UI_LEN_SPORT_EXERCISING_CANCEL_BIN         0x10a7

#define UI_BUF_SPORT_EXERCISING_DOU2_BIN           UI_ADDR_BASE(0x31da58)
#define UI_LEN_SPORT_EXERCISING_DOU2_BIN           0x1bf

#define UI_BUF_SPORT_EXERCISING_KCAL_BIN           UI_ADDR_BASE(0x31dc17)
#define UI_LEN_SPORT_EXERCISING_KCAL_BIN           0x7b7

#define UI_BUF_SPORT_EXERCISING_KM_BIN             UI_ADDR_BASE(0x31e3ce)
#define UI_LEN_SPORT_EXERCISING_KM_BIN             0x70c

#define UI_BUF_SPORT_EXERCISING_PAUSE_BIN          UI_ADDR_BASE(0x31eada)
#define UI_LEN_SPORT_EXERCISING_PAUSE_BIN          0x10e0

#define UI_BUF_SPORT_EXERCISING_STEP_BIN           UI_ADDR_BASE(0x31fbba)
#define UI_LEN_SPORT_EXERCISING_STEP_BIN           0x50b

#define UI_BUF_SPORT_EXERCISING_TIME_BIN           UI_ADDR_BASE(0x3200c5)
#define UI_LEN_SPORT_EXERCISING_TIME_BIN           0x655

#define UI_BUF_SPORT_ICON_BADMINTON_BIN            UI_ADDR_BASE(0x32071a)
#define UI_LEN_SPORT_ICON_BADMINTON_BIN            0xb04

#define UI_BUF_SPORT_ICON_BASEBALL_BIN             UI_ADDR_BASE(0x32121e)
#define UI_LEN_SPORT_ICON_BASEBALL_BIN             0xa62

#define UI_BUF_SPORT_ICON_BASKETBALL_BIN           UI_ADDR_BASE(0x321c80)
#define UI_LEN_SPORT_ICON_BASKETBALL_BIN           0xb9d

#define UI_BUF_SPORT_ICON_BOATING_BIN              UI_ADDR_BASE(0x32281d)
#define UI_LEN_SPORT_ICON_BOATING_BIN              0xfb0

#define UI_BUF_SPORT_ICON_CLIMBING_BIN             UI_ADDR_BASE(0x3237cd)
#define UI_LEN_SPORT_ICON_CLIMBING_BIN             0xba8

#define UI_BUF_SPORT_ICON_CRICKET_BIN              UI_ADDR_BASE(0x324375)
#define UI_LEN_SPORT_ICON_CRICKET_BIN              0x962

#define UI_BUF_SPORT_ICON_DANCE_BIN                UI_ADDR_BASE(0x324cd7)
#define UI_LEN_SPORT_ICON_DANCE_BIN                0x916

#define UI_BUF_SPORT_ICON_FOOTBALL_BIN             UI_ADDR_BASE(0x3255ed)
#define UI_LEN_SPORT_ICON_FOOTBALL_BIN             0xb24

#define UI_BUF_SPORT_ICON_FREE_TRAINING_BIN        UI_ADDR_BASE(0x326111)
#define UI_LEN_SPORT_ICON_FREE_TRAINING_BIN        0x92a

#define UI_BUF_SPORT_ICON_GYMNASTICS_BIN           UI_ADDR_BASE(0x326a3b)
#define UI_LEN_SPORT_ICON_GYMNASTICS_BIN           0x888

#define UI_BUF_SPORT_ICON_HOCKEY_BIN               UI_ADDR_BASE(0x3272c3)
#define UI_LEN_SPORT_ICON_HOCKEY_BIN               0xa88

#define UI_BUF_SPORT_ICON_JUMPING_JACK_BIN         UI_ADDR_BASE(0x327d4b)
#define UI_LEN_SPORT_ICON_JUMPING_JACK_BIN         0xa20

#define UI_BUF_SPORT_ICON_JUMP_ROPE_BIN            UI_ADDR_BASE(0x32876b)
#define UI_LEN_SPORT_ICON_JUMP_ROPE_BIN            0xc00

#define UI_BUF_SPORT_ICON_RIDE_BIKE_BIN            UI_ADDR_BASE(0x32936b)
#define UI_LEN_SPORT_ICON_RIDE_BIKE_BIN            0xece

#define UI_BUF_SPORT_ICON_RUGBY_BIN                UI_ADDR_BASE(0x32a239)
#define UI_LEN_SPORT_ICON_RUGBY_BIN                0xa71

#define UI_BUF_SPORT_ICON_RUN_BIN                  UI_ADDR_BASE(0x32acaa)
#define UI_LEN_SPORT_ICON_RUN_BIN                  0x9a0

#define UI_BUF_SPORT_ICON_SIT_UP_BIN               UI_ADDR_BASE(0x32b64a)
#define UI_LEN_SPORT_ICON_SIT_UP_BIN               0x78e

#define UI_BUF_SPORT_ICON_SPINNING_BIN             UI_ADDR_BASE(0x32bdd8)
#define UI_LEN_SPORT_ICON_SPINNING_BIN             0xe3e

#define UI_BUF_SPORT_ICON_SWIMMING_BIN             UI_ADDR_BASE(0x32cc16)
#define UI_LEN_SPORT_ICON_SWIMMING_BIN             0xbb4

#define UI_BUF_SPORT_ICON_TABLE_TENNIS_BIN         UI_ADDR_BASE(0x32d7ca)
#define UI_LEN_SPORT_ICON_TABLE_TENNIS_BIN         0xb2e

#define UI_BUF_SPORT_ICON_TENNIS_BIN               UI_ADDR_BASE(0x32e2f8)
#define UI_LEN_SPORT_ICON_TENNIS_BIN               0xbe8

#define UI_BUF_SPORT_ICON_TREADMILL_BIN            UI_ADDR_BASE(0x32eee0)
#define UI_LEN_SPORT_ICON_TREADMILL_BIN            0xb8e

#define UI_BUF_SPORT_ICON_VOLLEYBALL_BIN           UI_ADDR_BASE(0x32fa6e)
#define UI_LEN_SPORT_ICON_VOLLEYBALL_BIN           0xa81

#define UI_BUF_SPORT_ICON_WALKING_BIN              UI_ADDR_BASE(0x3304ef)
#define UI_LEN_SPORT_ICON_WALKING_BIN              0xa9c

#define UI_BUF_SPORT_ICON_YOGA_BIN                 UI_ADDR_BASE(0x330f8b)
#define UI_LEN_SPORT_ICON_YOGA_BIN                 0x968

#define UI_BUF_STOPWATCH_AFRESH_BIN                UI_ADDR_BASE(0x3318f3)
#define UI_LEN_STOPWATCH_AFRESH_BIN                0x833

#define UI_BUF_STOPWATCH_AFRESH_CLICK_BIN          UI_ADDR_BASE(0x332126)
#define UI_LEN_STOPWATCH_AFRESH_CLICK_BIN          0x81e

#define UI_BUF_STOPWATCH_NUM1_12_18_BIN            UI_ADDR_BASE(0x332944)
#define UI_LEN_STOPWATCH_NUM1_12_18_BIN            0x17ee

#define UI_BUF_STOPWATCH_NUM1_12_18_CLICK_BIN      UI_ADDR_BASE(0x334132)
#define UI_LEN_STOPWATCH_NUM1_12_18_CLICK_BIN      0x17ef

#define UI_BUF_STOPWATCH_NUM1_16_24_BIN            UI_ADDR_BASE(0x335921)
#define UI_LEN_STOPWATCH_NUM1_16_24_BIN            0x1a28

#define UI_BUF_STOPWATCH_NUM1_16_24_CLICK_BIN      UI_ADDR_BASE(0x337349)
#define UI_LEN_STOPWATCH_NUM1_16_24_CLICK_BIN      0x1a29

#define UI_BUF_STOPWATCH_RECORD_BIN                UI_ADDR_BASE(0x338d72)
#define UI_LEN_STOPWATCH_RECORD_BIN                0x83b

#define UI_BUF_STOPWATCH_RECORD1_BIN               UI_ADDR_BASE(0x3395ad)
#define UI_LEN_STOPWATCH_RECORD1_BIN               0x57b

#define UI_BUF_STOPWATCH_RECORD1_CLICK_BIN         UI_ADDR_BASE(0x339b28)
#define UI_LEN_STOPWATCH_RECORD1_CLICK_BIN         0x56b

#define UI_BUF_STOPWATCH_RECORD_CLICK_BIN          UI_ADDR_BASE(0x33a093)
#define UI_LEN_STOPWATCH_RECORD_CLICK_BIN          0x81b

#define UI_BUF_STYLE_01_BIN                        UI_ADDR_BASE(0x33a8ae)
#define UI_LEN_STYLE_01_BIN                        0x492

#define UI_BUF_STYLE_02_BIN                        UI_ADDR_BASE(0x33ad40)
#define UI_LEN_STYLE_02_BIN                        0x4c6

#define UI_BUF_STYLE_03_BIN                        UI_ADDR_BASE(0x33b206)
#define UI_LEN_STYLE_03_BIN                        0x677

#define UI_BUF_STYLE_04_BIN                        UI_ADDR_BASE(0x33b87d)
#define UI_LEN_STYLE_04_BIN                        0x595

#define UI_BUF_STYLE_05_BIN                        UI_ADDR_BASE(0x33be12)
#define UI_LEN_STYLE_05_BIN                        0x4e6

#define UI_BUF_STYLE_06_BIN                        UI_ADDR_BASE(0x33c2f8)
#define UI_LEN_STYLE_06_BIN                        0x59b

#define UI_BUF_STYLE_07_BIN                        UI_ADDR_BASE(0x33c893)
#define UI_LEN_STYLE_07_BIN                        0x637

#define UI_BUF_STYLE_08_BIN                        UI_ADDR_BASE(0x33ceca)
#define UI_LEN_STYLE_08_BIN                        0x34d

#define UI_BUF_STYLE_09_BIN                        UI_ADDR_BASE(0x33d217)
#define UI_LEN_STYLE_09_BIN                        0x5e0

#define UI_BUF_STYLE_10_BIN                        UI_ADDR_BASE(0x33d7f7)
#define UI_LEN_STYLE_10_BIN                        0x5b2

#define UI_BUF_STYLE_11_BIN                        UI_ADDR_BASE(0x33dda9)
#define UI_LEN_STYLE_11_BIN                        0x4c1

#define UI_BUF_STYLE_12_BIN                        UI_ADDR_BASE(0x33e26a)
#define UI_LEN_STYLE_12_BIN                        0x68d

#define UI_BUF_STYLE_13_BIN                        UI_ADDR_BASE(0x33e8f7)
#define UI_LEN_STYLE_13_BIN                        0x442

#define UI_BUF_STYLE_14_BIN                        UI_ADDR_BASE(0x33ed39)
#define UI_LEN_STYLE_14_BIN                        0x499

#define UI_BUF_TETRIS__S_BJ_START_BIN              UI_ADDR_BASE(0x33f1d2)
#define UI_LEN_TETRIS__S_BJ_START_BIN              0x93bd

#define UI_BUF_TETRIS__S_FRAME_BIN                 UI_ADDR_BASE(0x34858f)
#define UI_LEN_TETRIS__S_FRAME_BIN                 0xa4ed

#define UI_BUF_TETRIS__S_NO_BIN                    UI_ADDR_BASE(0x352a7c)
#define UI_LEN_TETRIS__S_NO_BIN                    0x6e5

#define UI_BUF_TETRIS__S_REMIND_BIN                UI_ADDR_BASE(0x353161)
#define UI_LEN_TETRIS__S_REMIND_BIN                0x9c5

#define UI_BUF_TETRIS__S_START_BIN                 UI_ADDR_BASE(0x353b26)
#define UI_LEN_TETRIS__S_START_BIN                 0x92d

#define UI_BUF_TETRIS__S_SUSPEND_BIN               UI_ADDR_BASE(0x354453)
#define UI_LEN_TETRIS__S_SUSPEND_BIN               0xa35

#define UI_BUF_TETRIS__S_YES_BIN                   UI_ADDR_BASE(0x354e88)
#define UI_LEN_TETRIS__S_YES_BIN                   0x6cb

#define UI_BUF_TETRIS_16_1_BIN                     UI_ADDR_BASE(0x355553)
#define UI_LEN_TETRIS_16_1_BIN                     0x1fe

#define UI_BUF_TETRIS_16_2_BIN                     UI_ADDR_BASE(0x355751)
#define UI_LEN_TETRIS_16_2_BIN                     0x1d1

#define UI_BUF_TETRIS_16_3_BIN                     UI_ADDR_BASE(0x355922)
#define UI_LEN_TETRIS_16_3_BIN                     0x1dc

#define UI_BUF_TETRIS_16_4_BIN                     UI_ADDR_BASE(0x355afe)
#define UI_LEN_TETRIS_16_4_BIN                     0x1de

#define UI_BUF_TETRIS_16_5_BIN                     UI_ADDR_BASE(0x355cdc)
#define UI_LEN_TETRIS_16_5_BIN                     0x1e6

#define UI_BUF_TETRIS_16_6_BIN                     UI_ADDR_BASE(0x355ec2)
#define UI_LEN_TETRIS_16_6_BIN                     0x1f0

#define UI_BUF_TETRIS_BJ_BIN                       UI_ADDR_BASE(0x3560b2)
#define UI_LEN_TETRIS_BJ_BIN                       0x9f68

#define UI_BUF_TETRIS_BZ_BIN                       UI_ADDR_BASE(0x36001a)
#define UI_LEN_TETRIS_BZ_BIN                       0xcbf5

#define UI_BUF_TETRIS_BZ2_BIN                      UI_ADDR_BASE(0x36cc0f)
#define UI_LEN_TETRIS_BZ2_BIN                      0x4bde

#define UI_BUF_TETRIS_FALL_1_BIN                   UI_ADDR_BASE(0x3717ed)
#define UI_LEN_TETRIS_FALL_1_BIN                   0x184

#define UI_BUF_TETRIS_FALL_2_BIN                   UI_ADDR_BASE(0x371971)
#define UI_LEN_TETRIS_FALL_2_BIN                   0x176

#define UI_BUF_TETRIS_FALL_3_BIN                   UI_ADDR_BASE(0x371ae7)
#define UI_LEN_TETRIS_FALL_3_BIN                   0x18b

#define UI_BUF_TETRIS_FALL_4_BIN                   UI_ADDR_BASE(0x371c72)
#define UI_LEN_TETRIS_FALL_4_BIN                   0x186

#define UI_BUF_TETRIS_FALL_5_BIN                   UI_ADDR_BASE(0x371df8)
#define UI_LEN_TETRIS_FALL_5_BIN                   0x180

#define UI_BUF_TETRIS_FALL_6_BIN                   UI_ADDR_BASE(0x371f78)
#define UI_LEN_TETRIS_FALL_6_BIN                   0x180

#define UI_BUF_TETRIS_GAMEOVER_BIN                 UI_ADDR_BASE(0x3720f8)
#define UI_LEN_TETRIS_GAMEOVER_BIN                 0x662d

#define UI_BUF_TETRIS_GAME_TETRIS_BIN              UI_ADDR_BASE(0x378725)
#define UI_LEN_TETRIS_GAME_TETRIS_BIN              0xb941

#define UI_BUF_TETRIS_GAME_TETRIS_ENTER_BIN        UI_ADDR_BASE(0x384066)
#define UI_LEN_TETRIS_GAME_TETRIS_ENTER_BIN        0x9c84

#define UI_BUF_TETRIS_GAME_TETRIS_EXITNOTICE_BIN    UI_ADDR_BASE(0x38dcea)
#define UI_LEN_TETRIS_GAME_TETRIS_EXITNOTICE_BIN    0x36bf

#define UI_BUF_TETRIS_GAME_TETRIS_OVER_BIN         UI_ADDR_BASE(0x3913a9)
#define UI_LEN_TETRIS_GAME_TETRIS_OVER_BIN         0xc1d7

#define UI_BUF_TETRIS_GAME_TETRIS_STOP_BIN         UI_ADDR_BASE(0x39d580)
#define UI_LEN_TETRIS_GAME_TETRIS_STOP_BIN         0xb991

#define UI_BUF_TIMER_AGAIN_BIN                     UI_ADDR_BASE(0x3a8f11)
#define UI_LEN_TIMER_AGAIN_BIN                     0xe43

#define UI_BUF_TIMER_BG_BIN                        UI_ADDR_BASE(0x3a9d54)
#define UI_LEN_TIMER_BG_BIN                        0x792

#define UI_BUF_UPGRADE_ROCKET_BIN                  UI_ADDR_BASE(0x3aa4e6)
#define UI_LEN_UPGRADE_ROCKET_BIN                  0xae2

#define UI_BUF_UPGRADE_ROCKET_BASE_BIN             UI_ADDR_BASE(0x3aafc8)
#define UI_LEN_UPGRADE_ROCKET_BASE_BIN             0xf53

#define UI_BUF_VOICE_320_86_BIN                    UI_ADDR_BASE(0x3abf1b)
#define UI_LEN_VOICE_320_86_BIN                    0x3302

#define UI_BUF_WEATHER_CLOUDY_BIN                  UI_ADDR_BASE(0x3af21d)
#define UI_LEN_WEATHER_CLOUDY_BIN                  0x1c5a

#define UI_BUF_WEATHER_CLOUDY_NIGHT_BIN            UI_ADDR_BASE(0x3b0e77)
#define UI_LEN_WEATHER_CLOUDY_NIGHT_BIN            0x1b14

#define UI_BUF_WEATHER_DRIZZLE_BIN                 UI_ADDR_BASE(0x3b298b)
#define UI_LEN_WEATHER_DRIZZLE_BIN                 0x1e0e

#define UI_BUF_WEATHER_HAZE_BIN                    UI_ADDR_BASE(0x3b4799)
#define UI_LEN_WEATHER_HAZE_BIN                    0xfc2

#define UI_BUF_WEATHER_HEAVY_RAIN_BIN              UI_ADDR_BASE(0x3b575b)
#define UI_LEN_WEATHER_HEAVY_RAIN_BIN              0x1f02

#define UI_BUF_WEATHER_MODERATE_RAIN_BIN           UI_ADDR_BASE(0x3b765d)
#define UI_LEN_WEATHER_MODERATE_RAIN_BIN           0x1df2

#define UI_BUF_WEATHER_OVERCAST_BIN                UI_ADDR_BASE(0x3b944f)
#define UI_LEN_WEATHER_OVERCAST_BIN                0x1cf6

#define UI_BUF_WEATHER_RAINY_BIN                   UI_ADDR_BASE(0x3bb145)
#define UI_LEN_WEATHER_RAINY_BIN                   0x2136

#define UI_BUF_WEATHER_RAINY_NIGHT_BIN             UI_ADDR_BASE(0x3bd27b)
#define UI_LEN_WEATHER_RAINY_NIGHT_BIN             0x1c86

#define UI_BUF_WEATHER_RAINY_SHOWERS_BIN           UI_ADDR_BASE(0x3bef01)
#define UI_LEN_WEATHER_RAINY_SHOWERS_BIN           0x2002

#define UI_BUF_WEATHER_SAND_AND_DUST_BIN           UI_ADDR_BASE(0x3c0f03)
#define UI_LEN_WEATHER_SAND_AND_DUST_BIN           0xfe6

#define UI_BUF_WEATHER_SLEET_BIN                   UI_ADDR_BASE(0x3c1ee9)
#define UI_LEN_WEATHER_SLEET_BIN                   0x1f9e

#define UI_BUF_WEATHER_SUNNY_BIN                   UI_ADDR_BASE(0x3c3e87)
#define UI_LEN_WEATHER_SUNNY_BIN                   0xb2e

#define UI_BUF_WEATHER_TOMORROW_NIGHT_BIN          UI_ADDR_BASE(0x3c49b5)
#define UI_LEN_WEATHER_TOMORROW_NIGHT_BIN          0x81b

#define UI_BUF_WEATHER_UNKNOWN_BIN                 UI_ADDR_BASE(0x3c51d0)
#define UI_LEN_WEATHER_UNKNOWN_BIN                 0x1bab

#define UI_BUF_WEATHER_WEATHER_LIST_BIN            UI_ADDR_BASE(0x3c6d7b)
#define UI_LEN_WEATHER_WEATHER_LIST_BIN            0x869c

#define UI_BUF_WEATHER_WINDY_BIN                   UI_ADDR_BASE(0x3cf417)
#define UI_LEN_WEATHER_WINDY_BIN                   0xfb6

#endif
