/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: data.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif



#include "data.pb-c.h"
void   alipay__ret4_byte_recv__init
(Alipay__Ret4ByteRecv         *message)
{
    static const Alipay__Ret4ByteRecv init_value = ALIPAY__RET4_BYTE_RECV__INIT;
    *message = init_value;
}
size_t alipay__ret4_byte_recv__get_packed_size
(const Alipay__Ret4ByteRecv *message)
{
    //assert(message->base.descriptor == &alipay__ret4_byte_recv__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__ret4_byte_recv__pack
(const Alipay__Ret4ByteRecv *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__ret4_byte_recv__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__ret4_byte_recv__pack_to_buffer
(const Alipay__Ret4ByteRecv *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__ret4_byte_recv__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__Ret4ByteRecv *
alipay__ret4_byte_recv__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__Ret4ByteRecv *)
           protobuf_c_message_unpack (&alipay__ret4_byte_recv__descriptor,
                                      allocator, len, data);
}
void   alipay__ret4_byte_recv__free_unpacked
(Alipay__Ret4ByteRecv *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__ret4_byte_recv__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__socket__init
(Alipay__Socket         *message)
{
    static const Alipay__Socket init_value = ALIPAY__SOCKET__INIT;
    *message = init_value;
}
size_t alipay__socket__get_packed_size
(const Alipay__Socket *message)
{
    //assert(message->base.descriptor == &alipay__socket__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__socket__pack
(const Alipay__Socket *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__socket__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__socket__pack_to_buffer
(const Alipay__Socket *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__socket__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__Socket *
alipay__socket__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__Socket *)
           protobuf_c_message_unpack (&alipay__socket__descriptor,
                                      allocator, len, data);
}
void   alipay__socket__free_unpacked
(Alipay__Socket *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__socket__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__bind__init
(Alipay__Bind         *message)
{
    static const Alipay__Bind init_value = ALIPAY__BIND__INIT;
    *message = init_value;
}
size_t alipay__bind__get_packed_size
(const Alipay__Bind *message)
{
    //assert(message->base.descriptor == &alipay__bind__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__bind__pack
(const Alipay__Bind *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__bind__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__bind__pack_to_buffer
(const Alipay__Bind *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__bind__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__Bind *
alipay__bind__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__Bind *)
           protobuf_c_message_unpack (&alipay__bind__descriptor,
                                      allocator, len, data);
}
void   alipay__bind__free_unpacked
(Alipay__Bind *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__bind__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__connect__init
(Alipay__Connect         *message)
{
    static const Alipay__Connect init_value = ALIPAY__CONNECT__INIT;
    *message = init_value;
}
size_t alipay__connect__get_packed_size
(const Alipay__Connect *message)
{
    //assert(message->base.descriptor == &alipay__connect__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__connect__pack
(const Alipay__Connect *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__connect__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__connect__pack_to_buffer
(const Alipay__Connect *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__connect__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__Connect *
alipay__connect__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__Connect *)
           protobuf_c_message_unpack (&alipay__connect__descriptor,
                                      allocator, len, data);
}
void   alipay__connect__free_unpacked
(Alipay__Connect *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__connect__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__recv__init
(Alipay__Recv         *message)
{
    static const Alipay__Recv init_value = ALIPAY__RECV__INIT;
    *message = init_value;
}
size_t alipay__recv__get_packed_size
(const Alipay__Recv *message)
{
    //assert(message->base.descriptor == &alipay__recv__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__recv__pack
(const Alipay__Recv *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__recv__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__recv__pack_to_buffer
(const Alipay__Recv *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__recv__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__Recv *
alipay__recv__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__Recv *)
           protobuf_c_message_unpack (&alipay__recv__descriptor,
                                      allocator, len, data);
}
void   alipay__recv__free_unpacked
(Alipay__Recv *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__recv__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__buf_ret__init
(Alipay__BufRet         *message)
{
    static const Alipay__BufRet init_value = ALIPAY__BUF_RET__INIT;
    *message = init_value;
}
size_t alipay__buf_ret__get_packed_size
(const Alipay__BufRet *message)
{
    //assert(message->base.descriptor == &alipay__buf_ret__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__buf_ret__pack
(const Alipay__BufRet *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__buf_ret__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__buf_ret__pack_to_buffer
(const Alipay__BufRet *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__buf_ret__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__BufRet *
alipay__buf_ret__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__BufRet *)
           protobuf_c_message_unpack (&alipay__buf_ret__descriptor,
                                      allocator, len, data);
}
void   alipay__buf_ret__free_unpacked
(Alipay__BufRet *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__buf_ret__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__recv_from__init
(Alipay__RecvFrom         *message)
{
    static const Alipay__RecvFrom init_value = ALIPAY__RECV_FROM__INIT;
    *message = init_value;
}
size_t alipay__recv_from__get_packed_size
(const Alipay__RecvFrom *message)
{
    //assert(message->base.descriptor == &alipay__recv_from__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__recv_from__pack
(const Alipay__RecvFrom *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__recv_from__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__recv_from__pack_to_buffer
(const Alipay__RecvFrom *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__recv_from__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__RecvFrom *
alipay__recv_from__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__RecvFrom *)
           protobuf_c_message_unpack (&alipay__recv_from__descriptor,
                                      allocator, len, data);
}
void   alipay__recv_from__free_unpacked
(Alipay__RecvFrom *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__recv_from__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__recv_from_ret__init
(Alipay__RecvFromRet         *message)
{
    static const Alipay__RecvFromRet init_value = ALIPAY__RECV_FROM_RET__INIT;
    *message = init_value;
}
size_t alipay__recv_from_ret__get_packed_size
(const Alipay__RecvFromRet *message)
{
    //assert(message->base.descriptor == &alipay__recv_from_ret__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__recv_from_ret__pack
(const Alipay__RecvFromRet *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__recv_from_ret__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__recv_from_ret__pack_to_buffer
(const Alipay__RecvFromRet *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__recv_from_ret__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__RecvFromRet *
alipay__recv_from_ret__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__RecvFromRet *)
           protobuf_c_message_unpack (&alipay__recv_from_ret__descriptor,
                                      allocator, len, data);
}
void   alipay__recv_from_ret__free_unpacked
(Alipay__RecvFromRet *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__recv_from_ret__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__read__init
(Alipay__Read         *message)
{
    static const Alipay__Read init_value = ALIPAY__READ__INIT;
    *message = init_value;
}
size_t alipay__read__get_packed_size
(const Alipay__Read *message)
{
    //assert(message->base.descriptor == &alipay__read__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__read__pack
(const Alipay__Read *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__read__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__read__pack_to_buffer
(const Alipay__Read *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__read__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__Read *
alipay__read__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__Read *)
           protobuf_c_message_unpack (&alipay__read__descriptor,
                                      allocator, len, data);
}
void   alipay__read__free_unpacked
(Alipay__Read *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__read__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__send__init
(Alipay__Send         *message)
{
    static const Alipay__Send init_value = ALIPAY__SEND__INIT;
    *message = init_value;
}
size_t alipay__send__get_packed_size
(const Alipay__Send *message)
{
    //assert(message->base.descriptor == &alipay__send__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__send__pack
(const Alipay__Send *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__send__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__send__pack_to_buffer
(const Alipay__Send *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__send__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__Send *
alipay__send__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__Send *)
           protobuf_c_message_unpack (&alipay__send__descriptor,
                                      allocator, len, data);
}
void   alipay__send__free_unpacked
(Alipay__Send *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__send__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__send_msg__init
(Alipay__SendMsg         *message)
{
    static const Alipay__SendMsg init_value = ALIPAY__SEND_MSG__INIT;
    *message = init_value;
}
size_t alipay__send_msg__get_packed_size
(const Alipay__SendMsg *message)
{
    //assert(message->base.descriptor == &alipay__send_msg__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__send_msg__pack
(const Alipay__SendMsg *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__send_msg__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__send_msg__pack_to_buffer
(const Alipay__SendMsg *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__send_msg__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__SendMsg *
alipay__send_msg__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__SendMsg *)
           protobuf_c_message_unpack (&alipay__send_msg__descriptor,
                                      allocator, len, data);
}
void   alipay__send_msg__free_unpacked
(Alipay__SendMsg *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__send_msg__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__msg__init
(Alipay__Msg         *message)
{
    static const Alipay__Msg init_value = ALIPAY__MSG__INIT;
    *message = init_value;
}
size_t alipay__msg__get_packed_size
(const Alipay__Msg *message)
{
    //assert(message->base.descriptor == &alipay__msg__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__msg__pack
(const Alipay__Msg *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__msg__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__msg__pack_to_buffer
(const Alipay__Msg *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__msg__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__Msg *
alipay__msg__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__Msg *)
           protobuf_c_message_unpack (&alipay__msg__descriptor,
                                      allocator, len, data);
}
void   alipay__msg__free_unpacked
(Alipay__Msg *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__msg__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__iovec__init
(Alipay__Iovec         *message)
{
    static const Alipay__Iovec init_value = ALIPAY__IOVEC__INIT;
    *message = init_value;
}
size_t alipay__iovec__get_packed_size
(const Alipay__Iovec *message)
{
    //assert(message->base.descriptor == &alipay__iovec__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__iovec__pack
(const Alipay__Iovec *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__iovec__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__iovec__pack_to_buffer
(const Alipay__Iovec *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__iovec__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__Iovec *
alipay__iovec__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__Iovec *)
           protobuf_c_message_unpack (&alipay__iovec__descriptor,
                                      allocator, len, data);
}
void   alipay__iovec__free_unpacked
(Alipay__Iovec *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__iovec__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__write__init
(Alipay__Write         *message)
{
    static const Alipay__Write init_value = ALIPAY__WRITE__INIT;
    *message = init_value;
}
size_t alipay__write__get_packed_size
(const Alipay__Write *message)
{
    //assert(message->base.descriptor == &alipay__write__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__write__pack
(const Alipay__Write *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__write__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__write__pack_to_buffer
(const Alipay__Write *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__write__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__Write *
alipay__write__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__Write *)
           protobuf_c_message_unpack (&alipay__write__descriptor,
                                      allocator, len, data);
}
void   alipay__write__free_unpacked
(Alipay__Write *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__write__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__fcntl__init
(Alipay__Fcntl         *message)
{
    static const Alipay__Fcntl init_value = ALIPAY__FCNTL__INIT;
    *message = init_value;
}
size_t alipay__fcntl__get_packed_size
(const Alipay__Fcntl *message)
{
    //assert(message->base.descriptor == &alipay__fcntl__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__fcntl__pack
(const Alipay__Fcntl *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__fcntl__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__fcntl__pack_to_buffer
(const Alipay__Fcntl *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__fcntl__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__Fcntl *
alipay__fcntl__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__Fcntl *)
           protobuf_c_message_unpack (&alipay__fcntl__descriptor,
                                      allocator, len, data);
}
void   alipay__fcntl__free_unpacked
(Alipay__Fcntl *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__fcntl__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__name__init
(Alipay__Name         *message)
{
    static const Alipay__Name init_value = ALIPAY__NAME__INIT;
    *message = init_value;
}
size_t alipay__name__get_packed_size
(const Alipay__Name *message)
{
    //assert(message->base.descriptor == &alipay__name__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__name__pack
(const Alipay__Name *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__name__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__name__pack_to_buffer
(const Alipay__Name *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__name__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__Name *
alipay__name__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__Name *)
           protobuf_c_message_unpack (&alipay__name__descriptor,
                                      allocator, len, data);
}
void   alipay__name__free_unpacked
(Alipay__Name *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__name__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__hostent_res__init
(Alipay__HostentRes         *message)
{
    static const Alipay__HostentRes init_value = ALIPAY__HOSTENT_RES__INIT;
    *message = init_value;
}
size_t alipay__hostent_res__get_packed_size
(const Alipay__HostentRes *message)
{
    //assert(message->base.descriptor == &alipay__hostent_res__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__hostent_res__pack
(const Alipay__HostentRes *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__hostent_res__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__hostent_res__pack_to_buffer
(const Alipay__HostentRes *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__hostent_res__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__HostentRes *
alipay__hostent_res__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__HostentRes *)
           protobuf_c_message_unpack (&alipay__hostent_res__descriptor,
                                      allocator, len, data);
}
void   alipay__hostent_res__free_unpacked
(Alipay__HostentRes *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__hostent_res__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__close__init
(Alipay__Close         *message)
{
    static const Alipay__Close init_value = ALIPAY__CLOSE__INIT;
    *message = init_value;
}
size_t alipay__close__get_packed_size
(const Alipay__Close *message)
{
    //assert(message->base.descriptor == &alipay__close__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__close__pack
(const Alipay__Close *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__close__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__close__pack_to_buffer
(const Alipay__Close *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__close__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__Close *
alipay__close__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__Close *)
           protobuf_c_message_unpack (&alipay__close__descriptor,
                                      allocator, len, data);
}
void   alipay__close__free_unpacked
(Alipay__Close *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__close__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__select__init
(Alipay__Select         *message)
{
    static const Alipay__Select init_value = ALIPAY__SELECT__INIT;
    *message = init_value;
}
size_t alipay__select__get_packed_size
(const Alipay__Select *message)
{
    //assert(message->base.descriptor == &alipay__select__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__select__pack
(const Alipay__Select *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__select__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__select__pack_to_buffer
(const Alipay__Select *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__select__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__Select *
alipay__select__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__Select *)
           protobuf_c_message_unpack (&alipay__select__descriptor,
                                      allocator, len, data);
}
void   alipay__select__free_unpacked
(Alipay__Select *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__select__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__select_res__init
(Alipay__SelectRes         *message)
{
    static const Alipay__SelectRes init_value = ALIPAY__SELECT_RES__INIT;
    *message = init_value;
}
size_t alipay__select_res__get_packed_size
(const Alipay__SelectRes *message)
{
    //assert(message->base.descriptor == &alipay__select_res__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__select_res__pack
(const Alipay__SelectRes *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__select_res__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__select_res__pack_to_buffer
(const Alipay__SelectRes *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__select_res__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__SelectRes *
alipay__select_res__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__SelectRes *)
           protobuf_c_message_unpack (&alipay__select_res__descriptor,
                                      allocator, len, data);
}
void   alipay__select_res__free_unpacked
(Alipay__SelectRes *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__select_res__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__get_sockopt__init
(Alipay__GetSockopt         *message)
{
    static const Alipay__GetSockopt init_value = ALIPAY__GET_SOCKOPT__INIT;
    *message = init_value;
}
size_t alipay__get_sockopt__get_packed_size
(const Alipay__GetSockopt *message)
{
    //assert(message->base.descriptor == &alipay__get_sockopt__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__get_sockopt__pack
(const Alipay__GetSockopt *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__get_sockopt__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__get_sockopt__pack_to_buffer
(const Alipay__GetSockopt *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__get_sockopt__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__GetSockopt *
alipay__get_sockopt__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__GetSockopt *)
           protobuf_c_message_unpack (&alipay__get_sockopt__descriptor,
                                      allocator, len, data);
}
void   alipay__get_sockopt__free_unpacked
(Alipay__GetSockopt *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__get_sockopt__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__get_sockopt_res__init
(Alipay__GetSockoptRes         *message)
{
    static const Alipay__GetSockoptRes init_value = ALIPAY__GET_SOCKOPT_RES__INIT;
    *message = init_value;
}
size_t alipay__get_sockopt_res__get_packed_size
(const Alipay__GetSockoptRes *message)
{
    //assert(message->base.descriptor == &alipay__get_sockopt_res__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__get_sockopt_res__pack
(const Alipay__GetSockoptRes *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__get_sockopt_res__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__get_sockopt_res__pack_to_buffer
(const Alipay__GetSockoptRes *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__get_sockopt_res__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__GetSockoptRes *
alipay__get_sockopt_res__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__GetSockoptRes *)
           protobuf_c_message_unpack (&alipay__get_sockopt_res__descriptor,
                                      allocator, len, data);
}
void   alipay__get_sockopt_res__free_unpacked
(Alipay__GetSockoptRes *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__get_sockopt_res__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__set_sockopt__init
(Alipay__SetSockopt         *message)
{
    static const Alipay__SetSockopt init_value = ALIPAY__SET_SOCKOPT__INIT;
    *message = init_value;
}
size_t alipay__set_sockopt__get_packed_size
(const Alipay__SetSockopt *message)
{
    //assert(message->base.descriptor == &alipay__set_sockopt__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__set_sockopt__pack
(const Alipay__SetSockopt *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__set_sockopt__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__set_sockopt__pack_to_buffer
(const Alipay__SetSockopt *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__set_sockopt__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__SetSockopt *
alipay__set_sockopt__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__SetSockopt *)
           protobuf_c_message_unpack (&alipay__set_sockopt__descriptor,
                                      allocator, len, data);
}
void   alipay__set_sockopt__free_unpacked
(Alipay__SetSockopt *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__set_sockopt__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__tcppackage_iot_send__init
(Alipay__TCPPackageIotSend         *message)
{
    static const Alipay__TCPPackageIotSend init_value = ALIPAY__TCPPACKAGE_IOT_SEND__INIT;
    *message = init_value;
}
size_t alipay__tcppackage_iot_send__get_packed_size
(const Alipay__TCPPackageIotSend *message)
{
    //assert(message->base.descriptor == &alipay__tcppackage_iot_send__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__tcppackage_iot_send__pack
(const Alipay__TCPPackageIotSend *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__tcppackage_iot_send__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__tcppackage_iot_send__pack_to_buffer
(const Alipay__TCPPackageIotSend *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__tcppackage_iot_send__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__TCPPackageIotSend *
alipay__tcppackage_iot_send__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__TCPPackageIotSend *)
           protobuf_c_message_unpack (&alipay__tcppackage_iot_send__descriptor,
                                      allocator, len, data);
}
void   alipay__tcppackage_iot_send__free_unpacked
(Alipay__TCPPackageIotSend *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__tcppackage_iot_send__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alipay__tcppackage_iot_recv__init
(Alipay__TCPPackageIotRecv         *message)
{
    static const Alipay__TCPPackageIotRecv init_value = ALIPAY__TCPPACKAGE_IOT_RECV__INIT;
    *message = init_value;
}
size_t alipay__tcppackage_iot_recv__get_packed_size
(const Alipay__TCPPackageIotRecv *message)
{
    //assert(message->base.descriptor == &alipay__tcppackage_iot_recv__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alipay__tcppackage_iot_recv__pack
(const Alipay__TCPPackageIotRecv *message,
 uint8_t       *out)
{
    //assert(message->base.descriptor == &alipay__tcppackage_iot_recv__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alipay__tcppackage_iot_recv__pack_to_buffer
(const Alipay__TCPPackageIotRecv *message,
 ProtobufCBuffer *buffer)
{
    //assert(message->base.descriptor == &alipay__tcppackage_iot_recv__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Alipay__TCPPackageIotRecv *
alipay__tcppackage_iot_recv__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (Alipay__TCPPackageIotRecv *)
           protobuf_c_message_unpack (&alipay__tcppackage_iot_recv__descriptor,
                                      allocator, len, data);
}
void   alipay__tcppackage_iot_recv__free_unpacked
(Alipay__TCPPackageIotRecv *message,
 ProtobufCAllocator *allocator)
{
    if(!message)
        return;
    //assert(message->base.descriptor == &alipay__tcppackage_iot_recv__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor alipay__ret4_byte_recv__field_descriptors[1] =
{
    {
        "ret",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_INT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Ret4ByteRecv, ret),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__ret4_byte_recv__field_indices_by_name[] =
{
    0,   /* field[0] = ret */
};
static const ProtobufCIntRange alipay__ret4_byte_recv__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 1 }
};
const ProtobufCMessageDescriptor alipay__ret4_byte_recv__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.Ret4ByteRecv",
    "Ret4ByteRecv",
    "Alipay__Ret4ByteRecv",
    "alipay",
    sizeof(Alipay__Ret4ByteRecv),
    1,
    alipay__ret4_byte_recv__field_descriptors,
    alipay__ret4_byte_recv__field_indices_by_name,
    1,  alipay__ret4_byte_recv__number_ranges,
    (ProtobufCMessageInit) alipay__ret4_byte_recv__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__socket__field_descriptors[3] =
{
    {
        "domain",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Socket, domain),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "type",
        2,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Socket, type),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "protocol",
        3,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Socket, protocol),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__socket__field_indices_by_name[] =
{
    0,   /* field[0] = domain */
    2,   /* field[2] = protocol */
    1,   /* field[1] = type */
};
static const ProtobufCIntRange alipay__socket__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 3 }
};
const ProtobufCMessageDescriptor alipay__socket__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.Socket",
    "Socket",
    "Alipay__Socket",
    "alipay",
    sizeof(Alipay__Socket),
    3,
    alipay__socket__field_descriptors,
    alipay__socket__field_indices_by_name,
    1,  alipay__socket__number_ranges,
    (ProtobufCMessageInit) alipay__socket__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__bind__field_descriptors[4] =
{
    {
        "sockfd",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Bind, sockfd),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "sa_family",
        2,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Bind, sa_family),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "sa_len",
        3,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Bind, sa_len),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "sa_data",
        4,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(Alipay__Bind, sa_data),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__bind__field_indices_by_name[] =
{
    3,   /* field[3] = sa_data */
    1,   /* field[1] = sa_family */
    2,   /* field[2] = sa_len */
    0,   /* field[0] = sockfd */
};
static const ProtobufCIntRange alipay__bind__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 4 }
};
const ProtobufCMessageDescriptor alipay__bind__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.Bind",
    "Bind",
    "Alipay__Bind",
    "alipay",
    sizeof(Alipay__Bind),
    4,
    alipay__bind__field_descriptors,
    alipay__bind__field_indices_by_name,
    1,  alipay__bind__number_ranges,
    (ProtobufCMessageInit) alipay__bind__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__connect__field_descriptors[4] =
{
    {
        "sockfd",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Connect, sockfd),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "sa_family",
        2,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Connect, sa_family),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "sa_len",
        3,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Connect, sa_len),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "ip",
        4,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(Alipay__Connect, n_ip),
        offsetof(Alipay__Connect, ip),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__connect__field_indices_by_name[] =
{
    3,   /* field[3] = ip */
    1,   /* field[1] = sa_family */
    2,   /* field[2] = sa_len */
    0,   /* field[0] = sockfd */
};
static const ProtobufCIntRange alipay__connect__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 4 }
};
const ProtobufCMessageDescriptor alipay__connect__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.Connect",
    "Connect",
    "Alipay__Connect",
    "alipay",
    sizeof(Alipay__Connect),
    4,
    alipay__connect__field_descriptors,
    alipay__connect__field_indices_by_name,
    1,  alipay__connect__number_ranges,
    (ProtobufCMessageInit) alipay__connect__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__recv__field_descriptors[3] =
{
    {
        "sockfd",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Recv, sockfd),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "flags",
        2,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Recv, flags),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "len",
        3,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT64,
        0,   /* quantifier_offset */
        offsetof(Alipay__Recv, len),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__recv__field_indices_by_name[] =
{
    1,   /* field[1] = flags */
    2,   /* field[2] = len */
    0,   /* field[0] = sockfd */
};
static const ProtobufCIntRange alipay__recv__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 3 }
};
const ProtobufCMessageDescriptor alipay__recv__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.Recv",
    "Recv",
    "Alipay__Recv",
    "alipay",
    sizeof(Alipay__Recv),
    3,
    alipay__recv__field_descriptors,
    alipay__recv__field_indices_by_name,
    1,  alipay__recv__number_ranges,
    (ProtobufCMessageInit) alipay__recv__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__buf_ret__field_descriptors[3] =
{
    {
        "ret",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__BufRet, ret),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "len",
        2,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT64,
        0,   /* quantifier_offset */
        offsetof(Alipay__BufRet, len),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "buf",
        3,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_BYTES,
        0,   /* quantifier_offset */
        offsetof(Alipay__BufRet, buf),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__buf_ret__field_indices_by_name[] =
{
    2,   /* field[2] = buf */
    1,   /* field[1] = len */
    0,   /* field[0] = ret */
};
static const ProtobufCIntRange alipay__buf_ret__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 3 }
};
const ProtobufCMessageDescriptor alipay__buf_ret__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.BufRet",
    "BufRet",
    "Alipay__BufRet",
    "alipay",
    sizeof(Alipay__BufRet),
    3,
    alipay__buf_ret__field_descriptors,
    alipay__buf_ret__field_indices_by_name,
    1,  alipay__buf_ret__number_ranges,
    (ProtobufCMessageInit) alipay__buf_ret__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__recv_from__field_descriptors[4] =
{
    {
        "sockfd",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__RecvFrom, sockfd),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "flags",
        2,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__RecvFrom, flags),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "lenbuf",
        3,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT64,
        0,   /* quantifier_offset */
        offsetof(Alipay__RecvFrom, lenbuf),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "addrlen",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(Alipay__RecvFrom, has_addrlen),
        offsetof(Alipay__RecvFrom, addrlen),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__recv_from__field_indices_by_name[] =
{
    3,   /* field[3] = addrlen */
    1,   /* field[1] = flags */
    2,   /* field[2] = lenbuf */
    0,   /* field[0] = sockfd */
};
static const ProtobufCIntRange alipay__recv_from__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 4 }
};
const ProtobufCMessageDescriptor alipay__recv_from__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.RecvFrom",
    "RecvFrom",
    "Alipay__RecvFrom",
    "alipay",
    sizeof(Alipay__RecvFrom),
    4,
    alipay__recv_from__field_descriptors,
    alipay__recv_from__field_indices_by_name,
    1,  alipay__recv_from__number_ranges,
    (ProtobufCMessageInit) alipay__recv_from__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__recv_from_ret__field_descriptors[6] =
{
    {
        "buf",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(Alipay__RecvFromRet, buf),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "lenbuf",
        2,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT64,
        0,   /* quantifier_offset */
        offsetof(Alipay__RecvFromRet, lenbuf),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "addrlen",
        3,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(Alipay__RecvFromRet, has_addrlen),
        offsetof(Alipay__RecvFromRet, addrlen),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "sa_family",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(Alipay__RecvFromRet, has_sa_family),
        offsetof(Alipay__RecvFromRet, sa_family),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "sa_len",
        5,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(Alipay__RecvFromRet, has_sa_len),
        offsetof(Alipay__RecvFromRet, sa_len),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "sa_data",
        6,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(Alipay__RecvFromRet, sa_data),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__recv_from_ret__field_indices_by_name[] =
{
    2,   /* field[2] = addrlen */
    0,   /* field[0] = buf */
    1,   /* field[1] = lenbuf */
    5,   /* field[5] = sa_data */
    3,   /* field[3] = sa_family */
    4,   /* field[4] = sa_len */
};
static const ProtobufCIntRange alipay__recv_from_ret__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 6 }
};
const ProtobufCMessageDescriptor alipay__recv_from_ret__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.RecvFromRet",
    "RecvFromRet",
    "Alipay__RecvFromRet",
    "alipay",
    sizeof(Alipay__RecvFromRet),
    6,
    alipay__recv_from_ret__field_descriptors,
    alipay__recv_from_ret__field_indices_by_name,
    1,  alipay__recv_from_ret__number_ranges,
    (ProtobufCMessageInit) alipay__recv_from_ret__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__read__field_descriptors[2] =
{
    {
        "sockfd",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Read, sockfd),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "count",
        2,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT64,
        0,   /* quantifier_offset */
        offsetof(Alipay__Read, count),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__read__field_indices_by_name[] =
{
    1,   /* field[1] = count */
    0,   /* field[0] = sockfd */
};
static const ProtobufCIntRange alipay__read__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 2 }
};
const ProtobufCMessageDescriptor alipay__read__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.Read",
    "Read",
    "Alipay__Read",
    "alipay",
    sizeof(Alipay__Read),
    2,
    alipay__read__field_descriptors,
    alipay__read__field_indices_by_name,
    1,  alipay__read__number_ranges,
    (ProtobufCMessageInit) alipay__read__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__send__field_descriptors[4] =
{
    {
        "sockfd",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Send, sockfd),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "flags",
        2,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Send, flags),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "len",
        3,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT64,
        0,   /* quantifier_offset */
        offsetof(Alipay__Send, len),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "buf",
        4,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(Alipay__Send, buf),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__send__field_indices_by_name[] =
{
    3,   /* field[3] = buf */
    1,   /* field[1] = flags */
    2,   /* field[2] = len */
    0,   /* field[0] = sockfd */
};
static const ProtobufCIntRange alipay__send__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 4 }
};
const ProtobufCMessageDescriptor alipay__send__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.Send",
    "Send",
    "Alipay__Send",
    "alipay",
    sizeof(Alipay__Send),
    4,
    alipay__send__field_descriptors,
    alipay__send__field_indices_by_name,
    1,  alipay__send__number_ranges,
    (ProtobufCMessageInit) alipay__send__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__send_msg__field_descriptors[3] =
{
    {
        "sockfd",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__SendMsg, sockfd),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "flags",
        2,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__SendMsg, flags),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "msg",
        4,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        offsetof(Alipay__SendMsg, msg),
        &alipay__msg__descriptor,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__send_msg__field_indices_by_name[] =
{
    1,   /* field[1] = flags */
    2,   /* field[2] = msg */
    0,   /* field[0] = sockfd */
};
static const ProtobufCIntRange alipay__send_msg__number_ranges[2 + 1] =
{
    { 1, 0 },
    { 4, 2 },
    { 0, 3 }
};
const ProtobufCMessageDescriptor alipay__send_msg__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.SendMsg",
    "SendMsg",
    "Alipay__SendMsg",
    "alipay",
    sizeof(Alipay__SendMsg),
    3,
    alipay__send_msg__field_descriptors,
    alipay__send_msg__field_indices_by_name,
    2,  alipay__send_msg__number_ranges,
    (ProtobufCMessageInit) alipay__send_msg__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__msg__field_descriptors[7] =
{
    {
        "msg_name",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(Alipay__Msg, msg_name),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "msg_namelen",
        2,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT64,
        0,   /* quantifier_offset */
        offsetof(Alipay__Msg, msg_namelen),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "msg_iovlen",
        3,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Msg, msg_iovlen),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "msg_iov",
        4,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(Alipay__Msg, n_msg_iov),
        offsetof(Alipay__Msg, msg_iov),
        &alipay__iovec__descriptor,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "msg_control",
        5,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(Alipay__Msg, msg_control),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "msg_controllen",
        6,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_UINT64,
        offsetof(Alipay__Msg, has_msg_controllen),
        offsetof(Alipay__Msg, msg_controllen),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "msg_flags",
        7,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(Alipay__Msg, has_msg_flags),
        offsetof(Alipay__Msg, msg_flags),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__msg__field_indices_by_name[] =
{
    4,   /* field[4] = msg_control */
    5,   /* field[5] = msg_controllen */
    6,   /* field[6] = msg_flags */
    3,   /* field[3] = msg_iov */
    2,   /* field[2] = msg_iovlen */
    0,   /* field[0] = msg_name */
    1,   /* field[1] = msg_namelen */
};
static const ProtobufCIntRange alipay__msg__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 7 }
};
const ProtobufCMessageDescriptor alipay__msg__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.Msg",
    "Msg",
    "Alipay__Msg",
    "alipay",
    sizeof(Alipay__Msg),
    7,
    alipay__msg__field_descriptors,
    alipay__msg__field_indices_by_name,
    1,  alipay__msg__number_ranges,
    (ProtobufCMessageInit) alipay__msg__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__iovec__field_descriptors[2] =
{
    {
        "iov_base",
        1,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(Alipay__Iovec, n_iov_base),
        offsetof(Alipay__Iovec, iov_base),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "iov_len",
        2,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT64,
        0,   /* quantifier_offset */
        offsetof(Alipay__Iovec, iov_len),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__iovec__field_indices_by_name[] =
{
    0,   /* field[0] = iov_base */
    1,   /* field[1] = iov_len */
};
static const ProtobufCIntRange alipay__iovec__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 2 }
};
const ProtobufCMessageDescriptor alipay__iovec__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.Iovec",
    "Iovec",
    "Alipay__Iovec",
    "alipay",
    sizeof(Alipay__Iovec),
    2,
    alipay__iovec__field_descriptors,
    alipay__iovec__field_indices_by_name,
    1,  alipay__iovec__number_ranges,
    (ProtobufCMessageInit) alipay__iovec__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__write__field_descriptors[3] =
{
    {
        "sockfd",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Write, sockfd),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "nbyte",
        2,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT64,
        0,   /* quantifier_offset */
        offsetof(Alipay__Write, nbyte),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "buffer",
        3,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_BYTES,
        0,   /* quantifier_offset */
        offsetof(Alipay__Write, buffer),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__write__field_indices_by_name[] =
{
    2,   /* field[2] = buffer */
    1,   /* field[1] = nbyte */
    0,   /* field[0] = sockfd */
};
static const ProtobufCIntRange alipay__write__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 3 }
};
const ProtobufCMessageDescriptor alipay__write__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.Write",
    "Write",
    "Alipay__Write",
    "alipay",
    sizeof(Alipay__Write),
    3,
    alipay__write__field_descriptors,
    alipay__write__field_indices_by_name,
    1,  alipay__write__number_ranges,
    (ProtobufCMessageInit) alipay__write__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__fcntl__field_descriptors[3] =
{
    {
        "sockfd",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Fcntl, sockfd),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "cmd",
        2,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Fcntl, cmd),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "val",
        3,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Fcntl, val),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__fcntl__field_indices_by_name[] =
{
    1,   /* field[1] = cmd */
    0,   /* field[0] = sockfd */
    2,   /* field[2] = val */
};
static const ProtobufCIntRange alipay__fcntl__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 3 }
};
const ProtobufCMessageDescriptor alipay__fcntl__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.Fcntl",
    "Fcntl",
    "Alipay__Fcntl",
    "alipay",
    sizeof(Alipay__Fcntl),
    3,
    alipay__fcntl__field_descriptors,
    alipay__fcntl__field_indices_by_name,
    1,  alipay__fcntl__number_ranges,
    (ProtobufCMessageInit) alipay__fcntl__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__name__field_descriptors[2] =
{
    {
        "name",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(Alipay__Name, name),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "lenName",
        2,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Name, lenname),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__name__field_indices_by_name[] =
{
    1,   /* field[1] = lenName */
    0,   /* field[0] = name */
};
static const ProtobufCIntRange alipay__name__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 2 }
};
const ProtobufCMessageDescriptor alipay__name__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.Name",
    "Name",
    "Alipay__Name",
    "alipay",
    sizeof(Alipay__Name),
    2,
    alipay__name__field_descriptors,
    alipay__name__field_indices_by_name,
    1,  alipay__name__number_ranges,
    (ProtobufCMessageInit) alipay__name__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__hostent_res__field_descriptors[1] =
{
    {
        "h_addr_list_0_ip_arr",
        1,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(Alipay__HostentRes, n_h_addr_list_0_ip_arr),
        offsetof(Alipay__HostentRes, h_addr_list_0_ip_arr),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__hostent_res__field_indices_by_name[] =
{
    0,   /* field[0] = h_addr_list_0_ip_arr */
};
static const ProtobufCIntRange alipay__hostent_res__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 1 }
};
const ProtobufCMessageDescriptor alipay__hostent_res__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.HostentRes",
    "HostentRes",
    "Alipay__HostentRes",
    "alipay",
    sizeof(Alipay__HostentRes),
    1,
    alipay__hostent_res__field_descriptors,
    alipay__hostent_res__field_indices_by_name,
    1,  alipay__hostent_res__number_ranges,
    (ProtobufCMessageInit) alipay__hostent_res__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__close__field_descriptors[1] =
{
    {
        "fd",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Close, fd),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__close__field_indices_by_name[] =
{
    0,   /* field[0] = fd */
};
static const ProtobufCIntRange alipay__close__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 1 }
};
const ProtobufCMessageDescriptor alipay__close__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.Close",
    "Close",
    "Alipay__Close",
    "alipay",
    sizeof(Alipay__Close),
    1,
    alipay__close__field_descriptors,
    alipay__close__field_indices_by_name,
    1,  alipay__close__number_ranges,
    (ProtobufCMessageInit) alipay__close__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__select__field_descriptors[6] =
{
    {
        "nfds",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Select, nfds),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "readfds",
        2,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(Alipay__Select, n_readfds),
        offsetof(Alipay__Select, readfds),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "writefds",
        3,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(Alipay__Select, n_writefds),
        offsetof(Alipay__Select, writefds),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "exceptfds",
        4,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(Alipay__Select, n_exceptfds),
        offsetof(Alipay__Select, exceptfds),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "tv_sec",
        5,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Select, tv_sec),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "tv_usec",
        6,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__Select, tv_usec),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__select__field_indices_by_name[] =
{
    3,   /* field[3] = exceptfds */
    0,   /* field[0] = nfds */
    1,   /* field[1] = readfds */
    4,   /* field[4] = tv_sec */
    5,   /* field[5] = tv_usec */
    2,   /* field[2] = writefds */
};
static const ProtobufCIntRange alipay__select__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 6 }
};
const ProtobufCMessageDescriptor alipay__select__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.Select",
    "Select",
    "Alipay__Select",
    "alipay",
    sizeof(Alipay__Select),
    6,
    alipay__select__field_descriptors,
    alipay__select__field_indices_by_name,
    1,  alipay__select__number_ranges,
    (ProtobufCMessageInit) alipay__select__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__select_res__field_descriptors[4] =
{
    {
        "ret",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__SelectRes, ret),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "readfds",
        2,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(Alipay__SelectRes, n_readfds),
        offsetof(Alipay__SelectRes, readfds),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "writefds",
        3,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(Alipay__SelectRes, n_writefds),
        offsetof(Alipay__SelectRes, writefds),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "exceptfds",
        4,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(Alipay__SelectRes, n_exceptfds),
        offsetof(Alipay__SelectRes, exceptfds),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__select_res__field_indices_by_name[] =
{
    3,   /* field[3] = exceptfds */
    1,   /* field[1] = readfds */
    0,   /* field[0] = ret */
    2,   /* field[2] = writefds */
};
static const ProtobufCIntRange alipay__select_res__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 4 }
};
const ProtobufCMessageDescriptor alipay__select_res__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.SelectRes",
    "SelectRes",
    "Alipay__SelectRes",
    "alipay",
    sizeof(Alipay__SelectRes),
    4,
    alipay__select_res__field_descriptors,
    alipay__select_res__field_indices_by_name,
    1,  alipay__select_res__number_ranges,
    (ProtobufCMessageInit) alipay__select_res__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__get_sockopt__field_descriptors[3] =
{
    {
        "sockfd",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__GetSockopt, sockfd),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "level",
        2,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__GetSockopt, level),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "optname",
        3,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__GetSockopt, optname),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__get_sockopt__field_indices_by_name[] =
{
    1,   /* field[1] = level */
    2,   /* field[2] = optname */
    0,   /* field[0] = sockfd */
};
static const ProtobufCIntRange alipay__get_sockopt__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 3 }
};
const ProtobufCMessageDescriptor alipay__get_sockopt__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.GetSockopt",
    "GetSockopt",
    "Alipay__GetSockopt",
    "alipay",
    sizeof(Alipay__GetSockopt),
    3,
    alipay__get_sockopt__field_descriptors,
    alipay__get_sockopt__field_indices_by_name,
    1,  alipay__get_sockopt__number_ranges,
    (ProtobufCMessageInit) alipay__get_sockopt__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__get_sockopt_res__field_descriptors[5] =
{
    {
        "ret",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__GetSockoptRes, ret),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "sockfd",
        2,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__GetSockoptRes, sockfd),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "optname",
        3,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__GetSockoptRes, optname),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "optlen",
        4,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__GetSockoptRes, optlen),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "optval",
        5,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(Alipay__GetSockoptRes, optval),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__get_sockopt_res__field_indices_by_name[] =
{
    3,   /* field[3] = optlen */
    2,   /* field[2] = optname */
    4,   /* field[4] = optval */
    0,   /* field[0] = ret */
    1,   /* field[1] = sockfd */
};
static const ProtobufCIntRange alipay__get_sockopt_res__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 5 }
};
const ProtobufCMessageDescriptor alipay__get_sockopt_res__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.GetSockoptRes",
    "GetSockoptRes",
    "Alipay__GetSockoptRes",
    "alipay",
    sizeof(Alipay__GetSockoptRes),
    5,
    alipay__get_sockopt_res__field_descriptors,
    alipay__get_sockopt_res__field_indices_by_name,
    1,  alipay__get_sockopt_res__number_ranges,
    (ProtobufCMessageInit) alipay__get_sockopt_res__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alipay__set_sockopt__field_descriptors[5] =
{
    {
        "sockfd",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__SetSockopt, sockfd),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "level",
        2,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__SetSockopt, level),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "optname",
        3,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__SetSockopt, optname),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "optlen",
        4,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(Alipay__SetSockopt, optlen),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "optval",
        5,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(Alipay__SetSockopt, optval),
        NULL,
        NULL,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__set_sockopt__field_indices_by_name[] =
{
    1,   /* field[1] = level */
    3,   /* field[3] = optlen */
    2,   /* field[2] = optname */
    4,   /* field[4] = optval */
    0,   /* field[0] = sockfd */
};
static const ProtobufCIntRange alipay__set_sockopt__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 5 }
};
const ProtobufCMessageDescriptor alipay__set_sockopt__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.SetSockopt",
    "SetSockopt",
    "Alipay__SetSockopt",
    "alipay",
    sizeof(Alipay__SetSockopt),
    5,
    alipay__set_sockopt__field_descriptors,
    alipay__set_sockopt__field_indices_by_name,
    1,  alipay__set_sockopt__number_ranges,
    (ProtobufCMessageInit) alipay__set_sockopt__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const uint64_t alipay__tcppackage_iot_send__order__default_value = 0ull;
static const ProtobufCFieldDescriptor alipay__tcppackage_iot_send__field_descriptors[12] =
{
    {
        "order",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT64,
        0,   /* quantifier_offset */
        offsetof(Alipay__TCPPackageIotSend, order),
        NULL,
        &alipay__tcppackage_iot_send__order__default_value,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "socketMes",
        2,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(Alipay__TCPPackageIotSend, body_case),
        offsetof(Alipay__TCPPackageIotSend, socketmes),
        &alipay__socket__descriptor,
        NULL,
        0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "connectMes",
        3,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(Alipay__TCPPackageIotSend, body_case),
        offsetof(Alipay__TCPPackageIotSend, connectmes),
        &alipay__connect__descriptor,
        NULL,
        0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "sendMes",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(Alipay__TCPPackageIotSend, body_case),
        offsetof(Alipay__TCPPackageIotSend, sendmes),
        &alipay__send__descriptor,
        NULL,
        0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "writeMes",
        5,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(Alipay__TCPPackageIotSend, body_case),
        offsetof(Alipay__TCPPackageIotSend, writemes),
        &alipay__write__descriptor,
        NULL,
        0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "nameMes",
        6,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(Alipay__TCPPackageIotSend, body_case),
        offsetof(Alipay__TCPPackageIotSend, namemes),
        &alipay__name__descriptor,
        NULL,
        0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "readMes",
        7,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(Alipay__TCPPackageIotSend, body_case),
        offsetof(Alipay__TCPPackageIotSend, readmes),
        &alipay__read__descriptor,
        NULL,
        0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "recvMes",
        8,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(Alipay__TCPPackageIotSend, body_case),
        offsetof(Alipay__TCPPackageIotSend, recvmes),
        &alipay__recv__descriptor,
        NULL,
        0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "recvFromMes",
        9,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(Alipay__TCPPackageIotSend, body_case),
        offsetof(Alipay__TCPPackageIotSend, recvfrommes),
        &alipay__recv_from__descriptor,
        NULL,
        0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "selectMes",
        10,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(Alipay__TCPPackageIotSend, body_case),
        offsetof(Alipay__TCPPackageIotSend, selectmes),
        &alipay__select__descriptor,
        NULL,
        0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "closeMes",
        11,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(Alipay__TCPPackageIotSend, body_case),
        offsetof(Alipay__TCPPackageIotSend, closemes),
        &alipay__close__descriptor,
        NULL,
        0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "fcntlMes",
        12,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(Alipay__TCPPackageIotSend, body_case),
        offsetof(Alipay__TCPPackageIotSend, fcntlmes),
        &alipay__fcntl__descriptor,
        NULL,
        0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__tcppackage_iot_send__field_indices_by_name[] =
{
    10,   /* field[10] = closeMes */
    2,   /* field[2] = connectMes */
    11,   /* field[11] = fcntlMes */
    5,   /* field[5] = nameMes */
    0,   /* field[0] = order */
    6,   /* field[6] = readMes */
    8,   /* field[8] = recvFromMes */
    7,   /* field[7] = recvMes */
    9,   /* field[9] = selectMes */
    3,   /* field[3] = sendMes */
    1,   /* field[1] = socketMes */
    4,   /* field[4] = writeMes */
};
static const ProtobufCIntRange alipay__tcppackage_iot_send__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 12 }
};
const ProtobufCMessageDescriptor alipay__tcppackage_iot_send__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.TCPPackageIotSend",
    "TCPPackageIotSend",
    "Alipay__TCPPackageIotSend",
    "alipay",
    sizeof(Alipay__TCPPackageIotSend),
    12,
    alipay__tcppackage_iot_send__field_descriptors,
    alipay__tcppackage_iot_send__field_indices_by_name,
    1,  alipay__tcppackage_iot_send__number_ranges,
    (ProtobufCMessageInit) alipay__tcppackage_iot_send__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const uint64_t alipay__tcppackage_iot_recv__order__default_value = 0ull;
static const ProtobufCFieldDescriptor alipay__tcppackage_iot_recv__field_descriptors[7] =
{
    {
        "order",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_UINT64,
        0,   /* quantifier_offset */
        offsetof(Alipay__TCPPackageIotRecv, order),
        NULL,
        &alipay__tcppackage_iot_recv__order__default_value,
        0,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "ret4ByteRecvMes",
        2,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(Alipay__TCPPackageIotRecv, body_case),
        offsetof(Alipay__TCPPackageIotRecv, ret4byterecvmes),
        &alipay__ret4_byte_recv__descriptor,
        NULL,
        0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "bufRetMes",
        3,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(Alipay__TCPPackageIotRecv, body_case),
        offsetof(Alipay__TCPPackageIotRecv, bufretmes),
        &alipay__buf_ret__descriptor,
        NULL,
        0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "selectResMes",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(Alipay__TCPPackageIotRecv, body_case),
        offsetof(Alipay__TCPPackageIotRecv, selectresmes),
        &alipay__select_res__descriptor,
        NULL,
        0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "recvFromRetMes",
        5,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(Alipay__TCPPackageIotRecv, body_case),
        offsetof(Alipay__TCPPackageIotRecv, recvfromretmes),
        &alipay__recv_from_ret__descriptor,
        NULL,
        0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "getSockoptResMes",
        6,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(Alipay__TCPPackageIotRecv, body_case),
        offsetof(Alipay__TCPPackageIotRecv, getsockoptresmes),
        &alipay__get_sockopt_res__descriptor,
        NULL,
        0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "HostentResMes",
        7,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(Alipay__TCPPackageIotRecv, body_case),
        offsetof(Alipay__TCPPackageIotRecv, hostentresmes),
        &alipay__hostent_res__descriptor,
        NULL,
        0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned alipay__tcppackage_iot_recv__field_indices_by_name[] =
{
    6,   /* field[6] = HostentResMes */
    2,   /* field[2] = bufRetMes */
    5,   /* field[5] = getSockoptResMes */
    0,   /* field[0] = order */
    4,   /* field[4] = recvFromRetMes */
    1,   /* field[1] = ret4ByteRecvMes */
    3,   /* field[3] = selectResMes */
};
static const ProtobufCIntRange alipay__tcppackage_iot_recv__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 7 }
};
const ProtobufCMessageDescriptor alipay__tcppackage_iot_recv__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "alipay.TCPPackageIotRecv",
    "TCPPackageIotRecv",
    "Alipay__TCPPackageIotRecv",
    "alipay",
    sizeof(Alipay__TCPPackageIotRecv),
    7,
    alipay__tcppackage_iot_recv__field_descriptors,
    alipay__tcppackage_iot_recv__field_indices_by_name,
    1,  alipay__tcppackage_iot_recv__number_ranges,
    (ProtobufCMessageInit) alipay__tcppackage_iot_recv__init,
    NULL,NULL,NULL    /* reserved[123] */
};
