/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: data.proto */

#ifndef PROTOBUF_C_data_2eproto__INCLUDED
#define PROTOBUF_C_data_2eproto__INCLUDED

#include <protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Alipay__Ret4ByteRecv Alipay__Ret4ByteRecv;
typedef struct Alipay__Socket Alipay__Socket;
typedef struct Alipay__Bind Alipay__Bind;
typedef struct Alipay__Connect Alipay__Connect;
typedef struct Alipay__Recv Alipay__Recv;
typedef struct Alipay__BufRet Alipay__BufRet;
typedef struct Alipay__RecvFrom Alipay__RecvFrom;
typedef struct Alipay__RecvFromRet Alipay__RecvFromRet;
typedef struct Alipay__Read Alipay__Read;
typedef struct Alipay__Send Alipay__Send;
typedef struct Alipay__SendMsg Alipay__SendMsg;
typedef struct Alipay__Msg Alipay__Msg;
typedef struct Alipay__Iovec Alipay__Iovec;
typedef struct Alipay__Write Alipay__Write;
typedef struct Alipay__Fcntl Alipay__Fcntl;
typedef struct Alipay__Name Alipay__Name;
typedef struct Alipay__HostentRes Alipay__HostentRes;
typedef struct Alipay__Close Alipay__Close;
typedef struct Alipay__Select Alipay__Select;
typedef struct Alipay__SelectRes Alipay__SelectRes;
typedef struct Alipay__GetSockopt Alipay__GetSockopt;
typedef struct Alipay__GetSockoptRes Alipay__GetSockoptRes;
typedef struct Alipay__SetSockopt Alipay__SetSockopt;
typedef struct Alipay__TCPPackageIotSend Alipay__TCPPackageIotSend;
typedef struct Alipay__TCPPackageIotRecv Alipay__TCPPackageIotRecv;


/* --- enums --- */


/* --- messages --- */

/*
 *返回数据格式
 *+-----------+
 *|   4BYTE   |
 *+-----------+
 *|  ret/fd   |
 *+-----------+
 */
struct  Alipay__Ret4ByteRecv
{
    ProtobufCMessage base;
    int32_t ret;
};
#define ALIPAY__RET4_BYTE_RECV__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__ret4_byte_recv__descriptor) \
, 0 }


/*
 *请求数据格式
 *+-----------+-----------+-----------+
 *|   4BYTE   |   4BYTE   |   4BYTE   |
 *+-----------+-----------+-----------+
 *|   domain  |   type    |  protocol |
 *+-----------+-----------+-----------+
 */
struct  Alipay__Socket
{
    ProtobufCMessage base;
    uint32_t domain;
    uint32_t type;
    uint32_t protocol;
};
#define ALIPAY__SOCKET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__socket__descriptor) \
, 0, 0, 0 }


/*
 *请求数据格式
 *+-----------+-----------+-----------+-----------+
 *|   4BYTE   |   1BYTE   |   1BYTE   |sa_lenBYTE |
 *+-----------+-----------+-----------+-----------+
 *|   sockfd  | sa_famlily|   sa_len  |  sa_data  |
 *+-----------+-----------+-----------+-----------+
 */
struct  Alipay__Bind
{
    ProtobufCMessage base;
    uint32_t sockfd;
    uint32_t sa_family;
    uint32_t sa_len;
    char *sa_data;
};
#define ALIPAY__BIND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__bind__descriptor) \
, 0, 0, 0, NULL }


/*
 *请求数据格式
 *+-----------+-----------+-----------+-----------+
 *|   4BYTE   |   1BYTE   |   1BYTE   | sa_lenBYTE|
 *+-----------+-----------+-----------+-----------+
 *|   sockfd  | sa_family |   sa_len  |  sa_data  |
 *+-----------+-----------+-----------+-----------+
 */
struct  Alipay__Connect
{
    ProtobufCMessage base;
    uint32_t sockfd;
    uint32_t sa_family;
    uint32_t sa_len;
    size_t n_ip;
    uint32_t *ip;
};
#define ALIPAY__CONNECT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__connect__descriptor) \
, 0, 0, 0, 0,NULL }


/*
 *请求数据格式
 *+-----------+-----------+-----------+
 *|   4BYTE   |   4BYTE   |   4BYTE   |
 *+-----------+-----------+-----------+
 *|   sockfd  |    len    |  flags    |
 *+-----------+-----------+-----------+
 *返回数据格式
 *+-----------+-----------+-----------+
 *|   4BYTE   |   4BYTE   |  lenBYTE  |
 *+-----------+-----------+-----------+
 *|     ret   |   len     |   buf     |
 *+-----------+-----------+-----------+
 */
struct  Alipay__Recv
{
    ProtobufCMessage base;
    uint32_t sockfd;
    uint32_t flags;
    uint64_t len;
};
#define ALIPAY__RECV__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__recv__descriptor) \
, 0, 0, 0 }


struct  Alipay__BufRet
{
    ProtobufCMessage base;
    uint32_t ret;
    uint64_t len;
    ProtobufCBinaryData buf;
};
#define ALIPAY__BUF_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__buf_ret__descriptor) \
, 0, 0, {0,NULL} }


/*
 *函数名 ablue_ip_recvfrom
 *请求数据格式
 *+-----------+-----------+-----------+
 *|   4BYTE   |   4BYTE   |   4BYTE   |
 *+-----------+-----------+-----------+
 *|   sockfd  |    len    |  flags    |
 *+-----------+-----------+-----------+
 *返回数据格式
 *+-----------+-----------+-----------+
 *|   4BYTE   |   4BYTE   |  lenBYTE  |
 *+-----------+-----------+-----------+
 *|     ret   |   len     |   buf     |
 *+-----------+-----------+-----------+
 */
struct  Alipay__RecvFrom
{
    ProtobufCMessage base;
    uint32_t sockfd;
    uint32_t flags;
    uint64_t lenbuf;
    protobuf_c_boolean has_addrlen;
    uint32_t addrlen;
};
#define ALIPAY__RECV_FROM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__recv_from__descriptor) \
, 0, 0, 0, 0, 0 }


struct  Alipay__RecvFromRet
{
    ProtobufCMessage base;
    char *buf;
    uint64_t lenbuf;
    protobuf_c_boolean has_addrlen;
    uint32_t addrlen;
    protobuf_c_boolean has_sa_family;
    uint32_t sa_family;
    protobuf_c_boolean has_sa_len;
    uint32_t sa_len;
    /*
     * 14
     */
    char *sa_data;
};
#define ALIPAY__RECV_FROM_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__recv_from_ret__descriptor) \
, NULL, 0, 0, 0, 0, 0, 0, 0, NULL }


/*
 *请求数据格式
 *+-----------+-----------+
 *|   4BYTE   |   4BYTE   |
 *+-----------+-----------+
 *|   sockfd  |    count  |
 *+-----------+-----------+
 */
struct  Alipay__Read
{
    ProtobufCMessage base;
    uint32_t sockfd;
    uint64_t count;
};
#define ALIPAY__READ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__read__descriptor) \
, 0, 0 }


/*
 *请求数据格式
 *+-----------+-----------+-----------+
 *|   4BYTE   |   4BYTE   |   4BYTE   |
 *+-----------+-----------+-----------+
 *|   sockfd  |    len    |  flags    |
 *+-----------+-----------+-----------+
 *返回数据格式
 *+-----------+-----------+-----------+
 *|   4BYTE   |   4BYTE   |  lenBYTE  |
 *+-----------+-----------+-----------+
 *|     ret   |   len     |   buf     |
 *+-----------+-----------+-----------+
 */
struct  Alipay__Send
{
    ProtobufCMessage base;
    uint32_t sockfd;
    uint32_t flags;
    uint64_t len;
    char *buf;
};
#define ALIPAY__SEND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__send__descriptor) \
, 0, 0, 0, NULL }


/*
 *请求数据格式
 */
struct  Alipay__SendMsg
{
    ProtobufCMessage base;
    uint32_t sockfd;
    uint32_t flags;
    Alipay__Msg *msg;
};
#define ALIPAY__SEND_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__send_msg__descriptor) \
, 0, 0, NULL }


struct  Alipay__Msg
{
    ProtobufCMessage base;
    char *msg_name;
    uint64_t msg_namelen;
    uint32_t msg_iovlen;
    size_t n_msg_iov;
    Alipay__Iovec **msg_iov;
    char *msg_control;
    protobuf_c_boolean has_msg_controllen;
    uint64_t msg_controllen;
    protobuf_c_boolean has_msg_flags;
    uint32_t msg_flags;
};
#define ALIPAY__MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__msg__descriptor) \
, NULL, 0, 0, 0,NULL, NULL, 0, 0, 0, 0 }


struct  Alipay__Iovec
{
    ProtobufCMessage base;
    size_t n_iov_base;
    ProtobufCBinaryData *iov_base;
    uint64_t iov_len;
};
#define ALIPAY__IOVEC__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__iovec__descriptor) \
, 0,NULL, 0 }


struct  Alipay__Write
{
    ProtobufCMessage base;
    uint32_t sockfd;
    uint64_t nbyte;
    ProtobufCBinaryData buffer;
};
#define ALIPAY__WRITE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__write__descriptor) \
, 0, 0, {0,NULL} }


struct  Alipay__Fcntl
{
    ProtobufCMessage base;
    uint32_t sockfd;
    uint32_t cmd;
    uint32_t val;
};
#define ALIPAY__FCNTL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__fcntl__descriptor) \
, 0, 0, 0 }


struct  Alipay__Name
{
    ProtobufCMessage base;
    char *name;
    uint32_t lenname;
};
#define ALIPAY__NAME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__name__descriptor) \
, NULL, 0 }


struct  Alipay__HostentRes
{
    ProtobufCMessage base;
    /*
     * 地址列表中的第一项，IP地址根据分隔点划成4个整数返回
     */
    size_t n_h_addr_list_0_ip_arr;
    uint32_t *h_addr_list_0_ip_arr;
};
#define ALIPAY__HOSTENT_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__hostent_res__descriptor) \
, 0,NULL }


struct  Alipay__Close
{
    ProtobufCMessage base;
    uint32_t fd;
};
#define ALIPAY__CLOSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__close__descriptor) \
, 0 }


struct  Alipay__Select
{
    ProtobufCMessage base;
    uint32_t nfds;
    size_t n_readfds;
    uint32_t *readfds;
    size_t n_writefds;
    uint32_t *writefds;
    size_t n_exceptfds;
    uint32_t *exceptfds;
    uint32_t tv_sec;
    uint32_t tv_usec;
};
#define ALIPAY__SELECT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__select__descriptor) \
, 0, 0,NULL, 0,NULL, 0,NULL, 0, 0 }


/*
 * repeated 必须要赋值吗  可以不赋值吗？
 */
struct  Alipay__SelectRes
{
    ProtobufCMessage base;
    uint32_t ret;
    size_t n_readfds;
    uint32_t *readfds;
    size_t n_writefds;
    uint32_t *writefds;
    size_t n_exceptfds;
    uint32_t *exceptfds;
};
#define ALIPAY__SELECT_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__select_res__descriptor) \
, 0, 0,NULL, 0,NULL, 0,NULL }


struct  Alipay__GetSockopt
{
    ProtobufCMessage base;
    uint32_t sockfd;
    uint32_t level;
    uint32_t optname;
};
#define ALIPAY__GET_SOCKOPT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__get_sockopt__descriptor) \
, 0, 0, 0 }


struct  Alipay__GetSockoptRes
{
    ProtobufCMessage base;
    uint32_t ret;
    uint32_t sockfd;
    uint32_t optname;
    uint32_t optlen;
    char *optval;
};
#define ALIPAY__GET_SOCKOPT_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__get_sockopt_res__descriptor) \
, 0, 0, 0, 0, NULL }


struct  Alipay__SetSockopt
{
    ProtobufCMessage base;
    uint32_t sockfd;
    uint32_t level;
    uint32_t optname;
    uint32_t optlen;
    char *optval;
};
#define ALIPAY__SET_SOCKOPT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__set_sockopt__descriptor) \
, 0, 0, 0, 0, NULL }


typedef enum
{
    ALIPAY__TCPPACKAGE_IOT_SEND__BODY__NOT_SET = 0,
    ALIPAY__TCPPACKAGE_IOT_SEND__BODY_SOCKET_MES = 2,
    ALIPAY__TCPPACKAGE_IOT_SEND__BODY_CONNECT_MES = 3,
    ALIPAY__TCPPACKAGE_IOT_SEND__BODY_SEND_MES = 4,
    ALIPAY__TCPPACKAGE_IOT_SEND__BODY_WRITE_MES = 5,
    ALIPAY__TCPPACKAGE_IOT_SEND__BODY_NAME_MES = 6,
    ALIPAY__TCPPACKAGE_IOT_SEND__BODY_READ_MES = 7,
    ALIPAY__TCPPACKAGE_IOT_SEND__BODY_RECV_MES = 8,
    ALIPAY__TCPPACKAGE_IOT_SEND__BODY_RECV_FROM_MES = 9,
    ALIPAY__TCPPACKAGE_IOT_SEND__BODY_SELECT_MES = 10,
    ALIPAY__TCPPACKAGE_IOT_SEND__BODY_CLOSE_MES = 11,
    ALIPAY__TCPPACKAGE_IOT_SEND__BODY_FCNTL_MES = 12
            PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ALIPAY__TCPPACKAGE_IOT_SEND__BODY__CASE)
} Alipay__TCPPackageIotSend__BodyCase;

struct  Alipay__TCPPackageIotSend
{
    ProtobufCMessage base;
    /*
     * required SocketAPIType socketAPIType = 1;       // Socket 标识
     */
    /*
     * 包序
     */
    uint64_t order;
    Alipay__TCPPackageIotSend__BodyCase body_case;
    union
    {
        Alipay__Socket *socketmes;
        Alipay__Connect *connectmes;
        Alipay__Send *sendmes;
        Alipay__Write *writemes;
        Alipay__Name *namemes;
        Alipay__Read *readmes;
        Alipay__Recv *recvmes;
        Alipay__RecvFrom *recvfrommes;
        Alipay__Select *selectmes;
        Alipay__Close *closemes;
        Alipay__Fcntl *fcntlmes;
    };
};
#define ALIPAY__TCPPACKAGE_IOT_SEND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__tcppackage_iot_send__descriptor) \
, 0ull, ALIPAY__TCPPACKAGE_IOT_SEND__BODY__NOT_SET, {0} }


typedef enum
{
    ALIPAY__TCPPACKAGE_IOT_RECV__BODY__NOT_SET = 0,
    ALIPAY__TCPPACKAGE_IOT_RECV__BODY_RET4_BYTE_RECV_MES = 2,
    ALIPAY__TCPPACKAGE_IOT_RECV__BODY_BUF_RET_MES = 3,
    ALIPAY__TCPPACKAGE_IOT_RECV__BODY_SELECT_RES_MES = 4,
    ALIPAY__TCPPACKAGE_IOT_RECV__BODY_RECV_FROM_RET_MES = 5,
    ALIPAY__TCPPACKAGE_IOT_RECV__BODY_GET_SOCKOPT_RES_MES = 6,
    ALIPAY__TCPPACKAGE_IOT_RECV__BODY_HOSTENT_RES_MES = 7
            PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ALIPAY__TCPPACKAGE_IOT_RECV__BODY__CASE)
} Alipay__TCPPackageIotRecv__BodyCase;

struct  Alipay__TCPPackageIotRecv
{
    ProtobufCMessage base;
    /*
     * required SocketAPIType socketAPIType = 1;        // Socket 标识
     */
    /*
     * 包序
     */
    uint64_t order;
    Alipay__TCPPackageIotRecv__BodyCase body_case;
    union
    {
        Alipay__Ret4ByteRecv *ret4byterecvmes;
        Alipay__BufRet *bufretmes;
        Alipay__SelectRes *selectresmes;
        Alipay__RecvFromRet *recvfromretmes;
        Alipay__GetSockoptRes *getsockoptresmes;
        Alipay__HostentRes *hostentresmes;
    };
};
#define ALIPAY__TCPPACKAGE_IOT_RECV__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&alipay__tcppackage_iot_recv__descriptor) \
, 0ull, ALIPAY__TCPPACKAGE_IOT_RECV__BODY__NOT_SET, {0} }


/* Alipay__Ret4ByteRecv methods */
void   alipay__ret4_byte_recv__init
(Alipay__Ret4ByteRecv         *message);
size_t alipay__ret4_byte_recv__get_packed_size
(const Alipay__Ret4ByteRecv   *message);
size_t alipay__ret4_byte_recv__pack
(const Alipay__Ret4ByteRecv   *message,
 uint8_t             *out);
size_t alipay__ret4_byte_recv__pack_to_buffer
(const Alipay__Ret4ByteRecv   *message,
 ProtobufCBuffer     *buffer);
Alipay__Ret4ByteRecv *
alipay__ret4_byte_recv__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__ret4_byte_recv__free_unpacked
(Alipay__Ret4ByteRecv *message,
 ProtobufCAllocator *allocator);
/* Alipay__Socket methods */
void   alipay__socket__init
(Alipay__Socket         *message);
size_t alipay__socket__get_packed_size
(const Alipay__Socket   *message);
size_t alipay__socket__pack
(const Alipay__Socket   *message,
 uint8_t             *out);
size_t alipay__socket__pack_to_buffer
(const Alipay__Socket   *message,
 ProtobufCBuffer     *buffer);
Alipay__Socket *
alipay__socket__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__socket__free_unpacked
(Alipay__Socket *message,
 ProtobufCAllocator *allocator);
/* Alipay__Bind methods */
void   alipay__bind__init
(Alipay__Bind         *message);
size_t alipay__bind__get_packed_size
(const Alipay__Bind   *message);
size_t alipay__bind__pack
(const Alipay__Bind   *message,
 uint8_t             *out);
size_t alipay__bind__pack_to_buffer
(const Alipay__Bind   *message,
 ProtobufCBuffer     *buffer);
Alipay__Bind *
alipay__bind__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__bind__free_unpacked
(Alipay__Bind *message,
 ProtobufCAllocator *allocator);
/* Alipay__Connect methods */
void   alipay__connect__init
(Alipay__Connect         *message);
size_t alipay__connect__get_packed_size
(const Alipay__Connect   *message);
size_t alipay__connect__pack
(const Alipay__Connect   *message,
 uint8_t             *out);
size_t alipay__connect__pack_to_buffer
(const Alipay__Connect   *message,
 ProtobufCBuffer     *buffer);
Alipay__Connect *
alipay__connect__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__connect__free_unpacked
(Alipay__Connect *message,
 ProtobufCAllocator *allocator);
/* Alipay__Recv methods */
void   alipay__recv__init
(Alipay__Recv         *message);
size_t alipay__recv__get_packed_size
(const Alipay__Recv   *message);
size_t alipay__recv__pack
(const Alipay__Recv   *message,
 uint8_t             *out);
size_t alipay__recv__pack_to_buffer
(const Alipay__Recv   *message,
 ProtobufCBuffer     *buffer);
Alipay__Recv *
alipay__recv__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__recv__free_unpacked
(Alipay__Recv *message,
 ProtobufCAllocator *allocator);
/* Alipay__BufRet methods */
void   alipay__buf_ret__init
(Alipay__BufRet         *message);
size_t alipay__buf_ret__get_packed_size
(const Alipay__BufRet   *message);
size_t alipay__buf_ret__pack
(const Alipay__BufRet   *message,
 uint8_t             *out);
size_t alipay__buf_ret__pack_to_buffer
(const Alipay__BufRet   *message,
 ProtobufCBuffer     *buffer);
Alipay__BufRet *
alipay__buf_ret__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__buf_ret__free_unpacked
(Alipay__BufRet *message,
 ProtobufCAllocator *allocator);
/* Alipay__RecvFrom methods */
void   alipay__recv_from__init
(Alipay__RecvFrom         *message);
size_t alipay__recv_from__get_packed_size
(const Alipay__RecvFrom   *message);
size_t alipay__recv_from__pack
(const Alipay__RecvFrom   *message,
 uint8_t             *out);
size_t alipay__recv_from__pack_to_buffer
(const Alipay__RecvFrom   *message,
 ProtobufCBuffer     *buffer);
Alipay__RecvFrom *
alipay__recv_from__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__recv_from__free_unpacked
(Alipay__RecvFrom *message,
 ProtobufCAllocator *allocator);
/* Alipay__RecvFromRet methods */
void   alipay__recv_from_ret__init
(Alipay__RecvFromRet         *message);
size_t alipay__recv_from_ret__get_packed_size
(const Alipay__RecvFromRet   *message);
size_t alipay__recv_from_ret__pack
(const Alipay__RecvFromRet   *message,
 uint8_t             *out);
size_t alipay__recv_from_ret__pack_to_buffer
(const Alipay__RecvFromRet   *message,
 ProtobufCBuffer     *buffer);
Alipay__RecvFromRet *
alipay__recv_from_ret__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__recv_from_ret__free_unpacked
(Alipay__RecvFromRet *message,
 ProtobufCAllocator *allocator);
/* Alipay__Read methods */
void   alipay__read__init
(Alipay__Read         *message);
size_t alipay__read__get_packed_size
(const Alipay__Read   *message);
size_t alipay__read__pack
(const Alipay__Read   *message,
 uint8_t             *out);
size_t alipay__read__pack_to_buffer
(const Alipay__Read   *message,
 ProtobufCBuffer     *buffer);
Alipay__Read *
alipay__read__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__read__free_unpacked
(Alipay__Read *message,
 ProtobufCAllocator *allocator);
/* Alipay__Send methods */
void   alipay__send__init
(Alipay__Send         *message);
size_t alipay__send__get_packed_size
(const Alipay__Send   *message);
size_t alipay__send__pack
(const Alipay__Send   *message,
 uint8_t             *out);
size_t alipay__send__pack_to_buffer
(const Alipay__Send   *message,
 ProtobufCBuffer     *buffer);
Alipay__Send *
alipay__send__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__send__free_unpacked
(Alipay__Send *message,
 ProtobufCAllocator *allocator);
/* Alipay__SendMsg methods */
void   alipay__send_msg__init
(Alipay__SendMsg         *message);
size_t alipay__send_msg__get_packed_size
(const Alipay__SendMsg   *message);
size_t alipay__send_msg__pack
(const Alipay__SendMsg   *message,
 uint8_t             *out);
size_t alipay__send_msg__pack_to_buffer
(const Alipay__SendMsg   *message,
 ProtobufCBuffer     *buffer);
Alipay__SendMsg *
alipay__send_msg__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__send_msg__free_unpacked
(Alipay__SendMsg *message,
 ProtobufCAllocator *allocator);
/* Alipay__Msg methods */
void   alipay__msg__init
(Alipay__Msg         *message);
size_t alipay__msg__get_packed_size
(const Alipay__Msg   *message);
size_t alipay__msg__pack
(const Alipay__Msg   *message,
 uint8_t             *out);
size_t alipay__msg__pack_to_buffer
(const Alipay__Msg   *message,
 ProtobufCBuffer     *buffer);
Alipay__Msg *
alipay__msg__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__msg__free_unpacked
(Alipay__Msg *message,
 ProtobufCAllocator *allocator);
/* Alipay__Iovec methods */
void   alipay__iovec__init
(Alipay__Iovec         *message);
size_t alipay__iovec__get_packed_size
(const Alipay__Iovec   *message);
size_t alipay__iovec__pack
(const Alipay__Iovec   *message,
 uint8_t             *out);
size_t alipay__iovec__pack_to_buffer
(const Alipay__Iovec   *message,
 ProtobufCBuffer     *buffer);
Alipay__Iovec *
alipay__iovec__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__iovec__free_unpacked
(Alipay__Iovec *message,
 ProtobufCAllocator *allocator);
/* Alipay__Write methods */
void   alipay__write__init
(Alipay__Write         *message);
size_t alipay__write__get_packed_size
(const Alipay__Write   *message);
size_t alipay__write__pack
(const Alipay__Write   *message,
 uint8_t             *out);
size_t alipay__write__pack_to_buffer
(const Alipay__Write   *message,
 ProtobufCBuffer     *buffer);
Alipay__Write *
alipay__write__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__write__free_unpacked
(Alipay__Write *message,
 ProtobufCAllocator *allocator);
/* Alipay__Fcntl methods */
void   alipay__fcntl__init
(Alipay__Fcntl         *message);
size_t alipay__fcntl__get_packed_size
(const Alipay__Fcntl   *message);
size_t alipay__fcntl__pack
(const Alipay__Fcntl   *message,
 uint8_t             *out);
size_t alipay__fcntl__pack_to_buffer
(const Alipay__Fcntl   *message,
 ProtobufCBuffer     *buffer);
Alipay__Fcntl *
alipay__fcntl__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__fcntl__free_unpacked
(Alipay__Fcntl *message,
 ProtobufCAllocator *allocator);
/* Alipay__Name methods */
void   alipay__name__init
(Alipay__Name         *message);
size_t alipay__name__get_packed_size
(const Alipay__Name   *message);
size_t alipay__name__pack
(const Alipay__Name   *message,
 uint8_t             *out);
size_t alipay__name__pack_to_buffer
(const Alipay__Name   *message,
 ProtobufCBuffer     *buffer);
Alipay__Name *
alipay__name__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__name__free_unpacked
(Alipay__Name *message,
 ProtobufCAllocator *allocator);
/* Alipay__HostentRes methods */
void   alipay__hostent_res__init
(Alipay__HostentRes         *message);
size_t alipay__hostent_res__get_packed_size
(const Alipay__HostentRes   *message);
size_t alipay__hostent_res__pack
(const Alipay__HostentRes   *message,
 uint8_t             *out);
size_t alipay__hostent_res__pack_to_buffer
(const Alipay__HostentRes   *message,
 ProtobufCBuffer     *buffer);
Alipay__HostentRes *
alipay__hostent_res__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__hostent_res__free_unpacked
(Alipay__HostentRes *message,
 ProtobufCAllocator *allocator);
/* Alipay__Close methods */
void   alipay__close__init
(Alipay__Close         *message);
size_t alipay__close__get_packed_size
(const Alipay__Close   *message);
size_t alipay__close__pack
(const Alipay__Close   *message,
 uint8_t             *out);
size_t alipay__close__pack_to_buffer
(const Alipay__Close   *message,
 ProtobufCBuffer     *buffer);
Alipay__Close *
alipay__close__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__close__free_unpacked
(Alipay__Close *message,
 ProtobufCAllocator *allocator);
/* Alipay__Select methods */
void   alipay__select__init
(Alipay__Select         *message);
size_t alipay__select__get_packed_size
(const Alipay__Select   *message);
size_t alipay__select__pack
(const Alipay__Select   *message,
 uint8_t             *out);
size_t alipay__select__pack_to_buffer
(const Alipay__Select   *message,
 ProtobufCBuffer     *buffer);
Alipay__Select *
alipay__select__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__select__free_unpacked
(Alipay__Select *message,
 ProtobufCAllocator *allocator);
/* Alipay__SelectRes methods */
void   alipay__select_res__init
(Alipay__SelectRes         *message);
size_t alipay__select_res__get_packed_size
(const Alipay__SelectRes   *message);
size_t alipay__select_res__pack
(const Alipay__SelectRes   *message,
 uint8_t             *out);
size_t alipay__select_res__pack_to_buffer
(const Alipay__SelectRes   *message,
 ProtobufCBuffer     *buffer);
Alipay__SelectRes *
alipay__select_res__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__select_res__free_unpacked
(Alipay__SelectRes *message,
 ProtobufCAllocator *allocator);
/* Alipay__GetSockopt methods */
void   alipay__get_sockopt__init
(Alipay__GetSockopt         *message);
size_t alipay__get_sockopt__get_packed_size
(const Alipay__GetSockopt   *message);
size_t alipay__get_sockopt__pack
(const Alipay__GetSockopt   *message,
 uint8_t             *out);
size_t alipay__get_sockopt__pack_to_buffer
(const Alipay__GetSockopt   *message,
 ProtobufCBuffer     *buffer);
Alipay__GetSockopt *
alipay__get_sockopt__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__get_sockopt__free_unpacked
(Alipay__GetSockopt *message,
 ProtobufCAllocator *allocator);
/* Alipay__GetSockoptRes methods */
void   alipay__get_sockopt_res__init
(Alipay__GetSockoptRes         *message);
size_t alipay__get_sockopt_res__get_packed_size
(const Alipay__GetSockoptRes   *message);
size_t alipay__get_sockopt_res__pack
(const Alipay__GetSockoptRes   *message,
 uint8_t             *out);
size_t alipay__get_sockopt_res__pack_to_buffer
(const Alipay__GetSockoptRes   *message,
 ProtobufCBuffer     *buffer);
Alipay__GetSockoptRes *
alipay__get_sockopt_res__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__get_sockopt_res__free_unpacked
(Alipay__GetSockoptRes *message,
 ProtobufCAllocator *allocator);
/* Alipay__SetSockopt methods */
void   alipay__set_sockopt__init
(Alipay__SetSockopt         *message);
size_t alipay__set_sockopt__get_packed_size
(const Alipay__SetSockopt   *message);
size_t alipay__set_sockopt__pack
(const Alipay__SetSockopt   *message,
 uint8_t             *out);
size_t alipay__set_sockopt__pack_to_buffer
(const Alipay__SetSockopt   *message,
 ProtobufCBuffer     *buffer);
Alipay__SetSockopt *
alipay__set_sockopt__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__set_sockopt__free_unpacked
(Alipay__SetSockopt *message,
 ProtobufCAllocator *allocator);
/* Alipay__TCPPackageIotSend methods */
void   alipay__tcppackage_iot_send__init
(Alipay__TCPPackageIotSend         *message);
size_t alipay__tcppackage_iot_send__get_packed_size
(const Alipay__TCPPackageIotSend   *message);
size_t alipay__tcppackage_iot_send__pack
(const Alipay__TCPPackageIotSend   *message,
 uint8_t             *out);
size_t alipay__tcppackage_iot_send__pack_to_buffer
(const Alipay__TCPPackageIotSend   *message,
 ProtobufCBuffer     *buffer);
Alipay__TCPPackageIotSend *
alipay__tcppackage_iot_send__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__tcppackage_iot_send__free_unpacked
(Alipay__TCPPackageIotSend *message,
 ProtobufCAllocator *allocator);
/* Alipay__TCPPackageIotRecv methods */
void   alipay__tcppackage_iot_recv__init
(Alipay__TCPPackageIotRecv         *message);
size_t alipay__tcppackage_iot_recv__get_packed_size
(const Alipay__TCPPackageIotRecv   *message);
size_t alipay__tcppackage_iot_recv__pack
(const Alipay__TCPPackageIotRecv   *message,
 uint8_t             *out);
size_t alipay__tcppackage_iot_recv__pack_to_buffer
(const Alipay__TCPPackageIotRecv   *message,
 ProtobufCBuffer     *buffer);
Alipay__TCPPackageIotRecv *
alipay__tcppackage_iot_recv__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   alipay__tcppackage_iot_recv__free_unpacked
(Alipay__TCPPackageIotRecv *message,
 ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Alipay__Ret4ByteRecv_Closure)
(const Alipay__Ret4ByteRecv *message,
 void *closure_data);
typedef void (*Alipay__Socket_Closure)
(const Alipay__Socket *message,
 void *closure_data);
typedef void (*Alipay__Bind_Closure)
(const Alipay__Bind *message,
 void *closure_data);
typedef void (*Alipay__Connect_Closure)
(const Alipay__Connect *message,
 void *closure_data);
typedef void (*Alipay__Recv_Closure)
(const Alipay__Recv *message,
 void *closure_data);
typedef void (*Alipay__BufRet_Closure)
(const Alipay__BufRet *message,
 void *closure_data);
typedef void (*Alipay__RecvFrom_Closure)
(const Alipay__RecvFrom *message,
 void *closure_data);
typedef void (*Alipay__RecvFromRet_Closure)
(const Alipay__RecvFromRet *message,
 void *closure_data);
typedef void (*Alipay__Read_Closure)
(const Alipay__Read *message,
 void *closure_data);
typedef void (*Alipay__Send_Closure)
(const Alipay__Send *message,
 void *closure_data);
typedef void (*Alipay__SendMsg_Closure)
(const Alipay__SendMsg *message,
 void *closure_data);
typedef void (*Alipay__Msg_Closure)
(const Alipay__Msg *message,
 void *closure_data);
typedef void (*Alipay__Iovec_Closure)
(const Alipay__Iovec *message,
 void *closure_data);
typedef void (*Alipay__Write_Closure)
(const Alipay__Write *message,
 void *closure_data);
typedef void (*Alipay__Fcntl_Closure)
(const Alipay__Fcntl *message,
 void *closure_data);
typedef void (*Alipay__Name_Closure)
(const Alipay__Name *message,
 void *closure_data);
typedef void (*Alipay__HostentRes_Closure)
(const Alipay__HostentRes *message,
 void *closure_data);
typedef void (*Alipay__Close_Closure)
(const Alipay__Close *message,
 void *closure_data);
typedef void (*Alipay__Select_Closure)
(const Alipay__Select *message,
 void *closure_data);
typedef void (*Alipay__SelectRes_Closure)
(const Alipay__SelectRes *message,
 void *closure_data);
typedef void (*Alipay__GetSockopt_Closure)
(const Alipay__GetSockopt *message,
 void *closure_data);
typedef void (*Alipay__GetSockoptRes_Closure)
(const Alipay__GetSockoptRes *message,
 void *closure_data);
typedef void (*Alipay__SetSockopt_Closure)
(const Alipay__SetSockopt *message,
 void *closure_data);
typedef void (*Alipay__TCPPackageIotSend_Closure)
(const Alipay__TCPPackageIotSend *message,
 void *closure_data);
typedef void (*Alipay__TCPPackageIotRecv_Closure)
(const Alipay__TCPPackageIotRecv *message,
 void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor alipay__ret4_byte_recv__descriptor;
extern const ProtobufCMessageDescriptor alipay__socket__descriptor;
extern const ProtobufCMessageDescriptor alipay__bind__descriptor;
extern const ProtobufCMessageDescriptor alipay__connect__descriptor;
extern const ProtobufCMessageDescriptor alipay__recv__descriptor;
extern const ProtobufCMessageDescriptor alipay__buf_ret__descriptor;
extern const ProtobufCMessageDescriptor alipay__recv_from__descriptor;
extern const ProtobufCMessageDescriptor alipay__recv_from_ret__descriptor;
extern const ProtobufCMessageDescriptor alipay__read__descriptor;
extern const ProtobufCMessageDescriptor alipay__send__descriptor;
extern const ProtobufCMessageDescriptor alipay__send_msg__descriptor;
extern const ProtobufCMessageDescriptor alipay__msg__descriptor;
extern const ProtobufCMessageDescriptor alipay__iovec__descriptor;
extern const ProtobufCMessageDescriptor alipay__write__descriptor;
extern const ProtobufCMessageDescriptor alipay__fcntl__descriptor;
extern const ProtobufCMessageDescriptor alipay__name__descriptor;
extern const ProtobufCMessageDescriptor alipay__hostent_res__descriptor;
extern const ProtobufCMessageDescriptor alipay__close__descriptor;
extern const ProtobufCMessageDescriptor alipay__select__descriptor;
extern const ProtobufCMessageDescriptor alipay__select_res__descriptor;
extern const ProtobufCMessageDescriptor alipay__get_sockopt__descriptor;
extern const ProtobufCMessageDescriptor alipay__get_sockopt_res__descriptor;
extern const ProtobufCMessageDescriptor alipay__set_sockopt__descriptor;
extern const ProtobufCMessageDescriptor alipay__tcppackage_iot_send__descriptor;
extern const ProtobufCMessageDescriptor alipay__tcppackage_iot_recv__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_data_2eproto__INCLUDED */
