#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
#./tool/AStyle.exe --style=allman  --recursive *.c *.h
#OP_MODE=$?

check_results=`git status -s`

array=(${check_results// / })  
cchar=".c" 
ccharCnt=0
hchar=".h" 
hcharCnt=0
for var in ${array[@]}
do
if [[ $var == *$cchar ]]
then
ccharCnt=$((ccharCnt+1))
cchararray[ccharCnt]=$var
fi
if [[ $var == *$hchar ]]
then
hcharCnt=$((hcharCnt+1))
hchararray[hcharCnt]=$var
fi	
done

echo ".c file has astyle cnt is ${ccharCnt}"
echo ".h file has astyle cnt is ${hcharCnt}"
#echo ${cchararray[@]}
#echo ${hchararray[@]}
for var in ${cchararray[@]}
do
#./ute/tool/AStyle/AStyle.exe --style=allman -n $var
./ute/tool/AStyle/AStyle.exe --style=allman -s4 -S -N -L -m0 -M40 --convert-tabs --suffix=none $var
git add $var
done

for var in ${hchararray[@]}
do
./ute/tool/AStyle/AStyle.exe --style=allman -s4 -S -N -L -m0 -M40 --convert-tabs --suffix=none $var
git add $var
done

exit 0
