#include "func.h"
#include "func_menu.h"

typedef struct f_menu_ui_data_
{
    u8 func_sta;                            //普通菜单模式
    u32 str_idx;                                //文字
    u32 res_addr;                               //图标
    u32 fb_res_addr;                            //图标->球形菜单
} f_menu_ui_data;


static const compo_football_item_t tbl_menu_football[20] =
{
#if UTE_MODULE_SCREENS_ACTIVITY_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_ACTIVITY_BIN,         FUNC_ACTIVITY},
#endif // UTE_MODULE_SCREENS_ACTIVITY_SUPPORT
#if UTE_MODULE_SCREENS_ALARM_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_ALARM_BIN,            FUNC_ALARM_CLOCK},
#endif // UTE_MODULE_SCREENS_ALARM_SUPPORT
#if UTE_MODULE_SCREENS_BREATHE_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_BREATHE_BIN,          FUNC_BREATHE},
#endif // UTE_MODULE_SCREENS_BREATHE_SUPPORT
#if UTE_MODULE_SCREENS_CALCULATOR_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_CALCULATOR_BIN,       FUNC_CALCULATOR},
#endif // UTE_MODULE_SCREENS_CALCULATOR_SUPPORT
#if UTE_MODULE_SCREENS_CALL_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_CALL_BIN,             FUNC_CALL},
#endif // UTE_MODULE_SCREENS_CALL_SUPPORT
#if UTE_MODULE_SCREENS_FIND_PHNOE_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_FINDPHONE_BIN,        FUNC_FINDPHONE},
#endif // UTE_MODULE_SCREENS_FIND_PHNOE_SUPPORT
#if UTE_MODULE_SCREENS_HEARTRATE_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_HEART_BIN,            FUNC_HEARTRATE},
#endif // UTE_MODULE_SCREENS_HEARTRATE_SUPPORT
#if UTE_MODULE_SCREENS_MESSAGE_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_MESSAGE_BIN,          FUNC_MESSAGE},
#endif // UTE_MODULE_SCREENS_MESSAGE_SUPPORT
#if UTE_MODULE_SCREENS_MUSIC_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_MUSIC_BIN,            FUNC_BT},
#endif // UTE_MODULE_SCREENS_MUSIC_SUPPORT
#if UTE_MODULE_SCREENS_CAMERA_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_PHOTO_BIN,            FUNC_CAMERA},
#endif // UTE_MODULE_SCREENS_CAMERA_SUPPORT
#if UTE_MODULE_SCREENS_SETTING_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_SETTINGS_BIN,         FUNC_SETTING},
#endif // UTE_MODULE_SCREENS_SETTING_SUPPORT
#if UTE_MODULE_SCREENS_SLEEP_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_SLEEP_BIN,            FUNC_SLEEP},
#endif // UTE_MODULE_SCREENS_SLEEP_SUPPORT
#if UTE_MODULE_SCREENS_SPORT_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_SOPRT_BIN,            FUNC_SPORT},
#endif // UTE_MODULE_SCREENS_SPORT_SUPPORT
#if UTE_MODULE_SCREENS_BLOOD_OXYGEN_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_SPO2_BIN,             FUNC_BLOOD_OXYGEN},
#endif // UTE_MODULE_SCREENS_BLOOD_OXYGEN_SUPPORT
#if UTE_MODULE_SCREENS_STOPWATCH_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_STOPWATCH_BIN,        FUNC_STOPWATCH},
#endif // UTE_MODULE_SCREENS_STOPWATCH_SUPPORT
#if UTE_MODULE_SCREENS_TIMER_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_V_BIN,                FUNC_TIMER},
#endif // UTE_MODULE_SCREENS_TIMER_SUPPORT
#if UTE_MODULE_SCREENS_VOICE_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_VIOCE_BIN,            FUNC_VOICE},
#endif // UTE_MODULE_SCREENS_VOICE_SUPPORT
#if UTE_MODULE_SCREENS_WEATHER_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_WEATHER_BIN,          FUNC_WEATHER},
#endif // UTE_MODULE_SCREENS_WEATHER_SUPPORT
#if UTE_MODULE_SCREENS_PRESSURE_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_PRESSURE_BIN,         FUNC_PRESSURE},
#endif // UTE_MODULE_SCREENS_WEATHER_SUPPORT
#if UTE_MODULE_SCREENS_TOOLBOX_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_MORE_BIN,             FUNC_TOOLBOX},
#endif // UTE_MODULE_SCREENS_WEATHER_SUPPORT
    {UI_BUF_I338001_28_SET_MENU_FOOTBALL_FEMALE_BIN,           FUNC_WOMEN_HEALTH},
};


f_menu_ui_data f_menu_data[] =
{
#if UTE_MODULE_SCREENS_CALL_SUPPORT//通话
    {.func_sta=FUNC_CALL,          .str_idx=STR_PHONE,                .res_addr=UI_BUF_I338001_2_HONEYCOMB_CALL_BIN,      .fb_res_addr=UI_BUF_I338001_28_SET_MENU_FOOTBALL_CALL_BIN,  },
#endif
#if UTE_MODULE_SCREENS_TIMER_SUPPORT   //计时器
    {.func_sta=FUNC_TIMER,         .str_idx=STR_TIMER,                .res_addr=UI_BUF_I338001_2_HONEYCOMB_TIMER_BIN,     .fb_res_addr=UI_BUF_I338001_28_SET_MENU_FOOTBALL_V_BIN,     },
#endif
#if UTE_MODULE_SCREENS_ACTIVITY_SUPPORT//每日活动
    {.func_sta=FUNC_ACTIVITY,      .str_idx=STR_EVREY_DAY_ACTIVITY,   .res_addr=UI_BUF_I338001_2_HONEYCOMB_ACTIVITY_BIN,  .fb_res_addr=UI_BUF_I338001_28_SET_MENU_FOOTBALL_ACTIVITY_BIN },
#endif
#if UTE_MODULE_SCREENS_HEARTRATE_SUPPORT//心率
    {.func_sta=FUNC_HEARTRATE,     .str_idx=STR_HEART_RATE,           .res_addr=UI_BUF_I338001_2_HONEYCOMB_HEART_BIN,     .fb_res_addr=UI_BUF_I338001_28_SET_MENU_FOOTBALL_V_BIN,     },
#endif
};



const menu_hc_item_t tbl_menu_honeycomb[] =
{
#if UTE_MODULE_SCREENS_CALL_SUPPORT
    {.func_sta=FUNC_CALL,                     .res_addr=UI_BUF_I338001_2_HONEYCOMB_CALL_BIN,                  },   //电话
#endif // UTE_MODULE_SCREENS_CALL_SUPPORT
#if UTE_MODULE_SCREENS_ACTIVITY_SUPPORT
    {.func_sta=FUNC_ACTIVITY,                 .res_addr=UI_BUF_I338001_2_HONEYCOMB_ACTIVITY_BIN,              },   //每日活动
#endif // UTE_MODULE_SCREENS_ACTIVITY_SUPPORT
#if UTE_MODULE_SCREENS_HEARTRATE_SUPPORT
    {.func_sta=FUNC_HEARTRATE,                .res_addr=UI_BUF_I338001_2_HONEYCOMB_HEART_BIN,            },   //心率
#endif // UTE_MODULE_SCREENS_HEARTRATE_SUPPORT
#if UTE_MODULE_SCREENS_PRESSURE_SUPPORT
    {.func_sta=FUNC_PRESSURE,                .res_addr=UI_BUF_I338001_2_HONEYCOMB_STRESS_BIN,                },   //压力
#endif // UTE_MODULE_SCREENS_HEARTRATE_SUPPORT
#if UTE_MODULE_SCREENS_SPORT_SUPPORT
    {.func_sta=FUNC_SPORT,                    .res_addr=UI_BUF_I338001_2_HONEYCOMB_SOPRT_BIN,              },   //运动
#endif // UTE_MODULE_SCREENS_SPORT_SUPPORT
#if UTE_MODULE_SCREENS_BLOOD_OXYGEN_SUPPORT
    {.func_sta=FUNC_BLOOD_OXYGEN,             .res_addr=UI_BUF_I338001_2_HONEYCOMB_SPO2_BIN,          },   //血氧
#endif // UTE_MODULE_SCREENS_BLOOD_OXYGEN_SUPPORT
// #if UTE_MODULE_SCREENS_BLOOD_OXYGEN_SUPPORT
    // {.func_sta=FUNC_BLOOD_OXYGEN,             .res_addr=UI_BUF_I338001_2_HONEYCOMB_BLOOD_PRESSURE_BIN,        },   //血压
// #endif // UTE_MODULE_SCREENS_BLOOD_OXYGEN_SUPPORT
#if UTE_MODULE_SCREENS_SLEEP_SUPPORT
    {.func_sta=FUNC_SLEEP,                    .res_addr=UI_BUF_I338001_2_HONEYCOMB_SLEEP_BIN,                 },  //睡眠
#endif // UTE_MODULE_SCREENS_SLEEP_SUPPORT
#if UTE_MODULE_SCREENS_MUSIC_SUPPORT
    {.func_sta=FUNC_BT,                       .res_addr=UI_BUF_I338001_2_HONEYCOMB_MUSIC_BIN,                 },  //音乐
#endif // UTE_MODULE_SCREENS_MUSIC_SUPPORT
#if UTE_MODULE_SCREENS_WEATHER_SUPPORT
    {.func_sta=FUNC_WEATHER,                  .res_addr=UI_BUF_I338001_2_HONEYCOMB_WEATHER_BIN,               },  //天气
#endif // UTE_MODULE_SCREENS_WEATHER_SUPPORT
#if UTE_MODULE_SCREENS_ALARM_SUPPORT
    {.func_sta=FUNC_ALARM_CLOCK,              .res_addr=UI_BUF_I338001_2_HONEYCOMB_ALARM_BIN,                 },  //闹钟
#endif // UTE_MODULE_SCREENS_ALARM_SUPPORT
#if UTE_MODULE_SCREENS_EMOTION_SUPPORT
    {.func_sta=FUNC_MOOD,                    .res_addr=UI_BUF_I338001_2_HONEYCOMB_MOOD_BIN,                  },  //情绪
#endif // UTE_MODULE_SCREENS_HEARTRATE_SUPPORT
#if UTE_MODULE_SCREENS_BREATHE_SUPPORT
    {.func_sta=FUNC_BREATHE,                  .res_addr=UI_BUF_I338001_2_HONEYCOMB_BREATHING_BIN,               },  //呼吸
#endif // UTE_MODULE_SCREENS_BREATHE_SUPPORT
#if UTE_MODULE_SCREENS_MESSAGE_SUPPORT
    {.func_sta=FUNC_MESSAGE,                  .res_addr=UI_BUF_I338001_2_HONEYCOMB_MESSAGE_BIN,           },  //消息
#endif // UTE_MODULE_SCREENS_MESSAGE_SUPPORT
#if UTE_MODULE_SCREENS_VOICE_SUPPORT
    {.func_sta=FUNC_VOICE,                    .res_addr=UI_BUF_I338001_2_HONEYCOMB_VOICE_ASSISTANT_BIN,       },  //语音助手
#endif // UTE_MODULE_SCREENS_VOICE_SUPPORT
#if UTE_MODULE_SCREENS_TOOLBOX_SUPPORT
    {.func_sta=FUNC_TOOLBOX,                    .res_addr=UI_BUF_I338001_2_HONEYCOMB_TOOLBOX_BIN,               },  //工具箱
#endif // UTE_MODULE_SCREENS_VOICE_SUPPORT
#if UTE_MODULE_SCREENS_SETTING_SUPPORT
    {.func_sta=FUNC_SETTING,                  .res_addr=UI_BUF_I338001_2_HONEYCOMB_SETTINGS_BIN,              },  //设置
#endif // UTE_MODULE_SCREENS_SETTING_SUPPORT
#if UTE_MODULE_SCREENS_HEARTRATE_SUPPORT
    {.func_sta=FUNC_WOMEN_HEALTH,             .res_addr=UI_BUF_I338001_2_HONEYCOMB_PERIOD_BIN,                },  //女性健康
#endif // UTE_MODULE_SCREENS_HEARTRATE_SUPPORT
#if UTE_MODULE_SCREENS_STOPWATCH_SUPPORT
    {.func_sta=FUNC_STOPWATCH,                .res_addr=UI_BUF_I338001_2_HONEYCOMB_STOPWATCH_BIN,             },    //秒表
#endif // UTE_MODULE_SCREENS_STOPWATCH_SUPPORT
#if UTE_MODULE_SCREENS_TIMER_SUPPORT
    {.func_sta=FUNC_TIMER,                    .res_addr=UI_BUF_I338001_2_HONEYCOMB_TIMER_BIN,                 },    //定时器
#endif // UTE_MODULE_SCREENS_TIMER_SUPPORT
#if UTE_MODULE_SCREENS_FIND_PHNOE_SUPPORT
    {.func_sta=FUNC_FINDPHONE,                .res_addr=UI_BUF_I338001_2_HONEYCOMB_FINDPHONE_BIN            },    //查找手机
#endif
#if UTE_MODULE_SCREENS_FLASHLIGHT_SUPPORT
    {.func_sta=FUNC_FLASHLIGHT,               .res_addr=UI_BUF_I338001_2_HONEYCOMB_FLASHLIGHT_BIN,            },    //手电筒
#endif
#if UTE_MODULE_SCREENS_CAMERA_SUPPORT
    {.func_sta=FUNC_CAMERA,                    .res_addr=UI_BUF_I338001_2_HONEYCOMB_PHOTO_BIN,         },    //相机
#endif // UTE_MODULE_SCREENS_CAMERA_SUPPORT
#if UTE_MODULE_SCREENS_CALCULATOR_SUPPORT
    {.func_sta=FUNC_CALCULATOR,               .res_addr=UI_BUF_I338001_2_HONEYCOMB_CALCULATOR_BIN,             },    //计算器
#endif // UTE_MODULE_SCREENS_CALCULATOR_SUPPORT
};